### ISSUE TITLE
Add minify/uglify task to dist

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#102]
When running the `dist` task as mentioned in #101 add support for minifying/uglifying script and css files to be deployed in production.

**Comment by waldekmastykarz** [comment]
Shall I pick it up together with #101?

**Comment by andrewconnell** [comment]
makes sense since creating a distro folder involves creating a prod deployment which should be minified

**Comment by jthake** [comment]
I like this idea. ship it!

**Comment by waldekmastykarz** [comment]
Already did #111 ;)
