### ISSUE TITLE
Generated manifest doesn't show up in catalog

### ISSUE THREAD

**Issue by alexkieling** [OfficeDev/generator-office#107]
The following optional element doesn't have a valid value and is causing the app to not show up in the catalog for installation:
```
<SupportUrl DefaultValue="[Support URL]"/>
```
I would like to suggest this element to be removed or generated with a valid value. I understand the value is supposed to be changed, but it would be great if the generated manifest is 100% valid to avoid problems for beginners. Word doesn't indicate the issue, it just doesn't list the app in the catalog.

**Comment by andrewconnell** [comment]
Would be nice to have all non-required elements removed... want to do it and submit a PR @alexkieling ?

**Comment by alexkieling** [comment]
OK, I'll do it.

**Comment by waldekmastykarz** [comment]
Although the **SupportUrl** is not required for deploying Office Add-ins to your own App Catalog, it is required if you would like to publish your Add-in in the Office Store (https://msdn.microsoft.com/en-us/library/office/jj220035.aspx). If we just removed all optional properties it would mean that developers who want to publish their Add-ins to the Office Store will get a few surprises.

What if we could add a gulp task that would validate the manifest against the Office Store guidelines? That way we could keep deployment to own App Catalogs easy and help out devs who want to publish Add-ins in the Office Store.

**Comment by alexkieling** [comment]
We could keep it commented out, like this:
```
<!-- Support URL is required for add-ins submitted to the Office Store
<SupportUrl DefaultValue="[Support URL]"/>
-->
```

**Comment by andrewconnell** [comment]
I prefer to have the generator only include the absolutely required properties, but yes having a task that could validate for store submission would be nice. I don’t think the majority of add-ins are going to be submitted to the store so we shouldn’t have that be the default.

**Comment by waldekmastykarz** [comment]
OK, let's remove all optional parameters from the manifest and I'll add a new issue for new store validation task so we can track it separately.
