### ISSUE TITLE
appsforoffice.microsoft.com/lib/1.1/hosted/o15apptofilemappingtable.js:11 Uncaught TypeError: window.external.GetContext is not a function

### ISSUE THREAD

**Issue by mauricionr** [OfficeDev/generator-office#11]
![windowexternalgetcontext](https://cloud.githubusercontent.com/assets/2263551/9550936/97c866c6-4d84-11e5-8412-84ab7254bbb0.png)

Hey there, i'm trying to run this generator using angular, but i got this error, any sugestion?

Thanks!

**Comment by jthake** [comment]
Did you modify any code at all after the generator ran? Did you follow the youtube video to deploy the manifest and actually run the add-in in Outlook in a browser?
http://dev.office.com/blogs/creating-office-add-ins-with-any-editor-introducing-yo-office

**Comment by mauricionr** [comment]
Here is my manifest

![manifestfile](https://cloud.githubusercontent.com/assets/2263551/9553399/2d89c410-4d95-11e5-9190-100d03c4b23c.png)

**Comment by mauricionr** [comment]
My manifest file

![angularmanifestfile](https://cloud.githubusercontent.com/assets/2263551/9553427/5f116344-4d95-11e5-9663-00b7cc26afe9.png)

**Comment by mauricionr** [comment]
![runninginoutlook365](https://cloud.githubusercontent.com/assets/2263551/9553507/e959a642-4d95-11e5-8ff4-31cbabd9b8c7.png)

**Comment by andrewconnell** [comment]
@mauricionr These are not issues with the generator, rather the appear to be issues with the development of your addin. Please use this issue list for issues related to the generator & post development questions for office addins to StackOverflow and make sure to tag them with **[ms-office](http://stackoverflow.com/questions/tagged/ms-office)** and/or **[office-addins](http://stackoverflow.com/questions/tagged/office-addins)**

**Comment by shenshouer** [comment]
nothing more resource about office.js, and no Solution!!
