### ISSUE TITLE
Extend the validateHighResolutionIconUrl function to check for valid image URL

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#112]
We should extend the [_validateHighResolutionIconUrl](https://github.com/OfficeDev/generator-office/blob/c6f81dd4286fafbca12508250f2949c1ae10231c/generators/content/templates/common/gulpfile.js#L81) function in the generated `gulpfile.js` to check if the specified URL is a valid image URL (extension ending with `.png` or `.jpg`). Currently we only check if the specified URL is an https URL. The problem with that is that if you provide a non-image URL (eg. `https://contoso.com`), your add-in will work as expected in OWA but won't show up in Outlook client which is almost impossible to track back to the URL specified in the **HighResolutionIconUrl** property in the manifest. If we could check for it, it would be very helpful for the developers.

**Comment by andrewconnell** [comment]
:+1:

**Comment by waldekmastykarz** [comment]
Shall I pick it up after we merge PR #111 into main to avoid merge issues given that a fix for this will modify the same files?

**Comment by andrewconnell** [comment]
Go for it

**Comment by waldekmastykarz** [comment]
:+1:
