### ISSUE TITLE
Add .deployment file to leverage the dist task in CI on Azure Web Apps

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#113]
Since we now have the Gulp dist task in place how about we added a .deployment file to leverage it in continuous integration on Azure Web Apps with Kudu as described at http://blog.mastykarz.nl/easily-publishing-release-versions-web-applications-azure-web-apps-git-gulp-kudu/?

**Comment by beth-panx** [comment]
Refer to #219 for future enhancement discussion.
