### ISSUE TITLE
Consider to automatically inject static local css and javascript resources to html pages as needed

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/generator-office#120]
From my point of view static resource and bower resources should be automatically injected in the html files.
I can help you on this too.

**Comment by waldekmastykarz** [comment]
Could we combine this with something similar to bundles in ASP.NET MVC where you can have them automatically included as-is or merged and uglified?

**Comment by StfBauer** [comment]
To bundle in bower components I would use gulp-wiredep. Wiredep reads the bower.json and include all the required files into the HTML automatically.
gulp-inject I would use to bundle in all static resource into the html.

**Comment by waldekmastykarz** [comment]
What if bundles should include files outside of bower? Could wiredep include them too?

**Comment by StfBauer** [comment]
For this you will use gulp-inject. You can specify what you like to inject. e.g. all in ./app/scripts/ all in ./app/css/
Currently rewriting my [style guide app](https://github.com/StfBauer/SimpleStyle/tree/dev) base on all those thing. My goal with this is to have as much automation as needed to provide a tool for fast implementation. You will find my stuff currently in dev branch.

**Comment by waldekmastykarz** [comment]
Looks nice! Anything else we should take into account @andrewconnell?

**Comment by andrewconnell** [comment]
wiredup & inject are definitely the way to go. I hadn't pushed for this because I thought it might be too much for folks to grok.

**Comment by waldekmastykarz** [comment]
It would definitely be a great addition. @StfBauer would you like to give it a go?

**Comment by StfBauer** [comment]
Sure no problem :)

**Comment by waldekmastykarz** [comment]
:+1:
