### ISSUE TITLE
Missing script and css reference in Office UI Fabric bower component

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/generator-office#121]
Not sure where to address this but Office UI Fabric bower components doesn't have CSS or JS reference in the bower.son file of the bower components.

Therefor this couldn't be added dynamically using wiredep.

@andrewconnell can you fix this or do I need to address this to the Office UI Fabric team?

**Comment by andrewconnell** [comment]
As in the official Office UI Fabric? You should file that as an issue in their repo: 
https://github.com/officedev/office-ui-fabric

**Comment by StfBauer** [comment]
Thank you. It is missing in the official bower package.

**Comment by StfBauer** [comment]
Add issue to [Office UI Fabric](https://github.com/OfficeDev/Office-UI-Fabric/issues/245)
