### ISSUE TITLE
Bad reference to OfficeThemes.css in HTML/JS Mail add-in

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/generator-office#122]
Not sure if it applies to other projects, probably does, but home.html references OfficeThemes.css with a bad path.

**Path in template:**
```
../../bower_components/microsoft.office.js/styles/OfficeThemes.css
```

**Right path:**
```
../../bower_components/microsoft.office.js/content/OfficeThemes.css
```

**Comment by jthake** [comment]
nice spot. Do you want to do a pull request for this ? :-)

**Comment by andrewconnell** [comment]
:+1:

**Comment by StfBauer** [comment]
This will be fixed by this pull request. https://github.com/OfficeDev/generator-office/pull/123

**Comment by beth-panx** [comment]
I have merged the changes @vboctor and @jonasrk made in #169 #177 #178 that fixes this issue.
