### ISSUE TITLE
Update static reference to Angular ADAL

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#127]
Although the bower reference to Angular ADAL has been updated to v1.0.5 https://github.com/OfficeDev/generator-office/blob/master/generators/taskpane/templates/ng-adal/_bower.json#L9, `index.html` still references v1.0.0 https://github.com/OfficeDev/generator-office/blob/master/generators/taskpane/templates/ng-adal/index.html#L12-L13. Both references should be in sync. Also we could consider updating the reference to the latest version.

**Comment by jthake** [comment]
You putting your hand up for this one @waldekmastykarz ? ;-)

**Comment by waldekmastykarz** [comment]
Sure!
