### ISSUE TITLE
Fix invalid reference to officethemes.css

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#128]
In https://github.com/OfficeDev/generator-office/blob/master/generators/taskpane/templates/ng-adal/index.html#L30 there is an invalid reference to the officethemes.css file. In the URL the file should be spelled all lowercase (doesn't matter on IIS but will return 404 on different servers) and the file is located in the **content** directory rather than **styles**.

**Comment by jthake** [comment]
You putting your hand up for this one @waldekmastykarz ? ;-)

**Comment by waldekmastykarz** [comment]
Sure!
