### ISSUE TITLE
Add optional reference to jQuery

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#129]
In https://github.com/OfficeDev/generator-office/blob/7d108d36ee09785e93b26f9bcdb0c783c11b9181/generators/taskpane/templates/ng-adal/index.html#L22 there is an optional reference to Office UI Fabric components. Unfortunately if you uncomment this reference, the add-in fails because it misses jQuery which is required by Office UI Fabric scripts.
If the add-in contains a reference to scripts that depend on jQuery it should also reference jQuery.

**Comment by jthake** [comment]
What do you recommend here @waldekmastykarz ?

**Comment by waldekmastykarz** [comment]
1. Add jQuery to bower
2. Include commented out jQuery reference in *index.html* so that it's consistent with the commented out Office UI Fabric reference
