### ISSUE TITLE
The validation rule 7.15 for store publication returns false positive

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#130]
When the `index.html` file contains a commented out reference to `//appsforoffice.microsoft.com/lib/1.1/hosted/office.js` the validation rule 7.15 check at https://github.com/OfficeDev/generator-office/blob/7d108d36ee09785e93b26f9bcdb0c783c11b9181/generators/taskpane/templates/common/gulpfile.js#L100-L104 passes while it should fail as the script reference is not used.

**Comment by jthake** [comment]
What is your recommendation for this @waldekmastykarz?

**Comment by waldekmastykarz** [comment]
Currently we do a `string.indexOf`check for this rule which doesn't fail if the contents are within a comment. We could either change it to a regex (suboptimal) or to parse *index.html* to a DOM object and check if there is a script node with the correct URL (better). Let's try to see if it's possible to parse an HTML document to DOM to do the checks. If it's not possible we can always fall back to regex.
