### ISSUE TITLE
Manifest.xml only tech choice allows empty add-in start URL, creating invalid manifest

### ISSUE THREAD

**Issue by jasonjoh** [OfficeDev/generator-office#131]
Steps to reproduce:

```
? Project name (display name): badvalue-test
? Root folder of project? Default to current directory
 (C:\Users\jasonjoh\Source\Repos\mail-addins\test-manifests), or specify relative
path
 from current (src / public):
? Office project type: Mail Add-in (read & compose forms)
? Technology to use: Manifest.xml only (no application source files)
? Supported Outlook extension points: Message read, Message compose, Appointment a
ttendee, Appointment organizer
? Add-in start URL:
? Add buttons to: (Press <space> to select)
? Add buttons to: Default tab, Custom tab
? Supported button types: UI-less button, Drop-down menu button, Task-pane launche
r button
? Function file URL: https://localhost:8443/FunctionFile/Functions.html
? Task pane URL: https://localhost:8443/TaskPane/TaskPane.html
? Icon URL: https://localhost:8443/images/icon.png
   create manifest-badvalue-test.xml
```

This results in the following in the manifest:

```
<FormSettings>
  <Form xsi:type="ItemRead">
    <DesktopSettings>
      <SourceLocation DefaultValue=""/>
      <RequestedHeight>250</RequestedHeight>
    </DesktopSettings>
  </Form>
  <Form xsi:type="ItemEdit">
    <DesktopSettings>
      <SourceLocation DefaultValue=""/>
    </DesktopSettings>
  </Form>
</FormSettings>
```

When you try to upload the manifest, a schema validation error is thrown due to the empty `DefaultValue` attributes on the `SourceLocation` elements.

**Comment by jthake** [comment]
Interesting...so yeoman validation isn't great. @waldekmastykarz have you got any experience with this?

**Comment by jasonjoh** [comment]
Really all we need to do is make that prompt reject empty, maybe add a default value?

**Comment by waldekmastykarz** [comment]
@jasonjoh have you checked if the current validation task picks it up? If it does then combining it with rejecting an empty value in the generator would be sufficient imho.

**Comment by jasonjoh** [comment]
Yes it does, but running it against the manifest isn't trivial. When you do manifest only, we don't copy over the gulpfile with all of the validation stuff in it. So I had to do manifest only to create my repro manifest, then create an HTML addin in the same directory (just change the project name so the manifests won't overwrite) to get the gulpfile.

On a side note this caused a fatal error in `validate-forstore`. I'll check if there's an open issue on this and file one if not :)

**Comment by waldekmastykarz** [comment]
This is inconvenient indeed. It might be worth revisiting the idea of the manifest-only option and whether we should include `gulpfile.js` in it.

@jthake what's your thoughts on this?
