### ISSUE TITLE
Can't deselect Add buttons to default tab or custom tab

### ISSUE THREAD

**Issue by HamletHakobyan** [OfficeDev/generator-office#136]
Can't deselect Add buttons to default tab or custom tab when trying to use command "yo office:mail" and choosing technology as Angular. (Windows 8.1, npm version 2.11.3, yo version 1.6.0)

**Comment by HamletHakobyan** [comment]
Somebody can take care about this issue?

**Comment by jthake** [comment]
Right now we are stacked on things leading up to Build 2016 event so this is not a priority unfortunately. We will get to this shortly. @jasonjoh can you replicate this in your env?

**Comment by jasonjoh** [comment]
Yes, I can reproduce it. I believe it's an issue with the prompting library Yeoman uses. I can investigate after all the Build madness :)

**Comment by TCourtneyOwen** [comment]
Very stale issue. Please reactivate if this is still an issue
