### ISSUE TITLE
gulp-weberserver and routing

### ISSUE THREAD

**Issue by Mimetis** [OfficeDev/generator-office#137]
Hi guys;

Actually, I try to implement some customs routes to be able to create some API handlers in my office addin project
I tried some routing packages, but no one are actually working as expected. I actually find a solution with the package **connect-routing** but I have to modify the source code.
Finally I have something like that :

```
var Router = require('connect-routing');
var router = Router.instance();

router.addRoute('/api/videos', function (req, res, next) {
    var results = [{name:'john'}, {name:'alex'}];
    res.send(JSON.stringify(results));
    next();
});

gulp.task('serve-static', function () {
    gulp.src('.')
        .pipe(webserver({
            https: true,
            port: '8443',
            host: 'localhost',
            directoryListing: true,
            fallback: 'index.html',
            middleware : Router.middleware
        }));
});
```

As I said, It works as expected, but I have to modify the package code.
Do you know any way to do it in a more straightforward manner ?

Sebastien

**Comment by Mimetis** [comment]
Ok I investigate a lot on this behavior.
Actually, **gulp-webserver ** can't work with Azure (and it's node.js implementation with [IISNode](https://github.com/tjanczuk/iisnode) )

**gulp-webserver** needs to specify an host (if you don't gulp-webserver will use a default value to localhost) 
If you go in a submodule called **tiny-lr**, you will find this :

```
Server.prototype.listen = function listen(port, host, fn) {
  this.port = port;

  if (typeof host === 'function') {
    fn = host;
    host = undefined;
  }

  this.server.listen(port, host, fn);
};
```

But IISNode on Azure needs to configure the http listener without host  like explained here on the [Express node.js sample on Azure](https://tomasz.janczuk.org/2011/08/hosting-express-nodejs-applications-in.html)

As you can see, the host is mandatory. Actually I tried severals solutions, based on the [node.js http documentation](https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback), but no one works as expected.

So today, you can't develop a full web solution (server and client side) based on this template.

Why client code works if the **gulp-webserver** is not compatible with Azure ?

When you deploy your solution to Azure, the **gulp task serve-static is not called** , but thx to IISNode, node.js is invoked and will serve all static files (that's why everything works on client side)

Actually I stopped to use a custom routing system, and I finally decided to create two applications. 
One for client part and one for server part (with a simple node.js / express application)

I think we should definitively think on an alternative solution, compatible with Azure deployment :)

**Comment by jthake** [comment]
good hunting here ;-)

There was another exploration by @stfbauer who wrote #119 and investigated that. Do you know whether this is safe with Azure deployment?
