### ISSUE TITLE
Consider moving from tsd to typings for the type definition manager

### ISSUE THREAD

**Issue by gregvanl** [OfficeDev/generator-office#139]
TSD is being deprecated in favor of Typings (see DefinitelyTyped/tsd#269).
Currently the generator output includes a tsd.json files for typings.  Typings supports typings.json.

When this is issue is fixed, please update the VS Code doc issue https://github.com/Microsoft/vscode-docs/issues/183 and we'll update the Office topic to use Typings.

**Comment by jthake** [comment]
Thanks for heads up on this. Yes I m aware of the TSD being deprecated aspect, there are a few deprecated libraries in here. We need to find a resource to do this and test it. Right now we are all heads down on Build 2016. As this is not a breaking change it is not urgent.

**Comment by gregvanl** [comment]
@jthake Looks like TSD is really deprecated now.  http://definitelytyped.org/tsd is no longer resolving to the tool.

**Comment by bogacg** [comment]
Any progress in this front?

**Comment by bogacg** [comment]
I've followed [Upgrade](https://github.com/typings/typings/blob/master/docs/tsd.md#upgrade) steps as described in typings docs. Hope it doesn't break.

**Comment by josteink** [comment]
Normally I'd consider sending a PR for something like this, but the (lack of) attention other PRs are getting makes me not consider it worth the effort.

@jthake Is this repo abandoned at this point? Should the community create its own fork?

**Comment by beth-panx** [comment]
Hey guys! Great feedback. I am currently working on the next version of generator-office. It is moving away from tsd and will use typings instead.

**Comment by gregvanl** [comment]
@beth-panx Would you also be the person to do a freshness pass over the Office topic oncode.visualstudio.com? The Markdown is at https://github.com/Microsoft/vscode-docs/blob/master/docs/runtimes/office.md.
VS Code is doing a freshness pass over all our docs next week and we wondered who could review the Office topic to make sure it is still accurate.

**Comment by josteink** [comment]
@beth-panx  actually now typing a has been deprecated in favor of the new @types NPM organization. you install types by typing:

    npm install @types/libname

And that's it. No need for any additional tools .

**Comment by bogacg** [comment]
@josteink also, they are automaticaly included under node_modules folder of subject library so that devs using those libraries don't have to `npm install @types/libname` seperately, Typescript 2 understands that and so does VS Code. What I try to say is once `@types` are defined for current version they should also be included in main project for ease of use.

**Comment by josteink** [comment]
Agreed. I was thinking in case the generator had dependent libraries. 

Thinking it through though, you have 2 dimensions: consumed modules and exported modules. 

Obviously both needs to be addressed.

**Comment by beth-panx** [comment]
@slabereemsft could you take a look at the link @gregvanl provided and point us to the proper path/contact here?

**Comment by beth-panx** [comment]
@josteink looks like yeoman generator hasn't made it to @types npm org yet. However, it's certainly an interesting/easy way to install types for the dependent libraries. 

@bogacg how's the results when you follow the [upgrade](https://github.com/typings/typings/blob/master/docs/tsd.md#upgrade) doc? Wanna send a pr if it works? 😬

**Comment by beth-panx** [comment]
New release v1.0 leverages @types for both yo office itself and the generated projects.
