### ISSUE TITLE
location of certificate for gulp webserver is unclear

### ISSUE THREAD

**Issue by TristanD-MSFT** [OfficeDev/generator-office#141]
In readme.md, the instructions instruct the reader to trust the self-signed certificate used by the gulp serve-static, but does not specify the location of the certificate that they need to trust (just linking to the generic TechNet instructions for trusted a self-signed cert).

**Comment by chanmm** [comment]
Agree, I am still finding the location.

**Comment by ynp7** [comment]
Seriously! Where is the certificate?

**Comment by manaswi** [comment]
No, Seriously. No kidding. Where is it?

**Comment by beth-panx** [comment]
![screen shot 2016-12-08 at 2 04 37 pm](https://cloud.githubusercontent.com/assets/7429891/21029591/565b9c30-bd4f-11e6-95eb-bd27fde2657c.png)

At the last step when you are ready to import the cert.
1. Trusted Root Certification Authorities -> All Tasks -> Import
2. Certificate Import Wizard -> Next
3. File to Import -> Browse
4. ~/your_yo_office_project/node_modules/gulp-webserver/ssl/dev-cert.pem
** Make sure to change file type to *.* when you are in the directory to see all cert files.
