### ISSUE TITLE
Include ngOfficeUIFabric to be able to use the Office UI Fabric components?

### ISSUE THREAD

**Issue by rolandoldengarm** [OfficeDev/generator-office#145]
I would like to add an option to the generator to be able to include [ngOfficeUIFabric](https://github.com/ngOfficeUIFabric/ng-officeuifabric/). This way a developer could easily leverage this repository to use the Office UI Fabric components in his application without needing to copy/paste HTML. Is that OK?

**Comment by jthake** [comment]
That sounds like a great idea. You'd only be adding this to the Angular language flow right?

**Comment by rolandoldengarm** [comment]
Yes. So, if Angular is selected => next question is to include ngOfficeUIFabric.

Currently there are a ng and a ng-adal tech. Should I add 'ng-officeuifabric' as well? But what if a user wants both ADAL and Office UI Fabric?

**Comment by jthake** [comment]
mmm I would add thsi by default. we use fabric already i believe in these templates. Can ngOfficeUIFabric coexist fine with fabric already referenced? As I know this doesnt' do everything that Fabric can do directly just yet.

**Comment by rolandoldengarm** [comment]
That is no problem. ngOfficeUIFabric does not include the OfficeUIFabric CSS files, only a set of Angular directives.
But you are right that not all directives have been implemented yet, [there are 4 directives that have not been assigned yet](https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues?q=is%3Aopen+is%3Aissue+label%3Ahelp-wanted). All other directives have either been implemented or are about to be released.

**Comment by jthake** [comment]
So I'd suggest just having us use this  for the angular selection.

**Comment by rolandoldengarm** [comment]
OK All good! Can this issue be assigned to me please?

**Comment by andrewconnell** [comment]
LGTM from a pure code change... the new option is definitely welcomed IMHO

**Comment by rolandoldengarm** [comment]
@jthake Can you please review the PR and if OK, merge it? I'd like to write a blog post about it.

**Comment by jthake** [comment]
appreciate your eagerness here. I'm buried with Build 2016 event planning right now. I need to test this myself and have not had time. This'll have to wait until at least next week if not after build in all honesty.

**Comment by beth-panx** [comment]
Hey @rolandoldengarm could you take a look at the comments on the pr #157 you submitted? I'd be happy to test it again when you are done. Or else I will close both soon. :)

**Comment by rolandoldengarm** [comment]
@beth-panx sorry as it has been a long time ago, I don't have the repo configured on my machine anymore. I'll need to set it up again first, will try to do it next week!

**Comment by beth-panx** [comment]
Awesome!! Thank you 💯

**Comment by beth-panx** [comment]
In the new structure, we included Office UI fabric in package.json which uses the new Fabric Core and Fabric JS. #157
