### ISSUE TITLE
The ng templates don't reference the app

### ISSUE THREAD

**Issue by rolandoldengarm** [OfficeDev/generator-office#147]
When creating an ng-application, the HTML does not contain an attribute ng-app. So, the Angular module is never instantiated.
I ran into this issue when working on the change to incorporate ngOfficeUIFabric.

**Comment by rolandoldengarm** [comment]
This issue has been merged, closing.

**Comment by gavinbarron** [comment]
Dang, wish I'd spotted this earlier. The lack of ng-app attribute was due to the delayed bootstrapping approach when using ADAL.

**Comment by rolandoldengarm** [comment]
Ah, @gavinbarron so for ng-adal the ng-app should not have been added as part of this change?

**Comment by andrewconnell** [comment]
You can't load an Angular app in an Office Addin using `ng-app`... you must bootstrap it. The traditional option of using `ng-app` causes conflicts between the `office.js` & `angular.js` file with race condition on loading and neither will work. The reliable way to do it is to have Angular load first and then initialize `office.js`.

**Comment by jthake** [comment]
OK So i need to roll that out of the dev branch then. Thanks @andrewconnell .

**Comment by gavinbarron** [comment]
Just so I'm getting this straight @andrewconnell: The correct way to load up angular and office is to:
* Create the angular module
* Initialize Office
* Bootstrap the module to the template in the initialize function

Just asking as I found that the only way I could get an Outlook add-in to successfully run with ADAL was to make use of ng-app which I now suspect is only working due to lucky timing (even though I've not seen it fail once)

**Comment by andrewconnell** [comment]
@gavinbarron From my experience, you're simply lucky. I never had this issue in dev, but when hosting in production, I did have race conditions that were happening. I made Office aware of it and they suspected it was something in Office.js that was causing it.

What I recommend is you create the Angular module and very soon after that, implement the `Office.initialize()` function. Within that function, it bootstraps the Angular app. You can see a [full example here](https://github.com/andrewconnell/pres-o365-node/tree/master/officeaddin-outlook) (*ignore the fact it's old TypeScript... public sample from a session last year), or look at this snippet:

```typescript
(() => {
  'use strict';

  // create the angular app
  var app = angular.module('outlookApp', [
    'ngRoute',
    'ngAnimate',
    'ngSanitize',
    'ngMaterial'
  ]);

  // configure the app
  app.config([
    '$logProvider',
    '$routeProvider',
    '$mdThemingProvider',
      ($logProvider: ng.ILogProvider,
       $routeProvider: ng.route.IRouteProvider,
       $mdThemingProvider: any) => {

    // set debug logging to on
    if ($logProvider.debugEnabled) {
      $logProvider.debugEnabled(true);
    }

    // setup routing
    outlookApp.Routes.configure($routeProvider);

    // configure theme color
    $mdThemingProvider.theme('default')
                      .primaryPalette('blue');
  }]);

  // when office has initialized, manually bootstrap the app
  Office.initialize = () => {
    angular.bootstrap(jQuery('#container'), ['outlookApp']);
  };

})();
```

**Comment by gavinbarron** [comment]
Thanks. Looks like what I have is a) working by luck of timing and b) not going to work when done correctly at present :| 

I'll raise another issue but suspect that the bug is in outlook-web-16.01.js when used in an ADAL IFrame

**Comment by andrewconnell** [comment]
FWIW, I’ve seen it consistently without any ADAL involvement. In addition, I have not tested anything in the v16 release because it’s not in all clients.

**Comment by rolandoldengarm** [comment]
Ok, good to know! We've been using ng-app in Office add-ins without any problems so far, but I've forwarded it to the team to do it differently.
But fact is, that the template doesn't do the bootstrapping too, which brings me back to my initial issue: the angular module is not loaded. Is there a reason for that? Should I add the bootstrapping to the templates?

**Comment by andrewconnell** [comment]
It doesn't? A spot check looks like it does to me: 

https://github.com/OfficeDev/generator-office/blob/master/generators/mail/templates/ng/appcompose/app.module.js#L21

https://github.com/OfficeDev/generator-office/blob/master/generators/mail/templates/ng/appread/app.module.js#L21

https://github.com/OfficeDev/generator-office/blob/master/generators/mail/templates/ng-adal/appcompose/app.module.js#L20-L29

**Comment by rolandoldengarm** [comment]
Thanks, and I'm very sorry... 
I was testing in the browser, and then obviously the Office initialize function is not being called.

So it's a non issue. My bad.

**Comment by rolandoldengarm** [comment]
@jthake Will you undo the commit? The PR is here: https://github.com/OfficeDev/generator-office/issues/149

**Comment by andrewconnell** [comment]
Yoda says commit not undo, forward fail, pr fix issue submit you shall…

**Comment by jthake** [comment]
I like @andrewconnell suggesiton. @rolandoldengarm could you fork the dev branch and fix this and submit a new PR that rolls this out of dev branch? This saves me the work. Just glad we cuaght this before i promoted to main branch.

**Comment by rolandoldengarm** [comment]
Done. Reverted my changes and submitted a PR: https://github.com/OfficeDev/generator-office/pull/155

**Comment by jthake** [comment]
PR #156 accepted into dev branch now. Thanks for doing this.
