### ISSUE TITLE
Outlook Add-in with ADAL consistently fails

### ISSUE THREAD

**Issue by gavinbarron** [OfficeDev/generator-office#154]
I realize that this might not be the appropriate place to raise this issue, happy to have it closed and open it elsewhere. Really want to get it out so that the right people can see the issue,

When using the generated code for an Outlook Add-In using ADAL the app crashes due to an error in the ADAL IFrame after-redirection back to the app.

The outlook-web-16.01.js script throws an errorSys.ArgumentNullException: Sys.ArgumentNullException: Value cannot be null. Parameter name: conversationId 

Under the recommended approach this happens before the angular app has had a chance to bootstrap and causes the app to stop at this point.

Utilizing an ng-app directive to automate the bootstrap and moving the Office Initialize call inside the home controller allows the angular app to start in the IFrame and gather the ADAL access token thus allowing the main window to continue as it now has credentials to make ADAL secured calls.

This has also been noted on SO: http://stackoverflow.com/questions/35358911/first-time-loading-outlook-web-add-in-error-on-console 

Happy to create a trivial re-pro if that's helpful

**Comment by gavinbarron** [comment]
Created a  repro repository and a branch with the trivial work around 
https://github.com/gavinbarron/Outlook-ADAL-Issue
https://github.com/gavinbarron/Outlook-ADAL-Issue/tree/work-around

**Comment by jthake** [comment]
I was having a discussion with @richdizz that we may pull out ADAL.js usage in Office add-ins as this really doesn't work in production scenarios and there are better patterns to use. Such as that shown in the Clause Library code sample that use sockets via signalR. There is a node sample too that shows this and a document on MSDN also https://msdn.microsoft.com/en-us/library/office/mt629180.aspx

**Comment by waldekmastykarz** [comment]
It would be great to have an implementation that works everywhere every time, so if there is a better pattern than what we have in the generator now, let's replace it :smile:

**Comment by scuba747** [comment]
Nine months have now gone by on this issue. Are there thoughts out there as to the approach that should be taken by developers to make their apps work from the generated add-in? Is dropping ADAL really the answer?

**Comment by nigel-dewar** [comment]
@jthake , can you please elaborate on why "ADAL.js usage in Office add-ins as this really doesn't work in production scenarios and there are better patterns to use"?

I mean, ADAL.js seem to work perfectly fine in an office add-in, (I am yet to use in production though), and its allot simpler to work with than than fancy but complicated solution using SignalR and storing access_token and refresh_token in database.

**Comment by kkrzaczkowski** [comment]
@jthake , Any progress with support of ADAL within Outlook add-in ?

@nigel-dewar , Is your office add-in still working with ADAL ?
My outlook add-in application worked 1 month ago but now is broken. I gets the same error like gavinbarron .

**Comment by pwombwa** [comment]
@gavinbarron Kindly explain the work around you used here https://github.com/gavinbarron/Outlook-ADAL-Issue/tree/work-around
