### ISSUE TITLE
Error generating mail add-in

### ISSUE THREAD

**Issue by richarddavenport** [OfficeDev/generator-office#160]
node -v v5.10.1
npm -v 3.8.3
generator-office 0.6.5

I'm trying to generate a simple Mail add-in, but get this error
`error git submodule -q update --init --recursive: fatal: repository 'https://git.gnome.org/libxml2/' not found`

Here's one of the commands I've tried:
`yo office:mail --name 'Mail Add-In' --root-path '' --tech 'html' --extensionPoint 'MessageReadCommandSurface'`
Here is my [npm-debug.log](https://github.com/OfficeDev/generator-office/files/210608/npm-debug.txt)

I've tried on OS X and Windows 2008 R2 with the same outcome.

**Comment by jthake** [comment]
does this work for you in command prompt?
`git clone git://git.gnome.org/libxml2`

**Comment by richarddavenport** [comment]
Nope: 
```
git clone git://git.gnome.org/libxml2
Cloning into 'libxml2'...
fatal: repository 'https://git.gnome.org/libxml2/' not found
```
What would cause something like this?

**Comment by jthake** [comment]
Yes. As that works for me and three others I"ve reached out to. Must be something on your machine locking it down. Can you even resolve DNS on that url?

**Comment by richarddavenport** [comment]
Wow... Okay so it was a git configuration issue. At work we're behind a proxy that doesn't like the git:// protocol, so I configured git to only use https://. I've never had any problems, until now. 
Here's the problem:
<img width="312" alt="rad 2016-04-08 at 4 39 43 pm" src="https://cloud.githubusercontent.com/assets/3596012/14398313/c771002a-fda8-11e5-8b3c-627413626b95.png">

The https:// repo is at a different url, so it literally could not find it.

Thanks for the help @jthake!

**Comment by jthake** [comment]
No dramas, better than a change request that would mean work for me over this nice weekend ;-)
