### ISSUE TITLE
Change dist task behavior to replace base URL in manifest file

### ISSUE THREAD

**Issue by ministainer** [OfficeDev/generator-office#162]
Hi guys,
I'd like to propose a change to the dist gulp task by passing --url parameter  ie.
`gulp dist --url https://myaddin.azurewebsites.net/
`
another task 'replace-url' will kick in reading parameter from process.args using yargs  described here https://www.npmjs.com/package/yargs ,

if no url is passed original localhost baseurl will remain the same.

Thoughts?

Amr Fouad

**Comment by jthake** [comment]
that's actually a great idea. @andrewconnell was the brain child of this, i wonder whether he has implemented this in his more recent open source projects

**Comment by ministainer** [comment]
Great ,  I will wait for @andrewconnell  to confirm it's not implemented somewhere else, once it's ready to go I can have a PR ready for this one.

**Comment by andrewconnell** [comment]
Just noticed I was ping'd here... @ministainer I haven't done any work with this project in a while... so have at it. Unfortunately it seems the new owners of this project have not been keeping up with it... disappointing after such a strong start.

**Comment by jthake** [comment]
+1 to this too. I've been in new role for 3 months at microsoft and unfortunately just don't have the bandwidth to keep this up in my non work time either without support from Office engineering. There is an intern who has been handed this in Office engineering. It doesn't look like he has touched the repo though yet :-(

**Comment by ministainer** [comment]
Thanks for taking the time to reply, I think I don't have any other choice but wait :)

**Comment by andrewconnell** [comment]
Sure you do… fork it and use what you create! That’s the beauty in this solution.

**Comment by ministainer** [comment]
that's what I already did :) I even have a PR ready for that for a while now :+1:

**Comment by keyur32** [comment]
Hi there, we understand the frustration of this project, but we’re totally committed to it. After @jthake Jeremy left, we’ve been working through the staffing issues to pick this up.  To start with we’ve enlisted one our bright interns to coral and get up to date on moving this forward. We heard loud and clear this was a useful tool, and just started the discussions with @andrewconnell this week around the further investments we need to make to deliver an up-to-date experience.

**Comment by ministainer** [comment]
thanks @keyur32  I totally understand and keen to see more updates soon :)

**Comment by beth-panx** [comment]
Close by PR #167
