### ISSUE TITLE
ImageCoercion not enabled in Excel 2016/Excel online with from yo office

### ISSUE THREAD

**Issue by brucemcpherson** [OfficeDev/generator-office#168]
Actually I had posted this on the general office repo, before I realized that it seemed to be specific to yeoman generated projects. Apologize for the cross posting but I think this is the correct place. I'll make a note in the original issue (https://github.com/OfficeDev/office-js-docs/issues/289) that I've posted it here.

I'm trying to use ImageCoercion as in 

```
  Office.context.document.setSelectedDataAsync (png, {
        coercionType:Office.CoercionType.Image,
        imageLeft:offx ,
        imageRight:offy 
      } .... etc.
```

However this is refused by Excel 2016 & Excel Online. I did this to see what was supported (im using api v1.1)

```
   ['TextBindings','TextCoercion','TableCoercion','TableBindings','Settings',
        'MatrixBindings','MatrixCoercion','ImageCoercion','DocumentEvents',
        'BindingEvents','ExcelApi'].forEach(function (d) {
          console.log(d+':'+Office.context.requirements.isSetSupported(d,'1.1'));
        });
```

and it confirmed that ImageCoercion is not supported

```
TextBindings:true
TextCoercion:true
TableCoercion:true
TableBindings:true
Settings:true
MatrixBindings:true
MatrixCoercion:true
ImageCoercion:false
DocumentEvents:true
BindingEvents:true
ExcelApi:true
```

If I make it a requirement, the add-in fails to load at all.

```
 <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="ImageCoercion" MinVersion="1.1"/>
   </Sets>
   <Methods>
      <Method Name="Document.getSelectedDataAsync"/>
   </Methods>
</Requirements>
```

Additional info. For testing I fell back to the sample project created by  yeoman with yo office and confirmed that ImageCoercion is not supported. I then created the sample project that comes  with Visual Studio, added the same code, and ImageCoercion is supported. I then copied the manifest from VS to the Yo sample and it still shows as unsupported. So the issue is somehow between the VS environment and the simple YO environment. The same result for both content and taskpane.

**Comment by brucemcpherson** [comment]
Hi anyone... I notice that nobody has been assigned to look into this yet. If this is the wrong place to report this issue, can anyone point me to a different place. I'm doing this to see whether Google apps addons can be ported to Microsoft addins, and this is one issue that's stopping me progressing...

**Comment by beth-panx** [comment]
Please refer to office-js-doc [issue #289](https://github.com/OfficeDev/office-js-docs/issues/289)
