### ISSUE TITLE
Add TypeScript as an option for Technology to use

### ISSUE THREAD

**Issue by kcraigo** [OfficeDev/generator-office#17]
Maybe I'm just being lazy but TypeScript to me would be a great option to have in the list of Technology to use choices.

**Comment by alexkieling** [comment]
I would like to work on this task. We just need to discuss how to offer this option in the yeoman generator. Please add more details about the feature.

**Comment by kcraigo** [comment]
Hi Alex, 
When I suggested this I thought I was going to have some down time but the very next day I got pulled into a big project at work which is still ongoing, as a result I've had no time to devote to this, sorry Andrew. 
If you want to take the lead in this that would be fine with me.

**Comment by andrewconnell** [comment]
When I imagined how this would work, I expected another question added when you picked a template tech that involved JavaScript today (like the Angular options), it would then ask if you wanted JS / TS.

This is run by MSFT (@jthake) so I’ll defer to him to discuss implementation with you.

**Comment by pgrm** [comment]
Now that Angular2 is out, maybe there can be a template based on `ng-cli` with angular2 and typescript?

**Comment by beth-panx** [comment]
We are currently modifying the workflow of the project for vNext. I have added typescript support for both contributors and customers. Right now only jQuery and Angular1 are scheduled for release. @kcraigo and @alexkieling, help me review it once it's out? I will keep you both posted! @pgrm great idea on Angular2 and TypeScript template!

**Comment by beth-panx** [comment]
This is included in the new release. Feedback wanted and more than welcomed!
