### ISSUE TITLE
local reference to Office.js for offline debugging not working

### ISSUE THREAD

**Issue by jonasrk** [OfficeDev/generator-office#170]
Hi!

When I comment out the online office.js import and uncomment the offline one, office.js does not load.

I've been testing this on a freshly generated `yo office` project (Task-Pane, Excel, HTML/CSS/JS) and encounter the same behavior on Microsoft Excel for Mac Version 15.23.2 (160624) as well as Excel Online in Chrome.

Here's what I tried:
- replace the capital O in the Office folder of the path to a lower case o since this is how it is stored in my file-system: didn't work
- renaming that folder in my file system to capital O: didn't work
- moving the file office.js into the project root and adjusting the import reference: didn't work
- replacing the office.js provided by the generator with the file that is referenced in the online reference (`appsforoffice.microsoft.com/lib/1/hosted/office.js`): didn't work

It would be really nice if someone could look into this as it would be super nice to have offline debugging working ... thanks!

**Comment by beth-panx** [comment]
@jonasrk Hi there! It's been a long time coming but we have released a new version that incorporated latest Officejs and Fabric. Would you like to give it a try?

**Comment by beth-panx** [comment]
Hello @jonasrk, I am following up to see if you get a chance to try the generator again? Closing this soon.
