### ISSUE TITLE
Validation issue with Office 365 Exchange Online

### ISSUE THREAD

**Issue by YannickGagnon** [OfficeDev/generator-office#171]
Project generated from this generator is incompatible with Office 365. It fails to import with the following errors:

1. Schema Validation failed. Please ensure that your app manifest is a valid Office or SharePoint app manifest file.
2. The icon URL supplied in the app manifest is not valid or the file supplied is not a valid image. Icon URL: https://localhost:8443 **(Tried with a valid url without any more luck)**
3. Icon incorrectly sized - Your icon height is: 80. Your icon width is: 80. Your icon's dimensions should be at least 128*128 and no larger than 128*128

When I updated the HighResolutionIconUrl to be 128x128, it started complaining that:
1. IconUrl was not found
2. SupportUrl was not found

Then I figured there might be discrepancies between the provided schema and the one used by office 365, so I provided everything Office 365 complained about.

Which leaves me with the mysterious error:

- Schema Validation failed. Please ensure that your app manifest is a valid Office or SharePoint app manifest file.

Thanks,

**Comment by jasonjoh** [comment]
Thanks for the report @YannickGagnon! Can you confirm the options you used to create the add-in that failed for you?

**Comment by YannickGagnon** [comment]
Here it is @jasonjoh 

? Project name (display name): My Office Project
? Root folder of project? Default to current directory
 (/Users/YannickGagnon/Sites/Project), or specify relative path
 from current (src / public):  .
? Office project type: Mail Add-in (read & compose forms)
? Technology to use: HTML, CSS & JavaScript
? Supported Outlook extension points: Message compose

**Comment by jasonjoh** [comment]
Ok, I just tried the same options and had no problem with Office 365. Would you mind attaching your manifest? Here's what `yo office` generates for an icon for me:

`<HighResolutionIconUrl DefaultValue="https://localhost:8443/images/hi-res-icon.png"/>`

**Comment by YannickGagnon** [comment]
When I run: gulp validate --xmlfile manifest-my-office-project.xml 

I get:

[14:18:16] Using gulpfile ~/Sites/Humail/gulpfile.js
[14:18:16] Starting 'validate-xml'...
 
Manifest XML invalid
file_0.xml:28: element VersionOverrides: Schemas validity error : Element '{http://schemas.microsoft.com/office/mailappversionoverrides}VersionOverrides', attribute '{http://www.w3.org/2001/XMLSchema-instance}type': The QName value '{http://schemas.microsoft.com/office/mailappversionoverrides}VersionOverridesV1_0' of the xsi:type attribute does not resolve to a type definition.
file_0.xml:28: element VersionOverrides: Schemas validity error : Element '{http://schemas.microsoft.com/office/mailappversionoverrides}VersionOverrides': The type definition is absent.
[14:18:17] Finished 'validate-xml' after 981 ms
[14:18:17] Starting 'validate-highResolutionIconUrl'...
[14:18:17] Finished 'validate-highResolutionIconUrl' after 22 ms
[14:18:17] Starting 'validate-forstore'...
ERROR: 7.16. You must specify a valid Support URL in the SupportURL element of your Office Add-in manifest.
FIX: Add the SupportUrl element to the manifest, eg. <SupportUrl DefaultValue="http://contoso.com/support" />
[14:18:17] Finished 'validate-forstore' after 22 ms
[14:18:17] Starting 'validate'...
[14:18:17] Finished 'validate' after 12 μs

**Comment by YannickGagnon** [comment]
Here's the manifest.xml I came up with to comply with Office 365

[manifest-outlook-add-in.xml.txt](https://github.com/OfficeDev/generator-office/files/366649/manifest-outlook-add-in.xml.txt)

**Comment by YannickGagnon** [comment]
If that makes any difference, I run:

- node: v4.4.5
- npm: 2.15.5
- yo 1.8.4
- generator-office@0.6.6

**Comment by jasonjoh** [comment]
Ok, so the problem you're having with `SupportUrl` is in the placement. The schema is strict in requiring it in a specific place. It needs to appear immediately after `HighResolutionIconUrl`:

```
<IconUrl DefaultValue="https://our-company-website/images/icon-128.png"/>
<HighResolutionIconUrl DefaultValue="https://our-company-website/images/icon-128.jpg"/>
<SupportUrl DefaultValue="http://our-company-website/support" />
```

The generator doesn't include `SupportUrl`, so when you try to add it, you run into this problem. Updating the generator to include this element in the correct place would be helpful I think.

**Comment by YannickGagnon** [comment]
That's where I had the SupportUrl the first time, but even when placing it after HighResolutionIconUrl, I get the same result.

Schema Validation failed. Please ensure that your app manifest is a valid Office or SharePoint app manifest file.

**Comment by jasonjoh** [comment]
Is that error from Exchange or from the `gulp validate` task? Because I made the change to your manifest and Exchange accepted it for me.

**Comment by YannickGagnon** [comment]
That is from exchange, the local error is this one

https://github.com/OfficeDev/generator-office/issues/171#issuecomment-233033009

**Comment by jasonjoh** [comment]
Hmm. There must be something different, but I can't reproduce this on 2 different accounts. Can you try this version just for my own sanity? If that fails for you, then maybe we're on different server builds.

[manifest-outlook-add-in.xml.txt](https://github.com/OfficeDev/generator-office/files/366737/manifest-outlook-add-in.xml.txt)

**Comment by YannickGagnon** [comment]
Now we get this error from exchange:

Exception thrown when extracting the given manifest. 'System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary. at System.Collections.Generic.Dictionary`2.get_Item(TKey key) at Microsoft.Office.AssetValidationEnvironment.ManifestExtraction.PrivateCatalogManifestExtraction.GenerateLightweightManifestExtract(IManifestExtractionRequest request) at Microsoft.Office365.Management.BusinessLogic.PrivateCatalogBusinessLogic.ExtractManifest(Byte[] addInContents, IPrivateCatalogManifestExtractionResult& extractionResult, String domain, Boolean isUpdate, Guid id, String version)'

**Comment by jasonjoh** [comment]
Ok. Let me check with some folks internally.

**Comment by YannickGagnon** [comment]
@jasonjoh Thanks, 'cause we're pulling our hair out!!!

**Comment by jasonjoh** [comment]
Just to verify, you're getting this error when you're trying to install the add-in "from a file" (similar to the steps at https://github.com/jasonjoh/command-demo/)? Also what is your OWA url?

**Comment by jasonjoh** [comment]
Yannick, the devs I spoke with think that maybe you're trying to install the add-in from the admin portal through private catalogs? Private catalogs don't support Outlook yet. You should be following the steps from the link I showed above (for a single user) or from the Exchange Control Panel for an entire organization.

https://outlook.office.com/owa/?path=/options/manageapps should be the link for a single user. Let me know if your add-in loads for you using that method.

**Comment by jasonjoh** [comment]
I'll be on vacation next week, I'll ask the other owners to keep an eye on this.

**Comment by YannickGagnon** [comment]
Thanks @jasonjoh 
You're right, I was trying to add it through the Admin Center.

Enjoy your time off!

**Comment by jasonjoh** [comment]
Hey Yannick, I'm back from vacation and just wanted to confirm you were able to install from the link I provided?

The good news is that the error you're seeing was a known issue that they're fixing as part of the work to get Outlook supported via the admin portal :).

**Comment by YannickGagnon** [comment]
Hey @jasonjoh, Just came back from my vacations :)

Thanks, I was effectively able to install my development add-in for my account and hook it to a local host server.

Btw,  do you know where, if possible, I could get roadmaps of what's coming and when?

We're looking for a way to write a cross-platform add-in which would ideally, kick in automatically before sending and email.

Thanks,
