### ISSUE TITLE
'Office.js has not been fully loaded yet' when trying to call custom API

### ISSUE THREAD

**Issue by ChristianHaase** [OfficeDev/generator-office#172]
I'm not sure whether this is okay to post here, but I think it might be somewhat to the generator and the code it creates.

I have a custom API in Azure AD and this is included in my endpoints like this:

```
endpoints = { 
  'https://some-sign-on-url.azurewebsites.net': 'client-id-for-api' 
}
```

From this I should be able to connect to my API correct?
Now whenever I call a request to the API, I expect it to return some data. Instead though, I'm getting the following console error:

`SCRIPT5022: Office.js has not been fully loaded yet. Please try again later or make sure to add your initialization code on the Office.initialize function.`

If you need further code, please tell me.

**Comment by beth-panx** [comment]
The initialization function for Officejs is in the generated home.js file. Where do you put your initialization code?

**Comment by beth-panx** [comment]
@ChristianHaase following up to see if you still need help 🤓

**Comment by ChristianHaase** [comment]
Sorry for the late answer, but I do not need further help.
