### ISSUE TITLE
Support for SharePoint Add-Ins

### ISSUE THREAD

**Issue by justsayno** [OfficeDev/generator-office#173]
If I am right this generator is only for Office Add-Ins not SharePoint Add-Ins.

Are there any tools for SharePoint Add-Ins like this other that Visual Studio? Or even some resources on how you could do a local dev build like this for SharePoint Online Add-Ins.

**Comment by beth-panx** [comment]
I was just talking with some of my colleagues about this last week and looks like we have a developer preview program [here](https://github.com/SharePoint/sp-dev-docs). I also played around with [generator-sharepoint](https://www.npmjs.com/package/@microsoft/generator-sharepoint) myself for a bit and it's pretty cool! Hope this helps.

**Comment by samkevin** [comment]
I would like to recommend 365Appz SharePoint Accelerator Kit. I have used these [SharePoint online add-ins](http://365appz.ngenioussolutions.com/) which include 19 different add-ins, 3 custom theme and multiple beautiful layouts with modern design. It will definitely work for you. You can easily build intranet or SharePoint portal within days.
