### ISSUE TITLE
Schema validity errors in generated manifest file

### ISSUE THREAD

**Issue by vboctor** [OfficeDev/generator-office#176]
Manifest XML invalid
file_0.xml:40: element VersionOverrides: Schemas validity error : Element '{http://schemas.microsoft.com/office/mailappversionoverrides}VersionOverrides', attribute '{http://www.w3.org/2001/XMLSchema-instance}type': The QName value '{http://schemas.microsoft.com/office/mailappversionoverrides}VersionOverridesV1_0' of the xsi:type attribute does not resolve to a type definition.
file_0.xml:40: element VersionOverrides: Schemas validity error : Element '{http://schemas.microsoft.com/office/mailappversionoverrides}VersionOverrides': The type definition is absent.

**Comment by hdnha11** [comment]
I'm facing the same problem when running `gulp validate --xmlfile manifest.xml`.

Manifest XML invalid
file_0.xml:39: element VersionOverrides: Schemas validity error : Element '{http://schemas.microsoft.com/office/mailappversionoverrides}VersionOverrides', attribute '{http://www.w3.org/2001/XMLSchema-instance}type': The QName value '{http://schemas.microsoft.com/office/mailappversionoverrides}VersionOverridesV1_0' of the xsi:type attribute does not resolve to a type definition.
file_0.xml:39: element VersionOverrides: Schemas validity error : Element '{http://schemas.microsoft.com/office/mailappversionoverrides}VersionOverrides': The type definition is absent.

**Comment by beth-panx** [comment]
Hey @vboctor and @hdnha11 sorry for the late reply, we are aware of this problem and have been actively brainstorming solutions. I have backlogged this into it's own feature and will work on it soon. As of right now, please refer to [this document](https://dev.office.com/docs/add-ins/overview/add-in-manifests) for validation information.
