### ISSUE TITLE
Add "HiResolutionIconUrl" in manifest.xml by default

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/generator-office#18]
Apparently having the HighResolutionIconUrl element [is mandatory](https://msdn.microsoft.com/en-us/library/office/jj220035.aspx#bk_5) in submitting an Office Add-in. Might as well include that by default then.

**Comment by andrewconnell** [comment]
Hmmm... I'm not seeing it in that link... searched for **HighResolutionIconUrl**

**Comment by martellaj** [comment]
It was feedback I got when my app was reviewed. Maybe a bug in the content. I'll follow up when I get to the office.

**Comment by andrewconnell** [comment]
OK I see it listed in the [manifest schema](https://msdn.microsoft.com/en-us/library/office/fp123711.aspx) but the schema does not say it is required... however i'll include it as it can't hurt.

It's included in a future update that I'll push from my fork: b1eae8f894849df0aceffed23f2ba13304c9d580

**Comment by andrewconnell** [comment]
Oops... pulling this out of task pane & content apps... can't find it in the Office Store requirements link you have above, but did find it here as being listed only for mail apps: https://msdn.microsoft.com/en-us/library/office/fp161044.aspx
