### ISSUE TITLE
Outlook: Make manifest-only option use the add-in start URL as basis for other URLs

### ISSUE THREAD

**Issue by jasonjoh** [OfficeDev/generator-office#180]
Currently when you create a mail add-in with the manifest-only option, it asks for the "Add-in start URL", and then asks for the "Function file URL" and "Task pane URL". Function file and task pane ignore whatever you enter for start URL and default to `https://localhost:8443/...`. Would be good to derive the default value from the provided start URL.

**Comment by casieber** [comment]
The generator flow for manifest-only mail add-in has changed, making this issue obsolete.

Closing.
