### ISSUE TITLE
Confused about Angular setup

### ISSUE THREAD

**Issue by bpkennedy** [OfficeDev/generator-office#182]
I generated a new Angular type (not Angular ADAL) and tried to immediately `gulp serve-static`.  I navigated to https://localhost:8443/index.html, and it appears that this code in `app.module.js` is never getting called/executed:

```
  // when Office has initalized, manually bootstrap the app
  Office.initialize = function(){
    console.log('>>> Office.initialize()');
    angular.bootstrap(document.getElementById('container'), ['officeAddin']);
  };
```

Is this intended?  I found that `Office` was loaded on window.  I could put `Office.initialize()` in the console and then angular would fire up, triggering a bunch of console logs I'd put in the .config and .controller.

**Comment by bpkennedy** [comment]
Ohh....I think I see.  I just tried uploading the manifest to Word Online and it loaded on it's own.  I guess this was because I tried serving it up outside of office?  

That kind of confuses me since I was just working locally in the SharePoint Framework generator.  I suppose they are two different things, so it's reasonable.

**Comment by beth-panx** [comment]
Hi there, as you can see from the documentation on [Office Dev Center](http://dev.office.com/getting-started/addins), you need to host your add-in somewhere and then sideload it in Office Online to debug it. Let me know if you have more questions. I'm closing this issue.
