### ISSUE TITLE
Installed everything as required - but yeoman complains that cannot find module 'gulp-replace-name'

### ISSUE THREAD

**Issue by nigel-dewar** [OfficeDev/generator-office#188]
Installed everything as required - but yeoman complains that cannot find module 'gulp-replace-name'

I even tried installing 'gulp-replace-name' globally to try and get over this hurdle, to no avail. Is this generator broken?

**Comment by beth-panx** [comment]
When do you see the error message? After npm install? I can't repro this.
Try
`rm -rf node_modules/
npm install`

**Comment by beth-panx** [comment]
When do you see the error message? After npm install? I can't repro this.
Try
`rm -rf node_modules/`
`npm install`
