### ISSUE TITLE
Add "SupportUrl" in manifest.xml by default

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/generator-office#19]
Apparently having the SupportUrl element is mandatory in submitting an Office Add-in. Might as well include that by default then.

**Comment by andrewconnell** [comment]
Where do you see that? 
https://msdn.microsoft.com/en-us/library/office/fp161044.aspx#O15AgaveManifestOverview_Common

**Comment by andrewconnell** [comment]
It's included in a future update that I'll push from my fork: b1eae8f894849df0aceffed23f2ba13304c9d580
