### ISSUE TITLE
Outlook addin not showing up in compose mail mode

### ISSUE THREAD

**Issue by Ibrahim-Islam** [OfficeDev/generator-office#195]

**Comment by beth-panx** [comment]
Hi @Ibrahim-Islam, can you verify that you have `generator-office@0.6.8` installed? I just tested on my machine with `yo office:mail `and it generated my project fine.

**Comment by beth-panx** [comment]
@Ibrahim-Islam  
Following up here.. closing the issue if this is no longer a problem.
