### ISSUE TITLE
The dist task does not work

### ISSUE THREAD

**Issue by vjrantal** [OfficeDev/generator-office#196]
After creating the mail add-in with default settings, the dist task does not work and the error is: `$.minifyCss is not a function`. You can see the full context of the error from https://gist.github.com/vjrantal/d1e1dcd4c878f9da83ef3a012dc61959#file-dist-task-error-txt-L504.

**Comment by beth-panx** [comment]
Good catch @vjrantal! This is because we replaced `gulp-minify-css` with `gulp-clean-css` in the last release due to the deprecation of minifycss. I am currently modifying the workflow of this project and moving away from gulp tasks for v.next.

If you want to submit a pull request for the current version, I will help review and merge it. 😁

**Comment by vjrantal** [comment]
@beth-panx: The fix is relatively simple and here is as reference commit that fixes it for a generated project https://github.com/stampery/office/commit/400065e3b6209bd4e4c76680ae01b2d601571a4c. I could do a PR which patches these files in this repository that all have the same issue:

```
generators/content/templates/common/gulpfile.js
generators/mail/templates/common/gulpfile.js
generators/taskpane/templates/common/gulpfile.js
```

However, if your next npm release is anyways deprecating gulp tasks, this fix wouldn't help anyone using the releases so I wonder is it worth the effort..?

On a related matter, I noticed that the vet task that is supposed to run JSCS isn't really running it and the following patch would be needed:

```
diff --git a/gulpfile.js b/gulpfile.js
index 04b8ec5..87fbaf2 100644
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -39,7 +39,8 @@ gulp.task('vet', function(){
     .pipe($.if(args.verbose, $.print()))
     .pipe($.jshint())
     .pipe($.jshint.reporter('jshint-stylish', {verbose: true}))
-    .pipe($.jscs());
+    .pipe($.jscs())
+    .pipe($.jscs.reporter());
 });
```

This change introduce `44 code style errors found.` and this is again something I could do a PR for, but not worthy in case you are changing all of this.

Let me know if you prefer fixes to the existing codebase or will the vnext solve these in a timely manner.

**Comment by beth-panx** [comment]
We actually decided on a potential beta release at the end of this month for a new workflow and typescript support. So I would suggest that if it's working for you with the fix in your repo, there's no need for a pr. There will prob be a separate tool for minify/uglify files for projects that spans across windows, mac os, etc. in the future. Gulp tasks will be deprecated. :) 

Hope this helps.

**Comment by beth-panx** [comment]
Closing this because v1.0 uses Browsersync other than gulp.
