### ISSUE TITLE
Your badges are 404ing

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [OfficeDev/generator-office#197]
https://camo.githubusercontent.com/83ec5b83ff2bbb953a6dd45da80f765c26ca6e3d/68747470733a2f2f64617669642d646d2e6f72672f6f66666963656465762f67656e657261746f722d6f66666963652e737667

See README.md.

![image](https://cloud.githubusercontent.com/assets/3335181/22124917/8ed404f4-de46-11e6-9889-160b54a063ed.png)

**Comment by beth-panx** [comment]
Sometimes those resolve really slowly due to organizational settings. It came back yesterday. Didn't really change anything. Thanks for the heads up!!
