### ISSUE TITLE
Beta: Sideloading portion of resource.html incorrect for Outlook

### ISSUE THREAD

**Issue by jasonjoh** [OfficeDev/generator-office#203]
It lists these steps:

```
1. Go to Outlook and create a blank document.

2. Go to Insert > Office Add-ins.

# On the My Add-ins tab (or My Organization tab if you're signed in to a work or school account),
# you'll see a link in the upper-right corner of the dialog box to Upload My add-in or Manage My Add-ins.
3. Manage My Add-ins will open a menu where you can then choose Upload My add-in.

4. Choose Browse and select the my-office-add-in-manifest.xml file from the root of the project folder, and then choose Upload.
```

This does not accurately reflect the Outlook experience.

**Comment by beth-panx** [comment]
@WrathOfZombies @nokafor

**Comment by nokafor** [comment]
You are correct. It should mirror [this page](https://dev.office.com/getting-started/addins) and say:

- From your mailbox, click the gear icon in the upper-right corner of the page and choose Manage Add-ins. (If you don’t see Manage Add-ins, your account has not been migrated to Exchange yet. You can contact outlookdev@microsoft.com to get your account migrated, or create a new Microsoft account.)
- On the Manage Add-ins page, choose the plus (+) icon and select Add from a file.
- Choose Browse and select the manifest-myHelloWorldAddin.xml file from the root of the sample project folder, then choose Next and Install. You will see instructions on how to view the add-in in Outlook.

@WrathOfZombies can we make this change?

**Comment by jasonjoh** [comment]
Nah, there's a better in-client method using Outlook 2016. How about you guys let me update it? :)

**Comment by nokafor** [comment]
Sounds perfect!
