### ISSUE TITLE
Beta: Name of add-in gets weird casing

### ISSUE THREAD

**Issue by jasonjoh** [OfficeDev/generator-office#204]
For the add-in name, if I enter something like "My Test Add-in", the generator converts it to "My test add-in". This gets put into the Manifest, into the HTML source, etc.

This seems like incorrect behavior. I want my add-in to show up as title-cased, or at least to just show up as I entered it in the prompt.

This line in index.ts seems to be the cause of this:

```
this.project.projectDisplayName = _.capitalize(this.project.name);
```

**Comment by beth-panx** [comment]
Great spot!! project name should stay as is. Bug logged and will fix it soon.
