### ISSUE TITLE
Unclear documentation?

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/generator-office#206]
From the README:
****
This generator is for those developers who:

- use an editor other than Visual Studio
- are interested in using a technology other than plain HTML, CSS & JavaScript
****

Is the last bullet above correct?

**Comment by msholly** [comment]
The generator has the option to use AngularJS (and Typings now). I'm not with the project, but I'm assuming this is what they are referring to.

**Comment by beth-panx** [comment]
@msholly is correct. We are trying to bring in more frameworks such as Angular. That's what the bullet point intended to communicate. @Reezaali What would you recommend to reduce the level of confusion?
