### ISSUE TITLE
Dependency to typings not declared

### ISSUE THREAD

**Issue by baywet** [OfficeDev/generator-office#212]
I was testing out the generator on a brand new machine on which I didn't have typings globally installed.
Because the postinstall relies on typings but doesn't check if already here before trying to use it, the installation of the generator crashes with the following error message

'typings' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "generator-office@1.0.0-beta.1" "-g"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! generator-office@1.0.0-beta.1 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the generator-office@1.0.0-beta.1 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the generator-office package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs generator-office
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls generator-office
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vince\npm-debug.log

**Comment by beth-panx** [comment]
Hello! Please install the latest version of generator-office instead of generator-office@1.0.0-beta.1

**Comment by baywet** [comment]
Sorry I was following the installation procedure provided by Office preview program and didn't notice new versions.
