### ISSUE TITLE
ApplicationInsights:Sender [ { Error: unable to verify the first certificatey

### ISSUE THREAD

**Issue by baywet** [OfficeDev/generator-office#213]
I got the following error message right after the files creation and before the npm install sequence when generating an Outlook add-in.
Running nodejs 7.5.0 on windows 10x64 general ring.

ApplicationInsights:Sender [ { Error: unable to verify the first certificatey.npmjs.org/readdirp
      at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
      at emitNone (events.js:86:13)
      at TLSSocket.emit (events.js:186:7)
      at TLSSocket._finishInit (_tls_wrap.js:603:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' } ]

**Comment by beth-panx** [comment]
I saw this error yesterday on my machine briefly and found this issue with [App Insights](https://github.com/Microsoft/ApplicationInsights-node.js/issues/128). Tried it this morning and the error went away. I saw your other open issue. Could you install the latest version and let me know if it works?

**Comment by baywet** [comment]
Just ran the command again and didn't get the issue.
