### ISSUE TITLE
Add .gitignore, .vsproj, .sln, .deployment, .travis.yml, .nvmrc and a README to the project

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/generator-office#219]
Add .gitignore (with a set of Node + VS defaults (node_modules, bit, obj))
.vsproj and .sln (for Visual Studio)
And .deployment (for azure deployment, to specify dist folder)
.travis.yml (Travis continuous-integration)
maybe .nvmrc (Node Version Manager)

And a README to describe what all these files are, and the scenarios for when you need them.

**Comment by beth-panx** [comment]
- See [yeoman/generator issue #812](https://github.com/yeoman/generator/issues/812) for copying .gitignore not accomplishable
- In discussion for the rest

**Comment by Zlatkovsky** [comment]
@beth-panx , I find it strange that there would be such limitation.  Do the other templates really not add a .gitignore file?

What about the gitignore generator, how is it doing it?  https://www.npmjs.com/package/generator-gitignore

**Comment by mamoonraja** [comment]
@Zlatkovsky @beth-panx  Did you find a way to add .gitignore other than using generator-gitignore? So far every other post point out that there is no way to copy .gitignore using any custom generator.

**Comment by Zlatkovsky** [comment]
Adding @WrathOfZombies , @MIchaelMainer

**Comment by mamoonraja** [comment]
Never mind, found a [solution for .gitignore](https://github.com/Yoctol/generator-yoctol-ansible/pull/3)
