### ISSUE TITLE
Move generated manifest to its own "manifest" folder

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/generator-office#220]
Otherwise it:

1. Clutters the otherwise normal look of a node-based web project.
2. Gets lost amidst the other files (esp when, as per https://github.com/OfficeDev/generator-office/issues/219, more will be added).
3. Doesn't encourage the pattern of having multiple manifests (one for local, one for staging, one for production...)

**Comment by TCourtneyOwen** [comment]
@Zlatkovsky This is quite an old issue, and I a am hoping that we've addressed any concerns about project structure in the recent updates we've made to the templates.  Closing as resolved.   If you disagree with the resolution, please reopen the issue and we will investigate further.
