### ISSUE TITLE
Cannot Add Cert in Sierra

### ISSUE THREAD

**Issue by johnyradio** [OfficeDev/generator-office#226]
in Sierra, this step fails:
Click the plus button at the bottom and select the localhost.cer file you copied to the desktop.

When you click the plus, there's no way to select the cer file. You get:

![image](https://cloud.githubusercontent.com/assets/6564280/23779837/b48eb522-04f7-11e7-819b-8418197c4a78.png)

**Comment by johnyradio** [comment]
One workaround is to drag the .cer file into Keychain Access.

**Comment by beth-panx** [comment]
The reason you got that screen is you have 'Passwords' selected in 'Category' instead of 'Certificates'. So it was trying to add a keychain password instead of cert. I will update our doc to reflect this.
