### ISSUE TITLE
React version does not start

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/generator-office#235]
Hi, when running npm start I get the following error:

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.context: The provided value "c:\\code\\hello-react-yo-office\\src" is not an absolute path!
 - configuration.output.path: The provided value "c:\\code\\hello-react-yo-office\\dist" is not an absolute path!

**Comment by beth-panx** [comment]
For future reference:
@Reezaali and I worked together to try to reproduce the error. Seems like it has something to do with WebPack 2.3 does not work well with Windows cmd sometimes. Recommending using powershell for windows users.

The issue can not be reproduced after regenerate react project with the latest version.

**Comment by WrathOfZombies** [comment]
@Reezaali can you open webpack.dev.js and webpack.prod.js and whereever you see context and outputPath, just wrap the string inside of a path.resolve('<string here>')? That should solve the problem.

Also if it does, please send a pull request.

**Comment by roebuk** [comment]
Updating webpack to version 3.10.0 fixes this issue.
