### ISSUE TITLE
Generated resource.html doesn't display correctly on Safari

### ISSUE THREAD

**Issue by beders** [OfficeDev/generator-office#239]
Minor thing.

Can't scroll the section above to make it visible.
<img width="351" alt="screen shot 2017-05-11 at 1 38 09 pm" src="https://cloud.githubusercontent.com/assets/522318/25970864/0e818112-364f-11e7-910c-817765537b10.png">

**Comment by TCourtneyOwen** [comment]
@beders We no longer include resource.html in the project templates. Closing issue as resolved
