### ISSUE TITLE
Add XML validation gulp task

### ISSUE THREAD

**Issue by andrewconnell** [OfficeDev/generator-office#24]
Create a gulp task that will perform XSD validation on the Add-in manifest to ensure it's valid after edits.

**Comment by waldekmastykarz** [comment]
I've done some work around validating XML with XSD in the past and perhaps could help if still needed. Do you know if there is an XSD available or would we need to build it ourselves using the schema information from MSDN?

**Comment by andrewconnell** [comment]
The schema is defined and published: [MSDN: Schema reference for Office Add-ins manifests (v1.1)](https://msdn.microsoft.com/en-us/library/7e0cadc3-f613-8eb9-57ef-9032cbb97f92). The original idea here is to add a gulp task to the `gulpfile.js` that's added with the generated project (not in the generator's `gulpfile.js`). This way developers could use the gulp task to validate their `manifest.xml`.

Interested in taking this on?

**Comment by waldekmastykarz** [comment]
Definitely!

**Comment by andrewconnell** [comment]
Cool... it's yours @waldekmastykarz! Please ensure you've got some good tests around the task... curious to see how you implement unit tests for a gulp task as I haven't done that before. [This might help](http://stackoverflow.com/questions/24567417/how-to-test-gulp-tasks) with that.

Removing the **help-wanted** tag as it's now yours.

**Comment by waldekmastykarz** [comment]
So I've done some research and it seems like there aren't that many XML validators using XSD for Gulp/Node. Two I've found are https://github.com/polotek/libxmljs and https://www.npmjs.com/package/libxml-xsd, but some developers report issues with cross platform support. I'm going to continue the search, in the meanwhile any suggestions for a package that we could use for XML validation with XSD are welcome.

**Comment by waldekmastykarz** [comment]
I've done some additional research on libxmljs and libxml-xsd. Libxml-xsd fails during installation and libxmljs fails XML validation when using the Office App XSD. It seems like libxml, which does the XML processing, cannot deal with complex types: as soon as it finds one in XSD it throws an error: Invalid XSD Schema. One more thing that we could try is https://github.com/nikku/node-xsd-schema-validator but it requires JAVA.

**Comment by waldekmastykarz** [comment]
I've put up a [sample repo](https://github.com/waldekmastykarz/sample-xml-validation) showing how we could use the xsd-schema-validator for validating the manifest.xml file with its XSD. A couple of thoughts so far:

- the package used for validation requires Java. Additionally on OSX it requires you to manually configure the JAVA_HOME environment variable
- it's not always obvious from the validation error message where the error exactly is in the manifest file. The error message doesn't contain line/column numbers which would make it easier to locate the error in the manifest file
- the original XSD as published on https://msdn.microsoft.com/en-us/library/fp123711 had to be modified on line 249 (had to remove the trailing question mark in the regex) as it was causing validation errors when using the xsd-schema-validator package
- having tried a couple of packages this is the first approach I got to work. It's not perfect but it could be a good start

**Comment by andrewconnell** [comment]
We def. don't want to add a Java dependency... ideally no dependencies that require extra installs...

**Comment by waldekmastykarz** [comment]
Totally understood. In that case we'll have to continue looking for a working XML validation library. Both libxmljs and libxml-xsd that I mentioned before are based on the libxml library which doesn't seem to work with complex types.

**Comment by andrewconnell** [comment]
While it would be unfortunate, I personally would rather not have this feature than require an extra install somewhere. Surprised there isn't a NPM module for schema validation :-/

**Comment by waldekmastykarz** [comment]
I was surprised about that too. The few I've found either didn't install, didn't work with Office Add-in XSD and/or required additional installs. I still hope we'll be able to find one that works as this would be a great enhancement for the dev experience.

**Comment by andrewconnell** [comment]
Some prospects you can explore:
- https://www.npmjs.com/package/grunt-xml-validator (view source to port from grunt)
- https://github.com/jindw/xmldom

**Comment by waldekmastykarz** [comment]
Thanks for the tip. I'll take a look!

**Comment by waldekmastykarz** [comment]
OK, so I've just found another package working: [libxml-xsd](https://www.npmjs.com/package/libxml-xsd). The only thing is that the version published on npm has a bug with newer versions of Node and we would need to link to the commit from the main branch on Git instead until it gets published on npm (more info at https://github.com/albanm/node-libxml-xsd/issues/2#issuecomment-118427344). Would that be acceptable?

**Comment by waldekmastykarz** [comment]
I've had a look at xmldom (grunt-xml-validator uses it too) and it seems like it only validates the document structure (closed tags, attribute values in quotes, etc.) and not its contents using a schema. I might be missing something but I've found no references to schema or validation in xmldom code.

**Comment by andrewconnell** [comment]
Sure… that would be fine with me

--

-AC


Andrew Connell

www.andrewconnell.com<http://www.andrewconnell.com/> | me@andrewconnell.com<mailto:me@andrewconnell.com>

@andrewconnell<http://www.twitter.com/andrewconnell> | www.linkedin.com/in/andrewconnell<http://www.linkedin.com/in/andrewconnell>​

From: Waldek Mastykarz
Reply-To: OfficeDev/generator-office
Date: Friday, September 11, 2015 at 3:39 PM
To: OfficeDev/generator-office
Cc: Andrew Connell
Subject: Re: [generator-office] Add XML validation gulp task (#24)


OK, so I've just found another package working: libxml-xsd<https://www.npmjs.com/package/libxml-xsd>. The only thing is that the version published on npm has a bug with newer versions of Node and we would need to link to the commit from the main branch on Git instead until it gets published on npm (more info at albanm/node-libxml-xsd#2 (comment)<https://github.com/albanm/node-libxml-xsd/issues/2#issuecomment-118427344>). Would that be acceptable?

**Comment by waldekmastykarz** [comment]
Awesome. Let me refactor the sample I've built so that we can see if we're happy with the results.

**Comment by waldekmastykarz** [comment]
I'm having trouble with installing libxml-xsd on node v0.12.7 and node-gyp v3.0.2. There have been compatibility issues with the package and its dependencies in the past and now I'm experiencing something similar. I've opened an issue with the author of libxml-xsd. Hopefully it will be solved soon and we'll be able to proceed.

**Comment by waldekmastykarz** [comment]
I've found another library that we can use for XML validation with XSD without any odd dependencies. I've updated the sample at https://github.com/waldekmastykarz/sample-xml-validation. @andrewconnell would you mind taking a look if this is something we could use?

**Comment by andrewconnell** [comment]
Based on your samples it looks like it… the idea was to have a gulp task that you call to validate it and it looks like that’s what you’ve done. Nice work!

**Comment by waldekmastykarz** [comment]
Thanks! Let me start working on the unit tests for it.

**Comment by waldekmastykarz** [comment]
I've added unit tests to my sample repo at https://github.com/waldekmastykarz/sample-xml-validation. Would you mind checking it out @andrewconnell?

**Comment by andrewconnell** [comment]
Can you go ahead and add it to the generator-office repo and submit it as a PR? This avoids having to check this twice as when you submit the PR it will run all tests and make sure the test coverage is acceptable with the existing project. Thanks!

**Comment by waldekmastykarz** [comment]
Will do!

**Comment by waldekmastykarz** [comment]
For integrating unit tests for the xml validation gulp task I've been wondering what the best way to do that would be. Given that XML validation works the same for all generators we might include a separate suite of tests for XML validation. On the other hand if you really want to be sure that each copy of the gulp task will work as expected we could try to have the xml validation tests run after a test project has been created so that all dependencies are in place. Any suggestions @andrewconnell?

**Comment by andrewconnell** [comment]
Personally I prefer the latter… that each one works for each generator. Reason being if there’s a typo in one of the gulpfile.js when an update is applied down the road, the test suite won’t cover it.

**Comment by waldekmastykarz** [comment]
Check.

**Comment by waldekmastykarz** [comment]
I've just submitted the PR with the XML validation task and unit tests. Because we're running gulp on the project's gulpfile.js we have to do npm install to install local gulp. In the current setup this is done for each test. As a result the whole test run takes about 20mins. I'm curious if you see any way in which we could speed up this process.

**Comment by andrewconnell** [comment]
Good work man… but before we merge this in we have to address the duration of the test runs as it will dramatically hinder dev going forward IMHO.

Is it really necessary to do NPM install before EACH test? What’s the downside to running it just once before all the tests in the suite? We’ve got to figure another way out as if it takes 20m to run all tests, that’s going to really hinder development going forward.

If it can’t be cut down to something much more manageable, then we’ve got to separate these tests so they can be run outside of the main suite. The typical path of running the tests should be on the magnitude of seconds, not minutes.

Consider the following: as you dev you have the watcher setup to run tests as you change files. If the tests take more than 10-20s, standing up the watcher is effectively useless because the vast majority will never run.

**Comment by waldekmastykarz** [comment]
Thanks! The way the test are currently setup we do, because the temp directory where the local gulpfile.js is, is recreated for each test. I can of think two things that we could do:
1. We could wrap all tests into a single test and let is pass only if all conditions are satisfied. Not ideal because figuring out what went wrong might be harder but relatively easy to do and would have little impact on the existing tests.
2. We could create a separate set of tests outside of the technology set and have npm install run only once (ie. running it on before rather than beforeEach). I don't know if it would work but it could be worth trying. This approach would mean that we would have 3 rather than 2 sets of tests for each type of add-in but it just could help us get the test duration down.

What do you think?

**Comment by andrewconnell** [comment]
I’ll answer, but let’s consider something (after my answer)…

Option 2… create a separate test that refactors out the tests needed to test this… we can change the current test runners in the `package.json` file (https://github.com/OfficeDev/generator-office/blob/master/package.json#L26-L28) so that the existing ones (test & test-coverage) test all the non xml validation tests, but we have another option for **test-long** or something along those lines that does everything. The script for travis would include all tests though, including the long ones.

I would still look to optimize that test so that you don’t install gulp on every single test, see if you can do it just once using a `before()` rather than `before Each()`.

With that being said… but let’s rethink this for a minute…

Why is the entire validation code done in gulp? Gulp is a task runner. If there’s not a good XML / XSD validator out there, why not make a NPM module out of it and then the gulp task **validate-xml** can use this module? Then the tests can be out of generator-office and where they should be, within the module. Then gulp is just used to call the module… nothing more. It also provides a good XML validation plugin to the community.

One more thing… the errors should be emitted… not just logged. This way the errors will cause the gulp task to really fail, which is intended in validation, similar to how JSCS or JSHINT validation works.

**Comment by waldekmastykarz** [comment]
If you look at the code that we have now, we are using **xmllint** for XML validation all of which is done within the **xmllint** module https://github.com/waldekmastykarz/generator-office/blob/issue-24/generators/content/templates/common/gulpfile.js#L31-L34. The unit tests that we have built check that the validate-xml task works correctly, but now that you mention it I wonder if we aren't really testing xmllint itself which we shouldn't be doing.

If that is indeed the case then we could remove all tests other than tests for copying the XSD so that validation is possible.

For failing the **validate-xml** task in case of XML validation errors do you mean using something like https://www.npmjs.com/package/gulp-fail?

**Comment by andrewconnell** [comment]
That’s a really good point… not that I understand what you’ve written, it does seem like we’re testing an external component which we shouldn’t do… so it seems like we should just go ahead and get rid of all the tests you’ve written… just wack that one commit. Sorry you put that effort into it!

As for the fail, I was hoping the component you were using emitted errors as a stream, but appears that it doesn’t. Bummer… guess logging to the console is fine.

Once we get rid of those tests we can merge this in. Cool?

**Comment by waldekmastykarz** [comment]
Definitely!
