### ISSUE TITLE
Project manifest shouldn't offer Add-in Commands, since Project doesn't support them

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/generator-office#240]
Project manifest:  https://github.com/OfficeDev/generator-office/blob/master/src/app/templates/manifest/project.xml

In general, I don't see why the manifest isn't just one parametarized file, much as we did in https://github.com/OfficeDev/script-lab/blob/master/src/server/templates/manifest

See the handlebars-based `{{#if supportsAddinCommands}}`, `<Host Name="{{{hostType}}}" />`, etc.

**Comment by TCourtneyOwen** [comment]
Very stale issue. Please reactivate if this is still an issue
