### ISSUE TITLE
Gets stuck

### ISSUE THREAD

**Issue by sumurthy** [OfficeDev/generator-office#245]
I'm not able to get past 2nd prompt. It gets stuck. CTRL-C doesn't work. 
(Windows OS)

![image](https://user-images.githubusercontent.com/8384457/27034963-6d90462c-4f34-11e7-85c6-b301c803010d.png)

**Comment by MIchaelMainer** [comment]
Which release are you using? https://github.com/OfficeDev/generator-office/releases

**Comment by tehbilly** [comment]
I get the same thing. Windows 10 Anniversary update (at the office), version 1.1.5 of generator-office.

**Comment by addyosmani** [comment]
Yeah - unfortunately downgrading to Node 7.10.x is currently the best solution until the Node 8 readline issues have been fully addressed.

**Comment by casieber** [comment]
Closing since this has been identified as [external](https://github.com/yeoman/yeoman/issues/1671) and subsequently fixed.

If you do happen to hit this issue you may still be on a Node 8 version without the fix. Please try updating your Node install.
