### ISSUE TITLE
Why is react not an option in "Choose a Framework"?

### ISSUE THREAD

**Issue by timotius02** [OfficeDev/generator-office#246]
Didn't know for the longest time that the generator had support for React and had always used my own solution to use the vanilla output of the generator for React. Is there a reason why React isn't part of the "Choose a Framework" prompt?

**Comment by timotius02** [comment]
Note this in for installations that choose to not use TypeScript as I believe most people use React without it.

**Comment by Hongbo-Miao** [comment]
Hi @timotius02 for pure React project, please check https://github.com/Hongbo-Miao/office-addin-react

**Comment by timotius02** [comment]
That's similar to how I did it as well.  I guess since you can just add a manifest file to create-react-app there's no need for it to be included in the generator.

**Comment by Hongbo-Miao** [comment]
Yeah, personally I think YO Office in the future will only focus on manifest generation and validation.
