### ISSUE TITLE
Why Angular choice use FabricJs

### ISSUE THREAD

**Issue by charly37** [OfficeDev/generator-office#250]
Hi,

I used the generator to create my project with Excel/Angular and Javascript choice. It works fine but now that i m trying to add more UI widget I notice the project rely on FabricJS whereas I was hoping it would include ngofficeuifabric. Is it the desired behavior ? Is it because ngofficeuifabric is not officialy supported by MS ?

When I was looking for the reason behind that I come accross this other ticket: https://github.com/OfficeDev/generator-office/issues/145
and was curious to know if the generator now has an option to use ngofficeuifabric  instead of fabricjs (maybe i miss it) ?

Thx

**Comment by Hongbo-Miao** [comment]
Personally I think YO Office In the future will only focus on manifest generation and validation.

Please check the demo
https://github.com/Hongbo-Miao/office-addin-angular

and step by step tutorial to create an Angular add-in
https://hongbo-miao.gitbooks.io/excel/content/quick-start/angular.html

**Comment by Hongbo-Miao** [comment]
Hi @charly37 Personally I think YO Office In the future will only focus on manifest generation and validation. (We may remove React and Angular generation function)

Please check the demo
https://github.com/Hongbo-Miao/office-addin-angular

and step by step tutorial to create an Angular add-in
https://hongbo-miao.gitbooks.io/excel/content/quick-start/angular.html

**Comment by Hongbo-Miao** [comment]
Hi @charly37 Personally I think YO Office In the future will only focus on manifest generation and validation. (We may remove React and Angular generation function)

Please check the demo
https://github.com/Hongbo-Miao/office-addin-angular

and step by step tutorial to create an Angular add-in
https://hongbo-miao.gitbooks.io/excel/content/quick-start/angular.html

(Will move under OfficeDev in the future)

**Comment by charly37** [comment]
Thx for the info. I m closing for now since it was more question/info related than real issue
