### ISSUE TITLE
React project not starting

### ISSUE THREAD

**Issue by derCiamas** [OfficeDev/generator-office#252]
When I generate the Outlook Typescript/React project it is not starting up with "npm start" command, I keep getting multiple errors. 

Tried commenting out the plugin but then I get multiple different errors.

Here is the log:
const { CheckerPlugin } = require('awesome-typescript-loader');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\piotr\Documents\Dev\FailingReact\config\webpack.prod.js:3:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
 npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-office-add-in@1.0.0 build: `npm run clean && webpack --config config/webpack.prod.js --colors --progress --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-office-add-in@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\piotr\AppData\Roaming\npm-cache\_logs\2017-08-03T08_22_01_778Z-debug.log

**Comment by Hongbo-Miao** [comment]
Hi @derCiamas Personally I think YO Office In the future will only focus on manifest generation and validation. (We may remove React and Angular generation function)

Please check the demo
https://github.com/Hongbo-Miao/office-addin-react

and step by step tutorial to create a React add-in
https://hongbo-miao.gitbooks.io/excel/content/quick-start/react.html

(Will move under OfficeDev in the future)

**Comment by kevmcdonk** [comment]
Try fixing to "typescript": "2.2.2" in package.json. I found issues with 2.2.4

**Comment by casieber** [comment]
Closing given our recent ts+react template updates as well as the fact that this seemed to be an intermediate issue possibly due to a bug in an earlier TS version.

Please let us know if the latest ts+react template does not work for you.
