### ISSUE TITLE
Cannot test and Office add-ins anymore - Office for Mac

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/generator-office#253]
Strangely I cannot test Office Add-ins on Office for Mac anymore. The problem is that the local installed Excel always only redirects to the Office store and the Live ID but not the Office 365 Subscription.
The screen looks like this:
<img width="782" alt="screen shot 2017-08-03 at 23 16 10" src="https://user-images.githubusercontent.com/5503835/28944156-d18f1eaa-78a1-11e7-8273-4cc88fbf0e78.png">
But it should actually look somehow like this:
<img width="743" alt="screen shot 2017-08-03 at 23 18 58" src="https://user-images.githubusercontent.com/5503835/28944257-2ce3bfae-78a2-11e7-81d4-f173a77f8763.png">

If I'm not completely mistaken. The sideload info doesn't work for me somehow.

Thanx in Advance.

**Comment by Hongbo-Miao** [comment]
Hi @StfBauer do you still have the issue?
Can you create an repo to reproduce so I can test your code?

**Comment by StfBauer** [comment]
Below you see the version of my Excel but it seems to be more a general issue.

<img width="395" alt="screen shot 2017-08-21 at 11 17 43" src="https://user-images.githubusercontent.com/5503835/29512420-72336ba4-8662-11e7-8a7e-6e2b03c240fc.png">

Since in Office 365 some links have changed I cannot access the old add-in registration page anymore.

**Comment by TCourtneyOwen** [comment]
Very stale issue. Please reactivate if this is still an issue

**Comment by StfBauer** [comment]
Will do but is this generator still active?
