### ISSUE TITLE
TS2559 error for react type of project

### ISSUE THREAD

**Issue by wwy94621** [OfficeDev/generator-office#255]
I use generator-office 1.1.5 create a project with react and typescript. when try to run "npm run build", I'll get some errors like below.

![default](https://user-images.githubusercontent.com/15881207/29205994-7536024c-7eb2-11e7-91bd-1b9a62acf3fb.PNG)

Any body know how to fix this issue? Thanks.

**Comment by Hongbo-Miao** [comment]
Hi @wwy94621 Personally I think YO Office In the future will only focus on manifest generation and validation. (We may remove React and Angular generation function)

Please check the demo
https://github.com/Hongbo-Miao/office-addin-react

and step by step tutorial to create a React add-in
https://hongbo-miao.gitbooks.io/excel/content/quick-start/react.html

(Will move under OfficeDev in the future)

**Comment by wwy94621** [comment]
Thanks for your reply.

**Comment by Hongbo-Miao** [comment]
You are welcome!

**Comment by wwy94621** [comment]
I just fix the issue, just because some of the node_modules is not up to date. I updated @type/react, @uifabric， office-ui-fabric-react then it's working now.
Maybe you don't need to remove them in the future, it's really a good tool and can save lot's of time to prepare the develop environment. Thanks again.

**Comment by Hongbo-Miao** [comment]
Yeah, we will definitely think twice about removing.
