### ISSUE TITLE
Generate contributors guide when a project is created

### ISSUE THREAD

**Issue by strand** [OfficeDev/generator-office#260]
To encourage folks being able to more easily open source a project generated by generator-office, provide an option to generate a contributors guide.

Related to https://github.com/OfficeDev/generator-office/issues/219

I am interested in adding this feature if it is something which would be welcomed as an improvement to the project.

**Comment by TCourtneyOwen** [comment]
We have a Contributor's guide at https://github.com/OfficeDev/generator-office/blob/master/CONTRIBUTING.md
