### ISSUE TITLE
Generate a code of conduct when a project is created 

### ISSUE THREAD

**Issue by strand** [OfficeDev/generator-office#261]
To encourage folks to feel safe to contribute, provide an option to generate a Code of Conduct, like the [Contributors Covenant](https://www.contributor-covenant.org/) in the project.

Related to #219, #260

I am interested in adding this feature if it is something which would be welcomed as an improvement to the project.

**Comment by millerds** [comment]
Link to the code of conduct was added at the bottom of the readme.

**Comment by millerds** [comment]
I occurs to me that you may be referring to the project generated by this tool.  Those don't have a read me and all and really any guidelines needed should be expressed by the person creating the new project rather then us.
