### ISSUE TITLE
Cannot import certificate following the macOS guide

### ISSUE THREAD

**Issue by Hongbo-Miao** [OfficeDev/generator-office#273]
For macOS, the guide is probably wrong now

> iii. Click the plus button at the bottom and select the localhost.cer file you copied to the desktop.

![image](https://user-images.githubusercontent.com/3375461/34543332-2a7f9e2a-f095-11e7-831d-cfc9ea1e593c.png)

It pop up a dialog, and I still cannot import the certificate file

**Comment by MIchaelMainer** [comment]
Agreed. That probably does need to be updated.

**Comment by TCourtneyOwen** [comment]
@Hongbo-Miao We now generate the certificates via office-addin-dev-certs and automatically register them during "npm run build". Closing this issue as resolved
