### ISSUE TITLE
Self-signed certificate, React and bsonfig.json (macOS)

### ISSUE THREAD

**Issue by mesaugat** [OfficeDev/generator-office#274]
This is the first time I am using generator-office to create an Outlook Add-in. If someone is using MacOS to develop an add-in, here are the problems you might face.

The self-signed certificate as mentioned in the docs does not work. Thus, there's no point in downloading the certificate.

![screen shot 2018-01-04 at 4 35 39 pm](https://user-images.githubusercontent.com/4240991/34560305-5f349354-f16d-11e7-9d48-57ef23685e84.png)

The problem with the current certificate is that the certificate does not contain a `Subject Alternative Name (SAN)`.

<img width="469" alt="screen shot 2018-01-03 at 4 39 39 pm" src="https://user-images.githubusercontent.com/4240991/34560489-038a6618-f16e-11e7-8145-564879c19263.png">

Thus, the solution is to generate our own certificate using `openssl` and setting up `SAN` in `openssl.cnf`. The steps needed to create a new certificate is clearly mentioned in https://github.com/OfficeDev/generator-office/issues/244#issuecomment-306573386

`openssl.cnf` on macOS can be found here `/System/Library/OpenSSL/openssl.cnf` as mentioned in https://github.com/OfficeDev/generator-office/issues/264#issuecomment-347649764

After you've created the certificate you'll have to update your `bsconfig.json` file to use the new `server.key` and `server.crt`. **But, if you are using `React` to create your add-in changing the `bsconfig.json` won't work.** 

After some inspection, I figured out that the server certificate being used by BrowserSync was not the one that I just created even though I had changed `bsconfig.json`. Turns out, when we use TypeScript and React as our framework of choice, BrowserSync is run via. `browser-sync-webpack-plugin`. https://github.com/OfficeDev/generator-office/blob/master/src/app/templates/ts/react/config/webpack.dev.js#L11-L21

To my amazement, `bsconfig.json` is not being required anywhere. I think it should be merged with existing config provided to `browser-sync-webpack-plugin`. Now the question of where the current certificate is being served from? So, BrowserSync provides its own self-signed certificate. It is located in `node_modules/browser-sync/lib/server/certs`. This is the certificate that was being served.

**Temporary Fix:**

In order to solve the issue, we'll have to move our self-signed certificate to `node_modules/browser-sync/lib/server/certs`. Also, don't forget to add your certificate to `Keychain Access` and set it to `Always trust` everything.

You can simply drag and drop your new certificate to `Keychain Access`. Clicking the `+` button as mentioned in the docs is a bit confusing. https://github.com/OfficeDev/generator-office/issues/273

**Comment by aboldarev** [comment]
as a temporary fix I have changed  webpack.dev.js to 
        new BrowserSyncPlugin({
            https: {
                "key": "./certs/server.key",
                "cert": "./certs/server.crt"
            },
...

**Comment by LouMM** [comment]
We removed the need for Browsersync, if  you do an npm update on the yo office package you should be able to see and use the latest.
