### ISSUE TITLE
The dev server is not started correctly

### ISSUE THREAD

**Issue by felixliu226** [OfficeDev/generator-office#275]
Hi,

I'm new to Office Add-ins. I just following the [(tutorial)](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=visual-studio-code) to learn how to set up the add-in project.

But when I start the server after I trust site's certificates, I can only see the file list inside my directory (like the following pic) instead of the index.html, and if I click the `index.html`, it shows "`Cannot GET /index.html`".

<img width="1049" alt="screen shot 2018-01-05 at 15 38 58" src="https://user-images.githubusercontent.com/21051075/34599718-c6755384-f22e-11e7-92d9-6785e79d9fd9.png">

I really have no idea about how could this happened and i would appreciate it if any one could help me. Thanks in advance.

**Comment by HanVincent** [comment]
Same here. 😢

**Comment by HanVincent** [comment]
Hi @felixliu226 ,
I met the same problem in #274 . After following the steps in the issue, I add `--server` in
`browser-sync start --config bsconfig.json`, and then it works for me.

My evironment: macOS with Chrome v63

**Comment by Rick-Kirkham** [comment]
This is an error in build 2.23.2 of Browsersync:
https://github.com/BrowserSync/browser-sync/issues/1477
Backing down to 2.18.13 will fix it. 
`npm install browser-sync@2.18.13`

**Comment by felixliu226** [comment]
@Rick-Kirkham Thanks for your suggestion, now it works.

**Comment by Rick-Kirkham** [comment]
Update: It turned out that we had a mistake in our bsconfig.json. The server property should have had a baseDir subproperty set to "./". Apparently, earlier versions assume the current directory when baseDir wasn't specified. It seems that you now have to specify it.
