### ISSUE TITLE
Can this be updated to generate Angular2+ projects instead of Angular1?

### ISSUE THREAD

**Issue by crazyquark** [OfficeDev/generator-office#278]
I wanted to use Angular4 to develop an Outlook AddIn but realized the generator only creates an Angular1 projects.
Are there any workarounds for that?

Thank you

**Comment by asith-w** [comment]
+1

**Comment by Rick-Kirkham** [comment]
We have a work item to add Angular 2+ support, but it has not been scheduled yet.
