### ISSUE TITLE
npm build fails Error: node-sass@4.5.1 postinstall: `node scripts/build.js`

### ISSUE THREAD

**Issue by Astronaut4449** [OfficeDev/generator-office#279]
Specs:
Windows 10
npm 5.5.1

Settings:
Office client: Excel
New add-in: yes
TypeScript: yes
Framework: React

[bugreport.txt](https://github.com/OfficeDev/generator-office/files/1689039/bugreport.txt)
[debuglog.txt](https://github.com/OfficeDev/generator-office/files/1689038/debuglog.txt)

**Comment by LouMM** [comment]
Thank you @Astronaut4449 for the report and I am sorry you are running into issues. The node package installs [node-gyp]( https://github.com/nodejs/node-gyp), which requires python 2.x to run so it is a pre-req for the build/install. You can correct that specific error in your install by installing python2 and making sure it is in your ENV or in your PATH. I am looking through the rest of your log to see if there is anything else causing the issue.

**Comment by LouMM** [comment]
#280 Will fix these issues. Please sync and try again. We will be publishing a new NPM shortly.
