### ISSUE TITLE
Generator creates invalid manifest.xml file

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#29]
The generator creates an invalid add-in manifest file. If you try to upload the manifest.xml directly after generating the add-in, the Apps for Office catalog in SharePoint Online will consider the manifest as invalid. In order to fix the issue you need to remove the empty `<SupportUrl/>` element from manifest.xml. After that you will be able to upload the manifest.xml file as expected.

**Comment by andrewconnell** [comment]
When the `manifest.xml` file is built by the generator, it has some stuff in it that is designed for the user to act on... it's not perfect. For instance if you need regex matches in Outlook forms or to update the description and final URLs for the add-in's website.

One solution so it passes validation is to insert a dummy URL or insert the placeholder URL that the generator replaces. 

Thoughts?

**Comment by waldekmastykarz** [comment]
How about doing something similar as for the `ProviderName` element or the `Description DefaultValue` attribute where the value is a placeholder that the dev has to replace?

**Comment by andrewconnell** [comment]
Good suggestion... want to take it on?

**Comment by waldekmastykarz** [comment]
Definitely!
