### ISSUE TITLE
Broken aka.ms link in Outlook add-in template

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/generator-office#296]
In the Outlook add-in template manifest file, there's a link ("http://aka.ms/ExtensionPointsCommands") that is supposed to link to ExtensionPoint documentation (presumably "https://dev.office.com/reference/add-ins/manifest/extensionpoint"), but it links to microsoft.com instead.

**Comment by keyur32** [comment]
Thanks for the report @martellaj. should be fixed up now.
