### ISSUE TITLE
Created cert is invalid

### ISSUE THREAD

**Issue by elegault** [OfficeDev/generator-office#317]
I followed the instructions in "[Adding Self-Signed Certificates as Trusted Root Certificate](https://github.com/OfficeDev/generator-office/blob/master/src/docs/ssl.md)". However the certificate still doesn't work and loading the add-in's web page still shows "This site is not secure" (the add-in won't load in the Office client at all) .  Edge shows error code "DLG_FLAGS_INVALID_CA", and Chrome shows error code "NET::ERR_CERT_AUTHORITY_INVALID".

I tried following the steps in #244 to use Git's OpenSSL app to create the cert, but that cert doesn't work either (as other users in that thread have discovered when trying the same steps).. How can the cert be properly created?

**Comment by TCourtneyOwen** [comment]
@akrantz 
@keyur32 
Hi, I recently checked in a fix for this, but it may not have been published yet to the official version of Yo Office.  The fix was submitted as https://github.com/OfficeDev/generator-office/commit/3f45589ac0fc3691551bf885e7693687620fc3a5.

We are going to be merging some new changes and publishing a new version of Yo Office some time today, so if you install this latest version, it should be fixed.  In fact I just tried the certs out in both Chrome, Edge and from within Excel, and all looks to be working properly.

-Courtney

**Comment by elegault** [comment]
Awesome, the problem is resolved in the new build. There is a new issue though: the generated project fails to compile:

ERROR in ./src/components/App.tsx
[tsl] ERROR in C:\Users\elegault\source\repos\React test\my-react-addin3\src\components\App.tsx(7,1)
      TS6133: 'OfficeHelpers' is declared but its value is never read.

The project does compile when that line of code is removed.

**Comment by TCourtneyOwen** [comment]
Hi, glad the certificates now work.  Regarding the compile issue you are seeing, can you please let me know the Host (e.g. Excel) you are using and I will have a look.  Thanks!

**Comment by elegault** [comment]
Outlook

**Comment by TCourtneyOwen** [comment]
I just repro'd the compile issue with Outlook, as well PowerPoint, Project and Word add-ins (the issue doesn't repro for Excel or OneNote, however.).  Thanks so much for letting us know about this.  We will get this fixed and rolled out ASAP

**Comment by ivanov-dka** [comment]
Facing the same issue (error code "DLG_FLAGS_INVALID_CA") with Project addin. I was following this tutorial https://docs.microsoft.com/en-us/office/dev/add-ins/project/project-add-ins-get-started 
Latest version of generator used. Should I update anything else?

**Comment by Lotemn102** [comment]
still getting:
'Error Code: ERROR_INTERNET_SEC_CERT_REVOKED'

when trying to run 'https://localhost:3000' as this tutorial says:
https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial

same error occurs on chrome, edge and firefox

**Comment by Lotemn102** [comment]
Thanks for your answer.
I'm using windows 10. I did use these instructions, but it still won't work...

**Comment by Lotemn102** [comment]
Thanks, but still no change...
let me know if you come up with other solution

**Comment by TCourtneyOwen** [comment]
The only other thing I can think of is to open the Certificates Manager, select Trusted Root Certification Authorities-->Certificates, deleted the certificate that was issue by 'localhost-ca' and then reinstall the latest ca.crt.

-Courtney

**Comment by TCourtneyOwen** [comment]
@Lotemn102 We now generate the certificates via office-addin-dev-certs and automatically register them during "npm run build".  Closing this issue as resolved
