### ISSUE TITLE
`yo office` fails to generate project in v1.1.11 and v1.1.12

### ISSUE THREAD

**Issue by CeruleanJaguar** [OfficeDev/generator-office#327]
Title, running on Fedora, npm 5.6.0, yo 2.0.2

Running `yo office` and creating an angular outlook app fails after 0.2s with the following message:
```
npm WARN saveError ENOENT: no such file or directory, open '/home/theo.lawson/rep/j/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/theo.lawson/rep/j/package.json'
npm WARN j No description
npm WARN j No repository field.
npm WARN j No README data
npm WARN j No license field.
```

This sets up the following:
```
tree j
j
├── app.css
├── assets
│   ├── icon-16.png
│   ├── icon-32.png
│   ├── icon-80.png
│   └── logo-filled.png
├── certs
│   ├── ca.crt
│   ├── server.crt
│   └── server.key
├── function-file
│   ├── function-file.html
│   └── function-file.ts
├── j-manifest.xml
├── package-lock.json
├── tsconfig.json
└── webpack.config.js

3 directories, 14 files
```

Installing v1.1.10 instead and running the exact same commands/options successfully creates the project however: `1393 directories, 8340 files`

**Comment by djtango** [comment]
I can confirm that trying to run `yo office` using `npm 5.5.1` on Fedora fails to generate a proper project consistent with the docs: none of the scripts in the `package.json` are generated for me

**Comment by rajat-np** [comment]
@djtango,   thanks for this.

**Comment by TCourtneyOwen** [comment]
@CeruleanJaguar This is quite an old issue, and we haven't heard of any similar issues in the numerous yo office updates we have published since this issue was originally opened.  Please update to the latest version of yo office (1.3.0) to see if this fixes the issue.  If not, please reopen the issue and we will investigate further.

Thanks,

Courtney
