### ISSUE TITLE
Installation of outlook add-in fails

### ISSUE THREAD

**Issue by MarkusLanger** [OfficeDev/generator-office#332]
running on macOS 10.13.4 (17E202), npm 5.6.0, yo 2.0.1, generator-office 1.1.12

After creating a react outlook add-in with `yo office` the installation fails.

Generating the add-in
![image](https://user-images.githubusercontent.com/12131918/40782028-548b17a4-64de-11e8-94ba-0a48f723402f.png)

Everything works fine
![image](https://user-images.githubusercontent.com/12131918/40782060-6e4cd18c-64de-11e8-8bb7-cf8ecaeb84e5.png)

Starting the dev-server
![image](https://user-images.githubusercontent.com/12131918/40782075-78fb5c70-64de-11e8-9da9-97ca2f53f630.png)

Browsing the https://localhost:3000 page is ok
![image](https://user-images.githubusercontent.com/12131918/40782086-83786ab2-64de-11e8-9d47-04c236eeb0b8.png)

Installing the add-in in Outlook by selecting the manifest.xml
![image](https://user-images.githubusercontent.com/12131918/40782156-c43e12ae-64de-11e8-8076-ac69dd501c38.png)

Waiting for the process
![image](https://user-images.githubusercontent.com/12131918/40782163-cd549016-64de-11e8-9bbc-1d4cfc041077.png)

Installation failed
![image](https://user-images.githubusercontent.com/12131918/40782193-dc9c5ae0-64de-11e8-963e-de8a62ed533c.png)

![image](https://user-images.githubusercontent.com/12131918/40782219-e7e7fab2-64de-11e8-9fda-93e0aaf0300f.png)

The manifest.xml seems to be valid
![image](https://user-images.githubusercontent.com/12131918/40782239-f470aad6-64de-11e8-81fa-3e3e67c22e7f.png)

I have tested it in several environments and also in the outlook app for macOS.

An Excel add-in works fine without problems.

**Comment by Hacksore** [comment]
@MarkusLanger I created my add-in with Angular and had no issues importing the manifest.

**Comment by beth-panx** [comment]
@MarkusLanger go to [Manage add-ins](https://outlook.office.com/owa/?path=/options/manageapps) page to add your manifest file and make sure you turn it on afterwards.

**Comment by MarkusLanger** [comment]
> I created my Outlook add-in with Angular and had no issues importing the manifest.

I have tested these add-ins without success:
- React
- Angular
- jQuery with TypeScript
- jQuery without TypeScript

**Comment by MarkusLanger** [comment]
> go to Manage add-ins page to add your manifest file and make sure you turn it on afterwards.

@beth-panx Yeah! Thank you so much. It worked.
