### ISSUE TITLE
Value of SupportUrl is invalid, causes add-ins to silently fail when loading in Outlook

### ISSUE THREAD

**Issue by jasonjoh** [OfficeDev/generator-office#333]
How to reproduce:

1. Follow tutorial at https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial
1. When you get to [Test the generated add-in](https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial#test-the-generated-add-in), skip the instruction in *Update the manifest* that tells you to comment out the invalid `SupportUrl` element.
1. Continue with the *Sideload the add-in* section. You should see the add-in seems to install properly, but never shows up. Going back into the Store interface you'll see the add-in isn't really installed.

If you comment or remove `SupportUrl` the add-in installs properly.

Suggested fix: 

- comment the `SupportUrl` in the generated manifest, *or*,
- Add a support page into the project and point the `SupportUrl` at that.

**Comment by frommeyerc** [comment]
I just stumbled badly here as well. I would prefer the second suggestion as a fix.

**Comment by TCourtneyOwen** [comment]
This is a very old issue, so closing as we haven't heard of recent reports about this issue.  Please reactivate if this is still an issue
