### ISSUE TITLE
When generating an add-in in a directory relative to current some files get placed in the current directory rather than the specified project root directory

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#34]
When generating an add-in in a directory relative to current the following structure is generated (based on a Task Pane Add-in built using HTML):

```
.
|- bower.json
|- gulpfile.js
|- jsconfig.json
|- manifest.xml
|- node_modules
|- package.json
|- tsd.json
|- [project root directory]
|  |- app
|  |- bower_components
|  |- content
|  |- images
|  |- scripts
```

Shouldn't all files be placed in the project root directory which is what you get when you choose the current directory to be the project root directory, ie:

```
[project root directory]
|- bower.json
|- gulpfile.js
|- jsconfig.json
|- manifest.xml
|- node_modules
|- package.json
|- tsd.json
|- app
|- bower_components
|- content
|- images
|- scripts
```

**Comment by andrewconnell** [comment]
I think you're misunderstanding how the relative folder question works. When you don't use the current folder, the scenario is that you are currently in the root of a project (like an ASP.NET / Ruby / Node+Express) folder and want the addin to go in a special place. 

The files added to the root that you have listed above typically go in the root of a project as that's where the tools look for them. So it's working as designed. 

If you wanted it to work the way your second example shows, you'd CD into that `[project root directory]` and run `yo office` from there.

**Comment by waldekmastykarz** [comment]
Check. Misunderstood it indeed.
