### ISSUE TITLE
The 'dist' folder generated by the 'npm run build' command won't load

### ISSUE THREAD

**Issue by aramkoukia** [OfficeDev/generator-office#344]
Hi
I have setup this project and locally it works fine when I use `npm start`.
but when I want to deploy to some web server (IIS or Azure) I use `npm run build`. 
It generates a `dist` folder, I just copy that to my web server, but is looks like cannot load `React` and `ReactDom`

I see the following error in the browser's console:

```
Uncaught ReferenceError: React is not defined
    at Object.react (external "React":1)
    at __webpack_require__ (bootstrap 5dde89e0ff2bcfc0a7a2:54)
    at Object.0 (vendor.5dde89e0ff2bcfc0a7a2.js:52498)
    at __webpack_require__ (bootstrap 5dde89e0ff2bcfc0a7a2:54)
    at ../node_modules/@microsoft/load-themed-styles/lib/index.js (bootstrap 5dde89e0ff2bcfc0a7a2:100)
    at bootstrap 5dde89e0ff2bcfc0a7a2:100
external "ReactDOM":1 Uncaught ReferenceError: ReactDOM is not defined
    at Object.react-dom (external "ReactDOM":1)
    at __webpack_require__ (bootstrap 5dde89e0ff2bcfc0a7a2:54)
    at Object.<anonymous> (index.tsx:2)
    at Object../index.tsx (app.5dde89e0ff2bcfc0a7a2.js:6827)
    at __webpack_require__ (bootstrap 5dde89e0ff2bcfc0a7a2:54)
    at Object.1 (app.5dde89e0ff2bcfc0a7a2.js:6862)
    at __webpack_require__ (bootstrap 5dde89e0ff2bcfc0a7a2:54)
    at window.webpackJsonp (bootstrap 5dde89e0ff2bcfc0a7a2:25)
    at app.5dde89e0ff2bcfc0a7a2.js:2
```

This is what I see in my `dist` folder:
![image](https://user-images.githubusercontent.com/7307404/43435194-bf55b966-9433-11e8-9b06-9f9246c8ecd8.png)

The content of the `dist` folder is different than the content of the `build` folder of a regular react app.
Any ideas what might be the issue here?

**Comment by g-martinse** [comment]
Hi, 
in webpack.prod.js you there are the follwoing two lines:
 externals: {
        'react': 'React',
        'react-dom': 'ReactDOM'
},
if you remove them react and react-dom will also be packaged...
I had the same problem and found this:
https://stackoverflow.com/questions/32070303/uncaught-referenceerror-react-is-not-defined 

I hope this helps

**Comment by aramkoukia** [comment]
Thanks @g-martinse 
Yes, that fixed the issue

**Comment by SPDoctor** [comment]
We have to decide whether to bundle React or add a script link to CDN. Currently the generator produces a solution that can't be deployed without changes. 

My preferred option would be to bundle, which makes it easier to guarantee you have the correct React version. This will add about 3Mb to the bundle, but the client has to load this one way or another. OTOH the script link has the advantage that you have the option of using a public CDN.

**Comment by TCourtneyOwen** [comment]
@aramkoukia This is quite an old issue, and we haven't heard of any similar issues in the numerous yo office updates we have published since this issue was originally opened. Please update to the latest version of yo office (1.3.0) to see if this fixes the issue. If not, please reopen the issue and we will investigate further.
