### ISSUE TITLE
generator cuts out of process at "What do you want to name your add-in"

### ISSUE THREAD

**Issue by ivan7707** [OfficeDev/generator-office#354]
On my windows 10 new install, I was having an issue where I would start the generator, choose the project type, then the generator would automatically skip the "What do you want to name your add-in" line, and end the generator session.

This happens when I choose the options 2,4 and 5 on the list of project types.  For the Angular and Jquery options, the generator allows me to input a name for the add-in.

Even if I use the command line argument yo office react, it shows the name your add-in line, but I cannot type anything in, and it cuts out of the process itself after about 5 seconds. 

Windows 10.0.17134.285
Node: 10.10.0
Python 3.7.0

**Comment by TCourtneyOwen** [comment]
Thanks for reporting this issue. We think this may be an issue with your version of Node, as a couple others have reported this as well with Node 10.10.0. We will look into this problem and try and get a fix out ASAP

-Courtney

**Comment by ivan7707** [comment]
Thanks Courtney.  

Let me know if I can help out with logs, or testing of any type.   

Would you like me to downgrade to a previous version of Node to test?

Ivan

**Comment by TCourtneyOwen** [comment]
Hi Ivan,

I should have a fix out this afternoon. I was also able to repro with node 10.10.0 on one of my machines. However I wasn't able to repro on another machine with the same version of Node.  

I will update this issue once I publish the new version

Thanks,

Courtney

**Comment by ivan7707** [comment]
Thank you Courtney.  I am really looking forward to building some fun stuff with this module.

**Comment by ivan7707** [comment]
The merge worked.  Thank you Courtney.
