### ISSUE TITLE
Request to instruction

### ISSUE THREAD

**Issue by cschoeni** [OfficeDev/generator-office#357]
If I create an add-in with Angular with yo office like in giv, I get a working project, but not all functions of Angular are offered. There is also no angular.json file. 

If I create a new Angular project first, as in other guides, I can never use the project for Office. 

How can I integrate the yo Office into a new Angular project?

**Comment by ThorstenHans** [comment]
Hey @cschoeni 👋,

currently `generator-office` creates a angular projects based on custom webpack build. So there is no need to have a `angular.json` file.

You can integrate the result of `yo office` into any existing angular application that has been bootstrapped using `@angular/cli` I've a working sample here on github at https://github.com/ThorstenHans/currency-calculator-office-addin

I've also opened an issue to support `@angular/cli` and I'm currently working on a PR to finally get support for this

**Comment by ragavanrajan** [comment]
Really hard to get components / services generated without angular.json file.

**Comment by TCourtneyOwen** [comment]
Closing this issue as it's quite old and I don't envision us making changes to the angular template to accommodate this
