### ISSUE TITLE
Compose assets generated for a read form-only add-in

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#36]
Is it by design that even if you choose to have a Mail Add-in registered with the read form only the generator still creates assets for compose forms (ie. app files + manifest.xml registration info)?

**Comment by Ricalo** [comment]
I just looked at that behavior and it seems odd to me. Adds unnecessary clutter to the project.

**Comment by andrewconnell** [comment]
Yup... that's a bug. Need to [index.js#L465-L491](https://github.com/OfficeDev/generator-office/blob/master/generators/mail/index.js#L465-L491) so it checks which one you've selected.... also need to update the tests so they ensure only the correct stuff is added.

**Comment by waldekmastykarz** [comment]
I believe we would also need to generate the correct `Form` elements in the `manifest.xml` file so that we include `ItemRead` and `ItemEdit` forms only if applicable.
