### ISSUE TITLE
cannot put controlled textfield for some reason

### ISSUE THREAD

**Issue by manish-shukla01** [OfficeDev/generator-office#366]
i tried to use officejs react component in it and for osme reason i cant get it to work properly..effective here is the code. it works in codepen but when i put hte same code in excel addin project, i cant get the value in the textfields.
Code in codepen(it works):

[https://codepen.io/manish_shukla01/pen/ReWWmM](url)

Code in my project in app file(does not work in the sense that handlechange events are not getting fired i believe so value of my state.value1 remains blank even when i input anything):

import * as React from 'react';
import { Button, ButtonType } from 'office-ui-fabric-react';
import Header from './Header';

import { TextField } from 'office-ui-fabric-react/lib/TextField';

import * as OfficeHelpers from '@microsoft/office-js-helpers';

export default class App extends React.Component<any,any,any>{

    constructor(props) {
        super(props);
        this.state = {
           
                    value1: '',
                     value2:'',
                     message:'Helloooo'
                     };
    
        this.handleChange1 = this.handleChange1.bind(this);
        this.handleChange2 = this.handleChange2.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);
      }
    
      handleChange1(event) {
        this.setState({value1: event.target.value});
       

      }
        handleChange2(event) {
        this.setState({value2: event.target.value});
      
      }
    
   
  
      handleSubmit = async () => {
        event.preventDefault();
        this.setState({message: 'i got clicked'});
        try {
            //event.preventDefault();
            
            await Excel.run(async context => {
                /**
                 * Insert your Excel code here
                 */
                const range = context.workbook.getSelectedRange();

            // Read the range address
            range.load('address');
            
            // Update the fill color
            range.format.fill.color = 'blue';
            
            range.values = [[this.state.value2]];
  
        
           
            await context.sync();
            console.log(`The range address was ${range.address}.`);
            });
        } catch(error) {
            OfficeHelpers.UI.notify(error);
            OfficeHelpers.Utilities.log(error);
        };
    }

    render() {
     
        return (
            <form className='ms-welcome'  onSubmit={this.handleSubmit}>
                <Header logo='assets/logo-filled.png' title='Excel Analytics' message={this.state.message} />
               
                <TextField label="field1" 
      value={this.state.value1} onChange={this.handleChange1} 
required
      />
                <TextField label="field2" 
      value={this.state.value2} onChange={this.handleChange2} 
      />

    
    <Button className='ms-welcome__action' buttonType={ButtonType.primary} 
       
        onClick={this.handleSubmit}>Run
        </Button>

            </form>
        );
    }
}

**Comment by joshuahunsberger** [comment]
I was running into a similar issue.  This generator sets the dependency version to 5.51.0 (see [here](https://github.com/OfficeDev/generator-office/blob/c1f76dc1ed16951e28f292dcfad991565bd609e8/src/app/templates/ts/react/package.json#L17)).  I think in that version, you could use the "onChanged" property to work with the actual value in the box, but it is now marked as deprecated (although it still works).

What I noticed was that the [documentation](https://developer.microsoft.com/en-us/fabric#/components/textfield) is updated for the latest version 6+ of the Fabric UI components.  One of the things that appears to have changed is the signature of what gets passed into an onChange handler function.  Your link in CodePen appears to use the latest version of the Fabric UI components.  If you change the script tag to reference the specific version used in this generator, you'll see that the name doesn't get picked up any more in the popup. Try this modified [CodePen](https://codepen.io/anon/pen/aQzvXX).

Would it be possible to update the dependency in the React template for office-ui-fabric-react to something in the 6.xx.x release?

**Comment by TCourtneyOwen** [comment]
This is a very old issue, so closing as we haven't heard of recent reports about this issue.  Please reactivate if this is still an issue
