### ISSUE TITLE
Intellisense for manifest.xml

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#37]
I noticed that if you put the XSD with the OfficeApp schema in the same directory as manifest.xml, Visual Studio Code gives you intellisense for the manifest's XML. I can imagine this being very useful for editing it. I'm not sure if this behavior is specific for VSCode but if there are more editors supporting it, we could include the XSD with the generated project to simplify working with the manifest.xml.

**Comment by andrewconnell** [comment]
VSCode doesn't respect XSD's for IntelliSense unfortunately.
