### ISSUE TITLE
standardize manifest filename to "manifest.xml"

### ISSUE THREAD

**Issue by akrantz** [OfficeDev/generator-office#370]
If the manifest file names are standardized to "manifest.xml", then Yo Office would not need to rename them or update package.json script arguments to use the customized name. This would make things simpler.

Usually when the manifest path is used in the developer registry or in the shared folder path, the add-in for the manifest can be distinguished by the directory name in the full path, e.g. "c:\some\path\\**project-name**\manifest.xml".

The only other counter-example I can think of is having other manifests to customize the install location, e..g manifest.xml, manifest.stage.xml, manifest.prod.xml, such that manifest.xml is copied and the urls in the manifest are modified for the alternate install location, but still this doesn't preclude having the basic manifest filename be simply "manifest.xml".

**Comment by TCourtneyOwen** [comment]
Sounds good to me. Would certainly simplify things
