### ISSUE TITLE
TSLint should be added to the project

### ISSUE THREAD

**Issue by ThorstenHans** [OfficeDev/generator-office#373]
There is already a `tslint.json` in the project's root directory, but TSLint isn't used at all. I'd love to have linting back in the project to ensure unified code style. 

Before actually activating TSLint, several things need to be discussed

- are the rules defined in `tslint.json` okay for all members?
- should linting be executed in a `prebuild` script?

**Comment by millerds** [comment]
We should review all of our projects for linter hookup while we're fixing up the output projects to include linting.
