### ISSUE TITLE
Update packages for jquery project template

### ISSUE THREAD

**Issue by TCourtneyOwen** [OfficeDev/generator-office#379]
This issue was reported internally via email:

"I just ran Yo office for an excel jquery project and got the following:

I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

> fsevents@1.2.4 install /Users/mattgeim/Documents/GitHub/contact-manager/node_modules/fsevents
> node install

[fsevents] Success: "/Users/mattgeim/Documents/GitHub/contact-manager/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN contact-manager@0.1.0 No description
npm WARN contact-manager@0.1.0 No repository field.
npm WARN contact-manager@0.1.0 No license field.

added 1149 packages from 602 contributors and audited 17282 packages in 25.988s
found 2 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by akrantz** [comment]
This has been updated.
