### ISSUE TITLE
Add a content add-in template for Excel and PowerPoint

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/generator-office#382]
We don't have an easy way to build content add-ins.  Need the ability to have a manifest that loads the content add-in. In addition, this template should not use the function-file html.

Assign to me to spec

**Comment by shweaver-MSFT** [comment]
@keyur32 , what's the plan for this? I would really love to have quickstarts available for Content Add-Ins. It's a bit of a pain to configure a Hello World unless you are already familiar with the tech.

From what I can see, the Humongous Excel Content Add-In is the only working example of a Content Add-In available. This makes even approaching the topic difficult for new partners. Setup needs to be easier.

**Comment by keyur32** [comment]
Hey! Apologies, I never got to this. It's still on the backlog and @akrantz and @JuaneloJuanelo 

In terms of an add-in flow, here's what I would do in the mean time:
a) run yo office to get the template you want for Excel or PPT
b) after it is generated, replace the manifest from one of the samples and update as needed to point to your html.

Here are a couple more content add-ins for reference:
https://github.com/OfficeDev/Office-Apps/tree/master/PeopleGraph
https://github.com/OfficeDev/Office-Apps/tree/master/ModernTrend

**Comment by BeachAlmanack** [comment]
Do you know when a better quick start will be available. Do you know if you will be adding the capability to use control the content admin's through the task-pane or through custom function's.

**Comment by TCourtneyOwen** [comment]
@keyur32 Yes we should do this. I think this just requires a manifest change, so we should be able to use our standard project repos, and then during yo office project generation present content add-ins as a project choice and if selected make the neccessary manifest changes

**Comment by akrantz** [comment]
@TCourtneyOwen @keyur32 I have an example of this already. See the "content" branch in my fork: https://github.com/akrantz/Office-Addin-TaskPane/tree/content 

Note, that had an experimental change where content add-ins are enabled for Word, but that is not actually supported so that host should be removed as part of doing this work.

I presume we would create a separate repository for the content add-in, e.g. Office-Addin-Content.

We also need to make sure that sideload and debugging work as we add the content add-in type.

**Comment by TCourtneyOwen** [comment]
We have a work item for this quarter to add a content add-in template

**Comment by shweaver-MSFT** [comment]
@TCourtneyOwen, not to be that guy, but it doesn't sound like the feature is available quite yet. Are you sure this should be closed? Just my two cents :)

**Comment by TCourtneyOwen** [comment]
Sure we can leave this open. I will just tag it somehow so we know this issue is on track for resolution

**Comment by millerds** [comment]
We track feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
