### ISSUE TITLE
Missing documentation to build & deploy the default add-in

### ISSUE THREAD

**Issue by ltoinel** [OfficeDev/generator-office#384]
Hi,

The project generation, manifest validation, development process is very clear on the documentation.
However what are the main steps to package & deploy the default addin generated on a classic webserver ? 
npm pack ? npm run-script build ?  ... 

Thank-you.

**Comment by akrantz** [comment]
Documentation is available here: https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish

**Comment by ltoinel** [comment]
Sorry my question is more on how to compile the addin using the npm run-script build, npm pack .... provided in the template.

**Comment by akrantz** [comment]
The output from "npm run build" would produce the output, typically in the "dist" folder. You would deploy this to your webserver. The Yo Office templates don't currently contain scripts for the deployment, and the manifest needs to be updated to point to your server.
