### ISSUE TITLE
Cannot create a React JavaScript project

### ISSUE THREAD

**Issue by myokha2** [OfficeDev/generator-office#386]
Yeoman does not suggest picking a language. It creates a TypeScript project anyway.
Running something like `yo office react test outlook --js` doesn't work ether (even though `--js` is specified as option).

**Comment by ChristopherHButler** [comment]
So what is the solution?

**Comment by akrantz** [comment]
You could create a JQuery JavaScript project, and create a React TypeScript project, and then see about modifying the JQuery project to support React. 

Or you could just start with the React Typescript project and convert it from TypeScript to JavaScript.  TypeScript is a superset of JavaScript and you could use JavaScript, so I'm curious to know whether this would work for you, and if not, what things would need to be changed.

**Comment by sebnapi** [comment]
I'm not a java- or typescript developer but need to set this up. How to add a loader for js and jsx files so that I can use the typescript project. Would this suffice?

**Comment by TCourtneyOwen** [comment]
Generator-Office now offers both Typescript and JavaScript React templates. Please update generator-office to the latest version (1.3.0).

Thanks,

Courtney
