### ISSUE TITLE
Invalid reference to home/home.html in app.routes.js in generated appread files

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#39]
For a Mail Add-in the `appread/app.routes.js` file contains an invalid reference to the `home/home.html` file. The generated reference is `appread/home/home.html` while it should be `home/home/html` to point to the correct location of the file.

**Comment by martellaj** [comment]
It actually should be `/home/home.html`. The routing file is already in `appread`, but it's trying to find another `appread` directory. The same goes for the `appcompose`.

**Comment by martellaj** [comment]
Fixed in PR #56.
