### ISSUE TITLE
RangeError: Invalid typed array length: -4095

### ISSUE THREAD

**Issue by SKumarSpace** [OfficeDev/generator-office#395]
Hello,

I am receiving this runtime error when using "npm start". 

iMac:My Office Add-in sk$ npm start

&gt; my-office-add-in@0.1.0 start /Users/sk/My Office Add-in
&gt; webpack-dev-server --mode development --https --key ./certs/server.key --cert ./certs/server.crt --cacert ./certs/ca.crt --port 3000

ℹ ｢wds｣: Project is running at https://localhost:3000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wdm｣: Hash: bc4584fd3e589a44bc5e
Version: webpack 4.12.0
Time: 8540ms
Built at: 12/23/2018 6:33:21 PM
                           Asset       Size         Chunks             Chunk Names
                          app.js    338 KiB            app  [emitted]  app
                function-file.js    338 KiB  function-file  [emitted]  function-file
                     polyfill.js    793 KiB       polyfill  [emitted]  polyfill
                      index.html   2.03 KiB                 [emitted]  
function-file/function-file.html  737 bytes                 [emitted]  
Entrypoint polyfill = polyfill.js
Entrypoint app = app.js
Entrypoint function-file = function-file.js
[0] multi (webpack)-dev-server/client?https://localhost:3000 babel-polyfill 40 bytes {polyfill} [built]
[1] multi (webpack)-dev-server/client?https://localhost:3000 ./src/index.js 40 bytes {app} [built]
[2] multi (webpack)-dev-server/client?https://localhost:3000 ./function-file/function-file.js 40 bytes {function-file} [built]
[./function-file/function-file.js] 324 bytes {function-file} [built]
[./node_modules/babel-polyfill/lib/index.js] 833 bytes {polyfill} [built]
[./node_modules/core-js/fn/regexp/escape.js] 108 bytes {polyfill} [built]
[./node_modules/core-js/shim.js] 7.99 KiB {polyfill} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {function-file} {app} {polyfill} [built]
[./node_modules/regenerator-runtime/runtime.js] 23.9 KiB {polyfill} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {function-file} {app} {polyfill} [built]
[./node_modules/url/url.js] 22.8 KiB {function-file} {app} {polyfill} [built]
[./node_modules/webpack-dev-server/client/index.js?https://localhost:3000] (webpack)-dev-server/client?https://localhost:3000 7.75 KiB {function-file} {app} {polyfill} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {function-file} {app} {polyfill} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {function-file} {app} {polyfill} [built]
[./src/index.js] 642 bytes {app} [built]
    + 340 hidden modules
Child html-webpack-plugin for "function-file/function-file.html":
     1 asset
    Entrypoint undefined = function-file/function-file.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./function-file/function-file.html] 739 bytes {0} [built]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./index.html] 2.08 KiB {0} [built]
ℹ ｢wdm｣: Compiled successfully.
buffer.js:72
class FastBuffer extends Uint8Array {}
^

RangeError: Invalid typed array length: -4095
    at new Uint8Array (&lt;anonymous&gt;)
    at new FastBuffer (buffer.js:72:1)
    at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:144:17)
    at Stream.&lt;anonymous&gt; (/Users/sk/My Office Add-in/node_modules/handle-thing/lib/handle.js:120:12)
    at Stream.emit (events.js:194:15)
    at endReadableNT (/Users/sk/My Office Add-in/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-office-add-in@0.1.0 start: `webpack-dev-server --mode development --https --key ./certs/server.key --cert ./certs/server.crt --cacert ./certs/ca.crt --port 3000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-office-add-in@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sk/.npm/_logs/2018-12-23T23_33_30_945Z-debug.log
 iMac:My Office Add-in sk$

**Comment by TCourtneyOwen** [comment]
@SKumarSpace This is quite an old issue, and we haven't heard of any similar issues in the numerous yo office updates we have published since this issue was originally opened. Please update to the latest version of yo office (1.3.0) to see if this fixes the issue. If not, please reopen the issue and we will investigate further.

Thanks,

Courtney
