### ISSUE TITLE
dataValidation does not exist on type Excel.range

### ISSUE THREAD

**Issue by ianchouinard** [OfficeDev/generator-office#396]
Just installed the office add-in generator via yeoman 2 days ago. Created an angular/typescript excel add in. Trying to follow the examples here, but am getting the following type error dataValidation does not exist on type range. 
When looking at the range class in the typings file for office-js, dataValidation isn't listed there. 

I understand that range.dataValidation is from API v1.8, but I just installed the office add in generator via yeoman 2 days ago (so it should be there), and it is not clear how I check what version of the API I currently have, or how to update.

Thanks

package.json
```json
  "dependencies": {
    "office-toolbox": "^0.1.0",
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/platform-browser": "^5.2.9",
    "@angular/platform-browser-dynamic": "^5.2.9",
    "babel-polyfill": "^6.26.0",
    "@microsoft/office-js-helpers": "^1.0.1",
    "office-ui-fabric-js": "^1.3.0",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@types/node": "^9.4.7",
    "@types/office-js": "^0.0.37",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-env": "^1.6.1",
    "typescript": "^2.7.2",
    "file-loader": "^1.1.11",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.0.7",
    "ts-loader": "^4.1.0",
    "webpack": "^4.1.1",
    "webpack-cli": "^3.1.1",
    "webpack-dev-server": "^3.1.1"
  }
```

versions shown in manifest
``` xml
<OfficeApp
          xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
          xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides"
          xsi:type="TaskPaneApp">
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e12c8da9-16ef-b641-aa8a-b5dd37b93d63
* Version Independent ID: e8264f34-086a-65be-d91d-3405159c7bcb
* Content: [Add data validation to Excel ranges - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-data-validation)
* Content Source: [docs/excel/excel-add-ins-data-validation.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-data-validation.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by akrantz** [comment]
Pull request https://github.com/OfficeDev/generator-office/pull/397.
