### ISSUE TITLE
The type attribute is obsolete on script tags in html5

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#40]
According to the [HTML5 spec](http://www.w3.org/html/wg/drafts/html/master/semantics.html#the-script-element) if a script tag refers to a `text/javascript` script, then the `type` attribute is not required. Removing it from the code would simplify the markup.

**Comment by andrewconnell** [comment]
Yup, good call

**Comment by waldekmastykarz** [comment]
There are stil a couple of script references with the `type` attribute specified in https://github.com/OfficeDev/generator-office/blob/99362c30bf03bb19684ed9e807e13a544c10de61/generators/mail/templates/ng/appcompose/index.html#L36-L39

**Comment by andrewconnell** [comment]
Fix it :)
