### ISSUE TITLE
Yo Office generated react project cannot be sideloaded on Desktop nor Edge

### ISSUE THREAD

**Issue by Rickyp** [OfficeDev/generator-office#401]
Repro:
Run Yo Office, arguments shall be react and excel
Attempt to sideload the fresh generated project

Expected behavior:
The addin sideloads on a taskpane with the default template.

Actual behavior: Displays error message and throws the following information on Console when sideloading on excel online Edge browser.
![image](https://user-images.githubusercontent.com/7102621/50866568-3f84cf00-135f-11e9-9368-f7edd458a6f0.png)

Note: The page can still be loaded from an edge tab
![image](https://user-images.githubusercontent.com/7102621/50866481-f6347f80-135e-11e9-859b-111aaf6b6846.png)

The sideloading does work on excel online for Chrome and IE browsers. The sideload does NOT work on excel Desktop, my OS version is 1809 (17763.195) and office version is 1902 Build 11304

![image](https://user-images.githubusercontent.com/7102621/50866239-0a2bb180-135e-11e9-9680-afa60e51928a.png)

**Comment by TCourtneyOwen** [comment]
I am not repro'ing this behavior in either Edge or Chrome with a React Excel add-in.  When you say that you side-loaded the add-in, do you mean that you did Insert-->Office Addins and then uploaded the manifest? That's what I did, and things worked fine. Also, are you sure the that the dev-server is running ("npm start" for your React Excel project)?

-Courtney

**Comment by akrantz** [comment]
This is due to Edge webview control being used instead of IE webview.  The Edge webview requires the developer to allow access to localhost by running the following command: 

`CheckNetIsolation LoopbackExempt -a -n="microsoft.win32webviewhost_cw5n1h2txyewy"`

**Comment by Rickyp** [comment]
Using Adam's suggestion does work for excel Desktop now, but on excel online I still can't get it to load correctly on Edge.

I am following the basic steps of creating the default project from yo office, running npm start, and uploading addin manifest from insert addin, no other extra steps taken. Excel online Chrome and IE (and now excel Desktop thanks to Adam's command) on the other hand do work when attempting the same steps, it is only happening on excel online Edge.

**Comment by Rickyp** [comment]
The commands suggested solved everything, thanks guys!
