### ISSUE TITLE
Generator should use office-js by default

### ISSUE THREAD

**Issue by fpouyez** [OfficeDev/generator-office#403]
Hi !
When I generate a project with the generator (Angular project, TypeScript, for Word Addin), the package **@microsoft/office-js** is not in the dependencies.

The file index.html refers to :
`<script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.debug.js"></script>`
So, it works, but it's not the real lib we should use in prod.

The generator should use 
`<script src="/assets/office-js/office.js"></script>`
with these scripts copied by Angular-Cli :+1: 

```
      "assets": [
        { 
          "glob": "**/*",
          "input": "../node_modules/@microsoft/office-js/dist",
          "output": "./assets/office-js"
        }
      ],
```

Regards…

**Comment by akrantz** [comment]
This script tag should now reflect office.js instead of office.debug.js. Please re-open if you find there is still a problem.
