### ISSUE TITLE
Default manifest.xml for powerpoint appears to use an invalid permission name

### ISSUE THREAD

**Issue by SeanKilleen** [OfficeDev/generator-office#407]
Hey all! Came across this and figured I would mention it.

**Steps:**

* `npm install -g yo`
* `npm install -g generator-office`
* `yo office`
* Select React
* Select Powerpoint
* Complete the steps
* Update manifest.xml (guid, description, provider, etc.)
* `npm start`
* Go to add-in management page (e.g. on office365 portal)
* Add manifest from file and select `manifest.xml`

**Expected behavior:** Add-in is added for side-loading.

**Actual behavior:** Error message in the office365 portal: `The app list for the mailbox can't be read for the following reason: The value of the //owe1_1:Permissions element, ReadWriteDocument, is invalid..`

Should there be a different permissions element by default for powerpoint projects?

**Comment by TCourtneyOwen** [comment]
Thanks for reporting this issue, Sean. I will look into it when I’m back in the office on Monday. 

-Courtney

**Comment by TCourtneyOwen** [comment]
Hi Sean,

I think there must be a problem with the Add-ins link in general on the Office365 Portal.  I just clicked on it and got a 404 error.

As for the React PPT add-in, I didn't have any problems with it when using it with PowerPoint Online.  I opened a new PPT deck, clicked on Insert-->Add-ins and uploaded the manifest.  The add-in taskpane opened fine and worked as expected.  

You may want to try the steps I used above for inserting your PPT add-in.

Thanks,

Courtney

**Comment by akrantz** [comment]
This should be working now. Please re-open if there is still a problem.
