### ISSUE TITLE
how to deploy the solution to azure web app

### ISSUE THREAD

**Issue by chenxizhang** [OfficeDev/generator-office#408]
how to deploy the solution to azure web app?

**Comment by leoseccia** [comment]
I tried and I hit this error: https://stackoverflow.com/questions/56629689/ts2304-cannot-find-name-office-when-deploying-to-azure

**Comment by TCourtneyOwen** [comment]
This question is outside the scope of this project.  You may want to check out this article for details:  https://docs.microsoft.com/en-us/office/dev/add-ins/publish/host-an-office-add-in-on-microsoft-azure

**Comment by chenxizhang** [comment]
https://azure.microsoft.com/en-us/services/app-service/static/  this can help
