### ISSUE TITLE
Yo Office Requires Git (simple-git) to be installed for some templates

### ISSUE THREAD

**Issue by LouMM** [OfficeDev/generator-office#414]
The git commands to acquire templates from Git require that git be installed on the machine running Yeoman Office. (yo office). This should be made a requirement or messaged to the user that they need to install it.

Dependency Section here: https://github.com/steveukx/git-js#readme

**Comment by akrantz** [comment]
You can download a zip from GitHub directly. We don't actually need to clone and then delete the .git folder. That would remove the dependency.

**Comment by akrantz** [comment]
This is now resolved and git is no longer a requirement.
