### ISSUE TITLE
Webpack proxying doesn't work

### ISSUE THREAD

**Issue by mattcopas** [OfficeDev/generator-office#416]
Hi,

I have a separate backend domain that I need to access.

I want to use proxying for this so that my front end doesn't need to be aware of the backedn host - e.g. `/abc` should proxy to `https://localhost:8080`,

I've tried adding a proxy object to both package.json and webpack.config.js as follows:

```
'/abc': {
        target: 'https://localhost:8080',
        pathRewrite: {
          '^/abc': '',
        }
      }
```

However this seems to be being ignored, as I just get a 404 in the console for `https://localhost:3000/abc` and there is nothing in the webpack server logs after "Compiled Sucessfully"

is there some extra config required to get proxying to work? 

Thanks for any help

**Comment by millerds** [comment]
You have the backend running of port 8080?  If the proxy isn't running it wont be found.
