### ISSUE TITLE
Add Angular + ADAL JS as technology

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#42]
Add Angular + ADAL JS as technology to simplify building add-ins connected to Office 365. Add-in generated using this technology would contain all the manual steps described in the [ADAL JS manual](https://github.com/OfficeDev/generator-office/blob/master/docs/adal-config.md).

**Comment by andrewconnell** [comment]
I like the approach provided this is a new tech option and not a change to the existing angular tech option. Want to take it on @waldekmastykarz >

**Comment by jthake** [comment]
Let do it like how the angular generator has controller generators. check out script-base.js https://github.com/yeoman/generator-angular/blob/master/script-base.js
we can just have placeholder comments that file i/O can find and inject needed code.

**Comment by waldekmastykarz** [comment]
Sure!
