### ISSUE TITLE
YO Office plugin, webpack PROD mode 

### ISSUE THREAD

**Issue by vyasrao22** [OfficeDev/generator-office#420]
The YO OFFICE plugin does not work in prod mode. 

Everything works great in the Dev mode in WEBPACK, but when running using node on the prod mode with webpack, I am facing issues with es2015 regererator runtime and DOM - document reference error. 

I am developing an office addin with Excel and using Yo Office. I am able to do npm start but however the webpack prod mode is giving some issues on es2015, regenerator runtime. I solved this by setting preset as es2015 however, still not able to solve the below error. 

```
E:\ADDIN\bfm\models\dist\app.js:32
function(t){var e,n,r,o,i,s,u,a,c,l,f,p,d,h,v,y,g,m,b,x="sizzle"+1*new Date,w=t.document,_=0,j=0,S=st(),O=st(),E=st(),T=function(t,e){return t===e&&(f=!0),0},A={}.hasOwnProperty,k=[],P=k.pop,C=k.push,N=k.push,I=k.slice,D=function(t,e){for(var n=0,r=t.length;n<r;n++)if(t[n]===e)return n;return-1},M="checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",L="[\\x20\\t\\r\\n\\f]",F="(?:\\\\.|[\\w-]|[^\0-\\xa0])+",R="\\["+L+"*("+F+")(?:"+L+"*([*^$|!~]?=)"+L+"*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|("+F+"))|)"+L+"*\\]",U=":("+F+")(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|"+R+")*)|.*)\\)|)",q=new RegExp(L+"+","g"),W=new RegExp("^"+L+"+|((?:^|[^\\\\])(?:\\\\.)*)"+L+"+$","g"),H=new RegExp("^"+L+"*,"+L+"*"),B=new RegExp("^"+L+"*([>+~]|"+L+")"+L+"*"),z=new RegExp("="+L+"*([^\\]'\"]*?)"+L+"*\\]","g"),$=new RegExp(U),V=new RegExp("^"+F+"$"),G={ID:new RegExp("^#(

TypeError: Cannot read property 'document' of undefined
    at Object.<anonymous> (E:\ADDIN\bfm\models\dist\app.js:32:83167)
    at Object.<anonymous> (E:\ADDIN\bfm\models\dist\app.js:32:83291)
    at n (E:\ADDIN\bfm\models\dist\app.js:1:172)
    at Object.defineProperty.value (E:\ADDIN\bfm\models\dist\app.js:7:67766)
    at n (E:\ADDIN\bfm\models\dist\app.js:1:172)
    at E:\ADDIN\bfm\models\dist\app.js:1:964
    at Object.<anonymous> (E:\ADDIN\bfm\models\dist\app.js:1:975)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

**Comment by vyasrao22** [comment]
@kbrandl  thanks. I raised the issue there 2 days before and did not receive any response and hence raised here.

**Comment by kbrandl** [comment]
@akrantz or @TCourtneyOwen are either of you able to provide input about this issue?

**Comment by akrantz** [comment]
We will need to reproduce and investigate. 

@vyasrao22 If you could provide steps to reproduce, it will make it easier for us to look into it. Can you do this using the project as generated by Yo Office, or is there additional code that you've added which is required to show the problem? Also, providing details about OS, browser, Office version would be useful to know.

**Comment by vyasrao22** [comment]
@akrantz I am using this tutorial https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=visual-studio-code with YO OFFICE, J Query. Not additional code. You can even try running the project created in PROD mode, will create the same result. 

My workstation settings : 

Windows 10 
Office Excel: 
![image](https://user-images.githubusercontent.com/10957095/53587592-db7eca00-3b9b-11e9-8247-ae695c2e0267.png) 
node 8 
Bable and webpack as created by YO proeject

**Comment by akrantz** [comment]
@vyasrao22 I ran Yo Office using JQuery, JavaScript, Excel, and running webpack-dev-server in development or production mode works without errors. "npm start" for development, or editing the "start" script in package.json to switch mode to "production".

I followed the steps to edit the code from the tutorial link you provided, and again it works OK in both development and production modes.

I tried this with both Node 8 (8.15.1) and Node 10 (10.15.1).

I am unable to reproduce any problems.

You mention running using node with "es2015 regererator runtime". I would assume this is running in the browser or Excel webview, but if you're using Node where document is not defined, then code wouldn't work. I am not sure what "es2015 regererator runtime" ultimately refers, or what code you've added. I'd like to assist more but I don't have enough information to understand the problem you've encountered.

**Comment by vyasrao22** [comment]
I am addin the project here. 

These are the steps I am following : 

E:\EXCELADDIN\models>npm run build

> models@0.1.0 build E:\EXCELADDIN\models
> webpack --mode production

Hash: ca977dee540baf173758
Version: webpack 4.29.5
Time: 12478ms
Built at: 2019-03-01 12:58:21
                               Asset       Size  Chunks             Chunk Names
7f313c06a52dabe7267420021403d038.png   11.6 KiB          [emitted]
                              app.js     61 KiB       0  [emitted]  app
                    function-file.js  982 bytes       1  [emitted]  function-file
    function-file/function-file.html  737 bytes          [emitted]
                          index.html   2.69 KiB          [emitted]
                         polyfill.js   92.5 KiB       2  [emitted]  polyfill
Entrypoint polyfill = polyfill.js
Entrypoint app = app.js
Entrypoint function-file = function-file.js
 [93] (webpack)/buildin/global.js 472 bytes {2} [built]
[333] ./src/index.js 7.56 KiB {0} [built]
[334] ./src/groups/sales_assumptions.js 9.65 KiB {0} [built]
[335] ./function-file/function-file.js 324 bytes {1} [built]
    + 332 hidden modules
Child html-webpack-plugin for "function-file\function-file.html":
     1 asset
    Entrypoint undefined = function-file/function-file.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./function-file/function-file.html 739 bytes {0} [built]
Child html-webpack-plugin for "index.html":
                                   Asset      Size  Chunks             Chunk Names
    7f313c06a52dabe7267420021403d038.png  11.6 KiB          [emitted]
     + 1 hidden asset
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./index.html 2.81 KiB {0} [built]
    [1] ./assets/logo-filled.png 82 bytes {0} [built]

E:\EXCELADDIN\models>node dist/app.js
E:\EXCELADDIN\models\dist\app.js:7
var o;"undefined"!=typeof self&&self,o=function(){return function(e){var t={};function r(o){if(t[o])return t[o].exports;var n=t[o]={i:o,l:!1,exports:{}};return e[o].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.m=e,r.c=t,r.d=function(e,t,o){r.o(e,t)||Object.defineProperty(e,t,{configurable:!1,enumerable:!0,get:o})},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s="./src/index.ts")}({"./node_modules/lodash-es/_DataView.js":function(e,t,r){"use strict";var o=r("./node_modules/lodash-es/_getNative.js"),n=r("./node_modules/lodash-es/_root.js"),s=Object(o.a)(n.a,"DataView");t.a=s},"./node_modules/lodash-es/_Map.js":function(e,t,r){"use strict";var o=r("./node_modules/lodash-es/_getNative.js"),n=r("./node_modules/lodash-es/_root.js"),s=Object(o.a)(n.a,"Map");t.a=s},"./node_modules/lodash-es/_Promise.js":function(e,t,r){"use stri

ReferenceError: regeneratorRuntime is not defined
    at Object.333 (E:\EXCELADDIN\models\dist\app.js:7:56711)
    at r (E:\EXCELADDIN\models\dist\app.js:1:172)
    at 130.t (E:\EXCELADDIN\models\dist\app.js:1:964)
    at Object.<anonymous> (E:\EXCELADDIN\models\dist\app.js:1:975)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)



[models.zip](https://github.com/OfficeDev/generator-office/files/2918931/models.zip)

**Comment by vyasrao22** [comment]
@akrantz  
 or editing the "start" script in package.json to switch mode to "production".

=> Can you try with the existing build command and the run with the dist folder. This is where the error occurs.

**Comment by akrantz** [comment]
@vyasrao22 I downloaded the project, changed the npm start script to use --mode production and it doesn't encounter an error.

**Comment by vyasrao22** [comment]
Update : @akrantz 

Sorry for this ticket, the mistake was on my side. 

After doing the 'npm run build' I was trying to run the dist/app.js with node. 

I corrected that by hosting them as static files in express server. Then encountered a problem where the CSS and jquery and node module dependencies were not getting included. 

Sorted that by importing them in index.js. 

Closing this issue.

**Comment by akrantz** [comment]
@vyasrao22 No worries. Glad you sorted it out!
