### ISSUE TITLE
--js option not working

### ISSUE THREAD

**Issue by leoseccia** [OfficeDev/generator-office#421]
`yo office --js` still generate project using TypeScript...

**Comment by akrantz** [comment]
Which project? If you're trying to create an Office Add-in using React, there is not currently support for JavaScript. We're working on this.

**Comment by leoseccia** [comment]
ah ok... yes, it is react...

**Comment by leoseccia** [comment]
added a pull request for readme.md to explain this...

**Comment by TCourtneyOwen** [comment]
React JS support is coming in the very near future, but good catch that the ‘js’ switch currently doesn’t work with the React project template.

**Comment by akrantz** [comment]
We've released updates for all of the templates and React contains both TypeScript and JavaScript flavors. Please try it out now. Thanks.
