### ISSUE TITLE
Add sample of add-in commands in function_file for add-in generated in typescript

### ISSUE THREAD

**Issue by datatunning** [OfficeDev/generator-office#424]
**Issue**
As of today, we can generate a typescript based Outlook addin template but when the function_file.ts get ttranspiled, the generated code does not sync with the executeFunction set up in the manifest resulting in a banner showing up in the mail message stating that "...the request is being procesed..." but it actually does nothing.

**Expectation**
As a developer, I would like the typescript version of the function_file to includes a function that can be called from an executeFunction command set in the manifest.xml

**Outcome**
Once the typescript template is transpiled, the generated JS should allow the UI-less command to run from the Office Addin.

**Comment by ng-marcus** [comment]
I also have the same problem.    I think though it's the webpack part of the process that's failing, as I have the same issue if I use a pure Javascript version of the function_file.

**Comment by akrantz** [comment]
We've updated the templates to better partition the code so it is more clear what is used for app commands versus the task pane. Take a look here: https://github.com/OfficeDev/Office-Addin-TaskPane. The src\commands\commands.ts file contains code for the app commands.

This will build into `dist\commands.js` which should contain the function specified in the manifest.

**Comment by ng-marcus** [comment]
Thank you, this is useful as it seems to have a much cleaner configuration for webpack.

The example doesn't include an executable function within the commands, it just says 

// Add any ui-less function here

and I'm currently struggling to get functions declared there to run (with the old code).  The same code works fine when inlined into the html file.  I suspected with the old sample code this was some sort of webpack issue, so I'll try with this new sample code (I need to do some more work first as I'm working on Outlook plugins) and I'll raise a new issue if this doesn't work.

**Comment by datatunning** [comment]
I'll give it a try too as like Marcus, the previous template transpilling process was interfering with the UI-less command functions declaration/use from the manifest.

I'll let you know how the testing goes.

Thanks a lot.

**Comment by ng-marcus** [comment]
I still can't get it to work.   If I add the function where the comment suggests, it never gets called.  Is there any demo code of an actual command function working from a .ts file we can work from?

from manifest.xml

``` <Action xsi:type="ExecuteFunction">
                      <FunctionName>insertDefaultAttachment</FunctionName>
                    </Action>```

and the command.ts file

```(() => {
  // The initialize function must be run each time a new page is loaded
  Office.initialize = () => {
    console.log("contoso office init");
  };

  // Add any ui-less function here


   function insertDefaultAttachment(event) {
    console.log("insertDefaultAttachment");
  }

 
})();```

**Comment by datatunning** [comment]
I'm unable to test today, but if you could try this

(() => {
  // The initialize function must be run each time a new page is loaded
  Office.initialize = () => {
    console.log("contoso office init");
  };
  // Add any ui-less function here 
})();

export function insertDefaultAttachment(event) {
    console.log("insertDefaultAttachment");
 }

The idea is to prevent transpilation to wrap the function into the webpack code that become unreachable by the manifest.

Another option is to use a js file for the UI-less commands, but another issue arise when access to Transpiled code from the Js file is required....

**Comment by ng-marcus** [comment]
I added the function in both places just to test, and whilst it ends up in the transpiled JS, it's not called.  

My intuition is that is because it's become "exported" rather than just a simple inline function in the same file it now can't be invoked by Office JS.

Transpiled output below:

```
(function () {
    // The initialize function must be run each time a new page is loaded
    Office.initialize = function () {
        console.log("contoso office init");
    };
    // Add any ui-less function here
    function insertDefaultAttachment2(event) {
        console.log("insertDefaultAttachment");
    }
})();
function insertDefaultAttachment(event) {
    console.log("insertDefaultAttachment");
}
exports.insertDefaultAttachment = insertDefaultAttachment;
```

**Comment by leoseccia** [comment]
got the same issue - https://stackoverflow.com/questions/55870787/executefunction-not-invoking-the-function

**Comment by TCourtneyOwen** [comment]
Sorry to hear you are having problems.  Which version of generator-office are you running (the latest is 1.1.27)?  

Also, we are going to be pushing out a pretty big change to generator-office in the next day or so.  The updated version will pull the project templates from project repositories when it generates a new project.  The React repository is at https://github.com/OfficeDev/Office-Addin-TaskPane-React.  You may want to try cloning this repo and creating your project from this updated React template. Your Office-Js code would go under /src/taskpane/components/Outlook.App.tsx.

Thanks,

Courtney

**Comment by leoseccia** [comment]
@TCourtneyOwen - yes, I am using the latest version... 

What you are suggesting does not make sense, we are trying to get a function invoked by a ribbon button as described here: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/action and here: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile

**Comment by TCourtneyOwen** [comment]
Looping in @akrantz 

I think you actually want to put your code in https://github.com/OfficeDev/Office-Addin-TaskPane-React/blob/master/src/commands/commands.ts then.

**Comment by leoseccia** [comment]
@TCourtneyOwen - that is where my code is (and the others on this thread)...

As others have suggested, I think the issue is with the way webpack bundles/transpile the code.

**Comment by akrantz** [comment]
Does the code that is output into `dist\commands.js` look reasonable?  I will try to look into this later today...

**Comment by datatunning** [comment]
The issue is that during "tranpilation" of the command.ts file (or old function_file), any "unused" method defined after the Office.initialize() are removed and therefore the function is not in the JS output.

The issue exit in the old (only webpack) and new template, (webpack + babel)

Kind regards
Bruno

**Comment by ng-marcus** [comment]
I think also that the transpilation both modifies the function name and exports it from a module so it's not "inline" as the manifest processor expects.

**Comment by leoseccia** [comment]
@akrantz - did you manage to replicate the issue?

**Comment by leoseccia** [comment]
Hello,

I think I managed to fix this on my side by attaching my function to the global namespace like this:
```
(() => {
  Office.initialize = () => {
    console.log("function file loaded...!");
   };
  })();
 
function functionToInvoke(event: any): void {
    console.log("i got invoked!!!");
    event.completed();
}

const _global = (window /* browser */ || global /* node */) as any;
_global.functionToInvoke= functionToInvoke;
```

**Comment by ng-marcus** [comment]
@leoseccia  That looks good!   I'll give it a go too and report back.  Thanks for sharing!

**Comment by datatunning** [comment]
@leoseccia I've just tested your solution and it does work. 

I'm just wondering why the template set a comment to add UI-Less function right after the Office.Initialize() call which in turn make the function invisible with your solution.

Thanks for sharing a working option.

**Comment by leoseccia** [comment]
@datatunning this will also work:
```
(() => {
  // The initialize function must be run each time a new page is loaded
  Office.initialize = () => {
    console.log("function file loaded...!");
   };

  (window as any).functionToInvoke = (event: any)=>{
      console.log("i also get invoked...");
      event.completed();
  }
  })();
```
The issue here is that a function is not in the global namespace by default. 

On top of that, I find `typescript` strong typing to work against me a lot of the times - in this instance having to cast to any is a simple little step that is not that obvious... i'm too used to javascript loose typing.

**Comment by leoseccia** [comment]
@akrantz and @TCourtneyOwen - can you fix the templates by having a comment or an example on this please? I would do a PR but I'm not sure how it fits with your plans and changes... 

Thank you!

**Comment by TCourtneyOwen** [comment]
Thanks for sending the code snippet. Either Adam or I will look into this and see if we can incorporate it into the new project templates. If so, we will include you on the PR for review. 

-Courtney

**Comment by akrantz** [comment]
I have an example working with Outlook so that it shows a notification message when the command is invoked. Here's the code. 

```
Office.onReady(info => {
  console.log("commands are ready!");
});

function action(event: Office.AddinCommands.Event) {
  const message: Office.NotificationMessageDetails = {
    type: Office.MailboxEnums.ItemNotificationMessageType.InformationalMessage, 
    message: "Performed action.",
    icon: "Icon.80x80",
    persistent: false
  }

  Office.context.mailbox.item.notificationMessages.replaceAsync("action", message);

  event.completed();
}

function getGlobal() { 
  return (typeof self !== "undefined") ? self :
    (typeof window !== "undefined") ? window : 
    (typeof global !== "undefined") ? global :
    undefined;
}

const g = getGlobal() as any;
g.action = action;
```

The manifest contains:
```
                <Control xsi:type="Button" id="ActionButton">
                  <Label resid="ActionButton.Label"/>
                  <Supertip>
                    <Title resid="ActionButton.Label"/>
                    <Description resid="ActionButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ExecuteFunction">
                    <FunctionName>action</FunctionName>
                  </Action>
                </Control>                

    <Resources>
      <bt:ShortStrings>
        <bt:String id="ActionButton.Label" DefaultValue="Perform an action"/>
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="ActionButton.Tooltip" DefaultValue="Perform an action when clicked."/>
      </bt:LongStrings>
    </Resources>
```

**Comment by akrantz** [comment]
https://github.com/OfficeDev/Office-Addin-TaskPane/pull/30

We'll need to make sure that the documentation team is aware and is OK with taking this change right now.

**Comment by datatunning** [comment]
Thank you all for sorting out this.

**Comment by maniteja** [comment]
Hi,

I am also facing same issue unable to execute ui-less functions in function-file.can any one help on this please
