### ISSUE TITLE
Add monorepo (rush / lerna /  other) architecture option during generation

### ISSUE THREAD

**Issue by datatunning** [OfficeDev/generator-office#426]
**Issue**
The current base template can be too basic while exploring possible project architecures. When building project for addin that involves the development of libraries, the only option is via npm.

**Solution**
Monorepository offers project with substantial size to be splitted into smaller repo without the hoverhead of having to generates npm packages.

**Comment by akrantz** [comment]
The template will create a single package. If you set up Lerna or Rush, yuou can use Yo Office to create the package folder under the packages folder. It will be compatible.
