### ISSUE TITLE
Possible to include Angular-Material? 

### ISSUE THREAD

**Issue by bubuhubu9k** [OfficeDev/generator-office#433]
I have to create Outlook Add-in using Angular framework.
Once I have created project using office-generator; if I install Angular Material into the project, I get following warning while doing  `npm-start`

`WARNING in ./node_modules/@angular/core/esm5/core.js 6570:15-36
Critical dependency: the request of a dependency is an expression
 @ ./src/app/app.module.ts
 @ ./src/index.ts
 @ multi (webpack)-dev-server/client?https://localhost:3000 ./src/index.ts

WARNING in ./node_modules/@angular/core/esm5/core.js 6590:15-102
Critical dependency: the request of a dependency is an expression
 @ ./src/app/app.module.ts
 @ ./src/index.ts
 @ multi (webpack)-dev-server/client?https://localhost:3000 ./src/index.ts

WARNING in ./node_modules/@angular/core/esm5/core.js 6570:15-36
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
 @ ./src/app/app.module.ts 7:0-41 17:8-16
 @ ./src/index.ts
 @ multi (webpack)-dev-server/client?https://localhost:3000 ./src/index.ts

WARNING in ./node_modules/@angular/core/esm5/core.js 6590:15-102
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
 @ ./src/app/app.module.ts 7:0-41 17:8-16
 @ ./src/index.ts
 @ multi (webpack)-dev-server/client?https://localhost:3000 ./src/index.ts
Child html-webpack-plugin for "function-file\function-file.html":
     1 asset
    Entrypoint undefined = function-file/function-file.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./function-file/function-file.html] 821 bytes {0} [built]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./index.html] 1.58 KiB {0} [built]
i ｢wdm｣: Compiled with warnings.`

Add on doesn't all up either into Outlook. 

Anyone manage to include angular-material?

Thanks in advance.

**Comment by igor-ribeiiro** [comment]
@bubuhubu9k I know this bug is kinda old, but I just tried and didn't see any of the warnings you just mentioned.
I used the dependency `angular-material` in version `1.2.5` (latest) and no problems were raised.

If needed, it would be great if you could try again. I will be closing this issue until then, feel free to reopen it.
