### ISSUE TITLE
Code to make template target a single host needs to be in the templates themselves

### ISSUE THREAD

**Issue by akrantz** [OfficeDev/generator-office#447]
There is code to modify the template files so that it targets a single host. This is fragile in that changes in the template filesystem structure are dependent on generator-office code. Any changes will require both to be changed and published in lock-step.

The template itself should contain a script which allows it to be customized to target a single host, and generator-office should call that script instead.

**Comment by TCourtneyOwen** [comment]
@akrantz So you envision an npm script in the project repos that generator-office can call after running 'npm install' at the end of project generation?

**Comment by TCourtneyOwen** [comment]
VSO Task 3341632: Code to make template target a single host needs to be in the templates themselves is now tracking this

**Comment by akrantz** [comment]
yes, we need a package.json script, e.g. "convert-to-single-host" so that generator-office can run "npm run convert-to-single-host excel" after it does the npm install, and the script runs the code that is currently embedded in generator-office. It should be straight-forward to move the code over. Thus, the script can be changed along with other changes to the project and not require an update to generator-office to make project template changes.

**Comment by TCourtneyOwen** [comment]
Makes sense,  But it seems like we want to probably remove the convert-to-single-host script from the package.json after generator-office calls it. Otherwise if it still exists in the project and a user invokes it for some reason, it may possibly break their project

**Comment by akrantz** [comment]
Of course, that's one of the things it should do.

**Comment by akrantz** [comment]
This is now complete.
