### ISSUE TITLE
Why did my office NPM fail to start? Can you check it for me please?

### ISSUE THREAD

**Issue by u33445687** [OfficeDev/generator-office#448]
My program is written step by step in accordance with official documents, and so is the command.
Why can't I start port 3000?

![image](https://user-images.githubusercontent.com/37392339/57264846-f93e4300-70a6-11e9-9e5f-461d49255971.png)
Thank you.

**Comment by akrantz** [comment]
The start command did not find anything listening on port 3000. If you run webpack-dev-server, then you should be able to browse to https://localhost:3000/ and see it running.  

The start command will start the dev-server if it is not running before start is called, and wait until it is started before continuing.

Do you get a different result if you create a new TaskPane project and use that?  This would tell if there are changes you've made that are preventing the dev-server from running.

**Comment by TCourtneyOwen** [comment]
Is It possible port 3000 is already in use and thus the dev-server can’t use that port? If so you can specify a different port in the package.json file

**Comment by u33445687** [comment]
> The start command did not find anything listening on port 3000. If you run webpack-dev-server, then you should be able to browse to https://localhost:3000/ and see it running.
> 
> The start command will start the dev-server if it is not running before start is called, and wait until it is started before continuing.
> 
> Do you get a different result if you create a new TaskPane project and use that? This would tell if there are changes you've made that are preventing the dev-server from running.
Thank you for your reply.
The information displayed shows that port 3000 cannot be started. After checking, 3000 port is not used, and I have set up to open 3000 port on Windows. But ultimately it can't start. At present, I put this project in webapp of tomcat, and start Tomcat to be accessible.

**Comment by u33445687** [comment]
> The start command did not find anything listening on port 3000. If you run webpack-dev-server, then you should be able to browse to https://localhost:3000/ and see it running.
> 
> The start command will start the dev-server if it is not running before start is called, and wait until it is started before continuing.
> 
> Do you get a different result if you create a new TaskPane project and use that? This would tell if there are changes you've made that are preventing the dev-server from running.

Thank you for your reply.
The information displayed shows that port 3000 cannot be started. After checking, 3000 port is not used, and I have set up to open 3000 port on Windows. But ultimately it can't start. At present, I put this project in webapp of tomcat, and start Tomcat to be accessible.

**Comment by u33445687** [comment]
> Is It possible port 3000 is already in use and thus the dev-server can’t use that port? If so you can specify a different port in the package.json file

Thank you for your reply.
 After checking, 3000 port is not used, and I have set up to open 3000 port on Windows.

**Comment by TCourtneyOwen** [comment]
Can you possibly package your project up in a zip file, excluding the node_modules directory, and attach it on this thread so we can have a look at it?

**Comment by honb** [comment]
I also got the same issue here. Did you guys make this work? I'm using the latest generator
`{
    "name": "office-addin-taskpane-react",
    "version": "0.0.1",
    "repository": {
        "type": "git",
        "url": "https://github.com/OfficeDev/Office-Addin-TaskPane-React.git"
    },
    "license": "MIT",
    "config": {
        "app-to-debug": "outlook",
        "app-type-to-debug": "desktop",
        "dev-server-port": 3000
    },
    "scripts": {
        "build": "webpack -p --mode production",
        "build-dev": "webpack --mode development",
        "dev-server": "webpack-dev-server --mode development",
        "start": "office-addin-debugging start manifest.xml",
        "start:desktop": "office-addin-debugging start manifest.xml desktop",
        "start:web": "office-addin-debugging start manifest.xml web",
        "stop": "office-addin-debugging stop manifest.xml",
        "validate": "office-toolbox validate -m manifest.xml",
        "watch": "webpack --mode development --watch"
    },
    "dependencies": {
        "core-js": "^2.6.1",
        "es6-promise": "^4.2.6",
        "office-ui-fabric-react": "^6.139.0",
        "react": "^16.8.2",
        "react-dom": "^16.8.2"
    },
    "devDependencies": {
        "@babel/core": "^7.4.4",
        "@types/es6-collections": "^0.5.29",
        "@types/es6-promise": "0.0.32",
        "@types/office-js": "^1.0.1",
        "@types/office-runtime": "^1.0.7",
        "@types/react": "^16.8.3",
        "@types/react-dom": "^16.8.1",
        "@types/react-hot-loader": "^4.1.0",
        "@types/webpack": "4.4.22",
        "@types/webpack-dev-server": "3.1.1",
        "babel-loader": "^8.0.5",
        "clean-webpack-plugin": "^2.0.1",
        "copy-webpack-plugin": "^5.0.3",
        "css-loader": "^2.1.1",
        "extract-text-webpack-plugin": "4.0.0-beta.0",
        "file-loader": "^3.0.1",
        "html-loader": "^0.5.5",
        "html-webpack-plugin": "^3.2.0",
        "less": "^3.9.0",
        "less-loader": "^4.1.0",
        "office-addin-debugging": "^2.1.13",
        "office-addin-dev-certs": "^1.0.1",
        "office-toolbox": "^0.1.1",
        "postcss-loader": "3.0.0",
        "react-hot-loader": "^3.1.3",
        "source-map-loader": "^0.2.4",
        "style-loader": "0.23.0",
        "ts-loader": "^5.4.4",
        "typescript": "^3.4.5",
        "webpack": "^4.30.0",
        "webpack-cli": "^3.3.1",
        "webpack-dev-server": "^3.3.1"
    }
}
`

**Comment by akrantz** [comment]
If you run "npm run dev-server" directly, do you get an error or does it start successfully?

The first time you run, an SSL certificate for https://localhost will be generated, and you'll be prompted to install the CA certificate which signs it so that it is trusted. Could you possibly have that prompt appearing but you didn't see it?

**Comment by akrantz** [comment]
I believe the problem is that the start command is waiting 10 seconds for the dev server to start, but it hasn't started yet, which is likely because of the prompt to install the SSL certificate.

**Comment by honb** [comment]
I get an error when try to run ""
![image](https://user-images.githubusercontent.com/26110193/57776997-00bab780-774b-11e9-96dd-cef7f6e1d8a9.png)

For the old version generator, it was able to run the app without issues

**Comment by akrantz** [comment]
The powershell command used to install the CA certificate is giving an error.

Try running:
`npx office-addin-dev-certs uninstall`

Then:
`npx office-addin-dev-certs install`

This will delete and regenerate the certificates, and try to install the CA certificate.

**Comment by akrantz** [comment]
Also, is Windows activated? there is a message that implies it is not.

**Comment by honb** [comment]
Thanks, I have tried to run uninstall, got the same issue while running "npx office-addin-dev-certs install"
My window is not activated. 
Dont see the guide for CA here: https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/requirements-for-running-office-add-ins

**Comment by akrantz** [comment]
You could also try to manually install the CA certificate. It is located in %USERPROFILE%\.office-addin-dev-certs\ca.crt. You can open that file and install it into the Current User, Trusted Root Certificate Authorities location. Let me know if you can do that or not.

I suspect that this issue could be due to the fact that Windows is not activated.

**Comment by akrantz** [comment]
OK, I've identified the problem. The `npm start` command will start the dev-server in a detached process (separate window). On Mac, when the dev certs are not installed, the script will prompt for the password, but there is no window showing this prompt. It then times out after 30 seconds, and gives the misleading error message.

The workaround is to run `npx office-addin-dev-certs install` to install the dev certs. Then `npm start` will work properly.

**Comment by waqar-imtiaz** [comment]
@akrantz I am facing the same issue on my mac, tried `npx office-addin-dev-certs install` running this but got the same error. anyone knows the cause?

**Comment by akrantz** [comment]
> @akrantz I am facing the same issue on my mac, tried `npx office-addin-dev-certs install` running this but got the same error. anyone knows the cause?

When you run the command to install the dev certs, what is the error you get?

**Comment by waqar-imtiaz** [comment]
@akrantz dev certs were install successfully. When i run npm start, i got thr same above error

**Comment by akrantz** [comment]
Does `npx office-addin-dev-certs verify` show that you have access to https://localhost:3000 ? 
If you run `npm run dev-server`, will it start successfully? if not, what is the error?

**Comment by akrantz** [comment]
@waqar-imtiaz If you run the dev server inside VS Code, it will be a better experience. Use "code ." to open the folder in VS Code. Then, use Terminal, Run Task... `Dev Server` to start the dev server. If the dev certs are not installed, it will prompt for a password to allow them to be installed. After that it should start. You might get an error that port 3000 is in use. You can restart the computer to resolve that and try again. After that, switch to the Debug view, and use Debug, **Start Without Debugging**.  You can't debug with VS Code but you can launch from VS Code. You can right-click the task pane and open Inspector to debug.

**Comment by honb** [comment]
> @akrantz dev certs were install successfully. When i run npm start, i got thr same above error

If so I dont think the problem is Window is not activated yet. 
Tried to import CA manual, still get the error:

"npx office-addin-dev-certs verify"
You need to install certificates for trusted access to https://localhost.

**Comment by honb** [comment]
I tried to run the app on window which activated ==> Its OK
Thanks @akrantz

**Comment by DaveOuds** [comment]
Running into the same issues and tried everything mentioned here as well as the solutions in https://github.com/OfficeDev/office-js-docs-pr/issues/978 , any updates?

**Comment by akrantz** [comment]
Run "npx office-addin-dev-certs install" from a command prompt. It will show a dialog prompt on Windows or ask for a password on Mac. If you accept the prompt or enter the password, then the dev certs should be installed and everything should work after that. Please let me know how it goes.

**Comment by DaveOuds** [comment]
@akrantz its telling me (Im using a mac btw):
error: EACCES: permission denied, unlink '/Users/doudshoorn-a/.office-addin-dev-certs/localhost.crt'

I already ran:
sudo chown -R doudshoorn-a /Users/doudshoorn-a/.office-addin-dev-certs/localhost.crt

and I still get the same output.
If I run it with a sudo it seems to work, but npm start still gives permission errors.
After running sudo npm start everything seems to be fine, but when I look in word i get:

Add-in Error
This add-in is no longer available. If this add-in's manifest was removed, please restore it to its previous location and try again.

when running lsof -i :3000 the server also doesn't seem to be running. However when running netstat -vanp tcp | grep 3000, the server seems to be running

**Comment by akrantz** [comment]
@DaveOuds Run `npx office-toolbox remove`, choose word, and choose an existing manifest file. Repeat until no manifests are listed. Then try again.

There's an issue on mac that affects running add-ins when multiple ones are registered for development.

**Comment by DaveOuds** [comment]
@akrantz unfortunately that didn't help

**Comment by akrantz** [comment]
@DaveOuds I'm sorry you're having this problem. It's supposed to be fairly automatic to get the dev certs installed and I know it must be frustrating that this isn't working for you.

I think you might have generated the `~/.office-addin-dev-certs` folder with sudo permissions, but you don't have permission with a normal user. You shouldn't need to run as sudo for the certs.

I think you should delete the `!/.office-addin-dev-certs` folder. After that, you should run the command `npx office-addin-dev-certs install` as a regular user. This should create the ~/.office-addin-dev-certs folder with the relevant files, and then install the CA certificate.

**Comment by DaveOuds** [comment]
@akrantz That doesn't work either, I checked the permissions and changed them when necessary.

**Comment by akrantz** [comment]
There were a few different issues resolved here. Please open a new issue if you're still having problems.
