### ISSUE TITLE
Should include example unit tests

### ISSUE THREAD

**Issue by bestekov** [OfficeDev/generator-office#457]
Recommend adding support to show some examples of how to write unit tests of custom functions.

The generated example `src/functions/functions.js` contains lots of calls like `CustomFunctions.associate("ADD", add);` that prevent unit tests from just calling that file to test function logic.

I can't seem to find any documentation for best practices for unit testing custom functions so it would be very helpful if the generator included an example or two that tested the example custom functions.

Ideally with being able to access `CustomFunctions` itself to confirm things load correctly, but since that might require the build process, perhaps another way of just testing the functions themselves?

Apologies in advances that I am fairly new to JS testing, so very sorry if I'm missing something obvious.

**Comment by TCourtneyOwen** [comment]
Thanks for your feedback. I think this is an excellent idea. I will look into this and see if we can include some sample unit tests.

**Comment by TCourtneyOwen** [comment]
@bestekov I have a [PR](https://github.com/OfficeDev/Excel-Custom-Functions/pull/153) that implements unit tests for some of the built-in functions. As you will notice, the CustomFunctions.associate calls are removed from src/functions/functions.ts in this PR.  We should be merging these changes in the near future, but I thought I would give you a heads-up that writing unit tests is now possible.

**Comment by bestekov** [comment]
That's awesome! What quick turnaround. Thank you.
