### ISSUE TITLE
Addin Unavailable

### ISSUE THREAD

**Issue by ahmednrana** [OfficeDev/generator-office#461]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-react
## Issue
I am getting this error 
**Addin Unavailable**
This add in is no longer unavailable. If this addin's manifest was removed, please restore it to its previous location and try again.

I am Mac OS Mohave 10.14.5
Using Excel 16.26 provided by my office.

I followed the exact steps for Mac OS but getting this error. If I open the same code on a Windows based machine. It runs fine.

**Comment by AbdulRazaq02** [comment]
@ahmednrana @kbrandl  did you got any solutions for it. I am facing the same error in the angular version. Please help me out

**Comment by akrantz** [comment]
Try clearing out any existing manifests:
* In a Terminal window, run: `npx office-toolbox remove`, choose Excel, and then remove any manifests that are listed. If more than one, run it again until there are no manifests.

Then you should be able to sideload the add-in successfully.

**Comment by AbdulRazaq02** [comment]
@akrantz Thanks a lot mate. It works perfectly.

**Comment by ahmednrana** [comment]
> Try clearing out any existing manifests:
> 
> * In a Terminal window, run: `npx office-toolbox remove`, choose Excel, and then remove any manifests that are listed. If more than one, run it again until there are no manifests.
> 
> Then you should be able to sideload the add-in successfully.

Thanks this solved the issue
