### ISSUE TITLE
Unable to install the CA certificate

### ISSUE THREAD

**Issue by datavisiondt** [OfficeDev/generator-office#462]
When following the Excel custom function Add-in tutorial, I run into the following error when running "npm run build". Spaces in path? Not sure what will be causing this.

> excel-custom-functions-js@2.0.0 build C:\Users\John Doe\Installs\Programs\Visual Studio 2019\Source\Repos\oaddin
> webpack -p --mode production

The developer certificates have been generated in C:\Users\John Doe\.office-addin-dev-certs
The CA certificate is not installed.
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
**Error: Unable to install the CA certificate. Import-Certificate : A positional parameter cannot be found that accepts argument
'Doe\.office-addin-dev-certs\ca.crt'.**
At line:1 char:1
+ Import-Certificate -CertStoreLocation cert:\CurrentUser\Root C:\Users ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Import-Certificate], ParameterBindingExcepti
   on
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.CertificateServices.Commands
   .ImportCertificateCommand

    at C:\Users\John Doe\Installs\Programs\Visual Studio 2019\Source\Repos\oaddin\node_modules\office-addin-dev-certs\lib\install.js:52:19
    at Generator.next (<anonymous>)
    at C:\Users\John Doe\Installs\Programs\Visual Studio 2019\Source\Repos\oaddin\node_modules\office-addin-dev-certs\lib\install.js:6:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\John Doe\Installs\Programs\Visual Studio 2019\Source\Repos\oaddin\node_modules\office-addin-dev-certs\lib\install.js:2:12)
    at installCaCertificate (C:\Users\John Doe\Installs\Programs\Visual Studio 2019\Source\Repos\oaddin\node_modules\office-addin-dev-certs\lib\install.js:44:12)
    at Object.<anonymous> (C:\Users\John Doe\Installs\Programs\Visual Studio 2019\Source\Repos\oaddin\node_modules\office-addin-dev-certs\lib\install.js:38:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\John Doe\Installs\Programs\Visual Studio 2019\Source\Repos\oaddin\node_modules\office-addin-dev-certs\lib\install.js:3:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! excel-custom-functions-js@2.0.0 build: `webpack -p --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the excel-custom-functions-js@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\John Doe\AppData\Roaming\npm-cache\_logs\2019-06-17T21_09_11_770Z-debug.log

**Comment by akrantz** [comment]
I believe the powershell arguments need to be quoted to deal with spaces.

**Comment by akrantz** [comment]
office-addin-dev-certs@1.2.5 is now available that contains the fix for spaces in the path.

**Comment by datavisiondt** [comment]
I know this issue is closed, but I haven't had the time to test until now.   Looks like it is fixed when you npm run build.  But when you do npm run start:desktop, the scripts that starts the web server aborts while importing the Certificate.

**Comment by akrantz** [comment]
@asachin96 Please look into this.

**Comment by TCourtneyOwen** [comment]
@asachin96 has this issue been fixed? If so, can you please add comments and close the issue?  Thanks

**Comment by datavisiondt** [comment]
Hi Courtney,

 

I haven’t checked in the past 2 weeks.  But today I did a refresh of npm, yo and the office generator and was able to run successfully. 

 

Thank You for the great job!!!

 

Regards,

 

Donald Ten

Datavision Technologies - 360° Business Intelligence 

email dten@DatavisionTech.com <mailto:dten@DatavisionTech.com>  /  <http://www.datavisiontech.com/> www.DatavisionTech.com 

Phone (954) 433-3633 ext 116   <mailto:Support@DatavisionTech.com> Contact DV Support

Join us:  <https://www.linkedin.com/company/datavision-technologies/?viewAsMember=true> LinkedIn   <https://twitter.com/DVTechBI> Twitter  <https://www.facebook.com/DatavisionTech/> Facebook   <https://www.instagram.com/datavisiontech/> Instagram  #loveDVdata

 



Data. Information. Intelligence. 

Register  <https://www.regonline.com/builder/site/Default.aspx?EventID=2568920> here for Datavision University Oct 15-17th in Ft Lauderdale 


Disclaimer

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of Datavision Technologies, The recipient should check this email and any attachments for the presence of viruses. Datavision Technologies, Inc. accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by TCourtneyOwen** [comment]
Fantastic! Thanks for letting us know 😊
