### ISSUE TITLE
Hello World Template ?

### ISSUE THREAD

**Issue by OfficeAddins** [OfficeDev/generator-office#463]
These templates are a great way to start learning more about the Office JavaScript APIs. The complexity of the samples seems to be increasing over time though — would you consider adding a very basic ‘hello world’ template for absolute beginners?

**Comment by akrantz** [comment]
The [task pane template](https://github.com/OfficeDev/Office-Addin-TaskPane) is a simple template for getting started. However, if you want to just experiment, use Script Lab: https://docs.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab.

**Comment by kbrandl** [comment]
@OfficeAddins thanks for posting this suggestion here as I'd recommended. 

As @akrantz mentioned, the [task pane template](https://github.com/OfficeDev/Office-Addin-TaskPane) currently represents the simplest template available via the Yeoman generator for Office Add-ins. As you might already know, this project template creates a simple add-in with one ribbon button (i.e., add-in command) that launches a task pane, with minimal sample code that uses the Office JavaScript API to interact with the Office document. From a functionality perspective, it's hard for me to imagine an add-in simpler than this.

If you wouldn't mind, can you elaborate a bit on how a *very basic 'hello world'* add-in would differ from the project that's generated from the [task pane template](https://github.com/OfficeDev/Office-Addin-TaskPane)? Hearing your perspective on this may help inform how we can address your concern. Thanks in advance for any feedback you can share! 

(Leaving this issue closed for now, but would love to continue this dialogue here if you're so inclined.)

**Comment by OfficeAddins** [comment]
Thank you so much for replying so quickly and for requesting more information.
My thinking behind a “hello world” template was more from a technical perspective rather than functionality.

For people coming from a VBA and/or VSTO background that are trying to embrace Office.JS, the learning curve is very steep.
The actual Office.JS part is not too scary but the “world of web development is”, let me share my thoughts.

Let’s run the Yeoman generator, choose Office Add-in Task Pane project with JavaScript in Excel.
When you open this project up in Visual Studio Code there are not many files which is great.
The ‘package.json’ file though is very complicated.

For people that are new to web development, trying to understand Webpack, Babel and the Office XML Manifest is probably enough to start with.

 A “hello world” template could just have 5 devDependencies:
```
    "@babel/core": "^7.4.5", 
    "babel-loader": "^8.0.6", 
    "webpack": "^4.33.0", 
    "webpack-cli": "^3.3.4", 
    "webpack-dev-server": "^3.7.1"
```

I have uploaded an example project to the following repository:
https://github.com/OfficeAddins/helloworld

**Comment by kbrandl** [comment]
@OfficeAddins thanks for the additional clarification! I can certainly appreciate the perspective you've shared -- transitioning from VBA or VSTO to Office (web) Add-ins is a steep learning curve for someone without prior web dev experience, and the various projects that the Yeoman Generator for Office Add-in creates can seem fairly complex in terms of number of components being used.

I really appreciate you providing an example project that illustrates the type of 'hello world' project you're envisioning. I'll follow-up offline with the folks who maintain the Yeoman Generator for Office Add-ins to discuss this feedback and determine if it's feasible to implement a simple project like the one you've described, given the current architecture and functionality goals of the Yeoman Generator. Thanks again for providing this feedback!
