### ISSUE TITLE
Debugger disconnected

### ISSUE THREAD

**Issue by Abrissirba** [OfficeDev/generator-office#465]
I created a new excel add-in with the react template and executed npm start. This starts excel on my computer and sideload the add-in. Everything works as expected so far and if I open F12 I can debug the program. 

If I change the code and save it, it automatically reloads the add-in and this works fine the first 3-5 times. Then I get the following errors... Any ideas on what might cause this? I'm using Node 12.3.1

![image](https://user-images.githubusercontent.com/5156241/59976030-62c6d200-95bf-11e9-81e7-7dc2384f37d3.png)

**Comment by TCourtneyOwen** [comment]
Please try using out new VS Code **Microsoft Office Add-in Debugger for Visual Studio Code** extension for debugging your taskpane add-in.
