### ISSUE TITLE
How to integrate with React.Route

### ISSUE THREAD

**Issue by chenxizhang** [OfficeDev/generator-office#467]
I've tried to use react.route with this template, the code can works in the pure react application, but it doesn't work in the addin. Does it something I missing?

    return (
      <Router>
        <Route path="/" component={Home.default} exact />
        <Route path="/game" exact component={Game.default} />
      </Router>
    );

**Comment by TCourtneyOwen** [comment]
Sorry to hear you are having problems using a router. We have heard similar reports with the Angular project template as well. We will look into this and see about resolving the issue. 

Thanks,

Courtney

**Comment by chenxizhang** [comment]
Hi @TCourtneyOwen  Do you have any update on this?

I tried to get the details error information. you can find them as below. if I try to click a button to redirect a route link like '/game', nothing will happen, and the error message is "object expected"

![image](https://user-images.githubusercontent.com/1996954/60573178-c0220680-9da9-11e9-8c94-cf22d9bb0419.png)

it seems the history.js doesn't work fine?

![image](https://user-images.githubusercontent.com/1996954/60573307-00818480-9daa-11e9-9940-9052e6ef44d8.png)

**Comment by TCourtneyOwen** [comment]
Unfortunately I haven’t had a chance to look into this yet but I plan to next week. Is it possible to share out a link to your project?

**Comment by chenxizhang** [comment]
[test.zip](https://github.com/OfficeDev/generator-office/files/3357555/test.zip)
please use the sample project to test. Thank you.

After you extract the zip, run  `yarn && yarn start` 

You will see a simple page in Excel taskpane, try to click the link on the top of the page. you will see anything happen, and if you use the "Edge devtools preview" , you can see the error message : object expected.

@TCourtneyOwen

**Comment by chenxizhang** [comment]
I found the root cause is the hosted browser in Excel is not support the latest HTML 5 history API. I can change the BrowserRouter to HashRouter to solve this problem. But this is a part we can improve to Fully support HTML 5 API in such a modern world.

**Comment by TCourtneyOwen** [comment]
Glad to hear you solved the problem! This will be very useful information for others who run into this issue. Thanks for following up!

**Comment by anil1712** [comment]
@chenxizhang 
any solution on this?
