### ISSUE TITLE
Creation of TaskPane Addin failed.

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/generator-office#47]
Hi, i tried to create a TaskPane Addin and got the following  error. Is is a bug or is there something I can do about?

This generator can also be run with: yo office
<img width="844" alt="screen shot 2015-10-01 at 21 39 37" src="https://cloud.githubusercontent.com/assets/5503835/10231785/f6d4879c-6884-11e5-9e24-1d48a3054b23.png">

**Comment by waldekmastykarz** [comment]
Which version of node, npm, yo, generator are you using? I've tried building an app using the same parameters and everything seems to be working just fine.

**Comment by StfBauer** [comment]
Yo: 1.4.8
node: v0.12.7
Generator is the latest.
Haven't upgraded to latest version because it has some issues with default web app generator.

**Comment by waldekmastykarz** [comment]
That's odd. I'm on the same setup. Are other node packages working as expected or is this the only one that you are using?

**Comment by StfBauer** [comment]
Trashed the folder and tried it again. In the new folder it worked without any problem. Strange thou.
