### ISSUE TITLE
React project gives react-hot-loader error

### ISSUE THREAD

**Issue by rileymd88** [OfficeDev/generator-office#475]
It seems like starting the default react project with npm run dev-server will give the following errors related to react-hot-loader:

`React-Hot-Loader: misconfiguration detected, using production version in non-production environment.`

`React-Hot-Loader: Hot Module Replacement is not enabled.`

This is for an Outlook Add-In with React and Javascript

**Comment by ekatzenstein** [comment]
I'm also getting this error, any suggested workarounds?

**Comment by Mathyaku** [comment]
Same here =/

**Comment by TCourtneyOwen** [comment]
Sorry you are having problems. I will take a look at this today. Just to clarify, does the React addin work, despite the dev-server error you are seeing?

**Comment by TCourtneyOwen** [comment]
I just checked out both the React and React-Js project templates and am not having any problems. I am wondering if perhaps you are using an older version of generator-office that uses the old React project templates.  Can you please ensure you are running the latest version of generator-office (1.4.0)?  You can check the version by running 'npm view generator-office version'

**Comment by akrantz** [comment]
@TCourtneyOwen I think that command looks up the latest version of the generator-office package, not which version is installed.

**Comment by akrantz** [comment]
You can use "npm ls -g generator-office" to see if it is installed globally, or remove the -g option to check locally.

**Comment by Mathyaku** [comment]
Hey guys, I'm using thee latest version of generator-office package. I took a screenshot for you, take a look.

![image](https://user-images.githubusercontent.com/12189704/66194183-a344ea00-e69c-11e9-9ea2-a3f9a0868918.png)

I really dont know why those problems are happening =/

**Comment by denkristoffer** [comment]
You can add `hot: true` to the `devServer` configuration object in `webpack.config.js` to make the error go away:

```js
devServer: {
  headers: {
    'Access-Control-Allow-Origin': '*',
  },
  hot: true,
  https:
    options.https !== undefined
      ? options.https
      : await devCerts.getHttpsServerOptions(),
  port: process.env.npm_package_config_dev_server_port || 3000,
}
```

The problem is that the webpack config doesn't enable `react-hot-loader`, and although the `dev-server` script to enables with the CLI flag, I guess the `start` script doesn't wrap it?

**Comment by Mathyaku** [comment]
Thank you @denkristoffer. it solved my problem. =)
