### ISSUE TITLE
local npm web server won't start if there are spaces in add-in name / folder name

### ISSUE THREAD

**Issue by Tsing-Hsu** [OfficeDev/generator-office#476]
local web server won't start if there are spaces in add-in name / folder name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build your first Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=yeomangenerator)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@TCourtneyOwen and @akrantz FYI, I was just able to repro this issue with the latest version of Yo Office (1.3.0), with the following project settings:

![image](https://user-images.githubusercontent.com/3019529/62882632-2eca7c00-bce7-11e9-9c69-0085e3c8294e.png)

The project is successfully created, but when I run `npm start`, the dev server fails to start. The Node.js window pops like it's going to start the server, but then seems like it fails at the point when it tries to install certificates, at which point the Node.js window closes (and the server isn't started).

![image](https://user-images.githubusercontent.com/3019529/62882718-60dbde00-bce7-11e9-95e4-8e07c037caab.png)

**Comment by TCourtneyOwen** [comment]
@kbrandl Thanks Kim, I will take a look into it

**Comment by TCourtneyOwen** [comment]
@kbrandl @akrantz @asachin96 I am reproing this as well when following the outlined repro steps.  And I noticed the version of office-addin-dev-certs that's installed with the project looks to contain the fix that was supposed to handle project names with spaces in it (https://github.com/OfficeDev/Office-Addin-Scripts/commit/0bd295bb7861f2111cfa6e2788a6ab85102cd672#diff-177bb81fc395dc89207fc6a83894300e)

**Comment by akrantz** [comment]
@TCourtneyOwen @asachin96 When I look at this diff, it does not use quotes around the script variable which is part of the command line arguments to the powershell command. It would see that this could contain spaces if the path has a directory which contains spaces. Therefore, it seems that the original fix was not sufficient to fix this.

**Comment by TCourtneyOwen** [comment]
A command such as the following will work with spaces (putting ' ' around the folder with spaces)
powershell -ExecutionPolicy Bypass "C:\generator-office\'test spaces'\node_modules\office-addin-dev-certs\scripts\install.ps1" CurrentUser 'C:\Users\cowen\.office-addin-dev-certs\ca.crt'

But I am not sure how reliable or easy this is to do in code.  Looking into this some more

**Comment by TCourtneyOwen** [comment]
OK, I think I figured out the fix for this. Submitting a PR shortly

**Comment by TCourtneyOwen** [comment]
PR submitted for this: https://github.com/OfficeDev/Office-Addin-Scripts/pull/185

**Comment by TCourtneyOwen** [comment]
This issue has been fixed in office-addin-dev-certs.  We just need to publish out a new version of office-addin-dev-certs

**Comment by akrantz** [comment]
It's not really fixed until the PR has been merged.  :-)  You should put "Fixes #476" in the PR description so when it is merged, the issue will closed automatically.

**Comment by kbrandl** [comment]
@TCourtneyOwen looks like `office-addin-dev-certs@1.4.4` was published earlier today -- so I was expecting to see that this issue was resolved. However, I just created a project with the latest version of Yo Office (1.3.0) and I'm still seeing this issue (local web server won't start when I run `npm start` if the project name contains a space). Can you help me understand what I am missing? i.e., is there something else that you need to do (re publication of packages, etc.) before this issue is resolved, or I am I somehow missing a step on my side?

**Comment by TCourtneyOwen** [comment]
We will need to publish a new version of Yo Office that includes the new version of office-addin-dev-certs in package.json. I'll try and do that tomorrow

**Comment by TCourtneyOwen** [comment]
I take that back.  We just need to update the project template repos to use the updated package. No need to publish a new  version of yo office

**Comment by akrantz** [comment]
I just tried this. Because there was a major version update for office-addin-debugging, it's not getting the latest version of office-addin-dev-certs.

```
c:\dev\test\generator-office\My Office Add-in>npm ls office-addin-dev-certs
office-addin-taskpane@0.0.1 c:\dev\test\generator-office\My Office Add-in
+-- office-addin-debugging@2.4.2
| `-- office-addin-dev-certs@1.3.2  deduped
`-- office-addin-dev-certs@1.3.2
```

However, if you run `npm update office-addin-dev-certs` then it will get the latest:

```
c:\dev\test\generator-office\My Office Add-in>npm update office-addin-dev-certs
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ office-addin-dev-certs@1.4.5
added 1 package from 1 contributor, updated 1 package and audited 11032 packages in 5.315s
found 0 vulnerabilities


c:\dev\test\generator-office\My Office Add-in>npm ls office-addin-dev-certs
office-addin-taskpane@0.0.1 c:\dev\test\generator-office\My Office Add-in
+-- office-addin-debugging@2.4.2
| `-- office-addin-dev-certs@1.4.5  deduped
`-- office-addin-dev-certs@1.4.5
```

**Comment by kbrandl** [comment]
@akrantz I'm not sure I'm following -- hopefully customers won't need to do what you've described in order for Yo Office to pickup the newest release of office-addin-dev-certs?

**Comment by akrantz** [comment]
Once we release the updated templates, when Yo Office is run, the project will use the newest release of office-addin-dev-certs. 

For the current templates, it won't automatically pick up the latest office-addin-dev-certs. This is because the latest office-addin-debugging is a major version update so it isn't automatic. If a user still wants to get the latest version of office-addin-dev-certs, they can do using "npm update office-addin-dev-certs".

**Comment by kbrandl** [comment]
Got it; thanks for the clarification. @akrantz and @TCourtneyOwen please let me know when updated templates (using the latest office-addin-dev-certs) are released -- so that I can remove the note I previously added to the docs warning that spaces are not permitted in project name and folder path. Thanks!

**Comment by Tsing-Hsu** [comment]
using command below I am able to start the npm server
```
npm update office-addin-dev-certs
```

However if I try to access the site in a browser it gives certificate error:

![image](https://user-images.githubusercontent.com/33697972/63522219-87ef9800-c4bd-11e9-8efa-02e5918a0dfb.png)

**Comment by akrantz** [comment]
Close the dev server if running and do:
npm uninstall office-addin-dev-certs
npm install -D office-addin-dev-certs

That should give you the latest version of the package.
Then run: npx office-addin-dev-certs install
If prompted, accept installing the cert (Windows) or enter your password (Mac).
Then run the dev server: npm run dev-server.

Close and restart the browser, and then see if you have https://localhost access.

**Comment by Tsing-Hsu** [comment]
If I run directly it didn't do anything.
```
PS C:\test\git-the-gist> npx office-addin-dev-certs install 
You already have trusted access to https://localhost.    
```
It installed the updated certificates, when I deleted the old certificates in the .office-addin-dev-certs folder first.
```
 npx office-addin-dev-certs install
 Uninstalling CA certificate "Developer CA for Microsoft Office Add-ins"...                                              You no longer have trusted access to https://localhost.                                                                 
The developer certificates have been generated in C:\Users\user\.office-addin-dev-certs     
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...                                                You now have trusted access to https://localhost. 
```

**Comment by akrantz** [comment]
OK, so it sounds like things should be working for you now.

**Comment by Tsing-Hsu** [comment]
Yes, everything works now, thanks for quick help.

**Comment by kbrandl** [comment]
Closing this issue, per @TCourtneyOwen's recent confirmation that a fix for this issue has been deployed (project names / folder paths can now contain spaces).
