### ISSUE TITLE
certificate expired

### ISSUE THREAD

**Issue by anxiaoyi** [OfficeDev/generator-office#479]
![image](https://user-images.githubusercontent.com/4382796/63148801-e5569580-c034-11e9-8ea4-47f3678df53b.png)
![image](https://user-images.githubusercontent.com/4382796/63148819-f0a9c100-c034-11e9-878a-758627477166.png)

I can't find "certs" folder in my project root. I tried several approaches, but still not working.

**Comment by anxiaoyi** [comment]
finally I soved this question by typing the following command in my project root folder:

``` bash
npx office-addin-dev-certs install
```

From the promoting after the command, I delete the origin expired certificate, and re execute this command.

**Comment by akrantz** [comment]
@anxiaoyi I'm glad you were able to find the command to run. For your information, the certificates are created in "%UserProfile%\.office-addin-dev-certs. When you run the dev-server, it should detect if the certs have expired and will generate new ones automatically. In the future, if this does not work well for you, or you have any other feedback about how we could make it more clear, please let us know.
