### ISSUE TITLE
NPM start error

### ISSUE THREAD

**Issue by DKOliver** [OfficeDev/generator-office#480]
Following this tutorial https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial

When i get to the point of starting the web server i get the error 
$ npm start
npm ERR! missing script: start

Googling it seems that i lack some text in my package.json file in the project. 
This is what it currently looks like. Lacking a "start" script. 

Can someone tell me what i'm missing? Sorry for the noob question i'm very new to all this.. Hopefully it's okay posting here.

{
  "name": "git-the-gist",
  "description": "",
  "author": "",
  "version": "0.1.0",
  "scripts": {
    "validate": "office-toolbox validate -m manifest.xml"
  },
  "dependencies": {
    "jquery": "^3.4.1",
    "office-toolbox": "^0.1.1",
    "showdown": "^1.9.0",
    "urijs": "^1.19.1"
  },
  "devDependencies": {}
}

**Comment by akrantz** [comment]
Sorry you've had problems. If you do these steps, you should have a package.json with a "start" script.

```
npm install -g yo generator-office
yo office

? Choose a project type: Office Add-in Task Pane project
? Choose a script type: JavaScript
? What do you want to name your add-in? git-the-gist
? Which Office client application would you like to support? Outlook

cd git-the-gist
```

Please try again, and let me know what happens.

**Comment by TCourtneyOwen** [comment]
This is quite an old issue and I haven't heard any follow-up on this thread or seen similar issues.  Closing issue.  Please reactivate if this is still a problem
