### ISSUE TITLE
npm start - delete registry error

### ISSUE THREAD

**Issue by cpop-fr** [OfficeDev/generator-office#487]
Hi,

I get an error when I try to start the server 

```
Debugging is being started...
App type: desktop
Enabled debugging for add-in 05c2e1c9-3e1d-406e-9a91-e9ac64854143. Debug method: 0
The dev server is already running on port 3000.
Sideloading the Office Add-in...
Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in.
Error: Unable to delete registry value "c:\Users\XXXXX\sheet_organizer\manifest.xml" in key "HKCU\SOFTWARE\Microsoft\Office\16.0\Wef\Developer".
ProcessUncleanExitError: DELETE command exited with code 1:
```

I tried as admin but return the same error

**Comment by akrantz** [comment]
Can you use regedit to delete the registry value yourself? It shouldn't require being an Administrator. I'm not sure what would prevent it from being deleted.

**Comment by coolpix77** [comment]
Yes already tried. :/

Le ven. 6 sept. 2019 à 21:33, Adam Krantz <notifications@github.com> a
écrit :

**Comment by akrantz** [comment]
Can you check the permissions?

**Comment by coolpix77** [comment]
I have full control on the registry

**Comment by trader81** [comment]
Hi, i get the same error.  
What helped - i created registry record with key "...\manifest.xml" and empty value.  
Addin starts without errors, then it removes this record and add another record with key "05c2e1c9-3e1d-406e-9a91-e9ac64854143" and value "...\manifest.xml".  

Hope this helps

**Comment by Mathyaku** [comment]
@akrantz I had the same problem, using your abordation it is solved. Thank you! :)

**Comment by trader81** [comment]
> [OfficeDev/Office-Addin-Scripts#215](https://github.com/OfficeDev/Office-Addin-Scripts/issues/215)
> Please see if this issue is the same. The problem had to do with having a different language and the code relying on the error message text which differs if the language is not English.
> 
> You can use `npm install -D office-addin-dev-settings@next` to get the fix in the project and see if that resolves the issue.

yes, this helped, thanks

**Comment by millerds** [comment]
Sounds like this is solved . . . if not please reopen
