### ISSUE TITLE
jQuery in TaskPane project

### ISSUE THREAD

**Issue by chengthao** [OfficeDev/generator-office#489]
JQuery is not included in the TaskPane project.

**Comment by akrantz** [comment]
We removed jquery, as we didn't want to give the impression that it was required, but you're welcome to add it and use it with your own projects.

**Comment by chengthao** [comment]
I don't know how to include it.  

`node install jquery`

and add 

` var $=import('jquery')  `

to taskpane.js 

But not working.

**Comment by akrantz** [comment]
This is the change which removed jquery: https://github.com/OfficeDev/Office-Addin-TaskPane/pull/17. 

You can either use `npm install jquery` or edit package.json depedencies to add it. You can see from the pull request the package.json change that was made to remove the dependency.

You can also see the code change that was made to remove the usage of jquery. Making the opposite change should give you the idea of how to use it.
