### ISSUE TITLE
angular 8 support

### ISSUE THREAD

**Issue by IsaacSomething** [OfficeDev/generator-office#496]
Are there any plans to release an angular 8 version for the office generator?

**Comment by akrantz** [comment]
Do you want to help us provide it? You can do so by making a pull request in https://github.com/OfficeDev/Office-Addin-TaskPane-Angular. 

We would need to decide whether to update generator office to switch the template to Angular 8 only, or add another item for Angular 8 as a separate choice (using an angular8 branch in the template repository).

**Comment by IsaacSomething** [comment]
I can try. 
It would be nice to switch to angular 8+ only.

Ill give it a try 
thanks
