### ISSUE TITLE
Linux not supported (npm run start:web)

### ISSUE THREAD

**Issue by VladimirMikulic** [OfficeDev/generator-office#497]
I followed Microsoft docs on creating OneNote add-in.
Article URL: https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/onenote-quickstart

I get an error when I run this command.
```bash
npm run start:web
```

Error message:
Debugging is being started...
App type: web
Unable to start the dev server. Error: Platform not supported: linux
Debugging started.

I thought you support Linux :(

Thanks in advance.

**Comment by callingmybluff** [comment]
I've got the same problem. Was hoping to do most of the development there as one should be able to run via web

**Comment by VladimirMikulic** [comment]
@callingmybluff that's what I thought at first, but it seems they don't support Linux.

**Comment by akrantz** [comment]
There's a pull request for adding Linux support to office-addin-dev-certs which is what is currently blocking this from working.

https://github.com/OfficeDev/Office-Addin-Scripts/pull/156
https://github.com/OfficeDev/Office-Addin-Scripts/pull/199

**Comment by VladimirMikulic** [comment]
@akrantz by the time they get merged I'll probably be dead :)

**Comment by akrantz** [comment]
Sorry this hasn't had a lot of focus, I'm trying to get more attention on this so it can be completed.

If you generate the certs yourself, you can modify the webpack config so the dev-server.https config specifies them instead of calling office-addin-dev-certs. that would allow the webpack-dev-server to be started.

**Comment by VladimirMikulic** [comment]
Thanks for the advice, but I already have a workaround.

**Comment by oscarcosta** [comment]
> Thanks for the advice, but I already have a workaround.
Hi Vladmir, I am interested in your workaround. Do you have any running example? Thanks

**Comment by VladimirMikulic** [comment]
Hi @oscarcosta. Sorry for the late reply, I use the workaround from #490.
@akrantz @TCourtneyOwen any updates on this?
