### ISSUE TITLE
The dev server is already running on port 3000, even after npm stop

### ISSUE THREAD

**Issue by nosaku** [OfficeDev/generator-office#499]
First time when I started the dev server using "npm start" it worked fine. Then I did "npm stop" and the message said the dev server stopped. But when I again run the "npm start" getting the following error:

The dev server is already running on port 3000.

**Comment by ahmedsafadii** [comment]
kill the node in activity monitoring and it will works

**Comment by TCourtneyOwen** [comment]
Yes, this is not ideal.  Sometimes the dev-server process doesn't stop right away and port 3000 isn't immediately freed.
