### ISSUE TITLE
Impossible to execute gulp run-yo without mangling your gulpfile.js, packages.json, etc.

### ISSUE THREAD

**Issue by MrPiao** [OfficeDev/generator-office#50]
Is it supposed to be possible to run your private instance of the generator (presumably using gulp run-yo) without messing up your gulfile.js and others? What is the expected developer steps to test your version of the generator?

**Comment by waldekmastykarz** [comment]
I don't know the answer to the first question but for your second question what you can do is to clone the repo, uninstall the official generator then `cd` to the local clone of your repo and run `npm link`. This will make Yeoman use your local instance of the generator rather than the official one.

**Comment by MrPiao** [comment]
As a new contributor, I'm confused as to how to do this, and if I'm not mistaken we did not put this anywhere. Can we figure out a better manual testing story and meanwhile document what you said above in our contributing tips?

**Comment by waldekmastykarz** [comment]
Although there are some docs around contribution guidelines and testing this particular step isn't mentioned indeed. I guess it would be helpful to include it to help devs test their work locally before submitting PRs.

**Comment by andrewconnell** [comment]
To answer your first question, yes it is possible to run a private instance of the generator. Debugging and running your generator is documented... by Yeoman: http://yeoman.io/authoring. @waldekmastykarz has provided the basic steps here as you need to uninstall the public one and install your local one.

The `run-yo` gulp task is designed to be used with Visual Studio Code as it can fire up a gulp task and attach the debugger.

What do you mean about mangling files... can you be more specific? You don't have to mangle anything. The way the task is written is that it gets a reference where yeoman is running on your machine as everyone's path is different.

**Comment by andrewconnell** [comment]
Closing due to lack of follow up. Feel free to reopen.
