### ISSUE TITLE
where are they

### ISSUE THREAD

**Issue by zhuyuhaoliar** [OfficeDev/generator-office#502]
![WX20200104-141814](https://user-images.githubusercontent.com/23420270/71760731-2fb1b380-2efd-11ea-9d54-5a268d1a41ce.png)

**Comment by zhuyuhaoliar** [comment]
[cry]

**Comment by zhuyuhaoliar** [comment]
😭

**Comment by TCourtneyOwen** [comment]
Hi, sorry to hear you are having problems. What exactly is the problem? Are you unable to locate the project created by generator-office? It should be located under the path cited in the screenshot you sent.
