### ISSUE TITLE
Yo Office fails unzip project file with Node 13.6.0 (Current Version)

### ISSUE THREAD

**Issue by BladeMF** [OfficeDev/generator-office#503]
This is what I ran.

```
D:\Source\repos\Research>yo office

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the Office  │
    |--(o)--|    │   Add-in generator, by   │
   `---------´   │ @OfficeDev! Let's create │
    ( _´U`_ )    │    a project together!   │
    /___A___\   /╰──────────────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Choose a project type: Office Add-in Task Pane project
? Choose a script type: TypeScript
? What do you want to name your add-in? My Office Add-in
? Which Office client application would you like to support? Excel

----------------------------------------------------------------------------------

      Creating My Office Add-in add-in for Excel using TypeScript and Taskpane at D:\Source\repos\Research\My Office Add-in

----------------------------------------------------------------------------------
```
Not saying it's not me, just saying I ran out of ideas.

**Comment by TCourtneyOwen** [comment]
@BladeMF Sorry to hear you are having problems. From the file path cited in the attached screenshot it looks like you are on Windows.  Can you please check the version of Node you are running? I am running Node 10.17.0 and am not having any problems.  There have been issues in the past with earlier versions on Node, although I don't recall if your specific issue is related.  Also, can you please be sure that you are running the command prompt as an administrator?  While I don't think this is explicitly required, running as admin may help us narrow down the problem,

Thanks,

Courtney

**Comment by BladeMF** [comment]
Hi Courtney,

This is my version:
```
C:\Users\VladislavKosev>node
Welcome to Node.js v13.6.0.
Type ".help" for more information.
```

**Comment by BladeMF** [comment]
> Also, can you please be sure that you are running the command prompt as an administrator? While I don't think this is explicitly required, running as admin may help us narrow down the problem.

Just tested it as administrator - same thing.

How can I further help?

**Comment by TCourtneyOwen** [comment]
Interesting, I just updated Node to 13.6.0 and see the same behavior you are seeing.  Looks like a breaking change was introduced in the current Node version.  I am going to check with the LTS version as well (12.14.1)

**Comment by BladeMF** [comment]
I don't really mind which version I have to install, but it is probably best to have the latest version. Then again, I am kind of new to this Node/npm thing, so yea.

Thank you for your time. Will wait for further instructions.

**Comment by akrantz** [comment]
We normally use and test against the LTS version which is the stable version (even version numbers). The odd version numbers are the active development branch. Node 12 is the latest stable version, and what I would recommend using.

If you need to use multiple Node versions, use [Node Version Switcher](https://github.com/jasongin/nvs).

**Comment by TCourtneyOwen** [comment]
OK, 12.14.1 works, so if you uninstall Node via Add/Remove programs and then install the 12.14.1 from https://nodejs.org/en/, you should be good to go.  Also please be sure to close and reopen your command prompt after installing 12.14.1.

**Comment by BladeMF** [comment]
> We normally use and test against the LTS version which is the stable version (even version numbers). The odd version numbers are the active development branch. Node 12 is the latest stable version, and what I would recommend using.

Understood.

> OK, 12.14.1 works, so if you uninstall Node via Add/Remove programs and then install the 12.14.1 from https://nodejs.org/en/, you should be good to go. Also please be sure to close and reopen your command prompt after installing 12.14.1.

Will do and then write back.

**Comment by BladeMF** [comment]
I can confirm it works. I suppose this in the output is normal?

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 941 packages from 534 contributors and audited 11166 packages in 12.089s
found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by TCourtneyOwen** [comment]
OK, thanks for clarifying. I will debug and see if I can figure out the problem. My guess is that the package we use to unzip the project template (unzip) is broken by the current version of Node

**Comment by BladeMF** [comment]
What about the fsevents dependency?

Is there anyway a user like me can see some sort of error/debug log or something?

**Comment by akrantz** [comment]
Don't worry about that. fsevents are not supported on Windows. It shows this in an unhelpful way as if it is an error but it's not a problem and there's nothing that can be done to suppress it.

**Comment by BladeMF** [comment]
> Don't worry about that. fsevents are not supported on Windows. It shows this in an unhelpful way as if it is an error but it's not a problem and there's nothing that can be done to suppress it.

Thank you.

**Comment by daidaihuhu** [comment]
I also got some issue on the Node.js 12.13 (the taskpane page can't be loaded). I suggest that you can list out the workable version of Node.js for new users. Thank goodness I finally found this post!!!

**Comment by TCourtneyOwen** [comment]
@daidaihuhu Just to clarify, does Node 12.13 work for you?  I am looking into the specific problem caused by Node 13.6.0

**Comment by daidaihuhu** [comment]
The Node 12.13 can create the add-in package but the server (taskpane.html) can not be loaded into the taskpane.

**Comment by TCourtneyOwen** [comment]
This issue has been addressed in in the following commit:  https://github.com/OfficeDev/generator-office/commit/195d7488d331c62a05fcd6a397276a93d9f73f9c.  We will now prompt the user to install the NodeJs LTS version and bail out if the Current version is installed
