### ISSUE TITLE
Is it possible to generate a project with multiple hosts?

### ISSUE THREAD

**Issue by Cmoen11** [OfficeDev/generator-office#507]
I want to create a add-in that supports powerpoint, excel, word, outlook etc...

Is this possible? Or do we need to make individual projects?

**Comment by akrantz** [comment]
It is possible. You can have multiple hosts. In fact the underlying templates have multiple hosts, but Yo Office will run a script to convert the project to a single host. 

For example, the repository for the basic TaskPane template is here: https://github.com/OfficeDev/Office-Addin-TaskPane.

The manifest.xml file in that project is for multiple hosts. There are also files for each host (manifest.excel.xml, manifest.word.xml) which gets copied over to manifest.xml for single host support when Yo Office generates the project.

You can use GitHub to copy down a zip file for one of the templates to get all of the files (or do git clone and then delete the .git dir). Yo Office also runs "npm install" followed by "npx office-addin-manifest modify --guid --displayname <Name>" to generate a unique guid and change the name.

Alternatively, you can start with running Yo Office for a single project and then modify the manifest file to add support for other hosts.

**Comment by Cmoen11** [comment]
Thanks for an informative answer!
