### ISSUE TITLE
Excel Task Pane "Hello World" doesn't work on Chrome

### ISSUE THREAD

**Issue by robcecil** [OfficeDev/generator-office#510]
On: Windows 10 Enterprise, version 1809, Build 17763.973
Node: v12.2.0

Installed Yeoman globally using instructions here. Create Add-in Task Pane Project using React fx, +Typescript, Excel.

Build project/run as "npm start:web". Node server launches fine.

Login to Office.com and create a new workbook. Install add-in, browse to manifest.xml. Activation of add-in works fine ("see the Welcome: Discover what Office add-ins can do..."). Type in some data into some cells, select them, then click the [> Run ] button. Nothing changes. Check console:

```
App.tsx:62 TypeError: Cannot read property 'run' of undefined
    at App.<anonymous> (App.tsx:46)
    at step (log.js:59)
    at Object.next (log.js:59)
    at log.js:59
    at initializePromise (es6-promise.js:437)
    at new Promise (es6-promise.js:865)
    at ./src/taskpane/components/App.tsx.__awaiter (log.js:59)
    at Object.App._this.click [as onClick] (App.tsx:44)
    at BaseButton._this._onClick (BaseButton.js:196)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
```

When I perform the same steps with Edge, the highlighting works, and there is no error in the console.

**Comment by TCourtneyOwen** [comment]
Thanks for reporting this issue. I will see if I can reproduce the behavior and get back to you. 

-Courtney

**Comment by TCourtneyOwen** [comment]
@robcecil I just tried your scenario and am unable to reproduce the problem.  Do you happen to know which version of generator-office you are running? You can check by running 'npm list -g generator-office."  The latest version, and the one I am running is 1.5.0.  Please let me know what you find.

Thanks,

Courtney

**Comment by robcecil** [comment]
'yo --version' says 3.1.1
'npm list -g generator-office' says 

`-- generator-office@1.5.0

**Comment by TCourtneyOwen** [comment]
We are unable to repro this behavior. Please reactivate if this is still an issue
