### ISSUE TITLE
can't install the generator-office package 

### ISSUE THREAD

**Issue by Gil-Porsansky** [OfficeDev/generator-office#515]
i tried to to install npm install -g yo generator-office 
and i got this error :  
npm ERR! Unexpected end of JSON input while parsing near '...y":"^3.4.0","cpx":"^1'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gil\AppData\Roaming\npm-cache\_logs\2020-02-09T17_55_30_900Z-debug.log

i tried to install yo alone and it worked fine so i think the problem is with generator-office
anyone know how to solve it ?

**Comment by akrantz** [comment]
I just tried it and didn't have any issues.

What version of Node are you using? There was a security update recently so you might want to install the most recent LTS version, and see if that changes the result.

**Comment by Gil-Porsansky** [comment]
i just installed the LTS version and it didn't work
i tried to run npm cache clean --force  and then its still not working 
but the error changed to this : 
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm ERR! Unexpected end of JSON input while parsing near '..."},"devDependencies":'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gil\AppData\Roaming\npm-cache\_logs\2020-02-09T18_24_48_144Z-debug.log

**Comment by Gil-Porsansky** [comment]
this is the complete log : 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Gil\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'yo',
1 verbose cli   'generator-office'
1 verbose cli ]
2 info using npm@6.13.6
3 info using node@v12.15.0
4 verbose npm-session b5ee8788e2d0b65d
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/yo 277ms (from cache)
8 silly pacote tag manifest for yo@latest fetched in 305ms
9 http fetch GET 304 https://registry.npmjs.org/generator-office 480ms (from cache)
10 silly pacote tag manifest for generator-office@latest fetched in 485ms
11 timing stage:loadCurrentTree Completed in 530ms
12 silly install loadIdealTree
13 silly install cloneCurrentTreeToIdealTree
14 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
15 silly install loadShrinkwrap
16 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
17 silly install loadAllDepsIntoIdealTree
18 silly resolveWithNewModule yo@3.1.1 checking installable status
19 silly resolveWithNewModule generator-office@1.6.1 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/chalk 77ms (from cache)
21 silly pacote range manifest for chalk@^1.1.3 fetched in 81ms
22 silly resolveWithNewModule chalk@1.1.3 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/lodash 130ms (from cache)
24 silly pacote range manifest for lodash@^4.17.15 fetched in 133ms
25 silly resolveWithNewModule lodash@4.17.15 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/yosay 54ms (from cache)
27 silly pacote range manifest for yosay@^2.0.2 fetched in 56ms
28 silly resolveWithNewModule yosay@2.0.2 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/request 209ms (from cache)
30 silly pacote range manifest for request@^2.88.0 fetched in 215ms
31 silly resolveWithNewModule request@2.88.0 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/uuid 221ms (from cache)
33 http fetch GET 304 https://registry.npmjs.org/yeoman-generator 222ms (from cache)
34 silly fetchPackageMetaData error for yeoman-generator@^1.1.1 Unexpected end of JSON input while parsing near '..."},"devDependencies":'
35 silly pacote range manifest for uuid@^3.3.3 fetched in 227ms
36 silly resolveWithNewModule uuid@3.4.0 checking installable status
37 http fetch GET 304 https://registry.npmjs.org/rimraf 463ms (from cache)
38 http fetch GET 304 https://registry.npmjs.org/office-addin-usage-data 468ms (from cache)
39 silly pacote range manifest for rimraf@^3.0.0 fetched in 469ms
40 silly resolveWithNewModule rimraf@3.0.2 checking installable status
41 silly pacote range manifest for office-addin-usage-data@^1.0.3 fetched in 474ms
42 silly resolveWithNewModule office-addin-usage-data@1.0.7 checking installable status
43 http fetch GET 304 https://registry.npmjs.org/office-addin-manifest 482ms (from cache)
44 silly pacote range manifest for office-addin-manifest@^1.4.12 fetched in 484ms
45 silly resolveWithNewModule office-addin-manifest@1.4.17 checking installable status
46 http fetch GET 304 https://registry.npmjs.org/opn 1032ms (from cache)
47 silly pacote range manifest for opn@^6.0.0 fetched in 1035ms
48 warn deprecated opn@6.0.0: The package has been renamed to `open`
49 silly resolveWithNewModule opn@6.0.0 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/unzipper 2042ms (from cache)
51 silly pacote range manifest for unzipper@^0.10.4 fetched in 2059ms
52 silly resolveWithNewModule unzipper@0.10.8 checking installable status
53 timing stage:rollbackFailedOptional Completed in 1ms
54 timing stage:runTopLevelLifecycles Completed in 2613ms
55 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '..."},"devDependencies":'
55 verbose stack     at JSON.parse (<anonymous>)
55 verbose stack     at parseJson (C:\Users\Gil\AppData\Roaming\npm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
55 verbose stack     at C:\Users\Gil\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
55 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:94:5)
56 verbose cwd C:\Users\Gil
57 verbose Windows_NT 10.0.18362
58 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Gil\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo" "generator-office"
59 verbose node v12.15.0
60 verbose npm  v6.13.6
61 error Unexpected end of JSON input while parsing near '..."},"devDependencies":'
62 verbose exit [ 1, true ]

**Comment by akrantz** [comment]
Since this is just installing global packages, try from an empty directory. I am wondering if the parsing is due to an error with a local package.json file.

**Comment by akrantz** [comment]
I just saw that you put the log file.

```
33 http fetch GET 304 https://registry.npmjs.org/yeoman-generator 222ms (from cache)
34 silly fetchPackageMetaData error for yeoman-generator@^1.1.1 Unexpected end of JSON input while parsing near '..."},"devDependencies":'
```

yeoman-generator@1.1.1 is a dependency of generator-office. It seems like your cached copy is corrupt. 

Maybe uninstall generator-office `npm uninstall -g generator-office` and then remove the package in `C:\Users\Gil\AppData\Roaming\npm\node_modules\yeoman-generator`
This is saying that there is something wrong with the cached version of `yeoman-generator` package.

**Comment by Gil-Porsansky** [comment]
nope i tried to install it globally with no folder at all 
i tested some more npm packages and everything works fine 
it's only this package doing the problems it's really weird , maybe it's a problem with my OS i have no idea

**Comment by akrantz** [comment]
Let me know if you tried my comments above of removing the yeoman-generator cached copy in appdata\roaming\npm\node_modules.

**Comment by Gil-Porsansky** [comment]
I just saw that you put the log file.

33 http fetch GET 304 https://registry.npmjs.org/yeoman-generator 222ms (from cache)
34 silly fetchPackageMetaData error for yeoman-generator@^1.1.1 Unexpected end of JSON input while parsing near '..."},"devDependencies":'
yeoman-generator@1.1.1 is a dependency of generator-office. It seems like your cached copy is corrupt.

Maybe uninstall generator-office npm uninstall -g generator-office and then remove the package in C:\Users\Gil\AppData\Roaming\npm\node_modules\yeoman-generator
This is saying that there is something wrong with the cached version of yeoman-generator package.

I will try let's see , thanks for the help !!!

**Comment by Gil-Porsansky** [comment]
i did the uninstall  : 
$ npm uninstall -g generator-office
up to date in 0.046s  
looks like it's not exist 
and i opened C:\Users\Gil\AppData\Roaming\npm\node_modules
there's no yeoman-generator in this folder

**Comment by akrantz** [comment]
OK, now try installing again: `npm install -g generator-office`

**Comment by Gil-Porsansky** [comment]
no still the same error  :
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm ERR! Unexpected end of JSON input while parsing near '..."},"devDependencies":'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gil\AppData\Roaming\npm-cache\_logs\2020-02-09T18_56_48_036Z-debug.log


full log : 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Gil\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'generator-office'
1 verbose cli ]
2 info using npm@6.13.6
3 info using node@v12.15.0
4 verbose npm-session 490d3300403a01cc
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/generator-office 21ms (from cache)
8 silly pacote tag manifest for generator-office@latest fetched in 52ms
9 timing stage:loadCurrentTree Completed in 78ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule generator-office@1.6.1 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/office-addin-manifest 97ms (from cache)
18 http fetch GET 200 https://registry.npmjs.org/office-addin-usage-data 95ms (from cache)
19 http fetch GET 200 https://registry.npmjs.org/yeoman-generator 88ms (from cache)
20 silly fetchPackageMetaData error for yeoman-generator@^1.1.1 Unexpected end of JSON input while parsing near '..."},"devDependencies":'
21 silly pacote range manifest for office-addin-manifest@^1.4.12 fetched in 104ms
22 silly resolveWithNewModule office-addin-manifest@1.4.17 checking installable status
23 silly pacote range manifest for office-addin-usage-data@^1.0.3 fetched in 100ms
24 silly resolveWithNewModule office-addin-usage-data@1.0.7 checking installable status
25 http fetch GET 200 https://registry.npmjs.org/yosay 6ms (from cache)
26 silly pacote range manifest for yosay@^2.0.2 fetched in 8ms
27 silly resolveWithNewModule yosay@2.0.2 checking installable status
28 http fetch GET 304 https://registry.npmjs.org/opn 290ms (from cache)
29 http fetch GET 304 https://registry.npmjs.org/lodash 299ms (from cache)
30 http fetch GET 304 https://registry.npmjs.org/request 294ms (from cache)
31 silly pacote range manifest for opn@^6.0.0 fetched in 298ms
32 warn deprecated opn@6.0.0: The package has been renamed to `open`
33 silly resolveWithNewModule opn@6.0.0 checking installable status
34 silly pacote range manifest for lodash@^4.17.15 fetched in 310ms
35 silly resolveWithNewModule lodash@4.17.15 checking installable status
36 silly pacote range manifest for request@^2.88.0 fetched in 306ms
37 silly resolveWithNewModule request@2.88.0 checking installable status
38 http fetch GET 304 https://registry.npmjs.org/chalk 322ms (from cache)
39 silly pacote range manifest for chalk@^1.1.3 fetched in 325ms
40 silly resolveWithNewModule chalk@1.1.3 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/rimraf 345ms (from cache)
42 silly pacote range manifest for rimraf@^3.0.0 fetched in 348ms
43 silly resolveWithNewModule rimraf@3.0.2 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/unzipper 349ms (from cache)
45 silly pacote range manifest for unzipper@^0.10.4 fetched in 353ms
46 silly resolveWithNewModule unzipper@0.10.8 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/uuid 566ms (from cache)
48 silly pacote range manifest for uuid@^3.3.3 fetched in 568ms
49 silly resolveWithNewModule uuid@3.4.0 checking installable status
50 timing stage:rollbackFailedOptional Completed in 1ms
51 timing stage:runTopLevelLifecycles Completed in 675ms
52 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '..."},"devDependencies":'
52 verbose stack     at JSON.parse (<anonymous>)
52 verbose stack     at parseJson (C:\Users\Gil\AppData\Roaming\npm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
52 verbose stack     at C:\Users\Gil\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
52 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:94:5)
53 verbose cwd C:\Users\Gil
54 verbose Windows_NT 10.0.18362
55 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Gil\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "generator-office"
56 verbose node v12.15.0
57 verbose npm  v6.13.6
58 error Unexpected end of JSON input while parsing near '..."},"devDependencies":'
59 verbose exit [ 1, true ]

**Comment by akrantz** [comment]
Do you have this directory?:
`C:\Users\Gil\AppData\Roaming\npm\node_modules\generator-office\node_modules\yeoman-generator`

Does the package.json look OK?

Also, I have npm version 6.13.7. You can update using `npm install -g npm`.

**Comment by Gil-Porsansky** [comment]
no i don't have generator-office in this location 
ill try to update npm

**Comment by Gil-Porsansky** [comment]
i updated npm to 6.13.7 still now working .

**Comment by akrantz** [comment]
Sorry, but I am at a loss for what is going on. It is not because of generator-office itself. This has used yeoman-generator@1.1.1 for a long time. It seems like there is something going on with npm installing the yeoman-generator package such that it cannot parse the package.json for it, but I cannot tell you why.

**Comment by Gil-Porsansky** [comment]
what about this line from the log :  
(C:\Users\Gil\AppData\Roaming\npm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17    ??

**Comment by Gil-Porsansky** [comment]
this is the code from this file  , does it tells you something ? 


'use strict'

module.exports = parseJson
function parseJson (txt, reviver, context) {
  context = context || 20
  try {
    return JSON.parse(txt, reviver)
  } catch (e) {
    if (typeof txt !== 'string') {
      const isEmptyArray = Array.isArray(txt) && txt.length === 0
      const errorMessage = 'Cannot parse ' +
      (isEmptyArray ? 'an empty array' : String(txt))
      throw new TypeError(errorMessage)
    }
    const syntaxErr = e.message.match(/^Unexpected token.*position\s+(\d+)/i)
    const errIdx = syntaxErr
    ? +syntaxErr[1]
    : e.message.match(/^Unexpected end of JSON.*/i)
    ? txt.length - 1
    : null
    if (errIdx != null) {
      const start = errIdx <= context
      ? 0
      : errIdx - context
      const end = errIdx + context >= txt.length
      ? txt.length
      : errIdx + context
      e.message += ` while parsing near '${
        start === 0 ? '' : '...'
      }${txt.slice(start, end)}${
        end === txt.length ? '' : '...'
      }'`
    } else {
      e.message += ` while parsing '${txt.slice(0, context * 2)}'`
    }
    throw e
  }
}

**Comment by Gil-Porsansky** [comment]
ok man thanks for the help ill try to solve it !

**Comment by akrantz** [comment]
It tells me that it cannot parse the package.json file.

The earlier error seems to indicate the problem:
```
19 http fetch GET 200 https://registry.npmjs.org/yeoman-generator 88ms (from cache)
20 silly fetchPackageMetaData error for yeoman-generator@^1.1.1 Unexpected end of JSON input while parsing near '..."},"devDependencies":'
```

Can you get `https://registry.npmjs.org/yeoman-generator` and does it look like complete and valid json?

**Comment by Gil-Porsansky** [comment]
yes i copied you link to the browser and i see a valid json

**Comment by akrantz** [comment]
There's an "npm cache" command: file:///C:/Users/adamk/AppData/Roaming/npm/node_modules/npm/docs/public/cli-commands/npm-cache/index.html

Perhaps clearing the cache would help.

**Comment by Gil-Porsansky** [comment]
yes it worked !!!  i did  npm cache clean --force 
and it worked  , it's weird because i did this already before but it's working so all good 
thank you so much for the support i appreciate it !

**Comment by akrantz** [comment]
I'm so glad that you were able to get this working.
