### ISSUE TITLE
Connection timeout when generating an Outlook Add-In project

### ISSUE THREAD

**Issue by exextoc** [OfficeDev/generator-office#516]
This is from [outlook-dev-docs issue #831](https://github.com/OfficeDev/outlook-dev-docs/issues/831). Please see this issue for further details.

Copy/paste of original message from @berndgoetz:

Hi,
when I try to generate a project, I run into a connection timeout, trying to connect to 140.82.118.3 - which seems to be a Github load balancer - any help how to get rid of this? I'm behind a Internet firewall.... Thanks for your help.

Error from console
```
C:\srdev\tools\node-v12.8.1-win-x64\node_modules\generator-office\node_modules\cls-hooked\context.js:177
throw exception;
^
Error: connect ETIMEDOUT 140.82.118.3:443
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) {
errno: 'ETIMEDOUT',
code: 'ETIMEDOUT',
syscall: 'connect',
address: '140.82.118.3',
port: 443,
'error@context': { _ns_name: 'AI-CLS-Session', id: 281 }
}
```

**Comment by a-sahel** [comment]
Hi,

I'm getting the same error on Mac when I run `yo office`
```
/usr/local/lib/node_modules/generator-office/node_modules/cls-hooked/context.js:177
      throw exception;
      ^

Error: connect ETIMEDOUT 140.82.118.4:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '140.82.118.4',
  port: 443,
  'error@context': { _ns_name: 'AI-CLS-Session', id: 286 }
}
```

Thanks for your help

**Comment by TCourtneyOwen** [comment]
Tracking this issue in https://github.com/OfficeDev/generator-office/issues/529
