### ISSUE TITLE
"office-addin-debugging" is not recognized as an internal or external command.

### ISSUE THREAD

**Issue by elbae** [OfficeDev/generator-office#519]
Hi, I'm following https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator. I installed git, nodejs and npm and created the example with ```yo office```.  I'm having the following error:

```
PS C:\redacted\gits\test\test-1> npm start

> office-addin-taskpane-js@0.0.1 start C:\redacted\gits\test\test-1
> office-addin-debugging start manifest.xml

"office-addin-debugging" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! office-addin-taskpane-js@0.0.1 start: `office-addin-debugging start manifest.xml`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the office-addin-taskpane-js@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\redacted\AppData\Roaming\npm-cache\_logs\2020-03-15T15_08_25_119Z-debug.log
PS C:\redacted\gits\test\test-1> ls
```

![image](https://user-images.githubusercontent.com/19212922/76704191-78dd6b00-66d7-11ea-92d2-c968a550aa83.png)

> Content of ```C:\Users\redacted\AppData\Roaming\npm-cache\_logs\2020-03-15T15_08_25_119Z-debug.log```

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle office-addin-taskpane-js@0.0.1~prestart: office-addin-taskpane-js@0.0.1
6 info lifecycle office-addin-taskpane-js@0.0.1~start: office-addin-taskpane-js@0.0.1
7 verbose lifecycle office-addin-taskpane-js@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle office-addin-taskpane-js@0.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\redacted\gits\test\test-1\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GnuPG\bin;C:\Program Files\PuTTY\;C:\Program Files (x86)\Infocert\DiKe 6\RAO;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Android;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\redacted\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\redacted\AppData\Local\Programs\Python\Python36-32\;C:\Users\redacted\AppData\Local\Programs\Python\Launcher\;C:\Users\redacted\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Sophos\Sophos SSL VPN Client\bin;C:\Users\redacted\.dotnet\tools;C:\Users\redactedv\AppData\Roaming\npm
9 verbose lifecycle office-addin-taskpane-js@0.0.1~start: CWD: C:\redacted\gits\test\test-1
10 silly lifecycle office-addin-taskpane-js@0.0.1~start: Args: [ '/d /s /c', 'office-addin-debugging start manifest.xml' ]
11 silly lifecycle office-addin-taskpane-js@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle office-addin-taskpane-js@0.0.1~start: Failed to exec start script
13 verbose stack Error: office-addin-taskpane-js@0.0.1 start: `office-addin-debugging start manifest.xml`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid office-addin-taskpane-js@0.0.1
15 verbose cwd C:\redacted\gits\test\test-1
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error office-addin-taskpane-js@0.0.1 start: `office-addin-debugging start manifest.xml`
22 error Exit status 1
23 error Failed at the office-addin-taskpane-js@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
Do I miss something? maybe in the installation procedure?

**Comment by TCourtneyOwen** [comment]
@elbae Sorry to hear you are having problems.  Just to clarify, did you create an Office-Addin-Taskpane-**JS** project?  Also, can you please run the following command to see what version of **generator-office** you are running:  npm list -g --depth=0

The latest version is **1.6.1**.  If you aren't running this version, please run the following to pick up the latest version:

- npm uninstall -g generator-office
- npm install -g generator-office

Please let us know what you find.

Thanks,

Courtney

**Comment by elbae** [comment]
@TCourtneyOwen yep 1.6.1 as below:
![image](https://user-images.githubusercontent.com/19212922/76705904-f313ec80-66e3-11ea-8cf1-0d89e5ae34a1.png)
![image](https://user-images.githubusercontent.com/19212922/76706290-9e25a580-66e6-11ea-8137-30584053f31d.png)

I'm gonna do it again from the beginning so there is much more context.
![image](https://user-images.githubusercontent.com/19212922/76706111-73871d00-66e5-11ea-8727-3429178fea12.png)
![image](https://user-images.githubusercontent.com/19212922/76706190-fe681780-66e5-11ea-92a9-48d2b1ea712c.png)

**Comment by nokafor** [comment]
Hi @elbae were you able to get this fixed?

**Comment by elbae** [comment]
Hi @nokafor unfortunately I was not.

**Comment by TCourtneyOwen** [comment]
@elbae can you please CD to you project and run "npm install" again and then run "npm start:". Perhaps the initial "npm install" didn't succeed after the project was created

**Comment by elbae** [comment]
@TCourtneyOwen I tried again, same error (even with admin cmd).
In my mind, this should be a configuration problem residing in my specific installation.
Which information do you think I should try to find (o what should I reinstall)?
Also, where should be located `office-addin-debugging` after the execution of `npm install`? Because it seems the "error", maybe some PATH is missing.

**Comment by TCourtneyOwen** [comment]
@elbae Hi Andrea, please check under the **node_modules** directory in your yo-office project.  If you do not in fact see an office-addin-debugging folder there then the package is not getting installed successfully, Can you please check and see the directory is there and let me know?

Thanks,

Courtney

**Comment by elbae** [comment]
Sure, this is the content of node_modules/office-addin-debugging:
![image](https://user-images.githubusercontent.com/19212922/79480519-7a6bbd00-800e-11ea-86fd-634a96db49b4.png)

**Comment by Grifo89** [comment]
I'm having the same problem. 
![image](https://user-images.githubusercontent.com/9584549/93810071-be916800-fc13-11ea-933e-46cad838aa33.png)

So it seems, it doesn't work for now.

**Comment by TCourtneyOwen** [comment]
Sorry to hear you are having problems. I am looking into this now and will let you know once this is resolved.

-Courtney

**Comment by Grifo89** [comment]
I had to install it globally in order to make it works.

> I'm having the same problem.
> ![image](https://user-images.githubusercontent.com/9584549/93810071-be916800-fc13-11ea-933e-46cad838aa33.png)
> 
> So it seems, it doesn't work for now.

**Comment by TCourtneyOwen** [comment]
@Grifo89 Can you please send me a link to the tutorial you are following?

Thanks,

Courtney

**Comment by Grifo89** [comment]
Sure! Actually install it globally makes to run the command but the server gets stuck, doesn't work.  This is the link: https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator 

Looking forward to trying it when it's fixed.

**Comment by TCourtneyOwen** [comment]
I am not able to repro this behavior myself yet. Are you running on Windows or Mac?

**Comment by Grifo89** [comment]
I'm running on Windows using Node v13.2.0

**Comment by TCourtneyOwen** [comment]
Hmm.... I am not hitting any issues with Node v13.2.0 either.  I think let's try uninstalling office-addin-debugging globally and doing npm install at the project root again. Also, please try running the command prompt as admin - I don't think should matter, but it's worth a try:

Steps to run:
- npm uninstall - g office-addin-debugging
- cd to project root
- npm install
- npm start

**Comment by TCourtneyOwen** [comment]
I think this issue was the result of a package publishing issue that was fixed long ago.  Please reactivate if this is still an issue

**Comment by kattrujillo1016** [comment]
having the same issue tried different add-ins in outlook  same exact issue was this resolved

**Comment by Cuzbo** [comment]
Somehow this fixed it for me:
Delete node_module and package-lock.json
Add "office-addin-debugging": "^3.0.34" (or "^4.3.14") to devDependencies in package.json
npm install
npm start

**Comment by jclem326** [comment]
I am seeing a similar issue on both OS and Windows.  

The issue occurs when I use "yo office" and respond to the prompts.

But does not occur when I use  
yo office --projectType taskpane --name "MyAddIn3" --host Excel --js

**Comment by gustavhartz** [comment]
Had the same issue, but resolved it using
`
npm install -g office-addin-debugging
# cd into project if not already there
npm i
`
