### ISSUE TITLE
yo office giving syntax error

### ISSUE THREAD

**Issue by hlophek** [OfficeDev/generator-office#521]
I was able to use generator-office a few times but it suddenly stopped working. I can not run 
`yo office` anymore.

I can not even run other addins that were created in `yo office`

this is my error
`PS C:\Users\blaqu\Documents\Coding Projects\New Modern Charts> yo office --skip-install
C:\Users\blaqu\AppData\Roaming\npm\node_modules\generator-office\node_modules\office-addin-usage-data\lib\usageData.js:72
            throw new Error(err);
            ^

Error: SyntaxError: Unexpected token`

**Comment by TCourtneyOwen** [comment]
@hlophek Sorry you are having problems. Can you please let me know which version of the generator-office package you are running by looking in the package.json under C:\Users\blaqu\AppData\Roaming\npm\node_modules\generator-office\?

Thanks,

Courtney

**Comment by hlophek** [comment]
Hi @TCourtneyOwen 

The version is generator-office@1.6.1

**Comment by TCourtneyOwen** [comment]
@hlophek Can you please try this out: 

- Delete %:\Users\<user>\office-addin-usage-data.json
- Run yo office again

You are in fact running the latest version of yo office, but I am not able to repro the problem myself. Are you hitting the error right when you launch yo office, or is it later on while creating the project?

**Comment by hlophek** [comment]
Seems like the whole package is damaged. I get this error when I try to create a project or debug one of my old yo projects.

I think the problem started when I installed Visual Studio Pro 2019 and ran another addin from there. 

**HOWEVER**: You solution worked.

**Comment by TCourtneyOwen** [comment]
OK, glad to hear it! Wish I had a better idea how you got into that state. Please ping me back if you hit this problem again with a reliable repro,

Thanks,

Courtney
