### ISSUE TITLE
Questions: Is Mac Os web functionality supported.

### ISSUE THREAD

**Issue by rjpruitt16** [OfficeDev/generator-office#526]
I am having a hard time debugging in the application. I can get the code to run in outlook, but I am unable to see errors in console. Is there a workaround  in the react.js version.

The obvious workaround would be to use the web. This would not be a problem if I could use the web version on my mac. It seems like darwin is not supported for web for whatever reason. This information should be displayed in the readme.

**Comment by TCourtneyOwen** [comment]
Hi @rjpruitt16 Have you tried these steps for for debugging on Mac for add-in running if desktop Office:  https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac

**Comment by rjpruitt16** [comment]
I am so happy I could hug you. I have look at that documentation at least 10 times, but fail to realize that it was asking me to do something. Thank you!

**Comment by TCourtneyOwen** [comment]
@rjpruitt16 Glad to help! :-)

-Courtney
