### ISSUE TITLE
Error: getaddrinfo ENOTFOUND github.com when I try to generate a outlook addin project

### ISSUE THREAD

**Issue by majedess** [OfficeDev/generator-office#529]
Hi 
When I try to generate a project , I run into this error. I'm behind a firewall.
? Choose a project type: Office Add-in Task Pane project
? Choose a script type: JavaScript
? What do you want to name your add-in? test out
? Which Office client application would you like to support? Outlook

----------------------------------------------------------------------------------

      Creating test out add-in for Outlook using JavaScript and Taskpane at C:\Users\majedess\test out

----------------------------------------------------------------------------------
C:\Users\majedess\AppData\Roaming\npm\node_modules\generator-office\node_modules\cls-hooked\context.js:177
      throw exception;
      ^

Error: getaddrinfo ENOTFOUND github.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'github.com',
  'error@context': { _ns_name: 'AI-CLS-Session', id: 250 }

**Comment by TCourtneyOwen** [comment]
@majedess Sorry to hear you are having troubles.  Can you see if you can browse to https://github.com/OfficeDev/Office-Addin-TaskPane-JS/tree/yo-office? This is where yo-office pulls to the project files from on project creation. If you can browse to that url, I think we can rule out that there's an issue connecting to the project repo itself.  The next thing I think that could potentially be a problem is accessing NPM to install the project packages, but let's check on the process repo access first.

I was able to just create an Outlook JS Taskpane project with no problems on my Windows laptop.

Thanks,

Courtney

**Comment by majedess** [comment]
@TCourtneyOwen thanks. I confirm that the link is reachable. I would like to draw your attention that I'm using a private artifactory

**Comment by TCourtneyOwen** [comment]
If you want to create a project not using yo office, you could do the following:

- Clone https://github.com/OfficeDev/Office-Addin-TaskPane-JS
- CD to the Office-Addin-TaskPane-JS folder
- Run "node node convertToSingleHost.js outlook" (this will create an outlook project - you could also specify excel, word, powerpoint, project or onenote too)
- Run "npm install" to install the project dependencies

If you go this route and still hit the error, I think we can probably assume that the issue is with installing the dependencies and not with generator-office itself

**Comment by majedess** [comment]
Now I've this errorn ow
:node node convertToSingleHost.js outlook
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'C:\Users\majedess\Downloads\Office-Addin-TaskPane-JS-master\node'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:862:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by TCourtneyOwen** [comment]
Sorry the command was slightly off - please run "node convertToSingleHost.js outlook"

**Comment by majedess** [comment]
same error

**Comment by TCourtneyOwen** [comment]
Can you run "npm install" first before running the command? It may be that there are packages required by the script itself, although I'd be surprised.  Also what version of node are you running (run "node -v" to get version)?

**Comment by majedess** [comment]
Thanks. Your workaround did work. 
But through YO I still have an error. It looks like that YO try to reach directly the link github and bypass the proxy. Any missing setup for the proxy inYO?

**Comment by jscoder1009** [comment]
is there a resolution to this issue using yo?

**Comment by millerds** [comment]
If there is still a problem here please open a new issue.
