### ISSUE TITLE
npm install error "github.com/request/request/issues/3142"

### ISSUE THREAD

**Issue by asith-w** [OfficeDev/generator-office#531]
Following issue is occurred when installing the yo office . 

**npm install -g yo generator-office**
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! Unexpected end of JSON input while parsing near '....13.7","request":"^2.'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\deskoffice\AppData\Roaming\npm-cache\_logs\2020-05-02T09_59_39_690Z-debug.log

```
OS - windows 
npm -v
6.14.0

node -v
v12.16.3
```

**Comment by TCourtneyOwen** [comment]
@asith-w Sorry to hear you are having problems.  Can you please run the following command to see what version of generator-office you are running: **npm list -g --depth=0**

The latest version of generator-office is 1.6.1. If you aren't running this version, please run the following to pick up the latest version:

- npm uninstall -g generator-office
- npm install -g generator-office

Please let us know what you find. 

Thanks,

Courtney

**Comment by TCourtneyOwen** [comment]
@asith-w Can you also send the contents of the log at C:\Users\deskoffice\AppData\Roaming\npm-cache_logs\2020-05-02T09_59_39_690Z-debug.log and remove any potential private information from the log.

Thanks,

Courtney

**Comment by asith-w** [comment]
**npm list -g --depth=0**
```
+-- @microsoft/rush@5.7.1
+-- generator-chrome-extension@0.7.2
+-- generator-office@1.6.1
+-- npm@6.14.0
+-- open@7.0.3
+-- request@2.88.2
`-- yo@3.1.0
```

It works after reinstalling the generator-office.

i think issue is related to yeoman. not with office generator as below

C:\Users\deskoffice>**npm install -g yo**
```
npm ERR! Unexpected end of JSON input while parsing near '....13.7","request":"^2.'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\deskoffice\AppData\Roaming\npm-cache\_logs\2020-05-04T07_26_33_974Z-debug.log
```


_**C:\Users\deskoffice\AppData\Roaming\npm-cache_logs\2020-05-02T09_59_39_690Z-debug.log**_

1742 silly pacote range manifest for string-length@^2.0.0 fetched in 317ms
1743 silly resolveWithNewModule string-length@2.0.0 checking installable status
1744 silly pacote range manifest for yeoman-character@^1.0.0 fetched in 286ms
1745 silly resolveWithNewModule yeoman-character@1.1.0 checking installable status
1746 silly pacote range manifest for update-notifier@^2.5.0 fetched in 290ms
1747 silly resolveWithNewModule update-notifier@2.5.0 checking installable status
1748 silly pacote range manifest for titleize@^1.0.1 fetched in 291ms
1749 silly resolveWithNewModule titleize@1.0.1 checking installable status
1750 silly pacote range manifest for yeoman-doctor@^4.0.0 fetched in 283ms
1751 silly resolveWithNewModule yeoman-doctor@4.0.0 checking installable status
1752 timing stage:rollbackFailedOptional Completed in 1ms
1753 timing stage:runTopLevelLifecycles Completed in 32977ms
1754 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '....13.7","request":"^2.'
1754 verbose stack     at JSON.parse (<anonymous>)
1754 verbose stack     at parseJson (C:\Users\deskoffice\AppData\Roaming\npm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
1754 verbose stack     at C:\Users\deskoffice\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
1754 verbose stack     at runMicrotasks (<anonymous>)
1754 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
1755 verbose cwd C:\dev\My\fdd
1756 verbose Windows_NT 10.0.18362
1757 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\deskoffice\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo" "generator-office"
1758 verbose node v12.16.3
1759 verbose npm  v6.14.0
1760 error Unexpected end of JSON input while parsing near '....13.7","request":"^2.'
1761 verbose exit [ 1, true ]

**Comment by asith-w** [comment]
after reinstall the generator-office,  i get this details

**C:\Users\deskoffice\AppData\Roaming\npm list -g --depth=0**
```
+-- @microsoft/rush@5.7.1
+-- generator-chrome-extension@0.7.2
+-- generator-office@1.7.0
+-- npm@6.14.0
+-- open@7.0.3
+-- request@2.88.2
`-- yo@3.1.0
```
