### ISSUE TITLE
Unable to start the dev server - stdout maxBuffer length exceeded

### ISSUE THREAD

**Issue by zac404** [OfficeDev/generator-office#534]
I followed the instructions to set up an Excel Add-in Task Pane project: https://docs.microsoft.com/de-de/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator
I get the error
**Unable to start the dev server. RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded**
when I am trying to run the App with "npm start" :
```
office-addin-taskpane-js@0.0.1 start C:\...
office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
Enabled debugging for add-in 415ffd64-25cb-4c91-aca8-add703ebba19. Debug method: 0
Unable to start the dev server. RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
Sideloading the Office Add-in...
Debugging started.
```
Does anyone have an idea how to solve this problem?

**Comment by akrantz** [comment]
I'm not sure why this is happening, and it would help to know which OS you are using, which Node version, and perhaps others things, but I can offer some suggestions to help.

First, you might try rebooting, as maybe something is in use.

Second, try running `npm run dev-server` to start the dev-server by itself. Any difference? 

If you have the dev-server running and then do `npm start`, then it will detect it is running and won't try to start it.

I don't know if this will make a difference, but I like to run the dev server in VS Code so it stays running while you close and relaunch Excel. If you open the folder in VS Code, you can then do use `Run Task` from the `Terminal` menu and choose `Dev Server`. You can then use `Start Without Debugging` to launch Excel.  

(VS Code cannot debug the WebView control running in Excel so you have to use a different mechanism to debug it. You might still find using VS Code convenient as an editor.)

It would be interesting to know if having VS Code run the dev-server has a different result.

**Comment by igor-ribeiiro** [comment]
@zac404 Are you still facing this issue?

**Comment by igor-ribeiiro** [comment]
I will be closing this issue as I could not repro this error.
Please, reopen the issue if there are still errors.
