### ISSUE TITLE
ECONNRESET error when creating any yo office project

### ISSUE THREAD

**Issue by noon-otter** [OfficeDev/generator-office#535]
I'm not able to run `yo office` on my Windows 10 machine. When I run the following command

`yo office --projectType excel-functions --name "new addin" --host excel --ts true`

I get the following error message

```
D:\Users\{uname}\AppData\Roaming\npm\node_modules\generator-office\node_modules\cls-hookec\context.js:177
    throw exception;
    ^

Error: read ECONNRESET
    at TLSWRAP.onStreamRead (internal/stream_base_commons.js:201:27( {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',
'error@context': { _ns_name: 'AI-CLS-Session', id: 140 }
```

I'm using yo v6.14.5 and generator-office v6.14.5.

Additionally, I'm not able to run any of my previous projects. Excel won't sideload anything anymore and gives the same ECONNRESET error when trying to.

**Comment by TCourtneyOwen** [comment]
The latest version of yo office is 1.7.1 (https://github.com/OfficeDev/generator-office/releases/tag/v1.7.1).  Can you please try the following to ensure you have the latest version:
- npm uninstall -g yo generator-office
- npn install -g generator-office

This will ensure you pick up the latest version of yo office.  

Also, what version of NodeJs are you running?  You can check by running "node -v"

Thanks,

Courtney

**Comment by noon-otter** [comment]
I've update yo office to the current version using your commands, but I'm still getting the same ECONNRESET error.

I'm using node v12.13.1

**Comment by noon-otter** [comment]
I've found that my network is blocking a request to github when I run `yo office`. Github is blocked at my job. Is access to github required to use `yo office`?

**Comment by TCourtneyOwen** [comment]
Yo office does indeed require access to GitHub because that’s where it pulls the project templates from.

**Comment by noon-otter** [comment]
I'm not able to access GitHub at all outside of my personal computer.

**Comment by TCourtneyOwen** [comment]
Closing this issue as GitHub access is a requirement for using Yo Office because the project templates reside in GitHub

**Comment by dafengz** [comment]
I ran into the same problem. By executing the following code, I can now create add-in.
`
npm config set registry http://registry.npmjs.org/
`

**Comment by factanate** [comment]
@dafengz's approach does not resolve the issue for me.

I can ping github.com.  How else would I test for a block?

I receive this error at times, but not at others.
