### ISSUE TITLE
path {project_root}/certs does not exist

### ISSUE THREAD

**Issue by vlad-ed-git** [OfficeDev/generator-office#537]
To manually install the certificates, the instructions say go to {project_root}/certs . But this folder does NOT get created when I use Yeoman generator to create an Office Add-in project. There is no mention of what to do in this case either!

**Comment by TCourtneyOwen** [comment]
I think you must be referring to outdated documentation. You no longer need to install the certs manually. If you just do “npm start” at the project root you will be presented with a prompt asking if you want to install the auto-generated certs, and just say yes to the prompt. Once the certs are installed, your dev server will start and your project will open in the host application you selected. Please let me know if that works for you. 

Thanks,

Courtney

**Comment by vlad-ed-git** [comment]
Actually it is not the case that such a prompt is presented. At least it
wasn't in my case. But I did find the command to install them,
office-addin-dev-certs install , which seem to have worked.

On Saturday, June 13, 2020, Courtney Owen <notifications@github.com> wrote:
> I think you must be referring to outdated documentation. You no longer
need to install the certs manually. If you just do “npm start” at the
project root you will be presented with a prompt asking if you want to
install the auto-generated certs, and just say yes to the prompt. Once the
certs are installed, your dev server will start and your project will open
in the host application you selected. Please let me know if that works for
you.
>
> Thanks,
>
> Courtney
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/kxsAACRZ8KrNxxFEQ-z99_GHrOX21_4wsHBdoO1s_OyHOD1t3WG219CLNN-wRW8g_hypConAsa63Rp2olmHHU0_4UALTgpMdu1j8ZNUK31gsmfsb4qRPVLtO643yTRDaBKmZPbZ7I_80ILRmaEG4aDrkkyP5VrUicCmZ8J5UVvGkRau9Ld33S11gtF1FYrTksyEb0JOkPcAHMOpkyR84OxdIvANDH3zgQ407SDIyOw=s0-d-e1-ft#https://github.com/notifications/beacon/AJGBW64PFOJCDAZNHLE5G53RWLTCNA5CNFSM4N4Y7WTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEZN6YEA.gif>

**Comment by TCourtneyOwen** [comment]
Ok great, glad you figured it out. Sometimes that dialog I mentioned can get hidden behind other windows. If you are on Mac, then there isn’t a dialog - there’s only a prompt for an admin password before installing the certs. 

Can you please provide me the link to the documentation you were initially consulting so we can get that corrected?

Thanks,

Courtney
