### ISSUE TITLE
Office Online attach debugging only supported for Firefox 

### ISSUE THREAD

**Issue by pl4nty** [OfficeDev/generator-office#540]
`launch.json` needs a warning that attach debugging is only supported for Firefox. The add-in iframe causes errors for [Chrome](https://github.com/Microsoft/vscode-chrome-debug/issues/786) and [Edge](https://github.com/microsoft/vscode-edge-debug2/issues/185).

**Comment by millerds** [comment]
Can you specific a specific configuration in launch.json?  Currently there a number of launch entries for different office apps for edge and chromium.

**Comment by millerds** [comment]
Closing for now.  If you have more feedback please re-open or log a new issue.
