### ISSUE TITLE
Generated Custom Functions project for Excel doesn't sideload

### ISSUE THREAD

**Issue by ghost** [OfficeDev/generator-office#543]
I've tried to generate an Excel Custom Functions Add-in with the yo office command with Javascript as the chosen language. I'm using a Mac Mini with latest version of macOS and when I try to sideload the freshly created add-in in Excel by running npm start I get an error in Excel basically telling me the add-in wasn't sideloaded. And Indeed my add-in is nowhere to be found in Excel nor are my custom functions showing up when I type = in a cell.

This was with a freshly created project and I haven't changed anything. I tried npm run validate to check the manifest and it was fine. I'm not sure what the problem is but I think there might be a problem with the Generator for Excel functions.

**Comment by TCourtneyOwen** [comment]
@prxzr after you run "npm start" can you see if you can browse to https://localhost:3000/taskpane.html. Is you hit an error, it may be that your dev server certificates didn't get registered properly

**Comment by TCourtneyOwen** [comment]
@ghost, I have seen this issue myself when I have a previous instance of custom functions cached.  If you have created a custom functions in the past, you may want to try deleting your add-in cache following the steps for Mac outlined at https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache

**Comment by TCourtneyOwen** [comment]
Closing as we haven't heard any further communication on this issue after providing guidance.  Please reactivate if this is still an issue
