### ISSUE TITLE
Task Pane project for Microsoft Project - unable to get the UI and sideload

### ISSUE THREAD

**Issue by baaswietse** [OfficeDev/generator-office#544]
Hello,

After following the basic [tutorial](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/project-quickstart), I ran `npm start` and got following message in my console: 

```
> office-addin-taskpane-js@0.0.1 start C:\Users\wdelclef\OneDrive - Eiffage\Documenten\Programeren\ms project\My Office Add-in
> office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
? Allow localhost loopback for Microsoft Edge WebView? Yes
Enabled debugging for add-in 960d3456-d37f-475d-8c82-dbd0873a49b0. Debug method: 0
Starting the dev server... (webpack-dev-server --mode development)
The dev server is running on port 3000. Process id: 38132
Sideloading the Office Add-in...
Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in.
Error: Sideload is not supported.
```

When I go to `https://localhost:3000` I get the following:
![image](https://user-images.githubusercontent.com/40791418/86470497-d99ebb00-bd3b-11ea-9b16-dc1551135db1.png)

**Comment by TCourtneyOwen** [comment]
Which host are you using for your project? Sideloading is only supported for Word, Excel and PowerPoint. 

Thanks,

Courtney

**Comment by baaswietse** [comment]
> Which host are you using for your project? Sideloading is only supported for Word, Excel, and PowerPoint.
> 
> Thanks,
> 
> Courtney

Thanks for the quick response.

I don't really understand why the [tutorial](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/project-quickstart) specifically states that you have to sideload it then? 
I don't find any documentation on how to get this demo working otherwise.

Thanks

**Comment by TCourtneyOwen** [comment]
If you want to open the project you created via Yo Office you will need to sideload it. For Excel, PowerPoint and Word you can just run “npm start” and it will be automatically sideloaded.  If you are using a host such as Outlook you will need to manually sideload. Can you please clarify which host you are using so I can point you to the right steps?

Thanks

**Comment by baaswietse** [comment]
I am trying to use Microsoft Project ([https://www.microsoft.com/nl-be/microsoft-365/project/project-management-software](https://www.microsoft.com/nl-be/microsoft-365/project/project-management-software)), my company would like me to develop an addin which is able to push the data from a Projects file to an SQL database. Since I can't find any available options to do this, I'd have to try and make this myself.
I have no experience in developing for Office products, but I do have a background in Node.js backends so I thought this would be a great starting point.

Thanks in advance

**Comment by TCourtneyOwen** [comment]
Have you tried these steps yet to manually sideload your add-in:  https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins#:~:text=Sideload%20Office%20Add-ins%20for%20testing%201%20Share%20a,or%20Project.%20...%203%20Sideload%20your%20add-in.%20

**Comment by baaswietse** [comment]
Yes I did, but since the manifest file points to the localhost and it doesn't seem to be properly running there (see my first screenshot above).

This is what I get in Project: 
![image](https://user-images.githubusercontent.com/40791418/86531891-7f316600-bec5-11ea-81d9-007fe92fd13c.png)

**Comment by TCourtneyOwen** [comment]
Did you run “npm run dev-server” to start your local host server? You will need to do that before opening the add-in

**Comment by baaswietse** [comment]
**Still the same result, this is the output I get from running npm run dev-server:** 

C:\Users\wdelclef\OneDrive - Eiffage\Documenten\Programeren\ms project\My Office Add-in>npm run dev-server

 office-addin-taskpane-js@0.0.1 dev-server C:\Users\wdelclef\OneDrive - Eiffage\Documenten\Programeren\ms project\My Office Add-in
 webpack-dev-server --mode development

You already have trusted access to https://localhost.
Certificate: C:\Users\abinstaller\.office-addin-dev-certs\localhost.crt
Key: C:\Users\abinstaller\.office-addin-dev-certs\localhost.key
i ｢wds｣: Project is running at https://localhost:3000/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\wdelclef\OneDrive - Eiffage\Documenten\Programeren\ms project\My Office Add-in
i ｢wdm｣: Hash: b9b5d59d5a653ded9352
Version: webpack 4.43.0
Time: 5129ms
Built at: 2020-07-06 10:06:09
                               Asset       Size    Chunks                   Chunk Names
7f313c06a52dabe7267420021403d038.png   11.6 KiB            [emitted]
                       commands.html  473 bytes            [emitted]
                         commands.js    348 KiB  commands  [emitted]        commands
                     commands.js.map    399 KiB  commands  [emitted] [dev]  commands
                         polyfill.js    746 KiB  polyfill  [emitted]        polyfill
                     polyfill.js.map    715 KiB  polyfill  [emitted] [dev]  polyfill
                        taskpane.css   1.48 KiB            [emitted]
                       taskpane.html   2.52 KiB            [emitted]
                         taskpane.js    350 KiB  taskpane  [emitted]        taskpane
                     taskpane.js.map    400 KiB  taskpane  [emitted] [dev]  taskpane
Entrypoint polyfill = polyfill.js polyfill.js.map
Entrypoint taskpane = taskpane.js taskpane.js.map
Entrypoint commands = commands.js commands.js.map
[0] multi (webpack)-dev-server/client?https://localhost:3000 @babel/polyfill 40 bytes {polyfill} [built]
[1] multi (webpack)-dev-server/client?https://localhost:3000 ./src/taskpane/taskpane.js 40 bytes {taskpane} [built]
[2] multi (webpack)-dev-server/client?https://localhost:3000 ./src/commands/commands.js 40 bytes {commands} [built]
[./node_modules/@babel/polyfill/lib/index.js] 686 bytes {polyfill} [built]
[./node_modules/@babel/polyfill/lib/noConflict.js] 567 bytes {polyfill} [built]
[./node_modules/core-js/library/fn/global.js] 87 bytes {polyfill} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/index.js?https://localhost:3000] (webpack)-dev-server/client?https://localhost:3000 4.29 KiB {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {polyfill} {taskpane} {commands} [built]
[./src/commands/commands.js] 1.06 KiB {commands} [built]
[./src/taskpane/taskpane.js] 2.95 KiB {taskpane} [built]
    + 328 hidden modules
Child HtmlWebpackCompiler:
                                   Asset      Size  Chunks             Chunk Names
    7f313c06a52dabe7267420021403d038.png  11.6 KiB          [emitted]
     + 2 hidden assets
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_1 = __child-HtmlWebpackPlugin_1
    [./assets/logo-filled.png] 82 bytes {HtmlWebpackPlugin_0} [built]
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/commands/commands.html] 450 bytes {HtmlWebpackPlugin_1} [built]
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/taskpane/taskpane.html] 2.61 KiB {HtmlWebpackPlugin_0} [built]
i ｢wdm｣: Compiled successfully.

**my manifest file looks like this:**
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="TaskPaneApp">
  <Id>960d3456-d37f-475d-8c82-dbd0873a49b0</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Contoso</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="My Office Add-in"/>
  <Description DefaultValue="A template to get started."/>
  <IconUrl DefaultValue="https://localhost:3000/assets/icon-32.png"/>
  <HighResolutionIconUrl DefaultValue="https://localhost:3000/assets/icon-80.png"/>
  <SupportUrl DefaultValue="https://www.contoso.com/help"/>
  <AppDomains>
    <AppDomain>contoso.com</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Project"/>
  </Hosts>
  <DefaultSettings>
    <SourceLocation DefaultValue="https://localhost:3000/taskpane.html"/>
  </DefaultSettings>
  <Permissions>ReadWriteDocument</Permissions>
</OfficeApp>`

**Comment by baaswietse** [comment]
@TCourtneyOwen are you able to reproduce this issue?

Thanks a lot for the help so far.

**Comment by TCourtneyOwen** [comment]
@baaswietse I just tried out a Project Javascript Taskpane add-in and was unable to repro this behavior.  Here's what I see:

![image](https://user-images.githubusercontent.com/38081557/87174460-0c8d0580-c28c-11ea-9d42-e901de07c293.png)

Are you able to browse to https://localhost:3000/taskpane.html? If not, then there is something likely going on with your dev-server

**Comment by TCourtneyOwen** [comment]
@baaswietse Were you ever able to resolve this issue?  Have you tried browsing to https://localhost:3000/taskpane.html after sideloading the add-in to ensure that your dev-server is set up properly?

**Comment by baaswietse** [comment]
@TCourtneyOwen since I am on holiday without my work computer I was not able to resolve the issue yet. 
I will get back to you as soon as I am home. 

Thank you for your time and patience, really appreciate it!

**Comment by TCourtneyOwen** [comment]
@baaswietse Just checking in, any progress on this issue?

**Comment by baaswietse** [comment]
Hello, I was just in the process of making a screen recording to show you the steps I followed and suddenly it worked.
Even tho I didn't do anything different. I hope this issue doesn't appear anymore. I'm sorry to waste your time.

Can I just ask one more question? Are you aware of any resources/projects to directly push data from MS Project to an SQL database?

Thank you for your time.

**Comment by TCourtneyOwen** [comment]
I believe this issue was resolved, so closing
