### ISSUE TITLE
Error office  Cannot find module '.../v12.18.2/lib/node_modules/generator-office/node_modules/office-addin-manifest/lib/main.js'. Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by elmeet** [OfficeDev/generator-office#547]
# Prerequisites
```
> npm install -g yo generator-office
> yo office
Error office
Cannot find module '/Users/xxx/.nvm/versions/node/v12.18.2/lib/node_modules/generator-office/node_modules/office-addin-manifest/lib/main.js'. Please verify that the package.json has a valid "main" entry
```

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior
Expect normal execution and template generation

# Current behavior

Failed to execute `yo office`
```
> yo office
Error office
Cannot find module '/Users/xxx/.nvm/versions/node/v12.18.2/lib/node_modules/generator-office/node_modules/office-addin-manifest/lib/main.js'. Please verify that the package.json has a valid "main" entry
```

## Steps to Reproduce

1.  npm install -g yo generator-office
2. yo office

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:  macOS 10.15.4
* Node version: 12.18.2
* Office version: 16.93(20071300)
* Tool version: 1.5.5

**Comment by saschwarz** [comment]
I'm getting the same error with a freshly install node v12.16.3
```
> yodoctor

Yeoman Doctor
Running sanity checks on your system

✔ No .bowerrc file in home directory
✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ No .yo-rc.json file in home directory
✔ Node.js version
✔ npm version
✔ yo version

Everything looks all right!
+ generator-office@1.7.1
+ yo@3.1.1
added 1195 packages from 454 contributors in 21.309s

> yo
? 'Allo Steve! What would you like to do? Office

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo office

Error  

Cannot find module '/Users/saschwarz/.nvm/versions/node/v12.16.3/lib/node_modules/generator-office/node_modules/office-addin-manifest/lib/main.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by AGDholo** [comment]
Same error on
* nodejs v14.5.0
* windows 10 1909

Cannot find module 'C:\Users\agdho\AppData\Roaming\npm\node_modules\generator-office\node_modules\office-addin-manifest\lib\main.js'. Please verify that the package.json has a valid "main" entry

**Comment by TCourtneyOwen** [comment]
Thanks for reporting this issue. I will look into this today and get back to you.

-Courtney

**Comment by rpfeuti** [comment]
Same problem here, windows 10, tried on Node.js 12.18.2 LTS and 14.6.0 
yo office --projectType react --name "Testing" --host excel --ts true

**Comment by TCourtneyOwen** [comment]
I think it must be an issue with the new version of office-addin-manifest that was published yesterday. I noticed in the latest version there is no tsconfig contained in the package, so this would cause build of the lib file to fail. I suspect this was a problem with the NPM publishing process.  I will get a new version of the package published today

**Comment by saschwarz** [comment]
@TCourtneyOwen FWIW I manually linked an old version `office-addin-manifest` in the installed `generator-office` package in `node_modules` and was able to progress further. Then I got the same error on `office-addin-usage-data`.

**Comment by FabianValenciaR** [comment]
Same problem here.

Windows Version:    10.0.18363 Build 18363
Node Version:    12.18.2
yo version: 3.1.1
 
Error office
Cannot find module 'C:\Users\xxx\AppData\Roaming\npm\node_modules\generator-office\node_modules\office-addin-manifest\lib\main.js'. Please verify that the package.json has a valid "main" entry.

**Comment by TCourtneyOwen** [comment]
@saschwarz Yes something seems to have happened during lerna publish to NPM yesterday. While there were no errors thrown, the publish process seems to have failed in some way

**Comment by TCourtneyOwen** [comment]
OK, I republished all the packages I published yesterday (including office-addin-manifest) without making any changes, but the versions will be bumped up one.  Yo office is now working for me locally on three different machines.

Can you all please try the following:

- npm uninstall -g yo generator-office
- npm install -g yo generator-office
- run "yo office" again

I hope this fixes things for you.  

Thanks,

Courtney

**Comment by saschwarz** [comment]
I just pulled down `generator-office@1.7.1` again and with `office-addin-manifest@1.5.6` it works now. Thanks for resolving this so quickly!!

**Comment by TCourtneyOwen** [comment]
Awesome, glad to hear it!  As far as I can tell, there just must have been some publishing hiccup to NPM yesterday that didn't return any sort of error.  I merely republished and this time it appears to have worked as expected

**Comment by rpfeuti** [comment]
Is working. Thank you guys for so fast response.
Best regards

**Comment by Alex-Willenbrink** [comment]
YES! THANKS FOR THE FIX

**Comment by TCourtneyOwen** [comment]
Seems like everyone is good to now. I am closing this issue.
