### ISSUE TITLE
Add support for add-in commands to mail add-in

### ISSUE THREAD

**Issue by jasonjoh** [OfficeDev/generator-office#55]
We should show off the new add-in commands in the add-in that's generated.

http://blogs.msdn.com/b/exchangedev/archive/2015/08/31/introducing-add-in-commands.aspx
http://blogs.msdn.com/b/exchangedev/archive/2015/09/01/building-add-ins-with-commands.aspx

I have a demo add-in that shows the three command button types that's a straight HTML/CSS/JS project. It also uses Fabric: https://github.com/jasonjoh/command-demo

I'd propose using this in place of the demo add-in that's there now. We could prompt the user to include the command button types they are interested in and only include those types. I'm working on a prototype in my fork of this repo, I'll update once I have something to look at.

**Comment by andrewconnell** [comment]
I like it... curious to see your fork & the changes...

**Comment by jthake** [comment]
I see what you did there... ;-)

**Comment by jthake** [comment]
I would suggest maybe we add another question in the generator that asks whether you want demo code in the scaffolding or not. I think the ONLY real way to keep this clean is to have some special file alternatives (maybe a file prefix?) inside the mail\templates\ng\ and mail\templates\html\ .

e..g right now in \mail\templates\html\appcompose\home\home.html is the only file that has a change for a  code sample. So we could just have \mail\templates\html\appcompose\home\home-sample.html . Unfortuantely it does mean we have duplication across two files with a subset of the file different. But Yeoman doesn't handle injecting code into files.

If there are a ton of files that need changing...i'm guessing we may need mail\templates\ng\samplecode directory where we group the files together? that way its cleaner than having "-sample" alternatives everywhere. Thoughts?

**Comment by andrewconnell** [comment]
If we were adding sample code & content, I'd suggest we have a whole different subgenerator... so it would be mail, but mail-sample or taskpane-sample.

Personally I'm not much of a fan of adding sample code to the existing generators as it starts to Visual Studio-ize this project where VS uses the model of File=>NewProject=>F5 and you see stuff working. You end up having to pull this out.

This approach that I suggest lets you create a quick addin and run it as a good demo or as a reference implementation right inline with the rest of.

**Comment by jthake** [comment]
After discussing this in person with @andrewconnell . In actual fact, we are going to strip out all the sample code. The reality is that it'll just mean branches for each template. If people really want o see add-in commands they can clone your project @jasonjoh . Just looking at the manifest in the demo project....its just too much stuff to keep a project clean from scaffolding.

**Comment by andrewconnell** [comment]
+1

**Comment by jasonjoh** [comment]
My sample covers all of the cases (mail and appointments, read and compose for both, all 3 command types), so yeah, it's pretty big. The changes I've made so far allow you to pick and choose, and it doesn't get too bad. I'm fine with making this a different subgenerator or something. I could even include it as an add-on for yo office maybe, though I'd need to look into how you extend a generator via a separate package :).

However, I'd like for your sample manifest to at least include the scaffolding for the `VersionOverrides` element, with maybe some helpful comments in place to tell what it's for and why you would put stuff in it.

**Comment by andrewconnell** [comment]
I'd like for @jthake to make a call here... 

@jasonjoh what we discussed was to have the generator follow what other generators do and only build the scaffolding for the project, not a lot of stuff that you then have to go clean out or modify. The fear is that adding samples is going to start turning this generator what it wasn't supposed to be: the xplat version of VIsual Studio templates.

My concern is that what I've seen with commands is that it requires a considerable amount of XML to build up a single button. I'm with @jthake and think this makes more sense as a sample.

One thing we've discussed is a package of snippets for VSCode for Office Add-in development... commands would make for a great snippet.

Ultimately I'm going to yield to @jthake on this one.

**Comment by jthake** [comment]
@jasonjoh  we are all in Amsterdam right now and discussing this. Essentially i think having VS Code snippets or even working out how we can use an XSD to get intellisense when building the manifest (and not just when coding it) would be awesome. What is the risk if the VersionOverrides scaffolding is simply not filled out...will it pass the new manifest tests that @waldekmastykarz has built into the generator? Will it upload ok?

**Comment by jasonjoh** [comment]
Having an empty VersionOverrides will not break anything. Old clients will ignore it and newer clients should fall back to the old stuff. I'd have to test. What new manifest tests are we talking about, are they in the current version?

**Comment by waldekmastykarz** [comment]
There is quite some markup that goes into each one of these buttons. I can imagine how helpful would it be to have all of it generated, particularly when working with editors which don't offer intellisense for manifest.xml.
I don't have that much experience with add-in commands yet, but what if we could have a proper scaffolding (so not sample code but real XML that is a part of the add-in's functionality) for add-in commands implemented as a subgenerator that you could call on an existing mail add-in to add commands to it? That would allow us to keep the commands separate from the main generator and still help developers use them in their add-ins.

**Comment by andrewconnell** [comment]
I like that approach @waldekmastykarz. My understanding (correct if I'm wrong @jasonjoh / @jthake) is that addin commands will come to all the clients, not just mail, so having this as a seperate thing that adds the markup for a sample addin command to an existing project might be a nice option.

**Comment by jthake** [comment]
That is correct. add-in commands will eventually come to all Office products (Excel, PowerPoint, Word) like they are already in Outlook.

**Comment by waldekmastykarz** [comment]
Any suggestions which control would be the best to implement first @jthake?

**Comment by andrewsa** [comment]
@jasonjoh @andrewconnell @jthake Hey guys, JasonJ and I were just going thinking through yo office some more. I think what we really need to do is modify the yo office generator itself. The problem is that the question it's asking about Outlook - "Which form do you want?" - is no longer applicable, nor the main question we want developers to think about, when building an add-in. The right question would be "Which extension points do you want?" and provide a choice of MessageReadCommandSurface, Message Compose Command Surface, Custom Pane, etc. Thoughts?

**Comment by andrewconnell** [comment]
So instead of asking what kind of addin (mail / content / task pane) you ask this question?

Or are you saying instead of asking read / compose [mail | calendar] form, you ask this question?

How would this look if it was a content / task pane addin for Word / Excel / PowerPoint / etc?

**Comment by andrewsa** [comment]
first you ask what kind of addin, then, if the user said "mail", you ask "Which extension points?" instead of "which forms?"

**Comment by andrewconnell** [comment]
Am I correct in understanding that Word & Excel also support Addin Commands today? Or is it just Outlook?

If Word & Excel also support them, would they have the same sort of prompt?

**Comment by andrewsa** [comment]
Word and Excel support it in "dev preview" today. Outlook supports it as of Office 2016 GA.

**Comment by pretish** [comment]
And according to Humberto, word/excel has extension points like contextual menu, content pane etc. So the flow would work for them as well.

**Comment by waldekmastykarz** [comment]
Also am I understanding it correctly that a single add-in might have multiple extension points so when asking for which extension points a dev wants, we should support multiple choices?

**Comment by jasonjoh** [comment]
That's correct. I'm working on implementing the prompts, I'll post more details once I have a skeleton in place.

**Comment by jthake** [comment]
If you guys want to write out here what the extension point questions would be in TOTALITY e.g. not just for Outlook but what they would look like for Outlook, Word, Excel, PowerPoint we can review as a team. Its hard to envisage this without that thinking.

I believe this is separate from this current thinking around add-in commands though. We can still have the subgenerator for add-in commands without doing this change to the key generator right?

**Comment by andrewsa** [comment]
well yes and no. You're right in that we can still have a sub generator for commands, which can generate manifests for word, excel, ppt or outlook. 

But my point is that the main generator needs to change as well, as it's creating a legacy manifest now for outlook, instead of focusing on the new way of building add-ins. does that make sense?

**Comment by jasonjoh** [comment]
Perhaps it would be helpful to think of it like this:

- existing `mail` generator is there to create the "old" stuff, which can be useful for add-ins that want to work with legacy clients
- new `commands` generator is there to either extend an existing legacy manifest, or to create a new blank manifest with only add-in command features.

We could then modify the `mail` generator to invoke `commands` after it is done with its work, resulting in a manifest that has the new features but will still work in legacy clients.

**Comment by jthake** [comment]
"legacy manifest"?...what do you mean by "the new way of building add-ins"? I'm concerned of the use fo "old stuff"...how different is it really? are there breaking changes between project scaffolding? I thought the manifest doesn't have to change that much.
maybe we need an additional question on whether they want to support "legacy clients" (you are talking about Outlook 2013 on Windows only here right?) or not and branch the questions based on that.

**Comment by andrewsa** [comment]
so the current "yo office" generator results in a mail add-in manifest, which places an add-in in either the grey horizontal bar, or behind the "apps for office" button in compose. that's legacy behavior, so anyone using it will go down the wrong path, as they won't even know that they can do commands. worse, they may build an add-in using this approach, submit it to the store and have their add-in rejected, because now we require mail add-ins to have commands for scenarios, where the add-in appears on every message or appointment. 

what we want from the generator is to advertise the new behavior - developers can choose to have add-in commands or custom pane. and in a few months, we'll support even more extension points. this isn't about creating a generator for commands and telling developers you can do one or the other. this is about guiding developers down the only correct path - using extension points, including commands.

**Comment by jasonjoh** [comment]
Here's my own definitions :)

- legacy client: Any client that doesn't understand the `VersionOverrides` element in the manifest (which is where add-in commands are defined). Right now that means anything other than Outlook 2016 on Windows, but that will change at some point.
- legacy manifest: All the stuff in the manifest outside of `VersionOverrides`.

So it doesn't really break the scaffolding. The setup you guys currently create (the "old way" or "legacy manifest" way) would be used by any legacy client. Outlook 2016 would ignore all of that when it finds a `VersionOverrides` element in the manifest.

In addition, because all of the "new" stuff is contained in `VersionOverrides`, legacy clients just ignore it since they don't know what it is. So adding add-in commands doesn't break legacy clients.

**Comment by jasonjoh** [comment]
Ok, here's what I'm thinking for the prompt flow for the commands bit. This is assuming that it's called on its own. If it gets invoked from say the `mail` generator a lot of these prompts would already be answered.

- Office project type: (Outlook add-in, task pane, content)
- Root folder of project: (Default current directory)
- Relative path to manifest file (Default manifest.xml)
- Supported hosts: (Checkbox dependent on project type. If Outlook add-in is selected above, no prompt, just set to 'MailHost')
- Supported extension points (Checkbox dependent on supported hosts. For Outlook: `MessageReadCommandSurface`, `MessageComposeCommandSurface`, `AppointmentOrganizerCommandSurface`, `AppointmentAttendeeCommandSurface`, `CustomPane`)
- If `CustomPane` selected:
  - Requested height of pane in pixels:
  - Relative path to pane source file
- If `*CommandSurface` selected:
  - Add buttons to: (Checkbox dependent on supported hosts. For Outlook: `Default tab`, `Custom tab`)
  - Supported button types: (Checkbox: `UI-less button`, `Drop-down menu`, `Taskpane button`)

The generator would then take these choices and build a manifest. The choice of tabs and button types would repeat on each command surface, but with different values.

**Comment by andrewsa** [comment]
Jason, this makes sense, but now i'm not clear why we wouldn't update the existing generator for this. why would we build a new one? that just sounds confusing - so which one should developers use?

**Comment by jasonjoh** [comment]
I think doing it this way will make it easier for the taskpane and content generators to re-use the work. Developers will still use yo office, there's just another subgenerator that's called as part of the flow. It would be automatic.

**Comment by jthake** [comment]
OK. As @andrewconnell had stated before. This work will not be accepted into the branch without it working for Word/Excel/PowerPoint scenarios as well...with 100% coverage. So we need to loop in the other engineering teams to make sure this gets covered as well as the Outlook scenarios.

**Comment by jasonjoh** [comment]
I spoke with @andrewsa about this, and requiring it to work for all of the Word/Excel/PPT scenarios before we update the generator doesn't seem reasonable at this stage. They are still in preview right? Outlook support is GA'ed and commands are required by the store in a lot of cases, so it's important we can support this now for Outlook.

How about we can get this working for Outlook now (meaning that the `commands` subgenerator has a baseline implementation and the `mail` subgenerator is modified to invoke `commands`), and then work with folks from the different teams to address any gaps in the `commands` subgenerator for their specific needs?

**Comment by andrewconnell** [comment]
IMHO since they do work in the other clients I think it’s a reasonable request as people are going to ask for it. If the assumption by the users of the generator that it should be there and since MSFT Office group now has a habit of running stuff in preview for a while (which is good), I think support across the board should be there today.

With that being said, think @jthake gets the last call on this one.

**Comment by jasonjoh** [comment]
I'm not saying let's not add the support, I'm just saying don't gate this on getting 100% coverage. That seems like it's just going to delay adding the feature. Let's get this smaller scope in, then we can build on it.

**Comment by andrewconnell** [comment]
I get what you’re saying, but I still stand by my POV that a official release includes all / none since add-in commands work in all apps

**Comment by jasonjoh** [comment]
So maybe instead of an official release, we take a page from Office and release a "preview" that supports Outlook. :D

**Comment by andrewconnell** [comment]
If NPM supported something like that then maybe… but the way I see others doing this is having a specific branch with explanation of how folks can get and globally install an NPM package from a specific branch in a repo rather than NPM.

If this the approach that’s adopted (again, I yield to @jthake to make the call) then let’s ensure coordination before you submit a PR because we’ll likely need a branch just for that PR (we don’t want it going to the dev branch because that would hold up all future work until that feature is fully finished across all clients.

**Comment by jthake** [comment]
We've supported Outlook preview features in the yeoman generator in the past. Don't see the issue in not supporting Word/Excel/PowerPoint features too.
I get its extra effort and "not your team", but it'd be great if you could reach out and work with the other client teams to make this happen correctly....

**Comment by jasonjoh** [comment]
I’ve finally got something completed on this add-in commands feature for the yeoman generator. I’ve checked everything into my fork of the project, in the commands branch:

https://github.com/jasonjoh/generator-office/tree/commands 

### OVERVIEW

I implemented this as a subgenerator called ‘commands’. I designed it with two scenarios in mind:

- One of the existing subgenerators (‘mail’, ‘content’, etc) invokes it as part of their processing
- The user calls ‘commands’ directly to update an existing manifest

For the first scenario, I added the ability to pass a custom XML and JS file to the generator to bypass all of the prompts for command details. You can see this in action by creating a mail add-in using the HTML/CSS/JS tech. That particular template in the mail generator includes an XML file with command definitions and a JS file with supporting functions for the function file. These are designed to complement the existing code in the HTML template. The other templates don’t include any sample code, so once their prompts are done, the command generator prompts kick in and it asks for details.

For the second scenario, an existing manifest is required. The prompts ask the necessary questions to build out example command elements and updates the manifest. It will also insert a function file, a taskpane source file, and a custom pane source file, all based on the choices made by the user.

### TRYING IT OUT

You can try this out yourself by cloning my branch to your local machine, then using NPM to link to it. If you’ve already got yo office installed globally and you don’t want to muck with that, I recommend creating a separate directory for testing this out in, then in that directory running:

    npm link <directory to cloned branch>

That way whenever you’re in that directory you get my version of the generator. Anywhere else you get the one you have globally installed (the released version).

### OTHER DETAILS

- I did implement tests for this generator and insured all tests pass against the project. I did have to update the existing mail generator tests to account for the new option (replaced outlookForm with extensionPoint)
- I did run gulp vet against the code and fixed all the issues I could fix.

Let me know what you think!

**Comment by jthake** [comment]
OK i just reviewed this.
Note when I clone I had to clone the branch "commands".

Some feedback:
- I don't see ANY additional questions right now on "Do you want a blah" which would add an extension point?
- can you provide a sample file to parse in to yo office to see what else it can do?
- If i do a next next next, by default it puts in See Message Details, Set Subject, Get Subject, Set Receipient. I'm assuming this is what Outlook engineering wants as a minimum for each one? Otherwise people will have to remove this from manifest right? I would prefer by default the min bar is only add what is required.
- It'd be cool to have better icons for each sample ribbon button, rather than the add-in logo (which i  think is default)

**Comment by jasonjoh** [comment]
Thanks Jeremy, I'll go point by point.

- Additional questions: I'm assuming that you created an HTML/CSS add-in from the mail generator. In this case, you won't see questions, because the HTML/CSS template provides a pre-defined template of add-ins designed to mirror the existing functionality (more on this in later question). To see questions, either run the generator directly against an existing manifest (`yo office:commands`) or create an Angular add-in from the mail generator.
- Sample file: Easy enough to generate one, just run the unmodified yo office and use the manifest from that. 
- Buttons you see: These are designed to compliment the existing HTML/CSS sample. Before add-in commands, it opened a pane on read forms that showed some details, so I added a "Show Message Details" button to read forms that open a task pane with the same information. On compose forms, it showed three buttons. I just added those same buttons to the ribbon. **Pretish has asked to extend with a drop down, I'll be working on that today.**
- Better icons: We chatted about this one offline. If you have a designer that could help with this that would be awesome!

**Comment by jthake** [comment]
OK great that makes sense.

I would prefer if HTML and Angular did the same thing rather than different things. How much work is that?

Also, I wanted to double check the mocha test coverage and also how ready this was for a pull request. Unfortunately right now your coverage is only 67% and it needs to be at 98% to be accepted by the core team. It looks like you may have deleted existing tests too as running the tests shows 313 passing but in master there are 586.
This may be because this fork is 13  commits behind the master branch, which I believe will be quite a hefty merge there.

Can you take a look at this?

**Comment by jasonjoh** [comment]
Well currently the Angular template doesn't insert any code when it generates an add-in, it just creates basically empty pages for read and compose. We could definitely change that, but I think that should be a separate work item. Do you agree?

I didn't delete any tests, so it must be the merges that came after my fork. I'll work on updating my fork to be more current and see what I can do. How do I check my coverage percentage?

**Comment by jthake** [comment]
Yes, ok I agree that's a separate issue to be discussed around angular template being bare bones and html not being.

As for tests, @andrewconnell wrote a good guide on this here https://github.com/OfficeDev/generator-office/blob/master/docs/developer-testing.md . The latest section in that doc explains that there is a code report that is more dteailed than what shows up when you run "gulp test"

**Comment by jasonjoh** [comment]
Ok, I've addressed the test coverage issues, and I'm now seeing these percentages (across the entire project):

    Statements   : 98.75% ( 1029/1042 ), 34 ignored
    Branches     : 96.23% ( 408/424 ), 78 ignored
    Functions    : 99.24% ( 131/132 ), 10 ignored
    Lines        : 98.75% ( 1029/1042 )

If you sync back from my commands branch you should get similar numbers.

**Comment by jthake** [comment]
are you just running "gulp test" and getting this in the html in coverage folder?

**Comment by jasonjoh** [comment]
Sorry for the long delay, I was off for the holidays :). To get this to work I added a new entry in my package.json in the `scripts` entry:

    "test-travis-win": "node .\\node_modules\\istanbul\\lib\\cli.js cover .\\node_modules\\mocha\\bin\\_mocha -- -v -R spec -t 100000 .\\test .\\test\\commands .\\test\\content .\\test\\mail .\\test\\taskpane"

Then I ran this command:

    npm run-script test-travis-win

**Comment by andrewconnell** [comment]
By chance did you see the resolution to https://github.com/OfficeDev/generator-office/issues/115? The script you wrote can be simplified.

**Comment by jasonjoh** [comment]
Yep, saw that over the holiday and promptly forgot about it :)

**Comment by jasonjoh** [comment]
Just wanted to clarify next steps here. Should I proceed with a PR, or do you guys need any changes first?

**Comment by jthake** [comment]
Can you submit the PR if all the tests pass and coverage is complete. I believe it was failing before and was low so wouldn't be accepted.

**Comment by jasonjoh** [comment]
Submitted!
