### ISSUE TITLE
found 1 high severity vulnerability error - copy-webpack-plugin@6.0.3

### ISSUE THREAD

**Issue by FelixBoscoJ** [OfficeDev/generator-office#553]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

vulnerability count should be 0

# Current behavior

Please provide information about the failure. What is the current behavior? If it is not a bug, please add it to [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/164751-office-developer-tools), so that it gets added to our feature roadmap.
![image](https://user-images.githubusercontent.com/38680932/91049404-c7a21000-e63a-11ea-9412-c4a99aa88d07.png)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
Type below commands in cmd.
1. yo office --projectType taskpane --name "sample" --host excel --js true --skip-install
2. cd sample
3. npm audit

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* Node version: v12.18.3 64 bit
* Office version: Office online
* Tool version: 

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.
![image](https://user-images.githubusercontent.com/38680932/91049715-38e1c300-e63b-11ea-97c7-531212c2f97b.png)

## My fix
1. Change from "copy-webpack-plugin": "^6.0.3", to "copy-webpack-plugin": "^5.1.1", in package.json
2. 
![image](https://user-images.githubusercontent.com/38680932/91050574-798e0c00-e63c-11ea-9012-6661a3a7b911.png)

**Comment by TCourtneyOwen** [comment]
@FelixBoscoJ Thanks for opening this issue. I will make the fix today and include you in the PR assuming your proposed change addresses the issue.

-Courtney

**Comment by TCourtneyOwen** [comment]
Fixed and publishing out new version of generator-office today
