### ISSUE TITLE
Server gets stuck when running npm start

### ISSUE THREAD

**Issue by Grifo89** [OfficeDev/generator-office#558]
I'm following this tutorial https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator and when I'm gonna run `npm start` to test the app the server gets stuck.  

![image](https://user-images.githubusercontent.com/9584549/93812194-e33b0f00-fc16-11ea-8926-1c5e0bd5e84b.png)

**Comment by igor-ribeiiro** [comment]
@Grifo89 I just tried and followed the tutorial and it is working for me. Could you please try again?
If it still doesn't work, could you try Allowing localhost loopback?

**Comment by millerds** [comment]
You have to allow the localhost loopback in order for it to work.  Admittedly the experience here doesn't help you understand that.

Please re open if you feel something really should be changed here.
