### ISSUE TITLE
Issue with Microsoft Graph authentication when service add-in from AWS S3 as web server

### ISSUE THREAD

**Issue by arozwalak** [OfficeDev/generator-office#561]
I'm working on add-in for Outlook using SSO

When I run add-in project locally (using `npm start`) authentication with Microsoft Graph works fine and I can retrieve user details.
Problem occurs once I deploy add-in to AWS S3 bucket behind proxy_pass from Nginx Server as web-server. what I found is http request to `/auth` is returning 404 as it's trying to find it as file on S3 bucket rather than a auth request to MS Graph.

The idea behind that is that within add-in I'll have to make a call to my web application to retrieve some data and it's require same domain, so both Outlook add-in and my web app will be served from same domain managed by Nginx Server as proxy server

Is there any specific configuration for serving add-in from S3 bucket?

**Comment by millerds** [comment]
The configuration for authentication is going very widely for different add-ins.  The template generated here is just a sample case to provide an idea of it working.  Unfortunately we can't provide instructions for all the different forms that auth will take.
