### ISSUE TITLE
How to properly serve outlook add-on for production? (actual app, not manifest file)

### ISSUE THREAD

**Issue by arozwalak** [OfficeDev/generator-office#562]
I was digging through microsoft's documentation and found nothing about serving outlook add-on for production.
I found few options to serve manifest file, but nothing about how to actually serve addon files. I'm trying to use S3 bucket behind nginx proxy server but I have issue with `/auth` call to authenticate user. The call is working fine when serving locally using `npm start` for dev version, so my question is how to serve it properly for production environment? Do I have to run it as node server or simple static web server is enough?

**Comment by TCourtneyOwen** [comment]
@ElizabethSamuel-MSFT @AlexJerabek @Rick-Kirkham Do we have documentation describing best practices for deploying an add-in to Production?

Thanks,

Courtney

**Comment by ElizabethSamuel-MSFT** [comment]
@arozwalak Take a look at the deploy/publish options available.
[Deploy and publish Office Add-ins](https://docs.microsoft.com/office/dev/add-ins/publish/publish)

Thanks.

**Comment by TCourtneyOwen** [comment]
@arozwalak Also you might want to check this documentation:  https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish-add-in-vs-code
