### ISSUE TITLE
`npm run start:web` and `npm start` only show folder structure in browser

### ISSUE THREAD

**Issue by jaunruh** [OfficeDev/generator-office#565]
When following the setup process on macOS running the add-in in the webbrowser doesnt work instead the folder structure is served. Navigating to to `src/taskpane/taskpane.html` tells me I should sideload the plugin. Sideloading works as expected if `npm start` is used.

![image](https://user-images.githubusercontent.com/15611432/99068045-144b1680-25ac-11eb-9316-c6f411845d8d.png)

# Expected behavior

The taskpane should be shown in the browser

## Steps to Reproduce
- `npm install -g yo generator-office`
- `yo office` -> tested for plain/javascript and angular/typescript
- `npm install` -> was required in all cases because `gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp` was given when only running `yo office`
- `npm start` or `npm run start:web`

## Context
Tested only on macOS but with two different machines and two different setups:

* Operating System: macOS
* Node version: v12.13.1 | v12.18.2
* Office version: Word 16.43 in both cases
* Tool version: 3.1.1 in both cases

**Comment by TCourtneyOwen** [comment]
@jaunruh Thanks for reporting this issue. I will try and repro the behavior today and let you know what I find.

-Courtney

**Comment by TCourtneyOwen** [comment]
@jaunruh Did you register the add-in in the appropriate Office Online client. You will need to do that in order for the add-in to work in the browser.  Please follow these steps to register the add-in in Office Online:  https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing#:~:text=Open%20Office%20on%20the%20web.%20In%20Get%20started,Manage%20My%20Add-ins%2C%20and%20then%20Upload%20My%20Add-in.

**Comment by jaunruh** [comment]
I am referring to viewing the add-in directly in the browser.

I am refering to [this](https://github.com/OfficeDev/generator-office/raw/master/src/docs/assets/browsersync.gif) this gif from your own `readme.md`. It should be possible to view and debug the plugin (without opening it in Office desktop or web). I don't want to sideload the add-in in Office web. I only want to open the Angular App in the browser.

**Comment by akrantz** [comment]
This is the expected behavior.

After you do `npm start` and the dev-server is running, you can navigate to `https://localhost:3000/taskpane.html` and it will show the add-in. 

If you view other things, it will be served up from the webpack dev server running, so you can see files, etc. This is standard behavior for webpack-dev-server.
