### ISSUE TITLE
install + generator-office@1.7.6 with WARNs

### ISSUE THREAD

**Issue by puentesdiaz** [OfficeDev/generator-office#566]
I run 
C:\Users\sandbox> npm install -g generator-office

so i get these:
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
+ generator-office@1.7.6
updated 1 package in 9.785s

is it ok? or i will hace problems?

**Comment by akrantz** [comment]
It's OK.

**Comment by puentesdiaz** [comment]
tks

**Comment by puentesdiaz** [comment]
> It's OK.

thanks
