### ISSUE TITLE
Unable to install CA cert for local development on Windows 10 with VSCode

### ISSUE THREAD

**Issue by Nate53085** [OfficeDev/generator-office#569]
# Expected behavior

Developer documentation https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator works as expected

# Current behavior

When running the dev server OR when trying to manually install the dev CA cert, I get the following:

The developer certificates have been generated in C:\Users\Nathan\.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
Error: Unable to install the CA certificate.

The larger output when running the dev server (vs directly installing the CA cert) is:

C:\Users\Nathan\source\ask\Ask>npm run dev-server

> office-addin-taskpane-js@0.0.1 dev-server C:\Users\Nathan\source\ask\Ask
> webpack-dev-server --mode development

The developer certificates have been generated in C:\Users\Nathan\.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
office-addin-dev-certs: Unable to install the CA certificate.
    at install.js:65:19
    at Generator.next (<anonymous>)
    at install.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (install.js:5:12)
    at installCaCertificate (install.js:54:12)
    at Object.<anonymous> (install.js:42:23)
    at Generator.next (<anonymous>)
    at fulfilled (install.js:6:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! office-addin-taskpane-js@0.0.1 dev-server: `webpack-dev-server --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the office-addin-taskpane-js@0.0.1 dev-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nathan\AppData\Roaming\npm-cache\_logs\2020-11-20T18_35_11_934Z-debug.log

## Steps to Reproduce

Smallest repro I could do is:

1. npm install -g yo generator-office
2. yo office
3. Select outlook as the project
4. npm run dev-server OR npx office-addin-dev-certs install

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10

* Node version: v10.15.0

* Office version: Version 2010 Build 13328.20356 Click to Run

* Tool version: npx office-addin-dev-certs -V resulted in (version not available)
Package.json:

    "office-addin-cli": "^1.0.16",
    "office-addin-debugging": "^3.0.39",
    "office-addin-dev-certs": "^1.5.9",
    "office-addin-lint": "^1.0.29",
    "office-addin-manifest": "1.5.7",
    "office-addin-prettier-config": "^1.0.12",

## Failure Logs

[2020-11-20T18_14_43_050Z-debug.log](https://github.com/OfficeDev/generator-office/files/5575467/2020-11-20T18_14_43_050Z-debug.log)

**Comment by TCourtneyOwen** [comment]
@Nate53085 Are the developer certs in fact created at C:\Users\Nathan.office-addin-dev-certs? Do you see them in that path?

Can you also please try the following, independent of starting the dev-server:  run "npx office-addin-dev-certs install". If this also fails then we can rule out that it's an issue with the Yo Office project template

Thanks,

Courtney

**Comment by Nate53085** [comment]
npx office-addin-dev-certs install does fail with the following:

The developer certificates have been generated in C:\Users\Nathan\.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
Error: Unable to install the CA certificate.

As for the certs, they do look to be created:

11/20/2020  01:59 PM    <DIR>          .
11/20/2020  01:59 PM    <DIR>          ..
11/20/2020  01:59 PM             1,402 ca.crt
11/20/2020  01:59 PM             1,298 localhost.crt
11/20/2020  01:59 PM             1,706 localhost.key
               3 File(s)          4,406 bytes
               2 Dir(s)  126,750,793,728 bytes free

I also deleted them, to see if I could regenerate and it failed with the same error

**Comment by TCourtneyOwen** [comment]
Are you an admin on this machine? If so, can you please try the following:
npx office-addin-dev-certs install --machine

**Comment by Nate53085** [comment]
Unclear from instructions if I should run this from an admin terminal so I attempted both:

Non-admin:

C:\Users\Nathan>npx office-addin-dev-certs install --machine
npx: installed 29 in 3.993s
The developer certificates have been generated in C:\Users\Nathan\.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
Error: Unable to install the CA certificate.

Admin:

C:\WINDOWS\system32>npx office-addin-dev-certs install --machine
npx: installed 29 in 3.879s
The developer certificates have been generated in C:\Users\Nathan\.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
Error: Unable to install the CA certificate.

**Comment by TCourtneyOwen** [comment]
I am noticing your path is C:\Users\Nathan.office-addin-dev-certs.  It seem that it should be C:\Users\Nathan\.office-addin-dev-certs ("\" between Nathan and .office-addin-dev-certs).  
 
Here's what my path looks like: c:\Users\cowen\.office-addin-dev-certs

So I am guessing the problem has something to do with the install path being incorrectly constructed

**Comment by TCourtneyOwen** [comment]
However my comment above might just be related to GitHub erroneously stripping out that "\" I noticed my comment above also has that stripped out

**Comment by Nate53085** [comment]
Thats right, my path does have a slash between Nathan and .office, Github isn't rendering it (probably rendering it as an escape character)

**Comment by akrantz** [comment]
You don't need to be admin. I suspect there is a path issue or a problem being able to create the .office-addin-dev-certs folder in the %USERPROFILE% directory.

**Comment by TCourtneyOwen** [comment]
The code is failing here:

export async function installCaCertificate(caCertificatePath: string = defaults.caCertificatePath, machine: boolean = false) {
   const command = getInstallCommand(caCertificatePath, machine);

   try {
      console.log(`Installing CA certificate "Developer CA for Microsoft Office Add-ins"...`);
      // If the certificate is already installed by another instance skip it.
      if (!isCaCertificateInstalled()) {
         execSync(command, {stdio : "pipe" });
      }
      console.log(`You now have trusted access to https://localhost.\nCertificate: ${defaults.localhostCertificatePath}\nKey: ${defaults.localhostKeyPath}`);
   } catch (error) {
      throw new Error(`Unable to install the CA certificate. ${error.stderr.toString()}`);
   }
}

Effectively all getInstallCommand does it get a command to run a PowerShell script which is then executed via exexsync.  I wonder what would happen if you open PowerShell ISE, copy and pasted the following and executed the script?  Perhaps you might be missing a particular PowerShell module and this might help us detect the problem

$machine = "CurrentUser"
$caCertificatePath= "C:\Users\Nathan\.office-addin-dev-certs\ca.crt"
if(Get-Command -name Import-Certificate -ErrorAction SilentlyContinue){
    Import-Certificate -CertStoreLocation cert:\\$machine\\Root ${caCertificatePath}
}
else{
    # Legacy system support
    $pfx = new-object System.Security.Cryptography.X509Certificates.X509Certificate2
    $pfx.import($caCertificatePath)

    $store = new-object System.Security.Cryptography.X509Certificates.X509Store("Root", $machine)
    $store.open("MaxAllowed")
    $store.add($pfx)
    $store.close()
}

**Comment by akrantz** [comment]
Actually, it looks like it is creating the files OK, but then unable to install it. Do you get a dialog popup asking for permission to install them?

![image](https://user-images.githubusercontent.com/741153/99845069-e7a57a80-2b28-11eb-8492-02575d409e7f.png)

As Courtney has pointed out, it runs a PowerShell script to do the cert installation. Perhaps you don't have permissions or it is failing for some reason.

**Comment by Nate53085** [comment]
I do not get that popup. If it matters, this is a personal computer not a company managed device

**Comment by Nate53085** [comment]
I could attempt to install the generated cert manually: https://support.securly.com/hc/en-us/articles/360026808753-How-to-manually-install-the-Securly-SSL-certificate-on-Windows

**Comment by akrantz** [comment]
It would help to narrow down the error. Could you open a PowerShell prompt and execute: `Get-Command -name Import-Certificate`. 

If that succeeds, e.g. the command is available, then try: `Import-Certificate -CertStoreLocation cert:\$machine\Root ${caCertificatePath}`  where caCertificatePath is the path to the `ca.crt` file.

**Comment by Nate53085** [comment]
Well.. thats likely the issue

Powershell is refusing to open, either opening a powershell command prompt or opening powershell in a cmd terminal fail silently.

Currently investigating

**Comment by Nate53085** [comment]
Refreshing windows to repair powershell fixed the issue. I am now able to install the certificates. Thanks for all your help.

**Comment by TCourtneyOwen** [comment]
That's great to hear @Nate53085.  Thanks for letting us know!

-Courtney
