### ISSUE TITLE
HighResolutionIconUrl has to be https not caught by validate-xml

### ISSUE THREAD

**Issue by jthake** [OfficeDev/generator-office#57]
The new validate-xml feature does not catch the error that HighResolutionIconUrl  has to be https

<span class="_opc_2" tabindex="0">This app can't be installed. The value of the HighResolutionIconUrl attribute, 'http://dev.office.com', contains an unsupported URL. You can only use https:// URLs..</span>

**Comment by andrewconnell** [comment]
hey @waldekmastykarz you want to look into this since you added the functionality?

**Comment by waldekmastykarz** [comment]
Sure! Would a simple string comparison do?
