### ISSUE TITLE
Manifest file name based on project name

### ISSUE THREAD

**Issue by jthake** [OfficeDev/generator-office#58]
Rather than call every manifest "manifest.xml" actually create file name as "<project-name>-manifest.xml". Makes it useful when having a shared network folder for a Trusted add-in catalog on a local machine when testing in Office Windows client.

**Comment by andrewconnell** [comment]
You saying to literally call it `-manifest.xml`... simply prefix with a hyphen?

So when you reference a shared folder on the network for the Trusted Add-in Catalog, you can't name them `manifest.xml`?

**Comment by jthake** [comment]
If you have two manifest files in your Trusted Add-in Catalog (local shared folder) you can't obviously have them with teh same file name in your local drive.

yep...I think its nice to have -manifest on there just so its obvious what the file is and not just an xml file.

**Comment by andrewconnell** [comment]
Would it be better to default to the same name as the project name you gave it? We could use the same logic we use to create the name in the `package.json` or `bower.json` file so it's all lowercase & spaces are replaced with hyphens

**Comment by jthake** [comment]
oh yes....sorry maybe I wasn't clear on that. Yes we use the proejct name that was asked as first question for the prefix to file name.

**Comment by waldekmastykarz** [comment]
I would suggest using the project name as a suffix, ie. `manifest-my-addin.xml`. That way it would be easier to find the manifest file between all the other project files.

**Comment by andrewconnell** [comment]
@jthake ... thoughts? This is easy to implement...

**Comment by jthake** [comment]
yes i see what you mean around having manifest first then the project name. good idea. Ship It1

**Comment by waldekmastykarz** [comment]
When building this should we take into account the manifest name set by default in the `validate-xml` gulp task? By default it uses `manifest.xml` which initially made it easy to validate the manifest by simply calling `$ gulp validate-xml`. With this change the developer would either need to pass the manifest file name every time to the task or we would need to change the default manifest file in `gulpfile.js`. What do you think?

**Comment by andrewconnell** [comment]
@waldekmastykarz good point... I'll tweak the validation to look for `manifest-*.xml`

**Comment by waldekmastykarz** [comment]
One more place where we will need to include this are tests which currently also refer to `manifest.xml`.
