### ISSUE TITLE
Custom ui less - functions not working on react

### ISSUE THREAD

**Issue by maniteja** [OfficeDev/generator-office#589]
Hi,

Custom ui less functions are not working .

1.Added function in function-file 
2.changed the manifest

still facing the same issue can any one help on providing sample code

**Comment by TCourtneyOwen** [comment]
@maniteja You may want to check out Add-in Commands Samples repo at:  https://github.com/OfficeDev/Office-Add-in-Commands-Samples/.  The important thing to remember is that you will have to make an update to your manifest to define a function name that maps to the command method you define in your source code.  For example:

                  <Action xsi:type="ExecuteFunction">
                    
                    **<FunctionName>ODSampleData.ODataUX.getButton</FunctionName>**
                  </Action>

Hope this helps,

Courtney
