### ISSUE TITLE
Manifeste validation do not alert what Outlook for web add-in installation will throw

### ISSUE THREAD

**Issue by dimitri-bourreau** [OfficeDev/generator-office#591]
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

`npm run validate` would alert if the manifest could not be installed on Outlook for web.

# Current behavior

`npm run validate` do not throw the error specified by Outlook for web when refusing the installation of the manifeste.

`npm run validate` throws two errors about images, [an issue is already open about this](https://github.com/OfficeDev/generator-office/issues/590).

Outlook refuses the installation throwing:

> La section VersionOverrides 1.0 du manifeste n’est pas valide. La balise resid n’est pas valide.

Which would translate:

> The VersionOverrides 1.0 section of the manifest is invalid. The resid is not valid.

And this error didn't help me has actually I only needed to add this to my manifest:

```xml
          <Runtimes>
            <Runtime resid="WebViewRuntime.Url">
              <Override type="javascript" resid="JSRuntime.Url"/>
            </Runtime>
          </Runtimes>
```

This snippet wasn't included by Yeoman at generation.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `yo office` and generate an Outlook add-in with SSO and JavaScript.
2. Add event-based action such as:

```javascript
            <ExtensionPoint xsi:type="LaunchEvent">
              <LaunchEvents>
                <LaunchEvent 
                  Type="OnNewMessageCompose" 
                  FunctionName="reactToNewMessage"
                />
              </LaunchEvents>
              <SourceLocation resid="WebViewRuntime.Url"/>
            </ExtensionPoint>
```

I'm not sure this is enough. Though, I checked twice the Current behavior section.

## Context

* Operating System: Windows 10
* Node version: 14.15.1

**Comment by igor-ribeiiro** [comment]
Hey @dimitri-bourreau what kind of setup are you using currently on yo-office?
I just created a fresh project using the following:
```
? Choose a project type: Office Add-in Task Pane project supporting single sign-on
? Choose a script type: JavaScript
? What do you want to name your add-in? sso2
? Which Office client application would you like to support? Outlook
```

And I'm not getting this VersionOverride error.
I'm getting a lot of errors normally in the `npm run validate` step, which most seem related to the images in the manifest. Did you work around them? I feel the template might be outdated and not working right now because of these errors.

**Comment by igor-ribeiiro** [comment]
I Will be closing this issue as I didn't get any response

**Comment by dimitri-bourreau** [comment]
@igor-ribeiiro I'm so sorry I've totally forgot about this issue!

If I find this error again I'll share my setup and a demo repo.
Thanks for trying to help me and sorry again! 🙏
