### ISSUE TITLE
Node 15.7.0 `yo office` results in generator-office does not support your version of Node. Please switch to the latest LTS version of Node. 

### ISSUE THREAD

**Issue by emmett-miller** [OfficeDev/generator-office#598]
# Prerequisites

+ yo@3.1.1
+ generator-office@1.7.8
+ node --version v15.7.0

Windows 10

yo office --projectType angular --name "test" --host excel --ts true

generator-office does not support your version of Node. Please switch to the latest LTS version of Node.

**Comment by Appsenal** [comment]
I encountered same issue as well. I am using node-v14.15.4.

**Comment by akrantz** [comment]
Node v14 is the current LTS version. 

Node v15 is not supported. This is the active development version. We encountered enough problems that would arise from Node itself that we put this check in.

I would suggest using [Node Version Switcher](https://github.com/jasongin/nvs) on Windows, to be able to switch between different Node versions.

**Comment by TCourtneyOwen** [comment]
@emmett-miller  Node 15 not working is be design as we only support the latest **LTS** versions:

    if (parseInt(process.version.slice(1, process.version.indexOf('.'))) % 2 == 1) {
      console.log(yosay('generator-office does not support your version of Node. Please switch to the latest LTS version of Node.'));
      this._exitProcess();
    }

You could potentially comment out this code in your local instance of generator-office, but we will support any issues that might surface with this currently unsupported version of Node

@Appsenal I just tried 14.15.4 using Node Version Switcher and it works fine for me.


-Courtney

**Comment by Appsenal** [comment]
@TCourtneyOwen Thanks! It is working in my end now. I switched the version.

**Comment by emmett-miller** [comment]
Thank you @TCourtneyOwen / @Appsenal 14.15.4 works
