### ISSUE TITLE
Angular directive from Angular CommonModule not loaded correctly after building the App

### ISSUE THREAD

**Issue by AlexanderFinkbeiner** [OfficeDev/generator-office#600]
# Current behavior

I'm using the **yo office angular template with typescript for excel**. 
And want to use directives from the Angular **CommonModule**. 
For example a simple *ngIf. I added the Module to the AppModule
![image](https://user-images.githubusercontent.com/22540563/106866474-c9cdc780-66cc-11eb-9be9-871d63959f8f.png)
 and using the directive in my AppComponent Template.:
![image](https://user-images.githubusercontent.com/22540563/106866751-203b0600-66cd-11eb-9f11-2a8a6106cbe5.png)

**During development while using the webpack devserver with `npm run start` erverything works fine and all angular drectives are working.** 

But when I build the app with `npm run build` and run the app from the `dist `folder with 
`http-server dist/ -S -C ../.office-addin-dev-certs/localhost.crt -o -K ../.office-addin-dev-certs/localhost.key`
or deploying it to azure static web app
it showing the follwing error: 
![image](https://user-images.githubusercontent.com/22540563/106866156-6a6fb780-66cc-11eb-9d69-52b7b8894174.png)

Why is my app working with npm run start  but not when i build and deploy it? Is this a bug or do I miss something? 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create yo office app with angular and typescript for excel
2. add CommonModule to the AppModule as shown in image 1
3. Use a directive in a app template as shown in image 2
4. change to prodUrl in the `webpack.config.js` to the path where you want to host it. If you are using the local `http-server` set the url to `const urlProd="https://127.0.0.1:8080/";`
5. build the app with `npm run build`
6. run the app locally from from the `dist` folder with `http-server dist/ -S -C ../.office-addin-dev-certs/localhost.crt -o -K ../.office-addin-dev-certs/localhost.key`  or deploy it to a webserver
7. open excel with your browser and sideload the manifest from `dist/manifest.prod.xml`
8. you will find the error from image 3

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Win 10 
* Node version: 12.4.0
* Office version: 2019
* Tool version: yo version 3.1.1

**Comment by fdb-development** [comment]
+1

**Comment by AlexanderFinkbeiner** [comment]
As workaround, I stopped using yo generator. I generated an angular 11 app and modified it as described in this blog post: 
[https://ragavanrajan.medium.com/building-office-add-in-using-angular-8-209624ba61ed](https://ragavanrajan.medium.com/building-office-add-in-using-angular-8-209624ba61ed)
Then everthing is much cleaner and works perfect.

**Comment by igor-ribeiiro** [comment]
This doesn't seem like a problem with Angular CommonModule but actually the same issues as: https://github.com/OfficeDev/generator-office/issues/450
I will be closing this one as it appears to be the same prroblem.
