### ISSUE TITLE
Minor update to User Instructions

### ISSUE THREAD

**Issue by VashJuan** [OfficeDev/generator-office#606]
# Expected behavior

cd to a directory with spaces in it requires quotes around the directory name!

# Current behavior

Once having built 
 Congratulations! Your add-in has been created! Your next steps:

      1. Go the directory where your project was created:

         **cd D:\Projects\MSOffice Addins\JohnsExcelAddin**

      2. Start the local web server and sideload the add-in(https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/164751-office-developer-tools), so that it gets added to our feature roadmap.

## Steps to Reproduce

Go through:
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator

## Context

This is on Win10 Pro with latest everything. 

## Failure Logs

PS D:\Projects\MSOffice Addins> cd D:\Projects\MSOffice Addins\JohnsExcelAddin

NOTE: THE ABOVE LINE NEEDS QUOTES AROUND THE DIRECTORY NAME. BEGINNERS MAY NOT GET THIS!

Set-Location: A positional parameter cannot be found that accepts argument 'Addins\JohnsExcelAddin'.
PS D:\Projects\MSOffice Addins> cd "D:\Projects\MSOffice Addins\JohnsExcelAddin"
PS D:\Projects\MSOffice Addins\JohnsExcelAddin> npm start

**Comment by millerds** [comment]
Should be fixed now.
