### ISSUE TITLE
Created word addin fails to load with 'Cannot find module 'html'' error when https://localhost:3000 is launched

### ISSUE THREAD

**Issue by kotpal** [OfficeDev/generator-office#607]
# Expected behavior
Browsing https://localhost:3000 should show the taskpane.

Please describe the behavior you were expecting

# Current behavior
Instead it shows:
Error: Cannot find module 'html'
Require stack:
- C:\word-addin\First AddIn\node_modules\express\lib\view.js
- C:\word-addin\First AddIn\node_modules\express\lib\application.js
- C:\word-addin\First AddIn\node_modules\express\lib\express.js
- C:\word-addin\First AddIn\node_modules\express\index.js
- C:\word-addin\First AddIn\node_modules\office-addin-sso\lib\app.js
- C:\word-addin\First AddIn\node_modules\office-addin-sso\lib\server.js
- C:\word-addin\First AddIn\node_modules\office-addin-sso\lib\commands.js
- C:\word-addin\First AddIn\node_modules\office-addin-sso\lib\cli.js
- C:\word-addin\First AddIn\node_modules\office-addin-sso\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.patchedRequire [as require] (C:\xrc\legal-365\word-addin\First AddIn\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:88:18)
    at new View (C:\xrc\legal-365\word-addin\First AddIn\node_modules\express\lib\view.js:81:14)
    at Function.render (C:\xrc\legal-365\word-addin\First AddIn\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (C:\xrc\legal-365\word-addin\First AddIn\node_modules\express\lib\response.js:1012:7)
    at C:\xrc\legal-365\word-addin\First AddIn\node_modules\office-addin-sso\lib\app.js:59:21
    at Layer.handle [as handle_request] (C:\xrc\legal-365\word-addin\First AddIn\node_modules\express\lib\router\layer.js:95:5)

Please provide information about the failure. What is the current behavior? If it is not a bug, please add it to [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/164751-office-developer-tools), so that it gets added to our feature roadmap.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
1. yo office --projectType single-sign-on --name "First AddIn" --host word --ts true
2. cd "First AddIn"
3. npm run configure-sso
4. npm start

**Comment by TCourtneyOwen** [comment]
@kotpal I just published out a new version of the SSO template a few minutes ago.  I just tried running "yo office --projectType single-sign-on --name "First AddIn" --host word --ts true" and the generated add-in works fine for me

Also, if you continue to run into problems, can you please let me know which version of NodeJs you are running? The SSO add-in works for me with both Node v.14.15.4 and v12.16.1

Thanks,

Courtney

**Comment by kotpal** [comment]
I have Node v14.15.5 installed (latest LTS I installed today). 

The development experience so far has been quite frustrating. I have used VS Code and so far nothing is working. I am trying to build a Word Add-In using Visual Studio 2019.

**Comment by TCourtneyOwen** [comment]
@kotpal and I just spoke and he is now unblocked so closing this issue

**Comment by Chris2011** [comment]
So what is the solution here? I have the same problem. I use Node 14.16.0 and npm 7.5.2. When I call localhost:3000 I just got the same problem. And the plugin is not installed into outlook. I also tried another template from the yo office, the first one with taskpane and it will be installed via outlook online.

Please let me know, if you need more information @TCourtneyOwen

**Comment by 756890911** [comment]
I have the same problem. I use Node v18.3.0 and npm 8.11.0. When I call localhost:8080 I just got the same problem. And the plugin is not installed into Excel. I tried the template for single sign on and javascript.
