### ISSUE TITLE
npm start not working 

### ISSUE THREAD

**Issue by tluth** [OfficeDev/generator-office#617]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior
npm start runs the dev server, opens Excel and the add-in is side-loaded. 

# Current behavior
Nothing happens. 

## Steps to Reproduce
1.  npm start 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: windows10
* Node version: v15.11.0
* Office version: microsoft 365 apps for enterprise [version 2008 (build 13127.21216)]
* Tool version: latest

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.
```
$ npm start

> office-addin-taskpane-react-js@0.0.1 start
> office-addin-debugging start manifest-local.xml

Debugging is being started...
App type: desktop
Enabled debugging for add-in 
                416cdfda-3fb3-4884-a0ce-a4ded1c66797
        . Debug method: 0
Sideloading the Office Add-in...
Error: Unable to start debugging.
office-addin-debugging: Unable to sideload the Office Add-in.
office-addin-dev-settings: ENOENT: no such file or directory, open 'C:\Users\THOMAS~1.LUT\AppData\Local\Temp\Excel add-in
                416cdfda-3fb3-4884-a0ce-a4ded1c66797
        .xlsx'
```

**Comment by akrantz** [comment]
Does you manifest have newline characters in the  `<Id>{guid}</Id>`  field?

**Comment by tluth** [comment]
@akrantz ...yeah I did 😞 

I guess something changed in my autoformat settings since I last opened it which was some time ago 

Thanks for your help, and sorry for the dumb question
