### ISSUE TITLE
Add-ins created with this generator get rejected at submission process (Reason: Predictable Behavior)

### ISSUE THREAD

**Issue by alinnert** [OfficeDev/generator-office#619]
# Prerequisites

- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

An add-in created using this generator should in principle be able to be submitted to the Office Store. (Unless, of course, something is wrong, which is the developer's fault)

# Current behavior

Our add-in gets rejected when we try to submit it to the Office Store because it doesn't meet [certification policy 1100.4 Predictable Behavior](https://docs.microsoft.com/en-us/legal/marketplace/certification-policies#11004-predictable-behavior). The exact reason in the certification report is attached below (Certification Report). The screenshots explicitly show the "My Add-Ins" dropdown and that the add-in is not listed there.

Now, I've tried to create a completely blank project with the current version of the generator to make sure I haven't messed anything up:

~~~
npx -p yo -p generator-office yo office
~~~

Settings: React, TypeScript, Word

When I sideload this blank project I already can reproduce the behavior mentioned in the Certification Report. I can sideload the add-in but it's not listed under "Recently Used Add-ins" under "My Add-ins".

I should also add that:

- There is already a [question on StackOverflow](https://stackoverflow.com/questions/65571476/microsoft-word-add-in-failing-submission-compatibility-issue-with-desktop-versi) about this issue, opened two months ago, which has no answers or comments.
- I've also contacted the support team behind the certification process for any help on this. But they say they "cannot assist with resolving technical issues for add-ins".
- I struggle to find any information about this menu in any documentation.

*(which makes opening this issue already a kind of last resort move for me. I don't know what else I could do to make my add-in pass certification.)*

If it is really true, that the add-in should be listed in this dropdown, then I think something is missing or wrong with the code that's being generated by this generator since it doesn't work from the very beginning. Can you say anything about this? Any help is very welcome.

## Steps to Reproduce

- Create a new project using this generator
    - Settings: React, TypeScript, Word
- Sideload the app without any changes in Word for Desktop (Windows or Mac)
- Go to (in the ribbon menu) "Insert" > "My Add-Ins" (Open dropdown)
- The add-in should be loaded successfully, but that dropdown is still empty (or at least this add-in is not listed there)

## Context

* Operating System: I'm using **Windows 10**. The issue mentions **Windows 10** and **macOS**
* Node version: I'm using **Node 14.15.5**.
* Office version: I'm using **Word for Microsoft 365 MSO (16.0.13801.20288)**
* Tool version: I've created a new add-in yesterday (2021-03-17) through `npx` - i.e. latest version at that day (generator `1.7.9`) (see above)

### Certification Report

![rejection report](https://user-images.githubusercontent.com/2638971/111466370-7d41c700-8723-11eb-9cc0-4dd96ccd468c.png)

**Comment by millerds** [comment]
Closing due to age . . . if there is still a problem with this please open a new issue with fresh experience.
