### ISSUE TITLE
Taskpane fail to show after npm start

### ISSUE THREAD

**Issue by mchlui** [OfficeDev/generator-office#620]
**I have created a add-in project using the following command** 
yo office --projectType react --name "CBOT AddIn v3" --host word

**After the the add in created, i try to start the project as follow:**
D:\CBOT AddIn v3>npm run start

> office-addin-taskpane-react-js@0.0.1 start
> office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
Enabled debugging for add-in a3eb150e-2ae4-4c80-8615-6aa882ec105d. Debug method: 0
Sideloading the Office Add-in...
Debugging started.

**Then the word application started, when I try to open the taskpane, the following error show:**
This app could not be started. Close this dialog to ignore the problem or click "Restart" to try again.
![image](https://user-images.githubusercontent.com/13774778/111479365-dc2b2e80-876b-11eb-9685-c34c3e2e9de0.png)

**Comment by akrantz** [comment]
With NPM v7, it will not automatically start the dev server. This is because NPM v7 changed how env vars are defined during npm run. In the meantime, you should run the dev server yourself first. You can do this using "npm run dev-server". (On Windows, to have this open as a separate window use: "start npm run dev-server".)  If you're using Visual Studio Code, you can use Terminal, Run Task, Dev Server to run the dev server inside VS Code.

**Comment by Chris2011** [comment]
I also have a similar issue with NPM 7.5.* when I use npm start, it shows me "Debugging started" at the end, but after couple of seconds, I got my CMD line back `C:\Projects\`. When I use "npm run dev-server" The add-in is only available at office.com not in my installed outlook app. Is this the problem that you mentioned?

**Comment by mchlui** [comment]
> I also have a similar issue with NPM 7.5.* when I use npm start, it shows me "Debugging started" at the end, but after couple of seconds, I got my CMD line back `C:\Projects\` I mean it stops. When I use "npm run dev-server" the add-in is only available at office.com not in my installed outlook app. Is this the problem that you mentioned?

I have same behaviour as you, any idea?

**Comment by svickers** [comment]
> I also have a similar issue with NPM 7.5.* when I use npm start, it shows me "Debugging started" at the end, but after couple of seconds, I got my CMD line back `C:\Projects\` I mean it stops. When I use "npm run dev-server" the add-in is only available at office.com not in my installed outlook app. Is this the problem that you mentioned?

Same exact problem for me.  Have tried all different project types with the same results. Able to run the VisualStudio add-in project samples fine but would rather use React.

**Comment by akrantz** [comment]
@svickers Please just start the dev-server using "npm run dev-server" before using "npm start".

**Comment by mchlui** [comment]
> @svickers Please just start the dev-server using "npm run dev-server" before using "npm start".

Thanks for you reply, it works for me!

**Comment by akrantz** [comment]
@mchlui Glad to hear it.

**Comment by svickers** [comment]
@akrantz Yup that works.

**Comment by millerds** [comment]
Node that this should be working with npm v7 now as well.

**Comment by SIFAR786** [comment]
i have the latest version of npm to date but still have to start the `npm run dev-server` manually from a cmd window separately and it cannot be started from visual studio code terminal window.

**Comment by millerds** [comment]
Can you provide the terminal output when you run the npm start command?  Also, try using VSCode debugger using Word Desktop (Edge Chromium) and provide the debug console output.
