### ISSUE TITLE
Deploy Outlook Add-In.

### ISSUE THREAD

**Issue by DavidTD1** [OfficeDev/generator-office#621]
Greetings. I need guidance for deploying an outlook add-in created by Yeoman. 
I am new to this.  I already tried uploading the whole project generated by Yeoman to Heroku and according to Heroku, it deployed successfully. But I don't know what else I should do. I am confused.

**Comment by millerds** [comment]
Please see: https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish
