### ISSUE TITLE
+"generator-office does not support your version of node"

### ISSUE THREAD

**Issue by elthombre** [OfficeDev/generator-office#622]
I installed node, ran the

npm install -g yo generator-office

yada yada yada

if my version of Node is not supported, then which version is???

**Comment by elthombre** [comment]
I went here:

https://nodejs.org/download/release/latest-v14.x/

I am told during installation that the latest version of Node is already installed.

v15.12.0

**Comment by akrantz** [comment]
Please install the LTS version of Node, which is v14.  There are two choices for install on https://nodejs.org.

**Comment by elthombre** [comment]
To be clear, I need to uninstall what I have and reinstall this. Presently, when I the installer as suggested, it exits telling me the latest version is already installed.

**Comment by MatthewMarshall** [comment]
I've attached notes on the error "generator-office does not support your version of Node. The short version: in folder generators/app/index.js, the logic rejects any version of Node where the major version number is odd.  See the attached for more detail.
[Notes on Version of Node Not Supported in generator-office 2021-11-23.txt](https://github.com/OfficeDev/generator-office/files/7590083/Notes.on.Version.of.Node.Not.Supported.in.generator-office.2021-11-23.txt)

**Comment by millerds** [comment]
Per the nodejs web site (quoted below) LTS version will be even numbered and the odd versions are the currently in development versions.  Per the error message generator-office supports the LTS version and not the current in development version.

https://nodejs.org/en/about/releases/
_Major Node.js versions enter Current release status for six months, which gives library authors time to add support for them. After six months, odd-numbered releases (9, 11, etc.) become unsupported, and even-numbered releases (10, 12, etc.) move to Active LTS status and are ready for general use. LTS release status is "long-term support", which typically guarantees that critical bugs will be fixed for a total of 30 months. Production applications should only use Active LTS or Maintenance LTS releases._
