### ISSUE TITLE
'require' is not defined

### ISSUE THREAD

**Issue by zisco67** [OfficeDev/generator-office#623]
After successfully creating my first office addin I try to enhance the functionality in calling a Dynamics 365 Business Central REST API with `node-fetch` (a node.js implementation of `fetch`). Unfortunately I am stuck with this statement `const fetch = require('node-fetch');` in `taskpane.js` - my linter tells me `'require' is not defined.`
My package.json has included the necessary dependencies:
```
"node-fetch": "^2.6.1",
"require": "^2.4.20",
```
Any hints for me? Thanks in advance!

**Comment by ConyKitty** [comment]
Hello, I have this issue too, how did you fix it?

**Comment by millerds** [comment]
'reguire' is globally defined so it's not in the file . . . that plus the eslint rules saying to check for undefined variables give you this (it only checks in the file).  You can make this go away by adding /* global require */ to the top of the file.
