### ISSUE TITLE
Generated TaskPane Add-in does not allow to switch to latest WebView options

### ISSUE THREAD

**Issue by aafvstam** [OfficeDev/generator-office#624]
# Expected behavior
Running command:
npx office-addin-dev-settings webview .\manifest.xml edgelegacy

This should switch to EdgeHTML (WebViewType.Edge / WebView) according to the latest commands.tx in:
[commands.ts](https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/office-addin-dev-settings/src/commands.ts)

![image](https://user-images.githubusercontent.com/5305682/113355245-bf345500-9340-11eb-9ba1-99169f2e8550.png)

# Current behavior
Running the command to switch to WebView2 returns:
Error: Please select a valid web view type instead of 'edgelegacy'

![image](https://user-images.githubusercontent.com/5305682/113355069-7da3aa00-9340-11eb-8168-86245c65044e.png)

## Steps to Reproduce

1. Generate TaskPane Project using yo office
2. Try to set the WebView to EdgeLegacy with command:
npx office-addin-dev-settings webview .\manifest.xml edgelegacy

You get:
Error: Please select a valid web view type instead of 'edgelegacy'

## Solution

Bump **office-addin-debugging** npm package to the latest version in the Yeoman Templates

## Workaround

Manually bump **office-addin-debugging** npm package to the latest version in package.json in your project

## Workaround - Test Result

Manually bump **office-addin-debugging** npm package to the latest version in package.json in your project

![image](https://user-images.githubusercontent.com/5305682/113356333-5cdc5400-9342-11eb-8662-bf49fc5e2162.png)

Result:
![image](https://user-images.githubusercontent.com/5305682/113356381-7382ab00-9342-11eb-8fa7-50bbf6b6b6f5.png)

Proof:
Run **npm start**

Have a look at the 'security info' dialog
![image](https://user-images.githubusercontent.com/5305682/113356498-9c0aa500-9342-11eb-8d48-9b3a2a7eef56.png)

**Comment by aafvstam** [comment]
I was looking how/where to fix this. Apparently this is defined in:
https://github.com/OfficeDev/generator-office/blob/master/src/app/config/projectProperties.json

This means that all the source template projects need to be updated:
https://github.com/OfficeDev/Office-Addin-TaskPane-JS
https://github.com/OfficeDev/Office-Addin-TaskPane
https://github.com/OfficeDev/Office-Addin-TaskPane-Angular-JS
https://github.com/OfficeDev/Office-Addin-TaskPane-Angular
https://github.com/OfficeDev/Office-Addin-TaskPane-React-JS
https://github.com/OfficeDev/Office-Addin-TaskPane-React
https://github.com/OfficeDev/Office-Addin-TaskPane-SSO-JS
https://github.com/OfficeDev/Office-Addin-Taskpane-SSO
https://github.com/OfficeDev/Excel-Custom-Functions-JS
https://github.com/OfficeDev/Excel-Custom-Functions

@TCourtneyOwen @davidchesnut  I wonder, isn't there an option to get a shared base for all these items to avoid updating all the base templates used here?

**Comment by akrantz** [comment]
We're working to update the templates. In the meantime, for a project that you create using "yo office", you should be able to do "npm update --dev" to get updates for all package dependencies, or update specific packages yourself.  

But an easier workaround is to run "npx office-addin-dev-settings webview" from a different folder as this will get the latest office-addin-dev-settings package. 

There are other options you can use with npx to allow it to get the latest package.

**Comment by millerds** [comment]
The templates should be updated with good versions of the scripts packages now.
