### ISSUE TITLE
Edge Chromium Opens in External Browser Rather Than Task Pane

### ISSUE THREAD

**Issue by mickog** [OfficeDev/generator-office#625]
Hi

I hope this is the right place to create this issue, it might be more Microsoft related but maybe you can help?

When a user creates an outlook add in, with a task pane using Windows 10 version >= 1903 and Office 365 version >= 16.0.13530.20224 Then the outlook plugin by default will use Microsoft Edge, this seems to cause an issue for us, when we are using older version of windows and the plugin is using IE everything works seamlessly. When we update and Edge is default browser then when we load the plugin it exits to an external browser and brings us to a sharepoint online site (that is where we are hosting our UI). We think it might be something to do with SSO but is only happening when default browser is Edge. 

Any help would be appreciated.
Thanks

**Comment by LouMM** [comment]
@mickog Thank you for reporting this issue. We will try and route you to the Outlook Extensibility team. We want to collect some more info about your scenario. 
If you use our standard template, through Yo Office, can you load that template in Outlook fine?

**Comment by mickog** [comment]
That would be amazing if you could route me to that team! Yes if we load a standard template and use something other than Sharepoint(which requires SSO) there is no issues loading it in Outlook, only on some versions of 365 when we are using the Sharepoint site is this issue happening, we have resolved the issue for a lot of users by adding runtimes into our template which forces Outlook to use IE as its browser, but we are still experiencing the issue with some of our users who are brought to an external browser on url https://tokenprovider.termsofuse.identitygovernance.azure.com/<some-ids-in-here>/connect/authorizepage with an error message on the page
```

error:invalid_request
error_description:The mandatory ‘client_id’ parameter is missing.
```

Any help on this appreciated thanks

**Comment by millerds** [comment]
Sorry this hasn't been followed up on.  Is this still a problem?
