### ISSUE TITLE
Yoeman Office unable to get local issuer certificate

### ISSUE THREAD

**Issue by kausarp** [OfficeDev/generator-office#627]
# Prerequisites

- [X ] I am running the latest version of Node and the tools 
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

Operating System: Windows 10 Enterprise
Node version: 6.14.8
Office version: Office 2016
Tool versio: 3.1.1

Hello Office Gurus - I am trying to create Word TaskPane add-in. This is the article I am using. I am not able to create project. I am getting below error. 
![image](https://user-images.githubusercontent.com/82678124/115079131-50213980-9ec6-11eb-8652-113df9712766.png)

We have zscalar and I did whitelisted the URL http://registry.npmjs.org/   according to the Stackoverflow post https://stackoverflow.com/questions/45884752/npm-err-code-unable-to-get-issuer-cert-locally

Still I am unable to create a project.

Thanks & regards,
Kausar

Please provide information about the failure. What is the current behavior? If it is not a bug, please add it to [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/164751-office-developer-tools), so that it gets added to our feature roadmap.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* Node version:
* Office version:
* Tool version:

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by kausarp** [comment]
@LouMM what kind of more info can I provide? I provided the screenshot where the error is showing. It is happening on creation of project. project folder is empty. Which log can I provide? Could you suggest the log source/location?

**Comment by millerds** [comment]
The tool also downloads a zip file with the template content from github.  If you have to whitelist URLs you'll need to include github as well.

If there are further problems please re-open with updated information.
