### ISSUE TITLE
Extraneous app_to_debug line in config section of package.json

### ISSUE THREAD

**Issue by paul-ionicsecurity** [OfficeDev/generator-office#630]
When I use 'yo office' to generate an Office Add-In Task Pane no matter which Office App I choose, an extraneous line declaring that excel is the app to use to debug is added to the config section of package.json. This is what I see when I choose to create an Office Add-In for Word:

  "config": {
    "app_to_debug": "excel",
    "app_type_to_debug": "desktop",
    "dev_server_port": 3000,
    "app-to-debug": "word"
  },

Because of this, when you run 'npm start' you see this output:

> office-addin-taskpane-js@0.0.1 start
> office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
The dev server is already running on port 3000.
Sideloading the Office Add-in...
Error: Unable to start debugging.
office-addin-debugging: Unable to sideload the Office Add-in. 
office-addin-dev-settings: The Office Add-in manifest does not support Excel.

* Operating System: macOS Catalina (10.15.7)
* Node version: v14.16.0
* Office version: v16.48
* Tool (yo) version: 3.1.1

By removing the extraneous line from package.json, the problem is solved.

**Comment by millerds** [comment]
This was due to a script updating this not using the same variable name.  This was fixed a while ago.
