### ISSUE TITLE
Facing issue with build file on deployment into a secured server

### ISSUE THREAD

**Issue by jjeevanjyoti** [OfficeDev/generator-office#631]
Hi Team,

When I am deploying the office add in for excel , project build file into a secured personal server.
I am getting below issue
`Refused to load https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js because it appears in neither the script-src directive nor the default-src directive of the Content Security Policy.`

I have tried with META tag in taskpane.html to avoid content security issue ie. But still facing issue.

<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: 'unsafe-eval' ws: ; style-src 'self' 'unsafe-inline'; script-src https//example.com ; media-src 'none'; connect-src *; img-src 'self' data: content:;">

<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' https://* 'unsafe-inline'; script-src 'self' https://* 'unsafe-inline' 'unsafe-eval'" />
 
As I am using it as react application with npm is there any solution for it or can we remove this cdn "https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js" .

I request for an early response.

Thanks

**Comment by millerds** [comment]
Sorry this wasn't responded to earlier.

That reference is what supports the interaction between the add-in and the office application so if you remove that then your office api calls won't work.

Please reopen and provide updated details if there is still something you are trying to figure out.
