### ISSUE TITLE
npm start deosn't sideload TaskPane in Desktop Excel

### ISSUE THREAD

**Issue by lukchen** [OfficeDev/generator-office#634]
OS: Windows 10
Browser: Chrome
Platform: Excel
Version: Office 365 MSO 16.0.13801.20442 64-bit; Excel 2102 (Build 13801.20506); yo @3.1.1; generator-office@1.7.9 

I created a Excel TaskPane project using yo office, when I run 'npm start', the TaskPane gets sideloaded a blink then closed,
video attached:

https://user-images.githubusercontent.com/26646767/116950753-fc4b7a00-ac53-11eb-95f9-35d9c5ad6113.mp4

https://user-images.githubusercontent.com/26646767/116950764-04a3b500-ac54-11eb-9f5b-74bd78d6e4e6.mp4

**Comment by lukchen** [comment]
My package.json:

{
  "name": "office-addin-taskpane-js",
  "version": "0.0.1",
  "repository": {
    "type": "git",
    "url": "https://github.com/OfficeDev/Office-Addin-TaskPane-JS.git"
  },
  "license": "MIT",
  "config": {
    "app_to_debug": "excel",
    "app_type_to_debug": "desktop",
    "dev_server_port": 3000,
    "app-to-debug": "excel"
  },
  "scripts": {
    "build": "webpack -p --mode production --https false",
    "build:dev": "webpack --mode development --https false",
    "build-dev": "webpack --mode development --https false && echo . && echo . && echo . && echo Please use 'build:dev' instead of 'build-dev'.",
    "dev-server": "webpack-dev-server --mode development",
    "lint": "office-addin-lint check",
    "lint:fix": "office-addin-lint fix",
    "prettier": "office-addin-lint prettier",
    "start": "office-addin-debugging start manifest.xml",
    "start:desktop": "office-addin-debugging start manifest.xml desktop",
    "start:web": "office-addin-debugging start manifest.xml web",
    "stop": "office-addin-debugging stop manifest.xml",
    "validate": "office-addin-manifest validate manifest.xml",
    "watch": "webpack --mode development --watch"
  },
  "dependencies": {
    "core-js": "^3.9.1",
    "regenerator-runtime": "^0.13.7"
  },
  "devDependencies": {
    "@babel/core": "^7.13.10",
    "@babel/preset-env": "^7.12.11",
    "@babel/preset-typescript": "^7.13.0",
    "@types/find-process": "1.2.0",
    "@types/office-js": "^1.0.160",
    "@types/office-runtime": "^1.0.17",
    "babel-loader": "^8.2.2",
    "clean-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "^6.4.1",
    "eslint-config-office-addins": "^1.0.22",
    "file-loader": "^4.2.0",
    "find-process": "^1.4.4",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^4.5.1",
    "office-addin-cli": "^1.0.17",
    "office-addin-debugging": "^4.0.3",
    "office-addin-dev-certs": "^1.5.12",
    "office-addin-lint": "^1.1.4",
    "office-addin-manifest": "^1.5.16",
    "office-addin-prettier-config": "^1.0.14",
    "source-map-loader": "^0.2.4",
    "ts-loader": "^6.2.2",
    "typescript": "^4.1.3",
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.2"
  },
  "prettier": "office-addin-prettier-config"
}

**Comment by millerds** [comment]
The blink is a side effect of the sideloading.  The new button in the ribbon opens the taskpane to work as normal.

**Comment by lukchen** [comment]
> The blink is a side effect of the sideloading. The new button in the ribbon opens the taskpane to work as normal.

I'm trying to automate my testing html page with side load Excel Addin, If the TaskPane cannnot opened automatically, it can't be automated

**Comment by millerds** [comment]
> > The blink is a side effect of the sideloading. The new button in the ribbon opens the taskpane to work as normal.
> 
> I'm trying to automate my testing html page with side load Excel Addin, If the TaskPane cannnot opened automatically, it can't be automated

Have the automation click the button to open it.

**Comment by akrantz** [comment]
Alternatively, you could alter the manifest to not use the button. In general, the recommendation is to use a button because it is less jarring for users who will click the button if they want to open it, but you could use an alternate manifest for development. I'm pretty sure that if the button isn't there, the task pane will open by default.

**Comment by lukchen** [comment]
> Alternatively, you could alter the manifest to not use the button. In general, the recommendation is to use a button because it is less jarring for users who will click the button if they want to open it, but you could use an alternate manifest for development. I'm pretty sure that if the button isn't there, the task pane will open by default.
