### ISSUE TITLE
WORD add-in generated by generator-office can not load Office object

### ISSUE THREAD

**Issue by 1983cc** [OfficeDev/generator-office#637]
According to the Microsoft official Office documentation, I tried to use Yeoman's generator-office to generate WORD add-in, and then use npm start to start, but in the Taskpane it always showed as bellow:

![img](https://filestore.community.support.microsoft.com/api/images/407c9987-d81e-462f-bc20-7ce91fb61c24?upload=true)

Using the Microsoft Edge DevTools Preview tool, I can see the missing Office objects:

![img](https://filestore.community.support.microsoft.com/api/images/b96b577d-8b66-43d4-84cd-c57752f8b863?upload=true)

But when I visited this add-in via the web page, I can see that the Office object is loaded successfully:

![img](https://filestore.community.support.microsoft.com/api/images/b2561bbf-80b4-4edc-a9b1-f36fcf994273?upload=true)

![img](https://filestore.community.support.microsoft.com/api/images/393e6fe1-ac72-4944-92be-e32083b88534?upload=true)

Why is the Office object unsuccessful when accessing this add-in in WORD,and how can I fix this?

**Comment by 1983cc** [comment]
After that, I tried to run it on another computer with win7 and office 2016 professional, it works well. I notice the version in question is 2019 home and student.

**Comment by millerds** [comment]
Are you sill encountering this?  This behavior seem to happen with there is something that is in the add-in code that isn't compatible with the web view technology used by the host (in this case word).  One example of this is using the IE11 view and adding "alert('Hit this code')" to code that was previously working will cause the behavior you describe.  There could also be some other custom creating a problem.  Unfortunately I don't have a good explanation about what code creates issues.

A chart talking about which view tech is used can be found at: https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins.

If you want to install webview2 (the most recent case) go to: https://developer.microsoft.com/en-us/microsoft-edge/webview2/
