### ISSUE TITLE
Attached debugger causes Excel TaskPane auto refresh

### ISSUE THREAD

**Issue by lukchen** [OfficeDev/generator-office#639]
Hi, after one recent Office 365 update, I open Excel TaskPane and attach debugger, the TaskPane will auto refresh in few seconds.
If I don't attach debugger, then no auto refresh.

![image](https://user-images.githubusercontent.com/26646767/120529420-7f263880-c3aa-11eb-89e6-772e09b76bbc.png)

**Comment by akrantz** [comment]
When you say "attach debugger", do you mean the browser dev tools, VS Code, or Visual Studio?

**Comment by lukchen** [comment]
> When you say "attach debugger", do you mean the browser dev tools, VS Code, or Visual Studio?

browser dev tools:

![image](https://user-images.githubusercontent.com/26646767/120544404-62463100-c3bb-11eb-8f86-fa3ad8fb7dc6.png)

**Comment by akrantz** [comment]
Thanks for that screenshot. What happens for you after you choose Attach Debugger?

**Comment by lukchen** [comment]
> Thanks for that screenshot. What happens for you after you choose Attach Debugger?

The debug window gets opened, but after 3-5 seconds, the TaskPane page gets refreshed and debug window gets closed

**Comment by millerds** [comment]
Sounds like this issue: https://github.com/OfficeDev/office-js/issues/1852

**Comment by lukchen** [comment]
Thanks, seems like you are working on a fix for the webwiew crash, I'll use VS code or the workaround mentioned in the issue above for now. Closing this issue
