### ISSUE TITLE
React class components to React functional components

### ISSUE THREAD

**Issue by minericpark** [OfficeDev/generator-office#646]
Hello,

I noticed the generated React project (JS/TS) are still using class components. Is there any plans on switching the generated template to functional components? 

I've ended up manually switching them all to functional components, though it doesn't seem to work for some reason. That's likely more a translation error of my own, but just to be sure, I was wondering if there was any incompatibilities between any updated features of React with the generated template?

**Comment by minericpark** [comment]
Resolved my issue; there was a translation error I made from class components to functional components in the sample project. Otherwise I also sometimes didn't let the project compile (which took longer than I thought), and that would often result in the test displaying a blank project.

Otherwise, are there still plans to convert the React templates here to functional components?

**Comment by robcecil** [comment]
I have wondered the same thing. It's when I converted a taskpane.tsx from a Class Component to Functional Component that I started to notice linter errors (unvalidated properties in an TS interface! It was saying I needed a prop-types definition, so weird)

Also, if you pick Typescript, ESLint and the TS Linter seem to be configured to run in VSCode. Seems like the ESLint linter should be removed?

**Comment by akrantz** [comment]
If you would like to update the https://github.com/OfficeDev/Office-AddinTaskPane-React template to use functional components, we would welcome the PR.

ESLint is now the preferred linter for TypeScript over TSLint, and in VS Code you should enable ESLint. There are ESLint rules for TypeScript/React so it might require updating the settings to use those appropriately. I think the ESLint documentation describes best practices there.

**Comment by millerds** [comment]
A dash was missing:  https://github.com/OfficeDev/Office-Addin-TaskPane-React

**Comment by millerds** [comment]
Anyone going to create a PR for this?
