### ISSUE TITLE
yo office fails with: 'webpack-dev-server' is not recognized

### ISSUE THREAD

**Issue by gitcnd** [OfficeDev/generator-office#649]
It looks like either instructions are wrong, or decencies are missing (or installed in the wrong place?) for brand new users of this "yo office" toolchain.

# Expected behavior

No errors

# Current behavior

>npm run dev-server

> office-addin-taskpane-js@0.0.1 dev-server C:\Users\wm_pu\OneDrive\RN5\RN5
> webpack-dev-server --mode development

'webpack-dev-server' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! office-addin-taskpane-js@0.0.1 dev-server: `webpack-dev-server --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the office-addin-taskpane-js@0.0.1 dev-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wm_pu\AppData\Roaming\npm-cache\_logs\2021-07-18T04_58_24_891Z-debug.log

>type C:\Users\wm_pu\AppData\Roaming\npm-cache\_logs\2021-07-18T04_58_24_891Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev-server'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.3
4 verbose run-script [ 'predev-server', 'dev-server', 'postdev-server' ]
5 info lifecycle office-addin-taskpane-js@0.0.1~predev-server: office-addin-taskpane-js@0.0.1
6 info lifecycle office-addin-taskpane-js@0.0.1~dev-server: office-addin-taskpane-js@0.0.1
7 verbose lifecycle office-addin-taskpane-js@0.0.1~dev-server: unsafe-perm in lifecycle true
8 verbose lifecycle office-addin-taskpane-js@0.0.1~dev-server: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\wm_pu\OneDrive\RN5\RN5\node_modules\.bin;C:\Python39\Scripts\;C:\Python39\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\wm_pu\AppData\Local\Microsoft\WindowsApps;;C:\Users\wm_pu\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\wm_pu\AppData\Roaming\npm
9 verbose lifecycle office-addin-taskpane-js@0.0.1~dev-server: CWD: C:\Users\wm_pu\OneDrive\RN5\RN5
10 silly lifecycle office-addin-taskpane-js@0.0.1~dev-server: Args: [ '/d /s /c', 'webpack-dev-server --mode development' ]
11 silly lifecycle office-addin-taskpane-js@0.0.1~dev-server: Returned: code: 1  signal: null
12 info lifecycle office-addin-taskpane-js@0.0.1~dev-server: Failed to exec dev-server script
13 verbose stack Error: office-addin-taskpane-js@0.0.1 dev-server: `webpack-dev-server --mode development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:375:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:375:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid office-addin-taskpane-js@0.0.1
15 verbose cwd C:\Users\wm_pu\OneDrive\RN5\RN5
16 verbose Windows_NT 10.0.19043
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev-server"
18 verbose node v14.17.3
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error office-addin-taskpane-js@0.0.1 dev-server: `webpack-dev-server --mode development`
22 error Exit status 1
23 error Failed at the office-addin-taskpane-js@0.0.1 dev-server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Carefully follow the instructions: https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator
2. It fails at the "Try it out" step.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Fresh Win10 latest install with all updates
* Node version: Fresh new version installed yesterday
* Office version: Fresh new version installed yesterday
* Tool version: Fresh everything, installed yesterday

## Failure Logs

yo log:-

yo office
? ==========================================================================
We're constantly looking for ways to make yo better!
May we anonymously report usage statistics to improve the tool over time?
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== No

     _-----_     Γò¡ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓò«
    |       |    Γöé   Welcome to the Office  Γöé
    |--(o)--|    Γöé   Add-in generator, by   Γöé
   `---------┬┤   Γöé @OfficeDev! Let's create Γöé
    ( _┬┤U`_ )    Γöé    a project together!   Γöé
    /___A___\   /Γò░ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓò»
     |  ~  |
   __'.___.'__
 ┬┤   `  |┬░ ┬┤ Y `

? Office Add-in CLI tools collect anonymized usage data which is sent to Microsoft to help improve our product. Please r
ead our privacy notice at https://aka.ms/OfficeAddInCLIPrivacy. ΓÇïTo disable data collection, choose Exit and run ΓÇ£npx of
fice-addin-usage-data offΓÇ¥.

 Continue
? Choose a project type: Office Add-in Task Pane project
? Choose a script type: JavaScript
? What do you want to name your add-in? RN5
? Which Office client application would you like to support? Outlook

----------------------------------------------------------------------------------

      Creating RN5 add-in for Outlook using JavaScript and Taskpane at C:\Users\wm_pu\OneDrive\RN5\RN5

----------------------------------------------------------------------------------

I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.

npm WARN office-addin-taskpane-js@0.0.1 No description
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code EBUSY
npm ERR! syscall rename
npm ERR! path C:\Users\wm_pu\OneDrive\RN5\RN5\node_modules\is-ip\package.json.1492284020
npm ERR! dest C:\Users\wm_pu\OneDrive\RN5\RN5\node_modules\is-ip\package.json
npm ERR! errno -4082
npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\wm_pu\OneDrive\RN5\RN5\node_modules\is-ip\package.json.1492284020' -> 'C:\Users\wm_pu\OneDrive\RN5\RN5\node_modules\is-ip\package.json'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wm_pu\AppData\Roaming\npm-cache\_logs\2021-07-18T04_54_21_717Z-debug.log
----------------------------------------------------------------------------------------------------------

      Congratulations! Your add-in has been created! Your next steps:

      1. Go the directory where your project was created:

         cd C:\Users\wm_pu\OneDrive\RN5\RN5

      2. Start the local web server:

         npm run dev-server

      3. Sideload the the add-in:

         Follow these instructions:
         https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing

      4. Open the project in VS Code:

         code .

         For more information, visit http://code.visualstudio.com.

      Please visit https://docs.microsoft.com/office/dev/add-ins for more information about Office Add-ins.

----------------------------------------------------------------------------------------------------------

**Comment by gitcnd** [comment]
Looks like a dependency mistake in "yo office" installation.
this solved the problem:-

     npm install webpack-dev-server --save-dev

but it should have been installed for me...

**Comment by millerds** [comment]
Based on the log you posted the 'npm install' didn't completely finish because of a busy or locked resource.  The log also stated that if npm install fails you should run the command yourself.  If you do that inside the folder all the packages (including webpack-dev-server) would get installed and the command would work.

**Comment by millerds** [comment]
Should be fixed in v1.8 of generator-office
