### ISSUE TITLE
UnhandledPromiseRejectionWarning in Office Code

### ISSUE THREAD

**Issue by JamesIgoe** [OfficeDev/generator-office#650]
# Expected behavior

I expect to run the yo generator, and then ran configure-sso. I have done this before and it has worked, but now after I get the error below.

# Current behavior

I ran the yo generator, and then ran configure-sso. I have done this before successfully but now I see the following error, and the code builds, but will not start via npm start.

> Login was successful!
(node:19636) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'readManifestFile' of undefined
    at Command.<anonymous> (G:\My Documents\GitHub\MSKSpamSubmitter\node_modules\office-addin-sso\lib\commands.js:47:84)
    at Generator.next (<anonymous>)
    at fulfilled (G:\My Documents\GitHub\MSKSpamSubmitter\node_modules\office-addin-sso\lib\commands.js:6:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Steps to Reproduce

Followed these instructions: https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/sso-quickstart.md

- Selected Outlook for SSO and Typescript.
- Ran npm run configure-sso

## Context

- Win 10 (with admin)
- Node LTS 14.17.4
- TS 4.2.4
- VS Code

## Failure Logs

- See error output above

**Comment by JamesIgoe** [comment]
No response?

**Comment by millerds** [comment]
I'm not able to repro this.

**Comment by JamesIgoe** [comment]
I'l try again

**Comment by JamesIgoe** [comment]
When I first run it, it fails:

>'office-addin-sso' is not recognized as an internal or external command,
operable program or batch file.
PS G:\My Documents\github\mskspamsubmitter3> 

Last time I tried, I simply installed office-addin-sso.

Should I?

**Comment by millerds** [comment]
That's a different issue (being fixed).  Run "npm install" and then setup sso.

**Comment by JamesIgoe** [comment]
Was able to build and deploy...

**Comment by millerds** [comment]
The was a breaking change in a dependent package.  An update has been pushed (still working on the JS version of this though)
