### ISSUE TITLE
Clean yo generated project won't build

### ISSUE THREAD

**Issue by efremsternbach** [OfficeDev/generator-office#660]
I recently took the initiative to update node.js from v12 to v14 LTS. This turns out to be a problem since the projects generated from yo no longer compile

Installed node-v14.17.6-x64
Running Windows 10 Pro 64 bit

Running the following commands
> npm install -g yo generator-office
> yo office --projectType excel-functions --name MyProject --host excel --ts true

yo runs npm install automatically

I have not yet made any changes to the project yet when I try to build

> npm run build

I get the following error

> excel-custom-functions@2.0.0 build {Path to my project}
> webpack -p --mode production --https false
(node:27364) UnhandledPromiseRejectionWarning: TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks ({Path to my project}\node_modules\custom-functions-metadata-plugin\node_modules\webpack\lib\NormalModule.js:203:10)
    at {Path to my project}\node_modules\custom-functions-metadata-plugin\lib\customfunctionsplugin.js:54:36
    at SyncHook.eval [as call] (eval at create ({Path to my project}\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:11:1)
    at SyncHook.lazyCompileHook ({Path to my project}\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.newCompilation ({Path to my project}\node_modules\webpack\lib\Compiler.js:631:26)
    at {Path to my project}\node_modules\webpack\lib\Compiler.js:667:29
    at eval (eval at create ({Path to my project}\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

where for privacy reasons I've replaced the actual path to my project with {Path to my project}

I'd rather not have to downgrade back to node v12 especially since the most recent version of office-generator says that v14 is required. It's especially annoying because this error happens after a fresh install of node.js (cleared npm-cache and all previous global packages) and yo. No changes have yet been made to the project and it still won't build.

This is either a problem with the current version of yo and/or office generator or perhaps there is some configuration issue with my machine (though everything used to work before I tried to upgrade node.js). 

It's hugely frustrating when this doesn't even function with a clean install. I'm also sure there is nothing unusual about my Windows configuration either.

Any help would be appreciated.

**Comment by millerds** [comment]
I tried running your command on two different machines and was able to successfully build the project without any modification.  This appears to be something else with your setup.  Can you run 'npm outdated -g --depth=0' and provide your output?

**Comment by efremsternbach** [comment]
> npm outdated -g --depth=0

returned nothing at all

> npm outdated--depth=0

in the project directory returns
```
Package                          Current   Wanted   Latest  Location
@babel/core                       7.13.1   7.15.4   7.15.4  excel-custom-functions
@babel/preset-env                 7.13.5   7.15.4   7.15.4  excel-custom-functions
@types/custom-functions-runtime    1.6.0    1.6.4    1.6.4  excel-custom-functions
@types/office-js                 1.0.166  1.0.201  1.0.201  excel-custom-functions
@types/office-runtime             1.0.17   1.0.21   1.0.21  excel-custom-functions
clean-webpack-plugin               2.0.2    2.0.2    4.0.0  excel-custom-functions
copy-webpack-plugin                5.1.2    5.1.2    9.0.1  excel-custom-functions
eslint-config-office-addins       1.0.20    1.3.2    1.3.2  excel-custom-functions
file-loader                        4.3.0    4.3.0    6.2.0  excel-custom-functions
html-loader                        0.5.5    0.5.5    2.1.2  excel-custom-functions
html-webpack-plugin                4.5.2    4.5.2    5.3.2  excel-custom-functions
office-addin-cli                  1.0.17    1.2.2    1.2.2  excel-custom-functions
office-addin-debugging            3.0.42   3.0.42    4.2.2  excel-custom-functions
office-addin-dev-certs            1.5.12    1.6.2    1.6.2  excel-custom-functions
office-addin-lint                 1.0.32    1.3.2    1.3.2  excel-custom-functions
office-addin-manifest             1.5.16    1.6.2    1.6.2  excel-custom-functions
office-addin-prettier-config      1.0.14    1.1.0    1.1.0  excel-custom-functions
source-map-loader                  0.2.4    0.2.4    3.0.0  excel-custom-functions
ts-loader                          6.2.2    6.2.2    9.2.5  excel-custom-functions
typescript                         4.2.2    4.4.2    4.4.2  excel-custom-functions
webpack                           4.46.0   4.46.0   5.52.0  excel-custom-functions
webpack-cli                       3.3.12   3.3.12    4.8.0  excel-custom-functions
webpack-dev-server                3.11.2   3.11.2    4.1.0  excel-custom-functions
```

Is there a web page that describes all the files installed by node.js on a Windows system? The installers clearly don't clean up after themselves very well.

I'm quite puzzled at what is happening.

**Comment by efremsternbach** [comment]
I was able to get a clean project building with Node.js 14 and I laboriously copied code from my old project to this "clean" project and got it to build.

None of this makes any sense since I'm using the same code from my git repository as the old project. The old project still fails to build even though it is functionally identical.

No point anyone else wasting time on this. I'm closing the issue. Thanks for your help.
