### ISSUE TITLE
Unable to verify dev-certs after installation

### ISSUE THREAD

**Issue by ademkikaj** [OfficeDev/generator-office#666]
I am running `npx office-addin-dev-certs install` to install the certificates and they seem to be generated properly by creating the directory `/office-addin-dev-certs` where I can see `ca.crt` and `localhost.crt`. However, only one certificate is registered at the Keychain Access under the name **Developer CA for Microsoft Office Add-ins**.

I get the following output after running `npx office-addin-dev-certs install`

```
The developer certificates have been generated in /Users/myusername/.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
You now have trusted access to https://localhost.
Certificate: /Users/myusername/.office-addin-dev-certs/localhost.crt
Key: /Users/myusername/.office-addin-dev-certs/localhost.key
```

When I try to verify that everything is properly set up by running `npx office-addin-dev-certs verify` I get the following output:
`You need to install certificates for trusted access to https://localhost.`

When I want to run the office-addin via `npm run dev-server` it cannot find the installed certificate and a new reinstallation begins.

**===== EDIT =====** 
It seems that the reason why it fails to verify the installed certificate is the common/subject name of the `localhost.crt `certificate. I can see in my Keychain Access that there is no localhost certificate added automatically. However, when I install the `localhost.crt` manually it adds the certificate under the common/subject name `127.0.0.1` (see picture below).

<img width="670" alt="Screenshot 2021-10-13 at 10 30 48" src="https://user-images.githubusercontent.com/26844158/137097063-448f3cce-2dd8-4f6b-ba26-8e598e4946c3.png">

My setup:
Node version: 14.16.0
NPM version: 7.6.3
office-addin-dev-certs version: 1.7.0
OS: macOS Big Sur

**Comment by millerds** [comment]
I have recently updated the office-addin-dev-certs package to work better on mac.  Please update to the latest version and try again.

Note . . . I also found out there is a recent change to Mac OS that seems to affect the cert being installed as trusted.  When this happens and you open an office application you'll get a certificate warning and even if you OK it the add-in will fail to load.  If this happens, find the cert in the keychain and adjust the trust settings to be trusted (I'm still looking at how to fix this without the manual steps).

**Comment by ademkikaj** [comment]
Thank you. In version 1.7.6, it did work.
