### ISSUE TITLE
TCP Timeout while Running Yo behind a restricted Proxy Server

### ISSUE THREAD

**Issue by bravehat** [OfficeDev/generator-office#667]
Hi

Our Server is behind a proxy that does not allow outbound traffic. So we need to enable it on demand. 
We have currently enabled access to github.com and its sub-urls.
Also, we have enabled access to http://registry.npmjs.org/generator-office
But we are still gettting the below error. 
Can you please help.

$ yo office

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the Office  │
    |--(o)--|    │   Add-in generator, by   │
   `---------´   │ @OfficeDev! Let's create │
    ( _´U`_ )    │    a project together!   │
    /___A___\   /╰──────────────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Choose a project type: Office Add-in Task Pane project
? Choose a script type: JavaScript
? What do you want to name your add-in? Demo3
? Which Office client application would you like to support? Outlook

----------------------------------------------------------------------------------

      Creating Demo3 add-in for Outlook using JavaScript and Taskpane at /home/appadmin/Demo3

----------------------------------------------------------------------------------
internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ETIMEDOUT 13.234.210.38:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '13.234.210.38',
  port: 443
}

**Comment by millerds** [comment]
Any further thoughts on this?

**Comment by bravehat** [comment]
Hi

I Appreciate the follow up.
The issue was a rule in the firewall.

Things are working fine now.
We are able to download and run the same.

**Comment by millerds** [comment]
Glad to hear it worked out.  Sorry it took so long to follow through.
