### ISSUE TITLE
Excel functions add-in project  seems to be broken

### ISSUE THREAD

**Issue by GregReddick** [OfficeDev/generator-office#668]
When I follow the install process shown at https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows exactly, the project fails to build. When I run the "npm run build" command, I get the following error message:

> excel-custom-functions-js@2.0.0 build D:\temp\starcount
> webpack --mode production

(node:9728) UnhandledPromiseRejectionWarning: TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (D:\temp\starcount\node_modules\webpack\lib\NormalModule.js:203:10)
    at D:\temp\starcount\node_modules\custom-functions-metadata-plugin\lib\customfunctionsplugin.js:54:36
    at Hook.eval [as call] (eval at create (D:\Temp\starcount\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (D:\Temp\starcount\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (D:\Temp\starcount\node_modules\webpack\lib\Compiler.js:1044:26)
    at D:\Temp\starcount\node_modules\webpack\lib\Compiler.js:1088:29
    at eval (eval at create (D:\Temp\starcount\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

What am I doing wrong? When I build the Excel Task Pane project for Excel, everything works okay, but the Excel Custom Functions Add-in project is broken. I have tried everything I can think of.

**Comment by millerds** [comment]
Glad you figured it out.  We'll take a look to see if this is something we should fix.  Feel free to express how important you think it is to be completely PowerShell compatible.
