### ISSUE TITLE
Localhost loopback for Microsoft Edge WebView cannot work

### ISSUE THREAD

**Issue by dukechain2333** [OfficeDev/generator-office#671]
Debugging is being started...
App type: desktop
? Allow localhost loopback for Microsoft Edge WebView? Yes
Error: Unable to start debugging.
:

**Comment by dukechain2333** [comment]
My Excel Version is Version 2110 Build 16.0.14527.20168
Edge version is 95.0.1020.38
I ran those commands in powershell (it may look strange because I am using Windows Terminal and has a theme on it).

**Comment by millerds** [comment]
Did you run them in PowerShell or windows terminal?  I think there might be a bug with running them in PowerShell instead of regular windows terminal.

**Comment by dss010101** [comment]
> Allow localhost loopback for Microsoft Edge WebView

so that dialogue always pops up, even you select 'Yes' to 'Allow localhost loopback for Microsoft Edge WebView?'?

**Comment by tsuyoshi-fukuzawa** [comment]
After running the command prompt as administrator, npm start could be started without any problems.
