### ISSUE TITLE
Add-in does not sideload with new start:web syntax

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/generator-office#683]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x ] I am running the latest version of Node and the tools
- x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

# Expected behavior

When I run the command:
```
npm run start:web -- --document {url}
```
I expect the file to open and the add-in to be sideloaded in it. 

# Current behavior

The document opens and I get the following two prompts, but the add-in is not sideloaded. I have to manually sideload it. 

![Screenshot 2022-01-14 134207](https://user-images.githubusercontent.com/9088056/149593796-f58a037f-f40c-4687-9c04-036285ded1cf.png)

![Screenshot 2022-01-14 134235](https://user-images.githubusercontent.com/9088056/149593839-dbeb3c51-3878-403d-a7b4-714ef1aedbbc.png)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. In the root of an add-in project that was created with Yo Office, run the command:
```
npm run start:web -- --document {url}
```
2. Answer to the two prompts in the screenshot above.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Win11
* Node version: 16.13.1
* Office version: 2202 43910.20000
* Tool version: latest

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by millerds** [comment]
The first dialog is the explanation . . . you have to enable developer mode in order to automatically sideload add-ins.

**Comment by Rick-Kirkham** [comment]
@millerds  We did that. So, that's not the problem. Is there a way to confirm that developer mode has been enabled? Something to see in the registry maybe?

**Comment by DarwinsBuddy** [comment]
I'm facing the same issue

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Operating System: Arch Linux
Node version: 16.13.2 / 17.4.0
Tool version: latest

Browser opening up w/ given document. But no add-in to be found.

**Comment by millerds** [comment]
I don't know how to verify developer mode is enabled other than the dialog asking for it should disappear.  If you check the box and click OK does that dialog box show up again?

**Comment by akshayta23** [comment]
@DarwinsBuddy - Can you address the question above?

**Comment by DarwinsBuddy** [comment]
It's been a year. What exactly can I assist with?
