### ISSUE TITLE
Root CA silently fails to be installed in the Trusted Root Cert store

### ISSUE THREAD

**Issue by ANHPearce** [OfficeDev/generator-office#685]
I am cross referencing this issue here as the other repo had asked. I would also like to post my simple workaround for the time being.

https://github.com/OfficeDev/office-js-docs-pr/issues/2937

# Expected behavior

When running the "npm start" script for an Outlook Task Pane office add-in project I expect the "office-addin-dev-certs install" sub command to correctly register the Root CA cert and the Localhost cert.

# Current behavior

After npm start finishes the node server is running and accessible but the task pane view is unable to open and provides the following error. This is also corroborated by viewing in the browser and being warned about an invalid cert. 

![image](https://user-images.githubusercontent.com/25624851/151590629-28ea076b-1ee7-4237-aa64-b58f2277c819.png)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Setup project according to https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial
2. Run npm start
3. Attempt to view Add-In in the task pane

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10 Pro  10.0.19041.1151
* Node version: 16.13.2
* Office version: Microsoft 365 Apps for enterprise
* Tool version: 
    "office-addin-debugging": "^4.3.7",
    "office-addin-dev-certs": "^1.7.6",
    "office-addin-lint": "^1.4.5",
    "office-addin-manifest": "^1.7.6",
    "office-addin-prettier-config": "^1.1.3",

**Comment by ANHPearce** [comment]
My simple workaround was simply to navigate to ~\.office-addin-dev-certs and manually install the certificates.

Note that you must install the Root CA in the Trusted Root Certificate store. To find that particular store on my machine I had to add it for the host/all users.

**Comment by millerds** [comment]
Did you find that running the "office-addin-dev-certs install" command reported an error of any kind?

If you have a repro environment (I know that you've unblocked yourself with the workaround) it would great if you could run some commands for us to narrow down the problem.

**Comment by millerds** [comment]
There have been some fixes to the office-addin-dev-certs package.  If the problem still exists please re-open the issue.
