### ISSUE TITLE
Office Add-in Task Pane project supporting single sign-on (not working)

### ISSUE THREAD

**Issue by x0ry** [OfficeDev/generator-office#692]
Using the tool to generate a project, I'm able to follow the steps - even ensuring sign in audience is set properly.  After it works successfully both on desktop and web, eventually the login window flashes open and closed when attempting to login without querying Microsoft graph.  I'm having a tough catching this exception in a debugger.

**Comment by millerds** [comment]
The SSO template has been significantly revamped.  It should be working now.
