### ISSUE TITLE
Unable to install package due to peer dependency on cmd-shim

### ISSUE THREAD

**Issue by samarthbharti217** [OfficeDev/generator-office#699]
# Expected behavior
Successfully install package

# Current behavior
Currently package install fails with below error
npm ERR! 404  'cmd-shim@^5.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

Raised this with cmd-shim as well, here: https://github.com/npm/cmd-shim/issues/62

## Steps to Reproduce
1. npm i yo generator-office --save-dev

## Context
* Operating System: Windows
* Node version: 14.18.1

## Failure Logs

npm ERR! 404  'cmd-shim@^5.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by millerds** [comment]
Can you try installing 'yo' seperately from 'generator-office' to figure out which one is throwing the error?

**Comment by samarthbharti217** [comment]
It's an issue with Yo, able to install generator-office

**Comment by millerds** [comment]
If that's the case then you'll have to follow with yeoman generator.  'generator-office' is a plugin for that framework.

**Comment by Rick-Kirkham** [comment]
@samarthbharti217 see [support for Yeoman generator](https://yeoman.io/learning/support.html)
