### ISSUE TITLE
Custom functions option just "copies" the template.  Doesn't create a project.

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/generator-office#703]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x ] I am running the latest version of Node and the tools
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

# Expected behavior

Choosing the Custom Functions option in Yo Office creates an Excel custom functions project.

# Current behavior

The project is not created. Instead, it appears hat the template for the project type is just copied into the folder where the project should be. See screenshot.
![image](https://user-images.githubusercontent.com/9088056/165151465-118f4b35-8d1d-4cf1-b20f-8bed8d9eaba7.png)

## Steps to Reproduce

1. Follow the steps in the quickstart: https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows
2. A project named "starcount" should be created. But it isn't. See screenshot.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Win 10
* Node version: 16.14.2
* Office version: 2205 build 15220.20000
* Tool version: latest (just installed Saturday)

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by millerds** [comment]
@Rick-Kirkham, if do step one in the document I get the startcount project as expected, I don't have the subfolder you show in the screen shot.

**Comment by Rick-Kirkham** [comment]
@millerds  ??? This is bizarre. What version of node and npm are you using?

**Comment by millerds** [comment]
Node v16.13.0
Npm v8.1.1
yo v4.3.0
generator-office v1.8.1

**Comment by Rick-Kirkham** [comment]
@millerds I Partly diagnosed this: When I run `npm install -g yo generator-office`, it runs without error, but I seem to still be on version 1.3. I've even tried `npm install -g yo generator-office@1.8.1`. It's just not overwriting any files. Is there a trick to updating office-generator? 

If I delete the \generator-office folder from the global \node-modules, will that get rid of all trace of it? Or does installation create registry entries or other artifacts somewhere?

**Comment by Rick-Kirkham** [comment]
I finally got it uninstalled and reinstalled. And I've created a project successfully. Weird thing though. If I try to create a project in an Admin Command Prompt, I get a permission error. But it works, if I'm in a non-elevated command prompt. Seems backwards, doesn't it?
