### ISSUE TITLE
Attaching vscode debugger creates error - ECONNREFUSED 127.0.0.1:9222

### ISSUE THREAD

**Issue by stevetfiligree** [OfficeDev/generator-office#711]
I have followed the instructions from - https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-with-vs-extension
- and I am getting this error:
> Error [vscode-debugger-extension-for-office-addins] Error processing "attach": connect
ECONNREFUSED 127.0.0.1:9222
open launch.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 614e6992-f9be-4ce5-1f15-0fc6bf285c43
* Version Independent ID: 1b37e38d-06ec-cd00-16bb-3324b1f0048f
* Content: [Microsoft Office Add-in Debugger Extension for Visual Studio Code - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-with-vs-extension#see-also)
* Content Source: [docs/testing/debug-with-vs-extension.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-with-vs-extension.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by millerds** [comment]
The VC Code plugin for debugging legacy edge webview had a problem with it.  A fix was published a few months ago.  Please try again
- Using the current version of the plugin 
- Ensuring that you area also using ' npx office-addin-dev-settings webview manifest.xml edge-legacy' to trigger using the legacy view
- Are in a M365 channel the support switching the view (Insiders I think)
- Are using the edge legacy debug configuration matching your host.

Open a new issue if you are still having problems.
