### ISSUE TITLE
Excel Add-in created not loading and giving error after updating to Windows 11

### ISSUE THREAD

**Issue by VamsiKrishnaNori** [OfficeDev/generator-office#712]
I am trying to build a new Excel Add-in using the link provided below from Microsoft office docs using Visual Studio 2019 but this is giving me This Add-In could not be started error after Trying out step 2. please find additional details below. When i build the Add-In with same steps in Windows 10 OS its working fine.

Content URL: https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=visualstudio

Product: Excel
Technology: add-ins
OS: Windows 11
Windows Version: Version 21H2 (OS Build 22000.258)
Excel Version: 2110 (build 16.0.14527.20008) 32 bit

**Comment by millerds** [comment]
I haven't been able to look at this in a while . . . is anyone still having trouble with this?
