### ISSUE TITLE
Certificatin installation not prompt after npm run, also can't find ca.crt in project root

### ISSUE THREAD

**Issue by Snailya** [OfficeDev/generator-office#719]
# Expected behavior

Prompt to install certificate when run `npm start` the first time.
Or provide ca.crt in {project root}/certs to allow mannually installation.

# Current behavior

Please provide information about the failure. What is the current behavior? If it is not a bug, please add it to [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/164751-office-developer-tools), so that it gets added to our feature roadmap.

Neither installation prompted.
Nor certs folder in project root.
![image](https://user-images.githubusercontent.com/19658624/175500568-7f93a563-229f-4090-ad70-5170ac79a22c.png)
![image](https://user-images.githubusercontent.com/19658624/175500526-f682c447-9729-478d-b24f-e09f5653fca7.png)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. yo office --projectType react --name "My Office Add-in" --host excel --ts true
2. npm run start

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 11
* Node version: 16.15.1
* Office version: office mono 2016
* Tool version: 

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by millerds** [comment]
The cert file is not added to the project, it's placed in your user profile folder under ".office-addin-dev-certs" folder and once you have approved it once it won't prompt you again until the cert expires (by default that is a couple of months).
