### ISSUE TITLE
No single sign-on option after running yo office

### ISSUE THREAD

**Issue by jjaronik** [OfficeDev/generator-office#722]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior
Expecting to see an option to select "Office Add-in Task Pane project supporting single sign-on" 

# Current behavior
No option to select  "Office Add-in Task Pane project supporting single sign-on" 

## Steps to Reproduce
1. run yo office

## Context
The option did show up about a week ago, but I wanted to start my project over. Now the option doesn't show up after running yo office. I've also tried running "yo office --projectType single-sign-on --name "Word Sso Add In" --host word --js true" but it just runs the generator again.

* Operating System: Windows
* Node version: v16.16.0
* Office version: 18.2106.12410.0
* Tool version: yo 4.3.0

## Failure Logs

![Screenshot (265)](https://user-images.githubusercontent.com/91170877/180135563-3a2c86f3-63cd-4b06-8da0-63273635bcc6.png)

**Comment by millerds** [comment]
This was intentionally removed temporarily.  The template needs to be updated to conform to current security best practices which will take some time and so it was removed.  We hope to add it back soon once we have a chance to update it.  In the meantime there is a sample and documentation you can use.  https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs?branch=davech-update-node-sso

Note: older versions of generator-office package still have the option listed, but the project output is stripped down to the readme explaining the template is not available.
