### ISSUE TITLE
Outlook Add-in with Teams Manifest option is not working

### ISSUE THREAD

**Issue by hamenon-ms** [OfficeDev/generator-office#724]
# Prerequisites

- [Y] I am running the latest version of Node and the tools
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed

# Expected behavior

Was trying to follow the instructions present here https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart-json-manifest 

Ran the yeoman generator choosing the Outlook Add-in with Teams Manifest option but the tool just generated the folder and no other files. The folder was empty

# Current behavior

The tool does not generate any files as part of running it. The folder gets created but its empty

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run yo office
2. Chosse the Outlook Add-in with Teams Manifest (Developer preview) option
3. Folder gets generated but its empty. None of the files mentioned in the document show up.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 11 
* Node version: 16.16
* Office version: Unsure. dont think it applies here
* Tool version: 1.9

## Failure Logs

None. The tool didn't generate any logs

**Comment by Rick-Kirkham** [comment]
I have reproduced this.

**Comment by millerds** [comment]
This looks to be a problem in the most recent version.  I will look into fixing it, but in the meantime you can run "npm install -g generator-office@1.8.8' to get a version that hasn't been broken yet.

**Comment by millerds** [comment]
Just published and update to generator-office.  should be working in version 1.9.1.
