### ISSUE TITLE
In Teams manifest option, the "resourceSpecific" AppendOnSend permission is ignored

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/generator-office#725]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x ] I am running the latest version of Node and the tools
- [ xx] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

# Expected behavior

When the "resourceSpecific" property has an AppendOnSend object like this:

```
"authorization":{
      "permissions":
        {"resourceSpecific":[
            {"name":"MailboxItem.ReadWrite.User",
             "type":"Delegated"},
            {"name":"AppendOnSend",
             "type":"Delegated"}
          ]
        }
    },
```
then it should create an `<ExtendedPermissions>` element just before the closing `</VersionOverrides>` element like this: 

```
    <ExtendedPermissions>
      <ExtendedPermission>AppendOnSend</ExtendedPermission>
    </ExtendedPermissions>
</VersionOverrides>
```

# Current behavior

The `<ExtendedPermissions>` element is not created. 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. manually add the additional object to the "resourceSpecific" array with "name" = "AppendOnSend"
2. start the server and sideload the add-in
3. Go to C:\Users\YOUR_USER_NAME\AppData\Local\Temp and open the manifest.xml file. The `<ExtendedOverrides>` element is not there.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* Node version:
* Office version:
* Tool version:

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by millerds** [comment]
We've switched away from xml conversion now the json is directly supported.
