### ISSUE TITLE
Please update the readme to correspond with 1.9 updates

### ISSUE THREAD

**Issue by AFosterTeleAI** [OfficeDev/generator-office#726]
# Prerequisites

- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

You should not show in the documentation for v 1.9 and above that sso is a valid startup option.

# Current behavior

The Read-me still shows sso project creation as an available option for 1.9<. It is also non functional if you revert back the version to 1.8.1>, when you use "npm run configure-sso" it displays 'Template Temperarily Unavailable'.

## Steps to Reproduce

1.  Look at the readme.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* Node version:  v16.13.2

**Comment by millerds** [comment]
SSO creation was re added
