### ISSUE TITLE
Taskbar React Typescript for Outlook fails linting out of the box

### ISSUE THREAD

**Issue by SeanKilleen** [OfficeDev/generator-office#730]
# Expected behavior

Run `npm run lint` with no failures after fresh generation.

# Current behavior

Running `npm run lint` yields:

> HeroList.tsx 15:13  error  'children' is missing in props validation

## Steps to Reproduce

* Install node (for me, `nvm install 16.17.0; nvm use 16.17.0`)
* `npm install -g yo generator-office`
  * At time of this issue, this command installed yo 4.3.0 and generator-office 1.9.2

* Run `yo office`
  * Select Task Pane with React
  * Select TypeScript
  * Select Outlook
 
* Run `npm install` from the project directory
* Run `npm run build`, see a successful build
* Run `npm run lint`, see lint failure.

**Comment by millerds** [comment]
Interesting that this doesn't happen on the template code directly, but does happen on the project generated from the template code.

**Comment by SeanKilleen** [comment]
@millerds Thanks for confirming I'm not imagining things! 😅 I'll see if I can find any more information.

**Comment by millerds** [comment]
Looks like you can fix this by adding "children: any;" to the HearListProps interface definition just about the class.  I will add this to the template code.

**Comment by millerds** [comment]
https://github.com/OfficeDev/Office-Addin-TaskPane-React/pull/100#pullrequestreview-1104876488
