### ISSUE TITLE
Outlook task pane project generates project.zip and fails

### ISSUE THREAD

**Issue by brandpeter** [OfficeDev/generator-office#740]
STR:
In CMD type yo office
? Choose a project type: Office Add-in Task Pane project
? Choose a script type: (Use arrow keys)
? Choose a script type: JavaScript
? What do you want to name your add-in? Outtask
? Which Office client application would you like to support? Outlook

----------------------------------------------------------------------------------

      Creating Outtask add-in for Outlook using JavaScript and Taskpane at C:\inetpub\wwwroot\Outtask

----------------------------------------------------------------------------------

After a while command prompt appears, and the only file in the folder is project.zip, which cannot be opened as it is invalid zip.
No idea why it asks for the script type twice.
Microsoft Windows [Version 10.0.19043.2130]
npm@8.19.2
Yeoman downloaded and installed today. Generated an Excel Task pane project just fine, deleted that, now it no longer works.
Tried re-installing npm install -g yo generator-office, no change.

**Comment by millerds** [comment]
what version of node are you using?

**Comment by brandpeter** [comment]
IIS uses that folder for localhost web server, which is where I thought the code should be for testing.  You are quite right, Yeoman runs successfully in another folder where I am the owner.
Incidentally, that "Choose a script type" needs to be responded to twice.
Node version I downloaded recently 18.20.0 LTS Windows 64. 
Thanks Darren.

**Comment by millerds** [comment]
Updated node support
