### ISSUE TITLE
Out of the box yo addin will not load in excel desktop. Web fine.

### ISSUE THREAD

**Issue by jabbera** [OfficeDev/generator-office#742]
# Expected behavior

Yo generated addin loads properly.

# Current behavior

generating an addin no longer works in excel desktop yielding the below error. Works fine on Excel Web. This might be realated to Windows 11 but I'm unsure. Either way it's really bad for us.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. yo office
2. Excel Custom Functions using a JavaScript-only Runtime
3. Javascript
4. My Office Add-in
5. cd '.\My Office Add-in\'
6. npm run build
7. npm start

Wait for a few minutes. Get Error. There is nothing that can be done here to get the error to go away. IE: Dismissing the debugger warning and hitting restart doesn't work.

<img width="586" alt="image" src="https://user-images.githubusercontent.com/301208/200229613-f8e942cb-5b9f-4801-8fc0-3047e7ba960f.png">

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 11 Enterprise 10.0.22621 Build 22621
* Node version: 16.17.1
* Office version: Version 2208 Build 15601.20230
* Tool version: generator-office@1.9.2

## Failure Logs

Addin Logs:

11/6/2022 23:55:55	Medium	Web Add-In Runtime Logging Session Started			
11/6/2022 23:55:55	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin]		
11/6/2022 23:55:55	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
11/6/2022 23:55:55	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.ADD		
11/6/2022 23:55:55	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
11/6/2022 23:55:55	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.CLOCK		
11/6/2022 23:55:55	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
11/6/2022 23:55:55	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.INCREMENT		
11/6/2022 23:55:55	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
11/6/2022 23:55:55	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.LOG		
11/6/2022 23:55:55	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success]		
11/6/2022 23:55:55	Verbose	CustomFunctions	[Installation] [Functions] [Begin] Solution=b829afd3-b791-40db-8d28-70cca5c56c56, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:55	Verbose	CustomFunctions	[Registration] [Begin] Function=CONTOSO.ADD, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:55	Medium	CustomFunctions	[Registration] [End] [Success] Function=CONTOSO.ADD, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:55	Verbose	CustomFunctions	[Registration] [Begin] Function=CONTOSO.CLOCK, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:55	Medium	CustomFunctions	[Registration] [End] [Success] Function=CONTOSO.CLOCK, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:55	Verbose	CustomFunctions	[Registration] [Begin] Function=CONTOSO.INCREMENT, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:55	Medium	CustomFunctions	[Registration] [End] [Success] Function=CONTOSO.INCREMENT, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:55	Verbose	CustomFunctions	[Registration] [Begin] Function=CONTOSO.LOG, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:55	Medium	CustomFunctions	[Registration] [End] [Success] Function=CONTOSO.LOG, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:55	Medium	CustomFunctions	[Installation] [Functions] [End] [Success] Solution=b829afd3-b791-40db-8d28-70cca5c56c56, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:55	Unexpected	Manifest	Issue encountered while parsing manifest, add-in ID : 12d18a4f-508c-464f-b1e3-91ee55172e0d, Location : Error at element "Version" : Add-in manifest parsing encountered a value that does not conform to its required format, Line=4, CharPosition=14		
11/6/2022 23:55:55	Unexpected	Manifest	Issue encountered while parsing manifest, add-in ID : 12d18a4f-508c-464f-b1e3-91ee55172e0d, Location : Error at element "Version" : Add-in manifest parsing encountered a value that does not conform to its required format, Line=4, CharPosition=14		
11/6/2022 23:55:55	Unexpected	Resource	The resource you are trying to use does not exist.		
11/6/2022 23:55:55	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin]		
11/6/2022 23:55:55	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
11/6/2022 23:55:55	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.ADD		
11/6/2022 23:55:55	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
11/6/2022 23:55:55	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.CLOCK		
11/6/2022 23:55:55	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
11/6/2022 23:55:55	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.INCREMENT		
11/6/2022 23:55:55	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
11/6/2022 23:55:55	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.LOG		
11/6/2022 23:55:55	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success]		
11/6/2022 23:55:56	Verbose	CustomFunctions	[Installation] [Addin] [Begin] Solution=b829afd3-b791-40db-8d28-70cca5c56c56, Version=1.0.0.0		
11/6/2022 23:55:56	Medium	CustomFunctions	[Installation] [Addin] [End] [Success] Solution=b829afd3-b791-40db-8d28-70cca5c56c56, Version=1.0.0.0		
11/6/2022 23:55:56	Verbose	CustomFunctions	[Installation] [Functions] [Begin] Solution=b829afd3-b791-40db-8d28-70cca5c56c56, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:56	Verbose	CustomFunctions	[Registration] [Begin] Function=CONTOSO.ADD, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:56	Medium	CustomFunctions	[Registration] [End] [Success] Function=CONTOSO.ADD, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:56	Verbose	CustomFunctions	[Registration] [Begin] Function=CONTOSO.CLOCK, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:56	Medium	CustomFunctions	[Registration] [End] [Success] Function=CONTOSO.CLOCK, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:56	Verbose	CustomFunctions	[Registration] [Begin] Function=CONTOSO.INCREMENT, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:56	Medium	CustomFunctions	[Registration] [End] [Success] Function=CONTOSO.INCREMENT, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:56	Verbose	CustomFunctions	[Registration] [Begin] Function=CONTOSO.LOG, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:56	Medium	CustomFunctions	[Registration] [End] [Success] Function=CONTOSO.LOG, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx		
11/6/2022 23:55:56	Medium	CustomFunctions	[Installation] [Functions] [End] [Success] Solution=b829afd3-b791-40db-8d28-70cca5c56c56, Workbook=Excel add-in b829afd3-b791-40db-8d28-70cca5c56c56.xlsx

**Comment by jabbera** [comment]
Note: Removing the custom functions part of the manifest (copied below) allows the addin to load sucesfully:

```
         <ExtensionPoint xsi:type="CustomFunctions">
            <Script>
              <SourceLocation resid="Functions.Script.Url"/>
            </Script>
            <Page>
              <SourceLocation resid="Functions.Page.Url"/>
            </Page>
            <Metadata>
              <SourceLocation resid="Functions.Metadata.Url"/>
            </Metadata>
            <Namespace resid="Functions.Namespace"/>
          </ExtensionPoint>
        </AllFormFactors>
```

**Comment by millerds** [comment]
There are some problems with the CF template that are currently being worked on.  I'll have to double check if this is part of that set or not.

I did note that the logs reported an error:

11/6/2022 23:55:55 Unexpected Manifest Issue encountered while parsing manifest, add-in ID : 12d18a4f-508c-464f-b1e3-91ee55172e0d, Location : Error at element "Version" : Add-in manifest parsing encountered a value that does not conform to its required format, Line=4, CharPosition=14
11/6/2022 23:55:55 Unexpected Manifest Issue encountered while parsing manifest, add-in ID : 12d18a4f-508c-464f-b1e3-91ee55172e0d, Location : Error at element "Version" : Add-in manifest parsing encountered a value that does not conform to its required format, Line=4, CharPosition=14

I'm not sure why this would only be a problem for CF in Win32, but you might try taking a look at that.

**Comment by jabbera** [comment]
It doesn't seem related plus the validator passes:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="TaskPaneApp">
  <Id>b829afd3-b791-40db-8d28-70cca5c56c56</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Contoso</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="My Office Add-in"/>
```

**Comment by jabbera** [comment]
@millerds is there anything you can tell me that would help figure out why this is happening? I'm really totally lost at next steps.

**Comment by jabbera** [comment]
After MUCH pain I figured out there was a second dev addin loading that was causing my issue. I had to delete a registry key to sort the issue.

**Comment by Lakshit-shah** [comment]
hey @jabbera , can you please tell us which registry key did you delete and how to got to know that this is the key to be deleted ?
