### ISSUE TITLE
Unable to see User Defined Functions

### ISSUE THREAD

**Issue by b0arderman** [OfficeDev/generator-office#744]
# Expected behavior

Ability to utilize a function that is defined in functions.js in Excel once it is loaded.

# Current behavior

The sidebar task pane loads, but the user defined functions are not available.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Followed the instructions at: https://github.com/OfficeDev/generator-office
2. I modified the instructions above to use the following command to generate the office plugin:
yo office --projectType excel-functions --name "mb_ns_excel_connector4" --host excel --js true
3.  Ran npm run build
4. Ran npm start and tried npm start:desktop

Excel opens after the above and I can see the task pane.  It appears to work and when I click run it highlights the cell in yellow.  When I try to access any of the functions can't find them.  I've tried the following:

=add(
=contoso.add(
=myfunctions.add(
=mb_ns_excel_connector4.add(

## Context

I am using Excel with Office 365 desktop version.
 
Below is the manifest.xml:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="TaskPaneApp">
  <Id>0a665989-ca49-4726-98f7-eef4042e90c5</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Contoso</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="mb_ns_excel_connector4"/>
  <Description DefaultValue="Write your own Excel functions in JavaScript."/>
  <IconUrl DefaultValue="https://localhost:3000/assets/icon-32.png"/>
  <HighResolutionIconUrl DefaultValue="https://localhost:3000/assets/icon-64.png"/>
  <SupportUrl DefaultValue="https://www.contoso.com/help"/>
  <AppDomains>
    <AppDomain>https://www.contoso.com</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Workbook"/>
  </Hosts>
  <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="CustomFunctionsRuntime" MinVersion="1.1"/>
    </Sets>
  </Requirements>
  <DefaultSettings>
    <SourceLocation DefaultValue="https://localhost:3000/taskpane.html"/>
  </DefaultSettings>
  <Permissions>ReadWriteDocument</Permissions>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Hosts>
      <Host xsi:type="Workbook">
        <AllFormFactors>
          <ExtensionPoint xsi:type="CustomFunctions">
            <Script>
              <SourceLocation resid="Functions.Script.Url"/>
            </Script>
            <Page>
              <SourceLocation resid="Functions.Page.Url"/>
            </Page>
            <Metadata>
              <SourceLocation resid="Functions.Metadata.Url"/>
            </Metadata>
            <Namespace resid="Functions.Namespace"/>
          </ExtensionPoint>
        </AllFormFactors>
        <DesktopFormFactor>
          <GetStarted>
            <Title resid="GetStarted.Title"/>
            <Description resid="GetStarted.Description"/>
            <LearnMoreUrl resid="GetStarted.LearnMoreUrl"/>
          </GetStarted>
          <FunctionFile resid="Commands.Url"/>
          <ExtensionPoint xsi:type="PrimaryCommandSurface">
            <OfficeTab id="TabHome">
              <Group id="CommandsGroup">
                <Label resid="CommandsGroup.Label"/>
                <Icon>
                  <bt:Image size="16" resid="Icon.16x16"/>
                  <bt:Image size="32" resid="Icon.32x32"/>
                  <bt:Image size="80" resid="Icon.80x80"/>
                </Icon>
                <Control xsi:type="Button" id="TaskpaneButton">
                  <Label resid="TaskpaneButton.Label"/>
                  <Supertip>
                    <Title resid="TaskpaneButton.Label"/>
                    <Description resid="TaskpaneButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <TaskpaneId>ButtonId1</TaskpaneId>
                    <SourceLocation resid="Taskpane.Url"/>
                  </Action>
                </Control>
              </Group>
            </OfficeTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>
    <Resources>
      <bt:Images>
        <bt:Image id="Icon.16x16" DefaultValue="https://localhost:3000/assets/icon-16.png"/>
        <bt:Image id="Icon.32x32" DefaultValue="https://localhost:3000/assets/icon-32.png"/>
        <bt:Image id="Icon.80x80" DefaultValue="https://localhost:3000/assets/icon-80.png"/>
      </bt:Images>
      <bt:Urls>
        <bt:Url id="Functions.Script.Url" DefaultValue="https://localhost:3000/dist/functions.js"/>
        <bt:Url id="Functions.Metadata.Url" DefaultValue="https://localhost:3000/dist/functions.json"/>
        <bt:Url id="Functions.Page.Url" DefaultValue="https://localhost:3000/dist/functions.html"/>
        <bt:Url id="GetStarted.LearnMoreUrl" DefaultValue="https://go.microsoft.com/fwlink/?LinkId=276812"/>
        <bt:Url id="Commands.Url" DefaultValue="https://localhost:3000/commands.html"/>
        <bt:Url id="Taskpane.Url" DefaultValue="https://localhost:3000/taskpane.html"/>
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="Functions.Namespace" DefaultValue="CONTOSO"/>
        <bt:String id="GetStarted.Title" DefaultValue="Get started with your sample add-in!"/>
        <bt:String id="CommandsGroup.Label" DefaultValue="Commands Group"/>
        <bt:String id="TaskpaneButton.Label" DefaultValue="Show Taskpane"/>
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="GetStarted.Description" DefaultValue="Your sample add-in loaded succesfully. Go to the HOME tab and click the 'Show Taskpane' button to get started."/>
        <bt:String id="TaskpaneButton.Tooltip" DefaultValue="Click to Show a Taskpane"/>
      </bt:LongStrings>
    </Resources>
  </VersionOverrides>
</OfficeApp>

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by millerds** [comment]
First thing to try is clearing the cache: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache
If that doesn't work, try using runtime logging to get more information about the failure to load the functions: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging

**Comment by b0arderman** [comment]
I cleared the cache and opened a new project and it is working now.  Thank you.  I am still unable to debug a user defined function or see results from the debugger.  I've tried several different methods over the past few hours.  Should I open a new issue for this?  
I've tried using the following command:
npx office-addin-debugging start .\manifest.xml

I've also tried using the following in the launch.json with the native debugger:
  "configurations": [
    {
      "name": "Excel Desktop (Custom Functions)",
      "type": "node",
      "request": "attach",
      "port": 9229,
      "timeout": 600000,
      "preLaunchTask": "Debug: Excel Desktop",
      "postDebugTask": "Stop Debug",
      "resolveSourceMapLocations": null
    }...
]

The debugger appears to connect to VS Code, but I'm not seeing any output from console.log.
Thanks,
Eric

**Comment by millerds** [comment]
This is actually a known issue that happened not too long ago that we are still trying to figure out.

**Comment by b0arderman** [comment]
Ok, thanks.  Are there any suggested work arounds, would you recommend temporarily using the sidebar as a log or another logging method other than console.log?  Thanks, Eric

**Comment by millerds** [comment]
I don't have a good workaround right now.  You could use if blocks and returning a message which will get written in the cell using the function.  I'm not sure if it's possible to modify other cells from within a function if you want to output a series of output statements rather than a single message.  These may or may not work for you.

**Comment by b0arderman** [comment]
Those are some greats thoughts. Thank you!

**Comment by gendev1** [comment]
I am also getting the same issue,is it resolved? I am doing this on Mac and Web
