### ISSUE TITLE
Dev certificates don't get installed automatically when starting the dev-server

### ISSUE THREAD

**Issue by alinnert** [OfficeDev/generator-office#746]
# Prerequisites

- [x] I am running the latest version of Node and the tools
  *My company is currently using v14.20.1 by default but I don't think that's a problem.*
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

Office Dev Certs get installed when starting the dev-server or I should get prompted to install the certificates.

# Current behavior

That doesn't happen. I've struggled making a Word add-in run again after not touching it and the related tools for about one year. Opening the add-in in Word resulted in the error message "ADD-IN ERROR - The content is blocked because it isn't signed by a valid security certificate.". After some trial and error, I found the root of the problem: The certificates `ca.crt` and `localhost.crt` get created but there's no attempt to install them. It doesn't matter if I run PowerShell normally or as an Administrator, or if I run `npm run dev-server`, `npm run start:desktop` or `npx office-addin-dev-certs install`. In all cases I need to install those certificates manually. Otherwise, the local certificates store doesn't contain those certificates or only the previous ones which are invalid at that point in time.

I'm pretty sure this wasn't necessary back then when I worked on the add-in the last time. Also, the [get started guide](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?view=word-js-preview&tabs=yeomangenerator#:~:text=If%20you%20are%20prompted%20to%20install%20a%20certificate%20after%20you%20run%20one%20of%20the%20following%20commands%2C%20accept%20the%20prompt%20to%20install%20the%20certificate%20that%20the%20Yeoman%20generator%20provides.) does mention such a prompt. Does someone know what could cause the prompt to not show up?

## Steps to Reproduce

I *think* following the [get started guide](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?view=word-js-preview&tabs=yeomangenerator) should reproduce the problem. At least I had the same problem with a new project created with `npx -p yo@latest -p generator-office@latest yo office` and then running `npm run dev-server` or `npm run start:desktop`.

## Context

* Operating System: Windows 10 22H2
* Node version: 14.20.1
* Office version: 2210 (Build 15726.20202)
* Tool version: What tool does this refer to? I've tried creating a new add-in using `yo@latest` (currently `4.3.1`) and `generator-office@latest` (currently `1.9.2`) which results in the same behavior.

## Failure Logs

*none*

**Comment by millerds** [comment]
A new pacakge was published with some updated to the certificate scripts.  Can you try again and see if it is any better?

**Comment by alinnert** [comment]
Now I was able to try it out. Did you mean `office-addin-dev-certs`? After upgrading it from 1.9 to 1.11 it works again. Thank you!
