### ISSUE TITLE
Missing script: "start:server" for SSO startup project

### ISSUE THREAD

**Issue by kinkoazc** [OfficeDev/generator-office#747]
# Prerequisites
- [ x ] I am running the latest version of Node and the tools
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

# Expected behavior
Project should start.

# Current behavior
Project fails with error:
```[0] npm ERR! Missing script: "start:server"```

## Steps to Reproduce
1. ```yo office --projectType single-sign-on --name "My Office Add-in SSO" --host outlook --js```
2. ```cd "My Office Add-in SSO"```
3. ```npm run configure-sso```
4. ```npm start```

## Context

* Tool version: ```generator-office@1.9.2```

## Failure Logs

```
[0] npm ERR! Missing script: "start:server"
[0] npm ERR!
[0] npm ERR! To see a list of scripts, run:
[0] npm ERR!   npm run
[0]
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     [...]
[0] npm run start:server exited with code 1
```

**Comment by millerds** [comment]
Looks like this is a bug in the recent template updated specific to outlook.  Well fix this and publish and update, but you can correct it by editing your package.json file like this:
-- Replace the existing start script with "office-addin-debugging start manifest.xml"
-- Update @babel/core package version to "^7.20.5"
-- Update @babel/preset-env package version to "^7.20.2"

After that do a "npm install" and then "npm start" should work again.

**Comment by kinkoazc** [comment]
Thank you!
