### ISSUE TITLE
Express with Custom function

### ISSUE THREAD

**Issue by edouardbrasier** [OfficeDev/generator-office#750]
Hello,

Is there a sample of a custom function excel addin with an express middle tiers?
I can't seem to be able to merge SSO taskpane add-in and custom function shared run time addin.
I have tried carefully editing the manifest but it doesn't work.

Thanks

**Comment by millerds** [comment]
There is an SSO sample that uses express as a middle tier (https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Office-Add-in-NodeJS-SSO), but no one for custom functions (which doesn't require any sort of middle tier service by itself).

What problem are you running into when trying to combine custom functions shared runtime and a SSO project?  You should be able to start with the SSO project, add the functions files, update the manifest for shared runtime with custom functions, and update webpack to include the functions files and it should work.  Note that the current SSO project from our template has a webpack file with both a client (office host) piece and the SSO middle tier part and the functions files only need to be part of the client part of the webpack config.

**Comment by edouardbrasier** [comment]
I have used the SSO sample that uses express as a middle tiers, removed the authentification part as I just want to launch some tedious azure code from the back end. It works well.
I have then tried to import custom functions (renamed Kontoso), I modified the manifest file (it validates with command line) I have modified webpack file. I get no error even when using the visual studio code debugger. My task pane button to launch azure code still works but the custom function are not there.

It looks like other people had the same issues (see below) and give up it is frustrating that it seems so complicated to use custom functions.
https://stackoverflow.com/questions/50932491/add-excel-custom-functions-to-an-existing-excel-add-in-javascript-api

if this is really possible an example would be nice.

**Comment by millerds** [comment]
It looks like the thread you referenced has an answer you should try.  One other thing you could try is deleting the WEF cache when modifying custom functions (there is a bug with deploying changes to functions when it's already been deployed): https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache

**Comment by edouardbrasier** [comment]
The outcome for me was the same as the thread I referenced. I couldn't make it work
