### ISSUE TITLE
Sideloading by file in Outlook for desktop doesn't "stick" when manually sideloaded

### ISSUE THREAD

**Issue by TranquilMarmot** [OfficeDev/generator-office#767]
# Expected behavior

Sideloading an add-in in Outlook on the desktop should work

# Current behavior

I can sideload the add-in in Outlook on the web just fine by choosing "Add from URL..."

When I try the same add-in in the desktop app on macOS or Windows, it _looks_ as though the add-in was properly added and it shows up under "Custom Addins".

However, as soon as you close the "Office Add-ins" pop-up it goes away. Re-opening it by clicking "Get Add-ins", you can see the custom add-in is gone.

## Steps to Reproduce

1. Generate add-in
2. [Follow the steps for sideloading it](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=mac#outlook-on-the-desktop)
3. Close the add-ins pop-up
4. Re-open the pop-up
5. Add-in is no longer there 😢 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: macOS / Windows
* Node version: `v16.15.0`
* Office version: Outlook 16.71.2
* Tool version:

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by millerds** [comment]
I have a few clarifying questions to ask:

- What version of Outlook on Windows did you try?
- Can you confirm it was the Win32 "Get Add-ins" button and not the "All Apps" button (the experience is changing in the most current builds)
- Are you using "Add from URL . . . " or "Add from file . . ." in the Win32 client?

**Comment by TranquilMarmot** [comment]
On Windows: Version 2302 Build 16.0.16130.20298) 64-bit 
It says "Get Add-ins"

On macOS: Outlook 16.71.2

We're doing "Add from URL..." which works fine in Outlook on the web.

Same behavior on both operating systems. It adds the add-in just fine but it goes away as soon as you close the add-in modal.

**Comment by millerds** [comment]
If you remove it everywhere, then "Add from URL . . . " in the Win32 client, and look for it in OWA does it show up?

It's possible there is something subtle in the manifest that is preventing the clients from parsing it vs. OWA parsing it (slightly different parsers).

**Comment by TranquilMarmot** [comment]
After debugging this for a few hours, I found the issue- we had some SVG files under `<Resources><bt:Images>....`

OWA loads these fine, but Outlook on the desktop silently fails and uninstalls the add-in.
