### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by sheldoncoates** [OfficeDev/generator-office#776]
Are there any plans to support React 18 in the future? It would be great to have it as the default React version.

How should we tackle upgrading existing projects? Having the generator be React 18 would be good to reverse engineer whats needed, but if there's a guide or a tool for upgrading as well I think it could be useful.

Thanks.

**Comment by millerds** [comment]
There is actually someone trying to make this work in the template repository (https://github.com/OfficeDev/Office-Addin-TaskPane-React/pull/116), however it's running into a compatibility issue.  We have to balance out moving forward with the basic template and maintaining support for older versions of office (which still use the i.e. webview which doesn't support some of the current modules the react template uses).

You can use that PR as an example of what needs to change to move forward, but realize that your add-in will not work in Office 2016.
