### ISSUE TITLE
Sample that combines taskpane React and custom functions

### ISSUE THREAD

**Issue by dsaf** [OfficeDev/generator-office#779]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

An option to produce a template that combines React and sample custom functions or a step-by-step guide on how to add custom functions into a React project post-generation.

# Current behavior

I spent a few days trying to make React sample show any custom functions but failed.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run the tool and observe no `react-excel-functions` option.
2. Try adding custom functions (including updating the manifest etc.).
3. Fail to achieve this.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows, of course.
* Node version: 18.16.1 LTS.
* Office version: Office 365 desktop.
* Tool version: v1.9.7, I believe.

## Failure Logs

Just trust me that I generated two samples: `excel-functions` and `react` and tried my best to port over relevant pieces of code from the former into the latter by using Beyond Compare etc. I am not a webpack expert and would have strongly preferred that Microsoft had stuck with normal C#/.NET.

**Comment by pinverso** [comment]
This may help:  https://support.microsoft.com/en-us/office/excel-functions-by-category-5f91f4e9-7b42-46d2-9bd1-63f26a86c0eb

**Comment by zhngx1** [comment]
Currently the feature:<react-excel-functions template>, you requested, is not a part of the product. We track add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
