### ISSUE TITLE
bug: react excel template outputs outlook commands or something

### ISSUE THREAD

**Issue by dsaf** [OfficeDev/generator-office#783]
Hi, why is react template for excel producing commands files? They don't seem to be used and they seem to mention some outlook related features like notifications and mailbox etc. Looks like a bug.

**Comment by Rick-Kirkham** [comment]
@dsaf This is a known problem and we have a work item to fix it. Since we have an internal tracking item, I'll close this issue.

**Comment by millerds** [comment]
The template repos these come from support all the different kinds of host the add-in can be used for.  They also include certain elements for different features (as opposed to host) like commands (which is not exclusive to outlook).  Not all the elements are used in all the resulting projects and there are many things the get cleaned up in the process of generating the project.  We could be a little better and creating leaner and more targeted project and as Ricky said this is an internal work item to improve this.
