### ISSUE TITLE
Cannot Remove Default Add-In

### ISSUE THREAD

**Issue by gagestinson** [OfficeDev/generator-office#785]
I was developing an add-in and when installing the generator I ran it by default to see how it looked in Outlook. It displays fine, I then uninstalled it  as well as node but the add-in buttons are still present and I cannot figure out how to get rid of them. I was running the latest version of Node and the tools. I have since uninstalled them, expecting this to cause the add-in to go away.
![image](https://github.com/OfficeDev/generator-office/assets/132514592/d60848bd-63c5-4571-bf55-e884bcb57825)

**Comment by Oleg-O** [comment]
You should be able to remove these using the add-in management UI, available either through "Get Add-ins" or "All Apps" ribbon buttons (depending on your Outlook version). [This page](https://support.microsoft.com/en-us/office/get-an-office-add-in-for-outlook-1ee261f9-49bf-4ba6-b3e2-2ba7bcab64c8) describes this in more detail. Let me know if this is what you were looking for?

**Comment by gagestinson** [comment]
I have gotten it now. That was not the issue, though. I followed the link you sent and it said that there should be a `Home > All Apps/Get Add-ins` button in the ribbon, which I did not see. So I went to customize the ribbon and it turns out the add-in buttons were just stuck on the ribbon and did not go away by default. But I now have manually removed them. Thanks!

**Comment by Oleg-O** [comment]
No, ribbon customization UI will not help here, I expect the buttons will re-appear if the add-ins are still installed. To really remove them, you should use the UI I pointed out. Did you see "Get Add-ins" button instead? You can also get to the management UI via File -> "Manage Add-ins" button:

![image](https://github.com/OfficeDev/generator-office/assets/16073773/5dab8def-f19d-4939-8a83-1a9f635cf93b)
