### ISSUE TITLE
Request to add more a hybrid template between modern ui (React) and custom functions

### ISSUE THREAD

**Issue by jess-boonekamp** [OfficeDev/generator-office#787]
### React Plugin with Custom Functions
It would be super beneficial if there was an option to generate a standard plugin or React plugin **with** custom functions embedded in it. Have spent some time comparing `webpack.config.js`, `package.json` and `manifext.xml` between the two template projects, and haven't been able to nail it as of yet, but I estimate this would be a common use case.

Our use cases involves interaction with the add-in to get various data points from external sources, and use this logic also in custom functions for direct model interaction

**Comment by ElizabethSamuel-MSFT** [comment]
@jess-boonekamp Thanks for letting us know.

@millerds Can you take a look?

Thanks.

**Comment by millerds** [comment]
In general, we don't provide templates for every combination of features (custom functions, sso, taskpane, app commands, events), platforms (html, react, angular, vue, etc), and languages (js, ts) as that can get complex.  However, we do track add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

Github Label: “Type: product feature request”
https://aka.ms/M365dev-suggestions
