### ISSUE TITLE
Including additional Gulp tasks to support releases & deployment

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#79]
@andrewconnell, @jthake: What do you guys think about including additional Gulps tasks in the generated gulpfile.js to support releases, such as copy the add-in files to be deployed to a separate folder (eg. dist), minifying scripts and CSS and bumping the version number in the manifest.xml and package.json? How about taking a look at the ability to upload the manifest.xml to the App Catalog? The main goal of these tasks would be to support developers in the deployment and release of projects built with the generator.

**Comment by andrewconnell** [comment]
As for more gulp tasks that are in the `gulpfile.js` that gets added to the generated addin project, I'm good with that... definitely good options. 

As for uploading... that's not that easy. @jthake and I looked into create an Office 365 command line tool, similar to what we have with Azure's X-Plat CLI. The key feature we were going to build was the ability to upload it to the app catalog, among MANY other things (for instance, to start to mirror what the Azure guys have... a xplat option for managing your tenant from the command line so you aren't limited to POSH scripts). However my understanding is that this is an effort that has been taken on by @MSFT engineering (is that correct @jthake?). The idea would be to then have peopl euse the command line directly, but also in a scripting sense as a type of CD process, such as using a gulp task.

So... if my understanding is correct, that is something we shouldn't work on now as we should take a dependency on the command line tool that MSFT is working on.

**Comment by waldekmastykarz** [comment]
Cool! I'm very curious about the CLI tools. It would be great to have these but even a small thing such as the ability to upload the manifest to the App Catalog would be very helpful.
What do you think about creating a separate issue for each task so that we can discuss and track them more easily?

**Comment by andrewconnell** [comment]
That’s how it should be… in a non-threaded forum like this, each issue should be treated separately… not all at once.

**Comment by waldekmastykarz** [comment]
Let's close this one then and create separate issues for the different ideas.
