### ISSUE TITLE
Outlook add-in disappearing after side loading in outlook app

### ISSUE THREAD

**Issue by nivethan-me** [OfficeDev/generator-office#792]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [X] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior
After side loading Outlook add-in should appear in `My add-ins` section in outlook and should be accessible in outlook app

# Current behavior

after selecting the `manifest.xml` file add-in show up in the `My add-ins` section temporarily and disappears once i close that `Office add-ins` window.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. in terminal type `yo office`
2. Choose a project type: Office Add-in Task Pane project using React framework
3. Choose a script type: TypeScript
4. What do you want to name your add-in? check-bug
5. Which Office client application would you like to support? Outlook
6. cd check-bug 
7. npm run dev-server
8. open the Outlook application and sideload the add-in by choosing the manifest.xml file
9. now close the Outlook Add-ins window and open again
10. You can find that the Add-in disappeared from the Outlook

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: mac os 13.4.1 (also in windows 11)
* Node version: v20.9.0 (also in v18.16.1)
* Office version: Outlook for mac 16.79(23111019)
* Tool version: yo 5.0.0 | npm view generator-office version 1.9.7

**Comment by millerds** [comment]
What version of Outlook on Windows are you using?
When you open Outlook to sideload the add-in do you see the "All Apps" or "Get Add-ins" button?
What happens if you run "npm start" on the Windows machine instead of "npm run dev-server"?

**Comment by nivethan-me** [comment]
@millerds 

> What version of Outlook on Windows are you using?

following comes from About Outlook section
You have Microsoft Outlook Version 1.2023.1108.200 (Production).
Client Version is 20231103003.19 .

>When you open Outlook to sideload the add-in do you see the "All Apps" or "Get Add-ins" button?
Yeah i get the "Get Add-ins" button

>What happens if you run "npm start" on the Windows machine instead of "npm run dev-server"?

it opens a new terminal and all looks green and i can even see the taskpane page on my browser at https://localhost:3000/taskpane.html but "My Add-ins > Custom Addins" says No add-ins found

**Comment by millerds** [comment]
Being able to browse the html file in the browser means that webpack is running and serving up the content for the add-in.  If an add-in is being removed from the "my add-ins" section it suggests there is something wrong with the manifest file.  Can you run the 'npm run validate' command and see what the output says?  Can you also check what happens if you try and sideload it using OWA instead of the rich client application?

**Comment by prasath-pc** [comment]
@millerds same issue for me as well, what could be the issue ?

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" xsi:type="MailApp">
  <Id>0a2c0a96-c046-42cf-8545-8228095caf17</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Pepper Cloud CRM</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Pepper Cloud"/>
  <Description DefaultValue=" "/>
  <IconUrl DefaultValue="https://demo.peppercloud.com/office365app/assets/chrome_logo.png"/>
  <HighResolutionIconUrl DefaultValue="https://demo.peppercloud.com/office365app/assets/pc-logo-128.png"/>
  <SupportUrl DefaultValue="https://peppercloud.com/contact"/>
  <AppDomains>
    <AppDomain>https://demo.peppercloud.com</AppDomain>
    <AppDomain>https://login.microsoftonline.com</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Mailbox"/>
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.1"/>
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://demo.peppercloud.com/office365app/taskpane.html"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
  <Permissions>ReadWriteItem</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read"/>
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      <Requirements>
        <bt:Sets DefaultMinVersion="1.4">
          <bt:Set Name="Mailbox"/>
        </bt:Sets>
      </Requirements>
      <Hosts>
        <Host xsi:type="MailHost">
          <Runtimes>
            <Runtime resid="WebViewRuntime.Url">
            </Runtime>
          </Runtimes>
          <DesktopFormFactor>
            <FunctionFile resid="Taskpane.Url"/>
            <ExtensionPoint xsi:type="LaunchEvent">
              <LaunchEvents>
                <LaunchEvent Type="OnMessageSend" FunctionName="LogMailToCRM" />
              </LaunchEvents>
              <SourceLocation resid="WebViewRuntime.Url"/>
            </ExtensionPoint>
            <ExtensionPoint xsi:type="MessageReadCommandSurface">
              <OfficeTab id="TabDefault">
                <Group id="msgReadGroup">
                  <Label resid="GroupLabel"/>
                  <Control xsi:type="Button" id="msgReadOpenPaneButton">
                    <Label resid="TaskpaneButton.Label"/>
                    <Supertip>
                      <Title resid="TaskpaneButton.Label"/>
                      <Description resid="TaskpaneButton.Tooltip"/>
                    </Supertip>
                    <Icon>
                      <bt:Image size="16" resid="Icon.16x16"/>
                      <bt:Image size="32" resid="Icon.32x32"/>
                      <bt:Image size="80" resid="Icon.80x80"/>
                    </Icon>
                    <Action xsi:type="ShowTaskpane">
                      <SourceLocation resid="Taskpane.Url"/>
                    </Action>
                  </Control>
                </Group>
              </OfficeTab>
            </ExtensionPoint>
            <ExtensionPoint xsi:type="MessageComposeCommandSurface">
              <OfficeTab id="TabDefault">
                <Group id="msgComposeGroup">
                  <Label resid="GroupLabel"/>
                  <Control xsi:type="Button" id="msgComposeOpenPaneButton">
                    <Label resid="TaskpaneButton.Label"/>
                    <Supertip>
                      <Title resid="TaskpaneButton.Label"/>
                      <Description resid="TaskpaneButton.Tooltip"/>
                    </Supertip>
                    <Icon>
                      <bt:Image size="16" resid="Icon.16x16"/>
                      <bt:Image size="32" resid="Icon.32x32"/>
                      <bt:Image size="80" resid="Icon.80x80"/>
                    </Icon>
                    <Action xsi:type="ShowTaskpane">
                      <SourceLocation resid="Taskpane.Url"/>
                    </Action>
                  </Control>
                </Group>
              </OfficeTab>
            </ExtensionPoint>
          </DesktopFormFactor>
        </Host>
      </Hosts>
      <Resources>
        <bt:Images>
          <bt:Image id="Icon.16x16" DefaultValue="https://demo.peppercloud.com/office365app/assets/logo.svg"/>
          <bt:Image id="Icon.32x32" DefaultValue="https://demo.peppercloud.com/office365app/assets/logo.svg"/>
          <bt:Image id="Icon.80x80" DefaultValue="https://demo.peppercloud.com/office365app/assets/logo.svg"/>
        </bt:Images>
        <bt:Urls>
          <bt:Url id="Commands.Url" DefaultValue="https://demo.peppercloud.com/office365app/commands.html"/>
          <bt:Url id="Taskpane.Url" DefaultValue="https://demo.peppercloud.com/office365app/taskpane.html"/>
          <bt:Url id="WebViewRuntime.Url" DefaultValue="https://demo.peppercloud.com/office365app/taskpane.html" />
          <bt:Url id="JSRuntime.Url" DefaultValue="https://demo.peppercloud.com/office365app/taskpane.js" />
        </bt:Urls>
        <bt:ShortStrings>
          <bt:String id="GroupLabel" DefaultValue="Pepper Cloud Add-in"/>
          <bt:String id="TaskpaneButton.Label" DefaultValue="Show Taskpane"/>
          <bt:String id="ActionButton.Label" DefaultValue="Perform an action"/>
        </bt:ShortStrings>
        <bt:LongStrings>
          <bt:String id="TaskpaneButton.Tooltip" DefaultValue="Opens a pane displaying all available properties."/>
          <bt:String id="ActionButton.Tooltip" DefaultValue="Perform an action when clicked."/>
        </bt:LongStrings>
      </Resources>
    </VersionOverrides>
  </VersionOverrides>
</OfficeApp>
