### ISSUE TITLE
Errors when creating new addin

### ISSUE THREAD

**Issue by jozefizso** [OfficeDev/generator-office#793]
# Prerequisites

- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

Creating new addin should work seamlessly.

# Current behavior

This error happens when new project is created:

```

I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.


npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-module-transforms@^7.23.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in: /Users/izso/.npm/_logs/2023-11-26T14_47_05_244Z-debug-0.log

No change to package.json was detected. No package manager install will be executed.
```

## Steps to Reproduce

Follow instructions at https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/powerpoint-tutorial?tabs=yeomangenerator

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: macOS 14
* Node version: 20
* Office version: -
* Tool version: -

**Comment by jozefizso** [comment]
When installing packages using `npm install` it shows another set of errors:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.18.4',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.10.0', npm: '10.2.3' }
npm WARN EBADENGINE }
npm WARN deprecated debuglog@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated @azure/msal-node@1.18.4: A newer major version of this library is available. Please upgrade to the latest available version.
npm WARN deprecated @azure/msal-browser@2.38.3: A newer major version of this library is available. Please upgrade to the latest available version.

added 1360 packages, and audited 1361 packages in 2m

186 packages are looking for funding
  run `npm fund` for details

10 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

**Comment by nivethan-dev** [comment]
Certainly! Here's a revised version of your GitHub comment:

---

@jozefizso, I am not a maintainer, but I believe the error you are encountering is due to the use of Node v20, which likely requires a lower version. If you have NVM installed, you can switch to version 18 by running the command `nvm use --lts=hydrogen`, which should resolve the issue. 

However, if you have opened this issue to prompt compatibility with v20, I hope the maintainers will do something about it.

**Comment by jozefizso** [comment]
Node 20 is current LTS available for 7 months already.

**Comment by millerds** [comment]
Updated packages that have support for Node 20 should be released now.
