### ISSUE TITLE
Change names of the generated Gulp tasks to follow the naming convention

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#80]
It seems like Gulp tasks follow the naming convention where a main task is a single word and a sub task consists of multiple words separated by a - or a :. In our case case the generated gulpfile.js files contain tasks such as **serve-static** and **validate-xml**. Shouldn't we have main tasks called **serve** and **validate** to call the existing sub tasks? We could either rename the existing tasks or add new tasks which would allow us for more flexibility in the future (like additional validation or serving files differently(?))?

**Comment by andrewconnell** [comment]
Is there a problem with what's there now or is it really just a naming convention? 

If there's not a problem I don't think we should go changing stuff at this time... just my opinion.

**Comment by waldekmastykarz** [comment]
It's just the naming convention. Had to work around it for building the help for the generated files but it's okay for now. We can pick it up some other time.
