### ISSUE TITLE
Cannot select Typescript

### ISSUE THREAD

**Issue by crgarcia12** [OfficeDev/generator-office#800]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [ X ] I am running the latest version of Node and the tools
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed

# Expected behavior
By pushing the down key, I will be able to select typescript

# Current behavior
I cannot select Typescript, I press the Down, Up, Right, Tab keys... none of them work.
I have the same behavior in two computers (laptop + Azure VM)
If I hit enter, then it creates the project in Javascript

<img width="561" alt="image" src="https://github.com/OfficeDev/generator-office/assets/27244028/b6c7c2dc-e8b7-4aac-ae11-bf0a98370c81">

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
```bash
> npm install -g yo generator-office
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
changed 1257 packages in 49s
> yo office

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the Office  │
    |--(o)--|    │   Add-in generator, by   │
   `---------´   │ @OfficeDev! Let's create │
    ( _´U`_ )    │    a project together!   │
    /___A___\   /╰──────────────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

> ? Choose a project type: Office Add-in Task Pane project using React framework
> ? Choose a script type: (Use arrow keys)
❯ JavaScript
  TypeScript
```
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 11
* Node version: v18.19.0
* Office version: latest
* Tool version: 5.0.0

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by millerds** [comment]
This is a known issue.  We haven't been able to determine the source of the problem as it happens when using an imported module, doesn't happen 100% of the time (though it appears consistent frequently), and isn't always on this question.  The work around is to simple press enter once and then question will repeat itself and you should be able to select a value.

**Comment by akrantz** [comment]
another workaround is to add `--ts` as a command line argument, e.g. run: `yo office --ts`.

**Comment by millerds** [comment]
This has been fixed a few months ago . . . this should not be a problem any more.
