### ISSUE TITLE
Node 20 not supported

### ISSUE THREAD

**Issue by sakgoyal** [OfficeDev/generator-office#806]
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior
Node 20 will work

# Current behavior
Current install is very outdated an the package.json needs to be updated to allow newer versions of node to work. there are lots of deprecation warnings that also need to be fixed as well as security issues. Please advise what I should do
![image](https://github.com/OfficeDev/generator-office/assets/19929553/5a3aabd8-eee6-468a-aaba-09ed866cbdd2)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Ubuntu
* Node version: 20
* Office version: -
* Tool version: -

**Comment by millerds** [comment]
Should be supported now.
