### ISSUE TITLE
unexpected behavior when compiling on a filesystem with other case-semantic in yo office add-ins

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/generator-office#807]
I created a Outlook Add-in using yo office in react js when I start my add-in first time its gives error and now facing same issue in all add-ins.

`WARNING in ./node_modules/es6-promise/dist/es6-promise.js`

![Error Image](https://github.com/OfficeDev/office-js-docs-pr/assets/134502135/470eba29-9781-4608-8463-c5b57e92834d)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15f43fe5-03e0-579c-165c-57e16b1a53ea
* Version Independent ID: 15f43fe5-03e0-579c-165c-57e16b1a53ea
* Content: [Create Office Add-in projects using the Yeoman Generator - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/yeoman-generator-overview)
* Content Source: [docs/develop/yeoman-generator-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/yeoman-generator-overview.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wenjun-Gong** [comment]
Assign @darrelmiller to take a look.

**Comment by junaid042** [comment]
Hi @Wenjun-Gong and @darrelmiller ,
why we can't add css file in react js add-in ? I have have a add-in created using React framework simply I added a style.css file in my comments folder and `import "./Style.css"` in my `App.jsx` file this is giving error 

![image](https://github.com/OfficeDev/generator-office/assets/134502135/678a73b2-fa1d-4880-bd8f-e83409b45644)
