### ISSUE TITLE
Update Deps

### ISSUE THREAD

**Issue by sakgoyal** [OfficeDev/generator-office#808]
When will the dependencies be updated? seems like everything is quite out of date

**Comment by AlexJerabek** [comment]
Hi @sakgoyal,

As with your observation in #806, yo office is dependent on services that have not yet updated to Node v20, which is blocking other updates. We will update the project when we are able to.

Let me assign @millerds to follow up when that work is complete.

**Comment by Adrian-MSFT** [comment]
Is there any specific functionality that you need from these newer package versions?
