### ISSUE TITLE
Issues with registry value using npm start

### ISSUE THREAD

**Issue by om327** [OfficeDev/generator-office#810]
Hi, I'm trying to follow the tutorial for creating an excel plugin - I seem to hit the same issue each time when trying to run the example using the command ```npm start```. 

```
PS C:\Users\SVL\Desktop\tradebe-excel-plugin\My Office Add-in> npm start

> office-addin-taskpane-js@0.0.1 start     
> office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
Enabled debugging for add-in 232b2e4e-d5c0-487e-bc60-e3f4e2d63e3b.
Starting the dev server... (webpack serve --mode development)
Unable to start the dev server. Error: The dev server is not running on port 3000.
Sideloading the Office Add-in...
Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in.
Error: Unable to set registry value "232b2e4e-d5c0-487e-bc60-e3f4e2d63e3b" to "C:\Users\SVL\Desktop\tradebe-excel-plugin\My Office Add-in\manifest.xml" (REG_SZ) for key ""HKCU\SOFTWARE\Microsoft\Office\16.0\Wef\Developer"".
ProcessUncleanExitError: ADD command exited with code 1:

ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
```
Node version v20.9.0
Microsoft® Excel® for Microsoft 365 MSO (Version 2310 Build 16.0.16924.20054) 64-bit 

It looks like its a permissions issue - I've tried running vs code as administrator but I'm still having the same issue. 

Its a little confusing as there is another microsoft excel-plugin repository that uses a different approch - ``` npm http-server ```

https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/hello-world/excel-hello-world

Following the examples in this repository and using the following works:

``` 
http-server -S -C localhost.crt -K localhost.key 
--cors . -p 3000 
```

Copying over the .crt and .key files and trying to use this server instead of ``` npm start ``` for this directory doesn't seem to work?

Any help would be fantastic. 

Many thanks, 
Ollie

**Comment by Adrian-MSFT** [comment]
There have been a few changes since the last comment. Can you retry again and let me know if it works? You might still get some version warnings but you should be able to continue past them
