### ISSUE TITLE
Changing accounts for generator offoice

### ISSUE THREAD

**Issue by ngacho** [OfficeDev/generator-office#819]
Apologies if this isn't the right forum (and please point me to the right forum for these questions), but I just started building add ons and I'm massively confused. 
1. How does one change the account that `npm start` uses. I have two accounts and one of them isn't authorised to be building add ons (which, conveniently, is the one office authorized) but I can't find an easy way to switch.
2. Where is the `manifest.xml`? While sideloading apps, I can only upload xml files, but the generator office comes prepackaged with `manifest.json`. If there isn't any, where can I find tools that seamlessly convert the provided json to xml. I can probably write a script, but I would rather not reinvent the wheel if it exists.

**Comment by millerds** [comment]
Which template did you select when running "yo office"?

The new unified manifest is json based and projects created using that specific preview template don't include an xml manifest and you don't need one.  Running 'npm start' will start up webpack and do the sideloading for you using a service call (that is why the account is needed in the first place).

The unified manifest project includes a couple of npm scripts to help in managing the account used to sideload.  If you execute 'npm run logout' your cached credentials will be removed.  After that you either run 'npm run login' or 'npm start' to trigger an auth flow involving the browser to enter the credentials you want to use.

If you are not read for the unified manifest project and want to stick to xml then choose one of the other templates and you will get an xml manifest.  Note that for Outlook 'npm start' will still require the account to sideload for you.

**Comment by Rick-Kirkham** [comment]
[like]  Ricky Kirkham reacted to your message:
________________________________
