### ISSUE TITLE
Manifest generated is invalid due to not creating a random GUID for the Id

### ISSUE THREAD

**Issue by emmasab** [OfficeDev/generator-office#824]
# Expected behavior

Run `yo office`

Select the following
- ? Choose a project type: Office Add-in Task Pane project
- ? Choose a script type: JavaScript
- ? What do you want to name your add-in? Test Add-In
- ? Which Office client application would you like to support? Excel

The manifest.xml produced contains a randomly generated GUID in the `<id><\id>` tag

# Current behavior

The manifest.xml produced contains `<Id>Add-In</Id>` instead

Running `npm run validate` confirms the manifest is invalid

```
Error OfficeDev/generator-office#1:
XML Schema Validation Error: Error found during XML Schema validation.
  - Details: The 'http://schemas.microsoft.com/office/appforoffice/1.1:Id' element is invalid - The value 'Add-In' is invalid according to its datatype 'http://schemas.microsoft.com/office/appforoffice/1.1:UUID' - The Pattern constraint failed.
  - Line: 3
  - Column: 4

Error OfficeDev/generator-office#2:
XML Schema Violation: Your manifest does not adhere to the current set of XML schema definitions for Office Add-in manifests.

Error OfficeDev/generator-office#3:
Manifest product ID Not Valid: The manifest product ID could not be parsed. The ID must be a plain GUID.
  - Details: Add-In

The manifest is not valid.
```

**Comment by Rick-Kirkham** [comment]
Change to conversion script is in [258](https://github.com/OfficeDev/Office-Addin-TaskPane/pull/258).

**Comment by millerds** [comment]
Fix to generator-office has been published.  Please update and it should work now.
