### ISSUE TITLE
Support the JSON manifest option for the 2 React and the 2 SSO projects

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/generator-office#833]
Not a bug. Enhancement request.

The 2 React and the 2 SSO templates now have support for the JSON manifest (assuming Outlook is the host). 

Please update the generator to give the user the option to use the unified manifest if they've chosen Outlook and either React or SSO. 

NOTE: The update for SSO will have a dependency on this issue: [853](https://github.com/OfficeDev/Office-Addin-Scripts/issues/853)

**Comment by millerds** [comment]
Change is checked it.  Will be published in the coming weeks.

**Comment by millerds** [comment]
Published
