### ISSUE TITLE
No matching version found for @typescript-eslint/typescript-estree@7.18.0

### ISSUE THREAD

**Issue by rogervanwile** [OfficeDev/generator-office#840]
# Expected behavior

I can create a new office add-in without errors when using genertor-office

# Current behavior

There is an error when creating a new office add-in:

```
npm error code ETARGET
npm error notarget No matching version found for @typescript-eslint/typescript-estree@7.18.0.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
```

## Steps to Reproduce

1. Install latest version of yo and generator-office `npm install -g yo generator-office`
2. Run `yo office` and use the defaults or always the first option. 

```
? Choose a project type: Office Add-in Task Pane project
? Choose a script type: JavaScript
? What do you want to name your add-in? My Office Add-in
? Which Office client application would you like to support? Excel
```

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Mac OS 14.5 
* Node version: 20.14.0
* Office version: 
* Tool version:

**Comment by AlexJerabek** [comment]
Hi @rogervanwile, 

I'm unable to reproduce this issue on the same version of Node. Just to clarify, are you seeing as part of yo office creating the new project (when yo office runs `npm install`) or when you run `npm start`?

Let me assign @millerds to take a look.
