### ISSUE TITLE
readline.js error during command execution

### ISSUE THREAD

**Issue by ashuetawah** [OfficeDev/generator-office#87]
I just setup the Yo and getting the error. Any pointers for fixing? I am running it on Win10 Pro.
![image](https://cloud.githubusercontent.com/assets/11130627/10907329/3a9bc618-827d-11e5-9a9b-55d7a5b300c5.png)

**Comment by andrewconnell** [comment]
What version of node? What version on NPM? Can you run other yeoman generators?

**Comment by ashuetawah** [comment]
node - 4.2.1
npm - 3.3.10
I did not try other yeoman gen.

just got different error.
![image](https://cloud.githubusercontent.com/assets/11130627/11020374/35c600ec-8672-11e5-8e47-85b0c06abc4e.png)

**Comment by andrewconnell** [comment]
The error indicates you don't have GIT installed... that appears to be a requirement for the NPM module Which that the generator uses. Can't repo this on a Windows machine that has GIT installed... if you could also try other generators and after you've installed GIT.
