### ISSUE TITLE
Install instructions assume pre reqs

### ISSUE THREAD

**Issue by jthake** [OfficeDev/generator-office#92]
AS the generator is targeting now just people familiar with yeoman but also those new to it. I think we should add the prereqs like the Visual Studio Code page does https://code.visualstudio.com/docs/runtimes/office

Right now it doesn't even mention that you need git and node installed on your desktop.

**Comment by andrewconnell** [comment]
Associated with #98 ... Will look at refactoring, cleaning up and doc'ing the getting started experience.

**Comment by andrewconnell** [comment]
Fixed in a1c884adfcf119cdd2d7a270256bfca037d7d5fc
