### ISSUE TITLE
Installation issue due to tsd error with process-nexttick-args

### ISSUE THREAD

**Issue by stefanreimers** [OfficeDev/generator-office#93]
When running

npm install -g bower yo generator-office gulp tsd

I got an error saying

Cannot find process-nexttick-args.

To avoid this error I ran the above npm install without generator-office which worked fine. Afterwards running 

npm install -g generator-office 

gave me the same error. See the log:
C:\Projekte>npm install -g generator-office

> generator-office@0.5.1 install C:\Program Files\nodejs\node_modules\generator-
office
> tsd install -r -o --save-dev

[ERR!] cwd  : C:\Program Files\nodejs\node_modules\generator-office
[ERR!] os   : Windows_NT 6.3.9600
[ERR!] argv : "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\tsd\\build\\cli.js" "install" "-r" "-o" "--save-dev"
[ERR!] node : v4.2.1
[ERR!] tsd  : 0.6.5
[ERR!] Error: Cannot find module 'process-nextick-args'
[ERR!] CODE : MODULE_NOT_FOUND
[ERR!] Cannot find module 'process-nextick-args'
[ERR!] If you need help, you may report this error at:
    https://github.com/DefinitelyTyped/tsd/issues

[ERR!] tsd.json could not be retrieved

[ERR!] .tsdrc could not be retrieved

[ERR!] Please include the following file with any support request:
    C:\Program Files\nodejs\node_modules\generator-office\tsd-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "generator-office"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! generator-office@0.5.1 install: `tsd install -r -o --save-dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the generator-office@0.5.1 install script 'tsd install -r -o
--save-dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the generator-office pack
age,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsd install -r -o --save-dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls generator-office
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projekte\npm-debug.log

**Comment by andrewconnell** [comment]
Pretty sure this is a dupe issue as bugged in issue #103... can you try to mitigation steps there and let us know if that fixes it? if not, feel free to re-open the issue.

**Comment by stefanreimers** [comment]
The link to #103 was very helpful. Installing an older version of tsd does the trick (0.6.0 works for me).
