### ISSUE TITLE
Validate Manifest Xml 

### ISSUE THREAD

**Issue by CodeMoggy** [OfficeDev/generator-office#94]
Could the Gulp task to validate the manifest xml include validation for Command Add-ins?

**Comment by andrewconnell** [comment]
Yup... We are currently doing two types of validation. The first type is up using the XSD defined on MSDN... So when it's updated to include command Addins, we will update our XSD as well which should cover it.

In addition we are also validating for specific nodes that's are required when submitting to the store like the highresicon.
