### ISSUE TITLE
Include a Gulp task to serve static and Node.js

### ISSUE THREAD

**Issue by CodeMoggy** [OfficeDev/generator-office#95]
Include a Gulp task to serve static (client) and Node.js content. For the purposes of our project we created the following task:

var nodemon = require('gulp-nodemon');
gulp.task('serve-nodejs-static', function () {
  nodemon({
    script: 'source/server.js',
    ext: 'js html',
    env: { 'NODE_ENV': 'development' }
  });
});

**Comment by andrewconnell** [comment]
We already have the task **serve-static**. I don't think we want to add any over dependencies like nodemon upon folks... They can certainly add it to their own projects though like you have. fwiw I add nodemon and node-inspector in my gulp tasks but I don't think it's right to force that on everyone
