### ISSUE TITLE
manifest file name based on project breaks validate-xml

### ISSUE THREAD

**Issue by jthake** [OfficeDev/generator-office#99]
Now that the manifest name is dynamic, validate-xml breaks because its looking for manifest.xml. @waldekmastykarz  @andrewconnell

**Comment by waldekmastykarz** [comment]
Shall I fix it @andrewconnell or do you want to pick it up?

**Comment by andrewconnell** [comment]
It's not "broken"... it doesn't assume the XML file you want to test. It requires you to pass in an option that specifies the file you want to test (in case you have multiple in the same folder. 

Ref: https://github.com/OfficeDev/generator-office/blob/master/generators/content/templates/common/gulpfile.js#L40

**Comment by jthake** [comment]
Is there a way to run a help command that gives more information on the gulp task to make that more obvious? and also add this to the readme page too then?

**Comment by andrewconnell** [comment]
As is now? No... generally people just comment gulp tasks using JSDoc (which we've done... granted the `validate-xml` task could use some additional comments explaining usage).

An enhancement could be done to use the [gulp-help](https://www.npmjs.com/package/gulp-help) plugin, but requires rework of our gulp tasks (should be done to the generator & generated projects. You can see an example of the output I generate for my projects in the screenshot here: http://www.andrewconnell.com/blog/dynamically-loading-gulp-tasks-for-simplified-reuse-and-maintenance

**Comment by waldekmastykarz** [comment]
We could also fix the default behavior to look for `manifest-*.xml` files and validate them as discussed in https://github.com/OfficeDev/generator-office/issues/58#issuecomment-147646915

**Comment by andrewconnell** [comment]
Right that's what I changed it to... To require dev to pass it in. That's not a big deal IMHO...

**Comment by waldekmastykarz** [comment]
Check. I thought the task would automatically look for any `manifest-*.xml` files if no specific filename has been passed. It's okay if it doesn't but then it would be better if the task failed with a clear error showing an example of the filename should be passed to the task.

Using gulp-help would be definitely a good way of documenting the different tasks particularly the ones that accept parameters such as validate-xml.

**Comment by andrewconnell** [comment]
Let's not have multiple discussions in this thread... Two issues discussed here. 

Can add an enhancement for the task to try to find a manifest in the current folder... Personally I don't like this because what if the manifest is in a sub folder? Can run gulp from the sub folder... So I'd require you pass a path to it.

As for gulp-help issue, spin up another issue as an enhancement to the generator.

**Comment by andrewconnell** [comment]
Where are we on this... the validate-xml for the manifest. Is it fine as is? Can we close this?

**Comment by waldekmastykarz** [comment]
My suggestion: check for `manifest-*.xml` in the current folder. If it isn't there, require dev to pass the path to the task explicitly.

@jthake?

**Comment by andrewconnell** [comment]
I’d amend to say *if there isn’t exactly one `manifest-*.xml` then require the caller to specify the filename / path*

**Comment by waldekmastykarz** [comment]
Yes, good idea @andrewconnell
